Destroy shoot access for DWD if Shoot is workerless
gardener/gardener pull request #10003
Opened 2024-06-19 09:01 UTC by shafeeqes

**How to categorize this PR?**

/area quality
/kind cleanup

**What this PR does / why we need it**:
The DWD probe is not created for workerless shoots, hence it doesn't need the shoot access secret and the `shoot-core-dependency-watchdog` MR. This PR adds cleanup code for this at gardenlet startup and also prevents deploying this component for workerless shoots in the future.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @unmarshall @aaronfern 
FYI @ary1992 @acumino 

**Release note**:

```other operator
NONE
```

2024-06-19 09:21 UTC, aaronfern requested changes

2024-06-19 09:21 UTC, aaronfern commented on cmd/gardenlet/app/migration.go
> +		if !workerlessShootNamespaces.Has(namespace.Name) {
Can you can skip namespaces that are terminating or that have a deletion timestamp set?

2024-06-19 09:29 UTC, shafeeqes commented on cmd/gardenlet/app/migration.go
> +		if !workerlessShootNamespaces.Has(namespace.Name) {
Should I rather skip shoots in deletion altogether?

2024-06-19 09:31 UTC, aaronfern commented on cmd/gardenlet/app/migration.go
> +		if !workerlessShootNamespaces.Has(namespace.Name) {
Yeah, that would be better ig

2024-06-19 12:27 UTC, shafeeqes commented
/retest

2024-06-20 12:28 UTC, plkokanov requested changes

2024-06-20 12:28 UTC, plkokanov commented on cmd/gardenlet/app/migration.go
> +	if err := gardenClient.List(ctx, shootList); err != nil {
Can't we only select the shoots for which this gardenlet is responsible? The `shoot.spec.seedName` can be used as a field selector for the `List` call. Then I guess you don't need to also retrieve all shoot control plane namespaces in the seed.

2024-06-21 05:14 UTC, aaronfern commented on cmd/gardenlet/app/migration.go
> +}
nit: we don't need two for loops now, and can combine them into one
But overall looks good to me

2024-06-21 10:10 UTC, shafeeqes commented
/retest

2024-06-24 04:32 UTC, shafeeqes commented
/retest

2024-06-24 05:57 UTC, aaronfern reviewed
/lgtm

2024-06-24 12:41 UTC, plkokanov commented
/lgtm
/approve

2024-06-24 16:19 UTC, merged