provider-local: Update outdated comment for appending hosts.toml files
gardener/gardener pull request #10061
Opened 2024-07-03 11:41 UTC by ialidzhikov

**How to categorize this PR?**

/kind enhancement

**What this PR does / why we need it**:
After https://github.com/gardener/gardener/pull/8834, provider-local appends hosts.toml files to the `provision` OSC. The registry-cache:
- for the registry-mirror case: continues to append them to the `reconcile` OSC
- for the registry-cache cache: appends unit and files are created by the unit when the cache endpoint is ready

Hence, provider-local no longer needs to use the custom `appendFileIfNotPresent` func/behaviour. 

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

2024-07-03 16:58 UTC, Kostov6 reviewed
Thanks for the PR! Just a minor suggestion from my side

2024-07-03 16:58 UTC, Kostov6 commented on pkg/provider-local/webhook/controlplane/ensurer.go
> +		// to allow testing the extension in local setup.
```suggestion
		// provider-local assumes that it's the only webhook acting on OSC with provision purpose. If a webhook wants to work on the local setup and wants to overwrite hosts.toml it should act on OSC with puprose reconcile
```
This wording creates an implicit dependency on registry-cache in g/g's code just by referencing it. I suggest we use a more general comment that enforces the needed assumptions in a broader context. By doing so we enforce external actors to adapt to g/g and not vice-versa while still not restricting registry-cache's functionality. Your proposed comment is more suited for [registry-cache's ensurer](https://github.com/gardener/gardener-extension-registry-cache/blob/2552b21038b017ff3ca877fd2d071d17f3aae980/pkg/webhook/mirror/ensurer.go#L106) imo. Wdyt?

2024-07-04 05:48 UTC, timuthy requested changes
This for the PR.

However, having https://github.com/gardener/gardener/pull/10050 in mind, this comment is removed anyways and the registry cache extension is supposed to contribute to `.spec.criConfig.containerd.registries`.

2024-07-09 11:55 UTC, ialidzhikov commented
/close
in favor of https://github.com/gardener/gardener/pull/10050

2024-07-09 11:55 UTC, closed without merging