Enable rolling restarts on resources deployed by MR
gardener/gardener pull request #10192
Opened 2024-07-25 06:23 UTC by Kostov6

**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR preserves the `kubectl.kubernetes.io/restartedAt` annotation for `Deployments`, `DaemonSets` and `StatefulSets` to make `kubectl rollout restart` work on them

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/8463

**Special notes for your reviewer**:

**Release note**:

```noteworthy operator
`kubectl rollout restart` works on `Deployments`, `DaemonSets` and `StatefulSets` deployed by MR
```

2024-07-25 10:50 UTC, timuthy requested changes

2024-07-25 10:50 UTC, timuthy commented on pkg/resourcemanager/controller/managedresource/reconciler.go
> +	}
```suggestion
	if err != nil {
		return fmt.Errorf("failed getting %s from %s/%s %s : %w", strings.Join(path, "."), apiVersion, kind, current.GetName(), err)
	}
	if !found {
		return nil
	}
	
```

2024-07-25 10:50 UTC, timuthy commented on pkg/resourcemanager/controller/managedresource/reconciler.go
> +	}
```suggestion
	if err != nil {
		return fmt.Errorf("failed getting %s from %s/%s %s : %w", strings.Join(path, "."), apiVersion, kind, desired.GetName(), err)
	}
	if !found {
		desiredAnnotations = map[string]string{}
	}
```

2024-07-25 10:50 UTC, timuthy commented on pkg/resourcemanager/controller/managedresource/reconciler.go
> +	return fmt.Errorf("failed setting annotation %s at %s for %s/%s %s: %w", annotationKey, strings.Join(path, "."), apiVersion, kind, desired.GetName(), err)
```suggestion
	if err := unstructured.SetNestedField(desired.Object, mergeLabels(map[string]string{annotationKey: value}, desiredAnnotations), path...); err != nil {
		return fmt.Errorf("failed preserving annotation %q at %q for %s/%s %s: %w", annotationKey, strings.Join(path, "."), apiVersion, kind, desired.GetName(), err)
	}
	return nil
```

Error check missing?

2024-07-25 10:50 UTC, timuthy commented on pkg/resourcemanager/controller/managedresource/reconciler.go
> +			}
Use switch-case here? I think the function doesn't need to be called three times in a row, nor does the `preserveAnnotation` requires kind and apiVersion.

2024-07-25 10:50 UTC, timuthy commented on pkg/resourcemanager/controller/managedresource/reconciler.go
> +func preserveAnnotation(kind string, apiVersion string, current *unstructured.Unstructured, desired *unstructured.Unstructured, annotationKey string, path ...string) error {
Tests are missing.

2024-07-30 07:26 UTC, ialidzhikov commented on pkg/resourcemanager/controller/managedresource/reconciler.go
> +			}
It seems conceptually wrong to add a merge functionality at this place and not in the `pkg/resourcemanager/controller/managedresource/merger.go` file.
Wouldn't it better to handle the merging of the annotation in the Pod template in the already existing merge funcs? 
For example, can't we add the logic for preserving the annotation in https://github.com/gardener/gardener/blob/6ba5765c27a1cb90e0fcb11764af7cfe6cc013cd/pkg/resourcemanager/controller/managedresource/merger.go#L148-L162?

2024-07-31 09:12 UTC, ialidzhikov reviewed
Cosmetic suggestions, otherwise lgtm

2024-07-31 09:12 UTC, ialidzhikov commented on pkg/resourcemanager/controller/managedresource/merger.go
> +	if metav1.HasAnnotation(oldPod.ObjectMeta, "kubectl.kubernetes.io/restartedAt") {
You could extract the well-known annotation to const. I checked whether we can reuse already existing const from k8s.io/... but it looks like they don't have a const about this annotation: https://github.com/kubernetes/kubectl/blob/2e31adb070639fef809fe111475be66dfb35beec/pkg/polymorphichelpers/objectrestarter.go#L41

```diff
diff --git a/pkg/resourcemanager/controller/managedresource/merger.go b/pkg/resourcemanager/controller/managedresource/merger.go
index 392f07a1c..aee7757f8 100644
--- a/pkg/resourcemanager/controller/managedresource/merger.go
+++ b/pkg/resourcemanager/controller/managedresource/merger.go
@@ -146,10 +146,12 @@ func mergeDeployment(scheme *runtime.Scheme, oldObj, newObj runtime.Object, pres
 	return scheme.Convert(newDeployment, newObj, nil)
 }
 
+const restartedAtAnnotation = "kubectl.kubernetes.io/restartedAt"
+
 func mergePodTemplate(oldPod, newPod *corev1.PodTemplateSpec, preserveResources bool) {
 	// ref https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-k8s-io-restart-at
-	if metav1.HasAnnotation(oldPod.ObjectMeta, "kubectl.kubernetes.io/restartedAt") {
-		metav1.SetMetaDataAnnotation(&newPod.ObjectMeta, "kubectl.kubernetes.io/restartedAt", oldPod.Annotations["kubectl.kubernetes.io/restartedAt"])
+	if metav1.HasAnnotation(oldPod.ObjectMeta, restartedAtAnnotation) {
+		metav1.SetMetaDataAnnotation(&newPod.ObjectMeta, restartedAtAnnotation, oldPod.Annotations[restartedAtAnnotation])
 	}
 
 	if preserveResources {

```

2024-07-31 09:12 UTC, ialidzhikov commented on pkg/resourcemanager/controller/managedresource/merger.go
> +	// ref https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-k8s-io-restart-at
You could add a more comprehensive comment on why we need to preserve this annotation:

```suggestion
	// Do not overwrite the "kubectl.kubernetes.io/restartedAt" annotation as it is used by
	// the "kubectl rollout restart <RESOURCE>" command to trigger rollouts.
	// Otherwise, the resource-manager would revert this annotation set by the kubectl command and
	// this would revert the triggered rollout.
	// Ref https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-k8s-io-restart-at
```

2024-07-31 09:12 UTC, ialidzhikov commented on pkg/resourcemanager/controller/managedresource/merger_test.go
> +
```suggestion
```

2024-07-31 09:12 UTC, ialidzhikov commented on pkg/resourcemanager/controller/managedresource/merger_test.go
> +			expected := old.DeepCopy()
I would personally not write 2 cases - one for with preserveResources=true and other one with false.

You can benefit from the fact that we duplicate the same test case for Deployments, StatefulSets, DaemonSets. For example for the Deployment use preserveResources=true, for the StatefulSet test use false:

```diff
diff --git a/pkg/resourcemanager/controller/managedresource/merger_test.go b/pkg/resourcemanager/controller/managedresource/merger_test.go
index 67abc8e4b..1c5df2fa6 100644
--- a/pkg/resourcemanager/controller/managedresource/merger_test.go
+++ b/pkg/resourcemanager/controller/managedresource/merger_test.go
@@ -300,19 +300,13 @@ var _ = Describe("merger", func() {
 			newDeployment = old.DeepCopy()
 		})
 
-		It("should preserve kubectl.kubernetes.io/restartedAt pod template annotation if present", func() {
+		It("should preserve kubectl.kubernetes.io/restartedAt annotation in pod template", func() {
 			old.Spec.Template.Annotations = map[string]string{"kubectl.kubernetes.io/restartedAt": "foo"}
 
-			newPreserveResources := newDeployment.DeepCopy()
-			newDontPreserveResources := newDeployment.DeepCopy()
 			expected := old.DeepCopy()
 
-			Expect(mergeDeployment(s, old, newPreserveResources, false, true)).NotTo(HaveOccurred(), "merge should be successful")
-			Expect(newPreserveResources).To(Equal(expected))
-
-			Expect(mergeDeployment(s, old, newDontPreserveResources, false, false)).NotTo(HaveOccurred(), "merge should be successful")
-			Expect(newDontPreserveResources).To(Equal(expected))
-
+			Expect(mergeDeployment(s, old, newDeployment, false, true)).NotTo(HaveOccurred(), "merge should be successful")
+			Expect(newDeployment).To(Equal(expected))
 		})
 
 		It("should not overwrite old .spec.replicas if the new one is nil", func() {
@@ -486,19 +480,13 @@ var _ = Describe("merger", func() {
 			newStatefulSet = old.DeepCopy()
 		})
 
-		It("should preserve kubectl.kubernetes.io/restartedAt pod template annotation if present", func() {
+		It("should preserve kubectl.kubernetes.io/restartedAt annotation in pod template annotation", func() {
 			old.Spec.Template.Annotations = map[string]string{"kubectl.kubernetes.io/restartedAt": "foo"}
 
-			newPreserveResources := newStatefulSet.DeepCopy()
-			newDontPreserveResources := newStatefulSet.DeepCopy()
 			expected := old.DeepCopy()
 
-			Expect(mergeStatefulSet(s, old, newPreserveResources, false, true)).NotTo(HaveOccurred(), "merge should be successful")
-			Expect(newPreserveResources).To(Equal(expected))
-
-			Expect(mergeStatefulSet(s, old, newDontPreserveResources, false, false)).NotTo(HaveOccurred(), "merge should be successful")
-			Expect(newDontPreserveResources).To(Equal(expected))
-
+			Expect(mergeStatefulSet(s, old, newStatefulSet, false, false)).NotTo(HaveOccurred(), "merge should be successful")
+			Expect(newStatefulSet).To(Equal(expected))
 		})
 
 		It("should not overwrite old .spec.replicas if the new one is nil", func() {
@@ -604,19 +592,13 @@ var _ = Describe("merger", func() {
 			newDaemonSet = old.DeepCopy()
 		})
 
-		It("should preserve kubectl.kubernetes.io/restartedAt pod template annotation if present", func() {
+		It("should preserve kubectl.kubernetes.io/restartedAt annotation in pod template", func() {
 			old.Spec.Template.Annotations = map[string]string{"kubectl.kubernetes.io/restartedAt": "foo"}
 
-			newPreserveResources := newDaemonSet.DeepCopy()
-			newDontPreserveResources := newDaemonSet.DeepCopy()
 			expected := old.DeepCopy()
 
-			Expect(mergeDaemonSet(s, old, newPreserveResources, true)).NotTo(HaveOccurred(), "merge should be successful")
-			Expect(newPreserveResources).To(Equal(expected))
-
-			Expect(mergeDaemonSet(s, old, newDontPreserveResources, false)).NotTo(HaveOccurred(), "merge should be successful")
-			Expect(newDontPreserveResources).To(Equal(expected))
-
+			Expect(mergeDaemonSet(s, old, newDaemonSet, true)).NotTo(HaveOccurred(), "merge should be successful")
+			Expect(newDaemonSet).To(Equal(expected))
 		})
 
 		It("should overwrite old .spec.containers[*].resources if preserveResources is false", func() {

```

2024-07-31 13:29 UTC, ialidzhikov reviewed
/lgtm

2024-08-05 08:42 UTC, dimitar-kostadinov commented
/assign plkokanov

2024-08-05 14:04 UTC, plkokanov commented
/lgtm

2024-08-06 05:27 UTC, ialidzhikov reviewed
/approve

2024-08-06 06:13 UTC, ialidzhikov commented
```
  [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/managedseed/create_rotate_delete.go:57 @ 08/06/24 05:43:19.328
  < Exit [It] Create Shoot, Create ManagedSeed, Delete ManagedSeed, Delete Shoot @ 08/06/24 05:43:19.328 (81ms)
  > Enter [AfterEach] ManagedSeed Tests @ 08/06/24 05:43:19.328
  < Exit [AfterEach] ManagedSeed Tests @ 08/06/24 05:43:19.328 (0s)
  > Enter [AfterEach] ManagedSeed Tests @ 08/06/24 05:43:19.329
  < Exit [AfterEach] ManagedSeed Tests @ 08/06/24 05:43:19.329 (0s)
  << Timeline
  [FAILED] Expected success, but got an error:
      <*errors.StatusError | 0xc0007b54a0>: 
      shoots.core.gardener.cloud "e2e-managedseed" is forbidden: 7 errors occurred:
      	* given Shoot uses non-registered given Shoot uses non-registered provider type: spec.provider.type ("local")
      	* given Shoot uses non-registered given Shoot uses non-registered provider type: spec.provider.type ("local")
      	* given Shoot uses non-registered given Shoot uses non-registered provider type: spec.provider.type ("local")
      	* given Shoot uses non-registered extension type: spec.extensions[0].type ("local-ext-seed")
      	* given Shoot uses non-registered extension type: spec.extensions[1].type ("local-ext-shoot")
      	* given Shoot uses non-registered extension type: spec.extensions[2].type ("local-ext-shoot-after-worker")
      	* given Shoot uses non-registered given Shoot uses non-registered operating system type: spec.provider.workers[0].machine.image.name ("local")
```

---

/test pull-gardener-e2e-kind-operator-seed

2024-08-06 06:59 UTC, ialidzhikov commented
```
  [FAILED] in [It] - /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/managedseed/create_rotate_delete.go:236 @ 08/06/24 06:52:45.543
  < Exit [It] Create Shoot, Create ManagedSeed, Delete ManagedSeed, Delete Shoot @ 08/06/24 06:52:45.543 (25m51.933s)
  > Enter [AfterEach] ManagedSeed Tests @ 08/06/24 06:52:45.543
  < Exit [AfterEach] ManagedSeed Tests @ 08/06/24 06:52:45.543 (0s)
  > Enter [AfterEach] ManagedSeed Tests @ 08/06/24 06:52:45.543
  < Exit [AfterEach] ManagedSeed Tests @ 08/06/24 06:52:45.543 (0s)
  << Timeline
  [FAILED] Timed out after 600.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000336d90>: 
      ManagedSeed "garden/e2e-managedseed" is not deleted yet: Waiting for garden namespace to be deleted from target cluster
      {
          s: "ManagedSeed \"garden/e2e-managedseed\" is not deleted yet: Waiting for garden namespace to be deleted from target cluster",
      }
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/e2e/gardener/managedseed/create_rotate_delete.go:236 @ 08/06/24 06:52:45.543
```

---

/test pull-gardener-e2e-kind-operator-seed

2024-08-06 07:23 UTC, ialidzhikov commented
```
⏳ Checking conditions for garden/local...
❌ ERROR: VirtualComponentsHealthy not met for garden/local after 600 seconds.
exit status 1
```

---

/test pull-gardener-e2e-kind-operator-seed

2024-08-06 08:05 UTC, merged