Fix ETCD dashboards
gardener/gardener pull request #10243
Opened 2024-08-01 09:26 UTC by rickardsjp

**How to categorize this PR?**

/area monitoring
/kind regression

**What this PR does / why we need it**:
Two ETCD dashboards were broken because the label values on etcd metrics had changed: From `role: <main/events>` to `role: etcd-<main/events>`. I also took the liberty of renaming the `$cluster` variable to be in line with the label name.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```user bugfix
The ETCD and ETCD Backup/Restore dashboards now display data again.
```

2024-08-02 06:43 UTC, renormalize commented
Fixes #10095.
Thanks for the PR @rickardsjp.

2024-08-02 07:36 UTC, shreyas-s-rao approved these changes
@rickardsjp thanks for the fix! 
/lgtm

2024-08-02 09:00 UTC, shreyas-s-rao requested changes
@rickardsjp on second thought, I also see a similar issue with [etcd-cluster-details-dashboard.json](https://github.com/gardener/gardener/blob/8d9f8d1a8b728b58f135d8c9832be4d7e1495efe/pkg/component/observability/plutono/dashboards/shoot/owners/etcd-cluster-details-dashboard.json) dashboard, specifically with the `Raft Proposals` panel. Could you please check and fix this as well?

2024-08-02 11:40 UTC, rickardsjp commented
> @rickardsjp on second thought, I also see a similar issue with [etcd-cluster-details-dashboard.json](https://github.com/gardener/gardener/blob/8d9f8d1a8b728b58f135d8c9832be4d7e1495efe/pkg/component/observability/plutono/dashboards/shoot/owners/etcd-cluster-details-dashboard.json) dashboard, specifically with the `Raft Proposals` panel. Could you please check and fix this as well?

Thank you, fixed it. PTAL :)

2024-08-05 10:35 UTC, rfranzke commented
/approve

2024-08-06 12:13 UTC, shreyas-s-rao approved these changes
@rickardsjp Thanks for addressing my comment!
/lgtm
/approve

2024-08-06 14:28 UTC, merged