[GEP-26] Add Support for Workload Identity Signing Key Rotation
gardener/gardener pull request #10313
Opened 2024-08-12 11:42 UTC by vpnachev

**How to categorize this PR?**
/area security ipcei
/kind enhancement
/ipcei workload-identity

**What this PR does / why we need it**:
Add Support for Workload Identity Signing Key Rotation

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Part of https://github.com/gardener/gardener/issues/9586
/cc @dimityrmirchev 

**Release note**:

```other operator

```

2024-08-12 11:46 UTC, rfranzke commented
/assign

2024-08-12 11:56 UTC, rfranzke requested changes
Nice PR, thank you! Please augment https://github.com/gardener/gardener/blob/master/docs/concepts/operator.md#credentials-rotation.

Question: After the rotation of this key is prepared (i.e., a new key got created and GAPI got rolled out), shouldn't we issue new tokens for all `WorkloadIdentity`s in the system? Otherwise, how do we prevent that the completion is triggered too fast/early?

2024-08-12 11:56 UTC, rfranzke commented on pkg/component/gardener/apiserver/apiserver.go
> +	SetWorkloadIdentityKeyRotationPhase(gardencorev1beta1.CredentialsRotationPhase)
Nit: Not directly related to this PR, but could you move https://github.com/gardener/gardener/blob/129a182213ee1bbc27f857c78483841780facaba/pkg/component/gardener/apiserver/deployment.go#L103 into https://github.com/gardener/gardener/blob/129a182213ee1bbc27f857c78483841780facaba/pkg/component/gardener/apiserver/deployment.go#L172? When browsing the file, I was confused why this CLI flag is not part of this function. Thank you!

2024-08-12 16:23 UTC, vpnachev commented
> Question: After the rotation of this key is prepared (i.e., a new key got created and GAPI got rolled out), shouldn't we issue new tokens for all `WorkloadIdentity`s in the system? Otherwise, how do we prevent that the completion is triggered too fast/early?

Good question, I was expecting the human operator to not trigger completion so fast, but as there is no prevention mechanism this could easily happen. I will think about this, but maybe a solution similar to [service account signing key rotation](https://github.com/gardener/gardener/blob/master/docs/extensions/garden-api-access.md#renewing-all-garden-access-secrets) will be the way forward, what do you think?

2024-08-12 18:59 UTC, rfranzke commented
> > Question: After the rotation of this key is prepared (i.e., a new key got created and GAPI got rolled out), shouldn't we issue new tokens for all `WorkloadIdentity`s in the system? Otherwise, how do we prevent that the completion is triggered too fast/early?
> 
> Good question, I was expecting the human operator to not trigger completion so fast, but as there is no prevention mechanism this could easily happen. I will think about this, but maybe a solution similar to [service account signing key rotation](https://github.com/gardener/gardener/blob/master/docs/extensions/garden-api-access.md#renewing-all-garden-access-secrets) will be the way forward, what do you think?

Yes, this makes sense. I guess we don't need such operation annotation in the setup w/ `gardener-operator` since we can just trigger this in the reconciliation flow. We do this here for the `ServiceAccount` secrets: https://github.com/gardener/gardener/blob/3a13ee1aa75ee7e6c500aaec69326cd0c8640037/pkg/operator/controller/garden/garden/reconciler_reconcile.go#L319-L329 and https://github.com/gardener/gardener/blob/3a13ee1aa75ee7e6c500aaec69326cd0c8640037/pkg/operator/controller/garden/garden/reconciler_reconcile.go#L357-L380
I guess we should add a similar task for the `WorkloadIdentity` secrets

2024-08-13 07:02 UTC, dimityrmirchev commented
Thanks! Apart from the https://github.com/gardener/gardener/pull/10313#pullrequestreview-2232788377 discussion other looks good to me so feel free move the PR forward once the discussion is resolved

2024-08-16 13:54 UTC, vpnachev commented
/label ipcei/workload-identity

2024-08-21 15:03 UTC, vpnachev commented
Workload identity tokens in all seeds are now renewed with [297a091](https://github.com/gardener/gardener/pull/10313/commits/297a0918927d8ae2aafd6d5dc6e86d1ceea05d45)

2024-08-22 08:24 UTC, rfranzke reviewed
Very nice! Please augment https://github.com/gardener/gardener/blob/master/docs/concepts/operator.md#credentials-rotation

2024-08-22 08:24 UTC, rfranzke commented on pkg/utils/gardener/tokenrequest/secrets.go
> +func RenewWorkloadIdentityTokens(ctx context.Context, c client.Client, opts ...client.ListOption) error {
Does it make sense to write a small unit test for it?

2024-08-22 08:25 UTC, rfranzke commented
> Thanks! Apart from the [#10313 (review)](https://github.com/gardener/gardener/pull/10313#pullrequestreview-2232788377) discussion other looks good to me so feel free move the PR forward once the discussion is resolved

@dimityrmirchev Do you plan to have a second look as well?

2024-08-22 08:53 UTC, dimityrmirchev commented
> @dimityrmirchev Do you plan to have a second look as well?

Yes, I will take a look in the afternoon

2024-08-22 11:49 UTC, dimityrmirchev approved these changes
/lgtm

2024-08-27 08:56 UTC, vpnachev commented on pkg/utils/gardener/tokenrequest/secrets.go
> +func RenewWorkloadIdentityTokens(ctx context.Context, c client.Client, opts ...client.ListOption) error {
Sure, done with 37d4fd421e98bfde22eda2cc8799ff5429625ce3

2024-08-28 08:32 UTC, rfranzke commented on docs/concepts/operator.md
> +Also, when the `WorkloadIdentity` token signing key is in `Preparing` phase, then `gardener-operator` annotates all `Seed`s with `gardener.cloud/operation=renew-workload-identity-tokens`.
```suggestion
Also, when the `WorkloadIdentity` token signing key rotation is in `Preparing` phase, then `gardener-operator` annotates all `Seed`s with `gardener.cloud/operation=renew-workload-identity-tokens`.
```

2024-08-28 08:32 UTC, rfranzke commented
/lgtm
/approve

2024-08-28 10:31 UTC, merged