Update maintenance window docs
gardener/gardener pull request #1035
Opened 2019-05-25 19:54 UTC by ialidzhikov

**What this PR does / why we need it**:
Update maintenance window docs to include info about OS roll-outs.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

2019-05-28 10:15 UTC, plkokanov requested changes

2019-05-28 10:15 UTC, plkokanov commented on docs/usage/shoots.md
> +If you update the `.spec.<provider>.constraints.machineImages` field in the CloudProfile used in the Shoot, then the maintenance controller will apply the new machine image to the Shoot spec (and wil
Minor nit: "Seed will be updated and `the` machine controller manager will take care `of` the actual state to match the desired one.

2019-05-28 10:15 UTC, plkokanov commented on docs/usage/shoots.md
> +If the annotation gets removed then the Alertmanager will be also removed during the next reconcilation of the cluster. The same is valid in the opposite if the annotation is added to an existing clu
Suggestion:
"The opposite is also valid, if the annotation is added to an existing cluster"

2019-05-28 10:15 UTC, plkokanov commented on pkg/apis/garden/validation/validation_test.go
> +					ShootUID: types.UID(utils.ComputeSHA1Hex([]byte(fmt.Sprintf("shoot-%s-%s", "garden", "backup-infrastructure")))),
Can't we just use:
```go
ShootUID: types.UID(utils.ComputeSHA1Hex([]byte("shoot-garden-backup-infrastructure))
```

2019-05-28 22:59 UTC, zanetworker approved these changes
/lgtm

2019-05-31 11:30 UTC, rfranzke approved these changes
/lgtm

2019-05-31 11:30 UTC, merged