Tls metrics in bb exporter
gardener/gardener pull request #10405
Opened 2024-08-28 06:17 UTC by mimiteto

**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
PR allows `probe_ssl_earliest_cert_expiry` to be kept for the `garden` Prometheus instance and adds the `kubernetes.default.svc.cluster.local` service to the target list.

**Which issue(s) this PR fixes**:
Provides a partial solution for #https://github.com/gardener/gardener/issues/10394

**Special notes for your reviewer**:

**Release note**:

```other operator
Introducing alerts for the expiration of the runtime API, dashboard, virtual API and gardener API CA certificates
```

2024-08-28 06:28 UTC, rfranzke requested changes
/cc @istvanballok @rickardsjp @vicwicker @chrkl 

Generally, I have doubts whether this is a  good approach to alert about  the CA certificate expiry - what about all other CAs/certs that are generated in the cluster (which maybe cannot be used so easily in `blackbox-exporter`)?

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
> +	VolumeMountPathClusterAccess = "/var/run/secrets/blackbox_exporter/" + volumeNameClusterAccess
It is conceptually wrong to use the `volumeName` constant here (even if the value is the same). These are two different things

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
> +	VolumeMountPathRuntimeCA  = "/var/run/secrets/blackbox_exporter/" + volumeNameRuntimeCA
same here

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
> +	VolumeMountPathRuntimeCA  = "/var/run/secrets/blackbox_exporter/" + volumeNameRuntimeCA
doc string missing

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/blackboxexporter.go
> +	RuntimeCAConfigMapKey     = "ca.crt"
doc string missing

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/blackboxexporter_test.go
> +		format.MaxLength = 100000
remove this

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/garden/config.go
> +		pathToRuntimeToken            = blackboxexporter.VolumeMountPathRuntimeCA + "/" + resourcesv1alpha1.DataKeyToken
```suggestion
		pathRuntimeToken            = blackboxexporter.VolumeMountPathRuntimeCA + "/" + resourcesv1alpha1.DataKeyToken
```

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/garden/scrapeconfig.go
> +	genScrapeConfig := func(name, module string, targets []monitoringv1alpha1.Target, metrics []string) *monitoringv1alpha1.ScrapeConfig {
```suggestion
	generateScrapeConfig := func(name, module string, targets []monitoringv1alpha1.Target, metrics []string) *monitoringv1alpha1.ScrapeConfig {
```

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/garden/scrapeconfig.go
> +	genScrapeConfig := func(name, module string, targets []monitoringv1alpha1.Target, metrics []string) *monitoringv1alpha1.ScrapeConfig {
Use `var ()` block

2024-08-28 06:28 UTC, rfranzke commented on pkg/component/observability/monitoring/blackboxexporter/garden/scrapeconfig.go
> +	tlsScrapeConfig := func(name, module string, targets []monitoringv1alpha1.Target) *monitoringv1alpha1.ScrapeConfig {
`var ()` block

2024-08-29 08:15 UTC, mimiteto commented
/retest

2024-08-29 12:19 UTC, oliver-goetz commented
/test all

2024-08-30 10:05 UTC, vicwicker reviewed
Thanks for addressing the previous review comments I sent you offline. I reviewed again and only found one more thing.

2024-08-30 10:05 UTC, vicwicker commented on pkg/component/observability/monitoring/prometheus/garden/prometheusrules.go
> +			For:    ptr.To(monitoringv1.Duration("10m")),
Maybe add a comment that this is supposed to be 30 days or break it down such as `24 * 3600 * 30`.

The for is optional and I think there is no need to wait 10 minutes for the alert to stay up before sending it. If a certificate is going to expire within X time then it's still going to expire 10 minutes later.

2024-08-30 12:19 UTC, closed without merging