Allow disabling CPU throttling
gardener/gardener pull request #1040
Opened 2019-05-27 15:32 UTC by afritzler

**What this PR does / why we need it**:
For latency critical workload you might want to disable the `--cpu-cfs-quota` flag on the kubelet (default is true). This PR allows you do that via the `shoot` spec

```
  kubernetes:
    kubelet:
      cpuCFSQuota: false
```
 
**Release note**:
```improvement operator
Allow disabling CPU throttling
```

2019-05-27 17:49 UTC, vlerenc commented
Thank you @afritzler. Have you seen also #987 and #996? Is there a way to find a generic solution, so that people can tweak their `kubelet`s more individually (at their risk)?

2019-05-27 21:01 UTC, afritzler commented
Yes, I saw those 2 issues. However after watching [0] I thought it would make sense to start with the CPU throttling/quota handling itself first. Also it was a pretty easy thing to build. Same can be applied for the more fine grained CPU management policies in the future pretty easily. 

The more general solution is a little cumbersome since the `kubelet` has a boat load of flags and the question here would be: should we just dump them into the kubelet service definition without validation or not. 

[0] https://www.youtube.com/watch?v=6sDTB4eV4F8

2019-05-27 21:05 UTC, afritzler commented
And of course, if you allow to configure everything the kubelet has to offer you need to consider the following:
1. make sure a flag is available in a particular kubelet version (otherwise the kubelet won't start)
2. we don't increase the ops effort on our side because people blowing up their cluster nodes by misconfiguring the kubelet

2019-05-28 00:31 UTC, vlerenc commented
Sure, I see that. On the other hand, Gardener is not about hyperscaler-alike me-too clusters. Freedom of infrastructure, freedom of choice, freedom of configuration is the most compelling argument for Gardener (besides its kubeception approach and the level of self-healing and auto-scaling). Whoever wants to use Gardener to setup a managed service can still limit the options, but primarily our strategy is to enable people and give them the options.

That's why I was thinking to follow in the footsteps of `kubeadm` here and their approach is to embed `KUBELET_EXTRA_ARGS` into their `kubelet` launch command (as last parameter), see https://kubernetes.io/docs/setup/independent/kubelet-integration.

If you do that as end user, i.e. pass in `kubelet` args in the shoot resource and we "blindly inject" them, then we do that and you are on your own/lose warranty if you will.

WDYT?

Then (1) would no longer be on us and (2) is something we also face today. If people give the cluster no quota or configure the shoot with only 1 tiny machine or use machine types currently not available in that region or have only one worker pool they taint with `NoSchedule` or break it in any other way, the cluster will fail. We anyways need a solution to this problem. Not a solution that will prevent these things from happening, because I do not believe that's possible, but a solution that highlights possible failure reasons conveniently, first to the end users and only second to the ops staff. In that sense, that's another hint ("Workers fail to register, possible reasons a.), b.), ... x.) custom `KUBELET_EXTRA_ARGS`).

2019-05-28 05:56 UTC, afritzler commented
Ok, then we need I guess an agreement on how we configure the kubelet in the future. Currently custom configuration goes into via the `KubeletConfiguration` api object like `podPIDLimits`. The `KUBELET_EXTRA_ARGS` has the highest priority and will override all other changes. So the most radical way to do it would be to allow `map[string]interface` in the `kubelet` section of the shoot spec. That way the user can set any flags he wants. Validating those would be tricky but that way you will end up with the most flexible solution. 

I am frankly more a fan of the `KubeletConfiguration` object approach myself since there we have proper types [0]. 

@rfranzke what is your take on that?

[0] https://github.com/kubernetes/kubelet/blob/master/config/v1beta1/types.go

2019-05-28 16:48 UTC, rfranzke commented
I'm not sure... I get @vlerenc's motivation in enabling the users to configure the stuff without the need to involve us/change Gardener. However, since the beginning of the project we were always very careful with what we expose and what not. If we start to allow configuring anything to the kubelet then I guess @afritzler is right: We will very soon end-up with a lot of clusters that are broken/can not be reconciled anymore/can not be repaired anymore/need manual intervention/require ops or effort.
Also, allowing this could break our updates (let's say a user configures a flag that is removed in the next k8s version). Sure, we can say that the user is responsible for breaking his cluster, nevertheless, it will be flagged red in our dashboards and at least requires ops attention.

I'd probably try to stick with our currently way of doing this: expose the flags with dedicated types/names, implement proper validation for valid values/supported k8s versions, and therefore reduce the potential ops effort.

2019-05-28 18:08 UTC, vlerenc commented
Please take a look at #996. Even if you would validate the keys, how would this help in preventing misconfiguration in the values? So my point is not to invest into something that doesn't deliver what we hope for. Controlling the `kubelet` args is not possible to the level that we can ensure that the cluster will work fine. That's all I am saying.

Anyway, I am fine if you decide to go for explicit args. Then please take a look at the screenshot in #996 and add `node-ip` and `cluster-dns`. Hmm... but `node-ip` is actually a problem in this case. The end user that asked for this/had multiple network interfaces? @afritzler Do you recall the use?

2019-05-28 21:10 UTC, afritzler commented
Well `node-ip` is going to be hard to implement no matter how we will approach this. Primarily this PR is going to cover just the CPU quota/throttling. We could add the `cpu-manager` policies or add them via a separate PR.

Regarding `KUBELET_EXTRA_ARGS` vs explicit types:
How about having a curated list of typed values where we know what will happen (like this PR) and which cover most of the use cases (in future we will add them as they are requested). And in parallel having a "Danger Zone" `kubeletExtraArgs *string` field which will allow the user to override everything. If `kubeletExtraArgs` is set, all typed values are ignored. I agree however with @rfranzke and his concerns on the potential extra effort in ops for us especially after upgrades.

2019-05-29 06:00 UTC, rfranzke commented
> So my point is not to invest into something that doesn't deliver what we hope for. 

That's true, we can't solve the problem to full extent/prevent all problems with the configuration, however, I think we can still cover a large portion of configuration issues by exposing the flags in the API (instead of allowing everything).

> And in parallel having a "Danger Zone" kubeletExtraArgs *string field which will allow the user to override everything.

Well, then it doesn't make sense to expose the flags individually. If we want to have that, then we should only have that, otherwise maintaining this kubelet block gets even more complicated.

2019-05-29 06:28 UTC, afritzler commented
Well I guess then we should stick to the individual flags. And add more upon request.

2019-05-29 06:43 UTC, vlerenc commented
OK, if you prefer the guarded approach, then we do that. This means:
- We have to get every required/requested flag in separately
- We have to keep track for which Kubernetes version they apply
- We may have bad feelings about alpha flags, but if there is a justified need, it's Gardener's strength to allow for this configurability, so we'll do that as well 

Consequently:
- Add `cpuCFSQuota` (may be true or false), because that's what @afritzler requires
- Add `cpuManagerPolicy`(may be `none` or `static`), because that's what @freegroup requires 
- Add `clusterDNS` (may be comma-separated list of DNS server IP addresses), because that's what another stakeholder requires

In addition please launch the `kubelet` always with the `$KUBELET_EXTRA_ARGS` just like `kubeadm`. This way our end users don't have to work around our reconciliation too hard, but can via daemon set inject/set the env var before the `kubelet` launches. They can do that anyway, we will not promote it, but I want them not to struggle too hard and make assumptions about our implementation details so that we remain free to change them anytime. Let's not go into the discussion, that they can't make these assumptions. That we are "right" doesn't help later when we change it and their workload fails and we have a nasty discussion. I always want to have an ace up our sleeves, so that they can help themselves and don't depend on us too much and this looks like a smart way to achieve that and a compromise hopefully concluding our discussion.

I hope you agree?

2019-05-29 09:07 UTC, adracus commented
I guess the guarded approach does not only bring us less ops effort, it also allows us to do proper upgrades in the future - what if, for instance, some flag ceases to exist in a certain version or is renamed? With the guarded approach, we can do the migration depending on the Kubernetes version of a Shoot without the user having to manually interfere.

About launching with `KUBELET_EXTRA_ARGS`: How should anybody be able to change that at runtime? The kubelet is launched by the operating system as a regular process and thus cannot be altered like any other pod. Even if a user deploys a `DaemonSet` on a cluster, changing the environment of a running process is not really possible / would involve a restart of the kubelet which again might to extra harm + will be overridden as soon as the operating system config controller reconciles.

2019-05-29 09:15 UTC, vlerenc commented
> About launching with KUBELET_EXTRA_ARGS: How should anybody be able to change that at runtime? The kubelet is launched by the operating system as a regular process and thus cannot be altered like any other pod. Even if a user deploys a DaemonSet on a cluster, changing the environment of a running process is not really possible / would involve a restart of the kubelet which again might to extra harm + will be overridden as soon as the operating system config controller reconciles.

Don't worry, people know how to do that - and more. The screenshot I showed in #996 was a real one. They even tricked/tweaked our update/reconciliation behaviour and restarted the machine. Please add the flag, so that they don't have to do that anymore to the extent they had to work around us in the past. I don't want them to do that, for their and our sake (their solution exploited our implementation details, which is not in our interest, whoever is "right" here).

2019-05-31 11:05 UTC, rfranzke requested changes
Two small suggestions to improve readability

2019-05-31 11:05 UTC, rfranzke commented on charts/seed-operatingsystemconfig/original/templates/kubelet/_kubelet-config-file
>  cpuCFSQuota: true
```suggestion
cpuCFSQuota: {{ .Values.kubernetes.kubelet.cpuCFSQuota }}
```

2019-05-31 11:05 UTC, rfranzke commented on charts/seed-operatingsystemconfig/original/values.yaml
> +#   cpuCFSQuota: true
```suggestion
    cpuCFSQuota: true
```

2019-05-31 11:18 UTC, rfranzke approved these changes
/lgtm

2019-05-31 11:18 UTC, rfranzke commented
The `KUBELET_EXTRA_ARGS` should be handled by a different PR, so let's merge this one now. Also, maybe we should have another discussion about the flag anyways.

2019-05-31 11:28 UTC, merged

2019-06-03 03:06 UTC, vlerenc commented
@afritzler @rfranzke Should we disable CPU throttling for our seeds now? Just wondering, because I have seen this recommended many times:
- https://github.com/kubernetes/kubernetes/issues/67577
- https://github.com/kubernetes/kubernetes/issues/70585
- https://github.com/hjacobs/kubernetes-failure-stories -> https://www.youtube.com/watch?v=6sDTB4eV4F8 (from minute 21:20)

2019-06-03 08:15 UTC, afritzler commented
This might help with etcd and kube-apiserver ... but this is just a gut feeling. We could try this in dev and compare the latency metrics.

2019-06-03 08:40 UTC, vlerenc commented
Yes, please.