gardener.unprivileged PSP default seccomp profile
gardener/gardener pull request #1048
Opened 2019-05-29 13:19 UTC by mvladev

**What this PR does / why we need it**:

The `PodSecurityPolicy` `gardener.unprivileged` now has a default seccomp policy `runtime/default` for clusters `>= 1.11` and `docker/default` for clusters `< 1.11`.
See https://github.com/kubernetes/kubernetes/pull/62662 for more info.

Allowed seccomp profiles now include `runtime/default` and `docker/default`.

This allows users to explicitly specify `seccomp.security.alpha.kubernetes.io/pod: runtime/default` as annotation on their Pods.

**Which issue(s) this PR fixes**:
n/a

**Special notes for your reviewer**:
n/a

**Release note**:

```improvement operator
`PodSecurityPolicy` `gardener.unprivileged` now has a default seccomp policy `runtime/default` for clusters `>= 1.11` and `docker/default` for clusters `< 1.11`.
```

```action user
`PodSecurityPolicy` `gardener.unprivileged` now uses the default docker seccomp policy (https://docs.docker.com/engine/security/seccomp/). 
If privileged containers are disabled with `.spec.kubernetes.allowPrivilegedContainers: false` and blocked system calls are used by containers, then a new `PodSecurity` policy needs to be created, allowing `unconfined` seccomp access. See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp.
```

2019-05-29 13:23 UTC, mvladev commented
/cc @marwinski @holgpar

2019-06-03 06:57 UTC, adracus requested changes
```
The PodSecurityPolicy "gardener.unprivileged" is invalid: metadata.annotations[seccomp.security.alpha.kubernetes.io/allowedProfileNames]: Invalid value: "runtime/default": must be a valid seccomp profile
```
PSP could not be created on a `1.10.x` cluster - I guess you'll have to remove `runtime/default` from the list of allowed profiles for `< 1.11`

2019-06-04 07:48 UTC, mvladev commented
Updated @adracus have another look.

2019-06-04 07:51 UTC, adracus approved these changes
/lgtm

2019-06-04 08:04 UTC, merged