[operator] Add extension `required` controller
gardener/gardener pull request #10650
Opened 2024-10-14 08:31 UTC by timuthy

**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
This PR adds a new `required` controller to `gardener-operator`. The controller maintains a `RequiredRuntime` condition for `Extensions`s to declare the runtime part of the extension as being required in the Garden Runtime cluster.

**Which issue(s) this PR fixes**:
Part of #9635

**Special notes for your reviewer**:
An enhancement is planned for the very same controller, to maintain another `Required` condition which indicates the extension is required for seed/shoot clusters (based on `ControllerInstallation` status).

**Release note**:

```noteworthy operator
A new `required` controller was added to `gardener-operator`. It maintains the `RequiredRuntime` condition for `Extension` resources to indicate that the extension deployment is required in the Garden-Runtime cluster.
```

2024-10-15 05:31 UTC, timuthy commented
/retest-required

2024-10-15 08:27 UTC, rfranzke commented
/assign

2024-10-16 12:53 UTC, MartinWeindel requested changes
If the Garden runtime cluster is also used as seed, the required controller should not react on resources of the seed. The mapper should check if the extension class name is `garden`.

2024-10-16 12:53 UTC, MartinWeindel commented on pkg/operator/controller/extension/required/add.go
> +			newRequiredTypes.Insert(obj.GetExtensionSpec().GetExtensionType())
It should only react on resources with `ExtensionClassName` =`garden`

```suggestion
			if ptr.Deref(obj.GetExtensionSpec().GetExtensionClass(), "") == extensionsv1alpha1.ExtensionClassGarden {
				newRequiredTypes.Insert(obj.GetExtensionSpec().GetExtensionType())
			}			
```

2024-10-17 08:00 UTC, oliver-goetz reviewed
Thanks for this well structured PR 😄 

Apart from my remarks, I found an incorrect description in the Extension API ([ref](https://github.com/gardener/gardener/blob/662a919b986e19a5efe01b28a2fc1d4469d36a29/pkg/apis/operator/v1alpha1/types_extension.go#L75-L76)). It is related to the `required` topic, so maybe you could fix it in this PR.

2024-10-17 08:00 UTC, oliver-goetz commented on pkg/operator/controller/extension/required/add.go
> +	}
Before, these watches have been started later if a `Garden` resource was found. This was done, because the CRDs do not exist, if there is no `Garden`.
Now, the operator would crash after a while when there is no `Garden` because it cannot establish these watches.

2024-10-17 08:00 UTC, oliver-goetz commented on pkg/operator/controller/extension/required/reconciler.go
> +		return reconcile.Result{}, fmt.Errorf("could not update extension statsus: %w", err)
```suggestion
		return reconcile.Result{}, fmt.Errorf("could not update extension status: %w", err)
```

2024-10-17 09:00 UTC, MartinWeindel commented on pkg/operator/controller/extension/required/reconciler.go
> +		if _, ok := r.KindToRequiredTypes[ext.objectKind]; !ok {
```suggestion
		r.Lock.RLock()
		_, ok := r.KindToRequiredTypes[ext.objectKind]
		r.Lock.RUnlock()
		if !ok {
```

2024-10-17 11:24 UTC, timuthy commented on pkg/operator/controller/extension/required/add.go
> +	}
In this PR, I shifted the registration of the controller to the `controller-registrar` controller (see [here](https://github.com/gardener/gardener/pull/10650/files#diff-02d0e39f294cb59e08ebcff27dc912a1d664ab8e257e1da6f62f2258ac1f06d7R72)). The registration is deferred until the `Garden` resource is created.

2024-10-17 11:50 UTC, timuthy commented on pkg/operator/controller/extension/required/add.go
> +	}
Nice catch, thank you. I added it to the predicates, though.

https://github.com/gardener/gardener/pull/10650/commits/2623f0cc603d6eff213547fb0fff1fc7d3b5d50d#diff-4c0e1e7e46da0bbcd073eed254fbacee8eae379dc0b89ba4b1614c33bab05c6bR95

2024-10-18 07:25 UTC, timuthy commented
/retest-required

2024-10-21 11:41 UTC, MartinWeindel commented
lgtm

2024-10-21 12:02 UTC, timuthy commented
/retest-required

2024-10-21 12:41 UTC, rfranzke commented on docs/concepts/operator.md
> +### [`Main` Reconciler](../../pkg/operator/controller/extension/extension)
```suggestion
#### [`Main` Reconciler](../../pkg/operator/controller/extension/extension)
```

2024-10-21 12:41 UTC, rfranzke commented on docs/concepts/operator.md
> +### [`Required` Reconciler](../../pkg/operator/controller/extension/required)
```suggestion
#### [`Required` Reconciler](../../pkg/operator/controller/extension/required)
```

2024-10-21 12:41 UTC, rfranzke commented on docs/concepts/operator.md
> +Based on these resources, and the related `Extension` specification, it is checked if the extension deployement is required in the garden runtime cluster.
```suggestion
Based on these resources and the related `Extension` specification, it is checked if the extension deployment is required in the garden runtime cluster.
```

2024-10-21 12:41 UTC, rfranzke commented on pkg/operator/controller/extension/add.go
> +		return fmt.Errorf("failed adding Extension controller: %w", err)
```suggestion
		return fmt.Errorf("failed adding main reconciler: %w", err)
```

2024-10-21 12:41 UTC, rfranzke commented on pkg/operator/predicate/extension.go
> +func ExtensionRequirementsChanged() predicate.Predicate {
Unit test?

2024-10-21 12:41 UTC, rfranzke commented on pkg/operator/predicate/extension.go
> +			}
Shouldn't `old != nil && new == nil` also return `true`?

2024-10-21 12:41 UTC, rfranzke commented on test/e2e/operator/garden/common.go
> +func defaultBuckupBucket() *extensionsv1alpha1.BackupBucket {
Buckle up! 🏎️

2024-10-21 12:41 UTC, rfranzke commented on test/e2e/operator/garden/create_delete.go
> +			// TODO(oliver-goetz): Remove this step when gardener-operator is able to create its backup bucket and DNS record by itself.
Change to @MartinWeindel?

2024-10-21 12:41 UTC, rfranzke commented on test/e2e/operator/garden/create_delete.go
>  		// TODO(oliver-goetz): Remove this step when gardener-operator is able to create its backup bucket and DNS record by itself.
same here?

2024-10-21 12:41 UTC, rfranzke commented on test/integration/operator/extension/required/required_test.go
> +			})
Add description to expectations in `for` loops, see https://github.com/gardener/gardener/blob/master/docs/development/testing.md#writing-tests-relevant-for-all-kinds

2024-10-21 12:41 UTC, rfranzke commented on test/integration/operator/extension/required/required_test.go
> +		By("Check provider extensions is reported as not required")
```suggestion
		By("Ensure provider extension is reported as not required")
```

2024-10-21 12:41 UTC, rfranzke commented on test/integration/operator/extension/required/required_test.go
> +		By("Check dns extensions is reported as not required")
```suggestion
		By("Check dns extension is reported as not required")
```

2024-10-21 20:05 UTC, timuthy commented
Thanks for your review Mr @rfranzke, PTAL 🙂

2024-10-22 07:26 UTC, rfranzke reviewed
Thanks @timuthy, one last nit

2024-10-22 07:26 UTC, rfranzke commented on pkg/operator/predicate/extension.go
> +				oldRequiredRuntimeCondition != nil && requiredRuntimeCondition == nil {
While this probably works, do you mind adding brackets to make it more clear/readable?

2024-10-22 07:41 UTC, rfranzke reviewed
/lgtm
/approve

2024-10-22 09:08 UTC, merged