Deprecate `gardener/controlplane` Helm chart in favor of `gardener-operator`
gardener/gardener pull request #10706
Opened 2024-10-23 13:13 UTC by rfranzke

**How to categorize this PR?**

/area open-source dev-productivity
/kind enhancement

**What this PR does / why we need it**:
We should only support one approach to reduce operational (and development) complexity. With `gardener-operator`, we have a better way of managing the Gardener control plane, which follows best practises and learnings for operating Gardener from the past 6-7 years.

**Release note**:

```noteworthy operator
The `gardener/controlplane` Helm chart has been deprecated and will be removed after `v1.135` has been released (around beginning of 2026). We urge you to switch to a [`gardener-operator`](https://github.com/gardener/gardener/blob/master/docs/concepts/operator.md)-based installation. Read all about it [here](https://github.com/gardener/gardener/blob/master/docs/concepts/operator.md#migrating-an-existing-gardener-landscape-to-gardener-operator).
```

2024-10-23 14:03 UTC, timuthy reviewed
/lgtm

2024-10-24 10:16 UTC, oliver-goetz commented
`gardener-operator` to the rescue 🥳 
/approve

2024-10-24 10:49 UTC, rfranzke commented
FYI @majst01 @Gerrit91 @lotharbach

2024-10-24 10:52 UTC, LucaBernstein requested changes

2024-10-24 10:52 UTC, LucaBernstein commented on docs/deployment/setup_gardener.md
> +> Below approach is deprecated and will be removed at after v1.135 of Gardener has been released (around beginning of 2026).
```suggestion
> Below approach is deprecated and will be removed after v1.135 of Gardener has been released (around beginning of 2026).
```

or is it intentional?

2024-10-24 10:52 UTC, LucaBernstein commented on charts/gardener/controlplane/README.md
> +> It will be removed at after v1.135 of Gardener has been released (around beginning of 2026).
```suggestion
> It will be removed after v1.135 of Gardener has been released (around beginning of 2026).
```

2024-10-24 10:54 UTC, LucaBernstein reviewed
Awesome, thank you! 🚀 

/lgtm

2024-10-24 12:31 UTC, berendt commented
That also works for us. We are already preparing everything for the changeover to the operator.

2024-10-24 13:43 UTC, merged