ClusterAutoscaler: Add support for startupTaints and statusTaints
gardener/gardener pull request #10858
Opened 2024-11-14 15:09 UTC by dhague

Deprecate ignoreTaints

**How to categorize this PR?**
/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
The --ignore-taints flag mentioned in https://github.com/gardener/gardener/issues/5166 [is now deprecated](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#ignore-taints) in favour of --startup-taints and its semantics have changed accordingly, such that any nodes with such a taint are considered unready by the cluster autoscaler (CA). This can cause the CA to stop working entirely if there are too many nodes with such taints.
Access to the new flag --status-taints is needed in order to restore the original functionality where the CA ignores the taint, but it does not affect the CA's view of node readiness.

**Which issue(s) this PR fixes**:
Fixes #10844

**Special notes for your reviewer**:

**Release note**:
```feature user
shoot spec.kubernetes.clusterAutoscaler: Add support for startupTaints and statusTaints
```

2024-11-18 16:22 UTC, oliver-goetz requested changes
Thanks for your PR 😄

2024-11-18 16:22 UTC, oliver-goetz commented on pkg/apis/core/v1beta1/types_shoot.go
> -	IgnoreTaints []string `json:"ignoreTaints,omitempty" protobuf:"bytes,10,opt,name=ignoreTaints"`
You must not change protobuf field numbers ([see docs](https://github.com/gardener/gardener/blob/master/docs/development/changing-the-api.md#changing-the-api-1)). Please keep it consistent and append the new fields.

2024-11-18 16:22 UTC, oliver-goetz commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// Deprecated: Ignore taints are now deprecated and treated as startup taints.
I don't think we should already deprecate this field until we drop support for Kubernetes 1.28. `IgnoreTaints` seems to be the only config option for Kubernetes <= v1.28.

2024-11-18 16:22 UTC, oliver-goetz commented on pkg/apis/core/validation/shoot.go
> +	}
I briefly scanned the cluster-autoscaler and it seems that these new flags are available for Kubernetes >= v1.29 only (see the flags for [cluster-autoscaler v1.28](https://github.com/gardener/autoscaler/blob/8d9feda527ed620d5fb3195246db08472b273b05/cluster-autoscaler/main.go#L195)). Gardener still supports older versions, so the Kubernetes version should be verified too, when these new taints are used.

2024-11-19 14:48 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +func validateClusterAutoscalerStartupStatusIgnoreTaints(taints []string, fldPath *field.Path) field.ErrorList {
```suggestion
func validateClusterAutoscalerTaints(taints []string, fldPath *field.Path) field.ErrorList {
```

2024-11-19 14:48 UTC, rfranzke commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
> +		configStartupStatusIgnoreTaints           = []string{"taint-1", "taint-2"}
```suggestion
		configTaints           = []string{"taint-1", "taint-2"}
```

2024-11-19 14:48 UTC, rfranzke commented on pkg/apis/core/types_shoot.go
> +	// Ignore taints are now deprecated and treated as startup taints.
We should forbid setting this field for Kubernetes 1.32 and higher `Shoot`s to make sure we can eventually get rid of it in the `Shoot` API. Please adapt the doc string and implement this kind of validation.

2024-11-22 15:25 UTC, rfranzke commented
/ok-to-test

2024-11-22 15:28 UTC, rfranzke reviewed
/lgtm

2024-11-22 15:28 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +	}
Neat approach :) I like it.

2024-11-22 20:32 UTC, oliver-goetz commented
/approve

2024-11-22 21:26 UTC, merged