Metrics for shoot operating time including dashboard
gardener/gardener pull request #10971
Opened 2024-12-04 10:10 UTC by simcod

**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Introduces the `shoot_operation_duration_seconds` metric exposed via `gardenlet` and adds a grafana dashboard. It is useful for providers to see how long the `shoot` operations `Create` and `Delete` take. 

**Which issue(s) this PR fixes**:
Hackathon: Gardener SLI topic

**Special notes for your reviewer**:

**Release note**:

```feature operator
Introduces `shoot_operation_duration_seconds` metric to record `Shoot` operation `Create` and `Delete`. 
```

2024-12-13 16:26 UTC, timebertt commented
@simcod what is missing to make this PR ready?

2024-12-13 16:55 UTC, timebertt commented
/assign

2024-12-16 09:19 UTC, simcod commented
@timebertt This PR should be ready. But I will look at it this week and remove the draft afterwards.

2025-01-02 08:01 UTC, timebertt requested changes
Nice, thanks for the PR!

2025-01-02 08:01 UTC, timebertt commented on pkg/gardenlet/metrics/metrics.go
> +	Factory = promauto.With(runtimemetrics.Registry)
This variable shouldn't be exposed.
```suggestion
	factory = promauto.With(runtimemetrics.Registry)
```

2025-01-02 08:01 UTC, timebertt commented on pkg/gardenlet/metrics/metrics.go
> +			Help:      "Duration of shoot operations.",
```suggestion
			Help:      "Duration of shoot operations in seconds.",
```

2025-01-02 08:01 UTC, timebertt commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +	var (
This code for reporting the metrics is duplicated. Can you extract a reusable function?
The invocation here should move up to be before line 139 (before the call to `CalculateControllerInfos`).

2025-01-02 08:01 UTC, timebertt commented on pkg/gardenlet/metrics/metrics.go
> +	ShootOperationTimings = Factory.NewHistogramVec(
```suggestion
	ShootOperationDurationSeconds = Factory.NewHistogramVec(
```

2025-01-02 08:01 UTC, timebertt commented on pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
> +      "type": "row"
We could drop this row as the dashboard doesn't have any other "sections".

2025-01-02 08:01 UTC, timebertt commented on pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
> +      "description": "The histogram provides a visual representation of the distribution of create and delete shoot operations.",
If panels visualize a histogram by calculating a specific percentile, the title and description should mention it, so that viewers know what they are looking at.

2025-01-02 08:01 UTC, timebertt commented on pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
> +          "expr": "rate(gardenlet_shoot_operation_duration_seconds_sum{operation=~\"$operation_type\",workerless=~\"$workerless\",hibernated=~\"$hibernated\"}[$__rate_interval]) / rate(gardenlet_shoo
Typically, dashboards either allow selecting a percentile variable out of a few options (like the [Controller Runtime / Controllers](https://github.com/gardener/gardener/blob/b6b857890afabfa10c75a2016f3f02ddde5762a6/pkg/component/observability/plutono/dashboards/common/controllers.json) dashboard) or visualize three percentiles next to each other over time (like the [Controller Runtime / Controller Details](https://github.com/gardener/gardener/blob/master/pkg/component/observability/plutono/dashboards/common/controller-details.json) dashboard).

Can you do either option on this dashboard?

2025-01-02 08:01 UTC, timebertt commented on pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
> +          "legendFormat": "{{workerless}}",
This looks off. Why is the `workerless` label used as a legend?

2025-01-02 08:03 UTC, timebertt commented on pkg/gardenlet/metrics/metrics.go
> +			Name:      "shoot_operation_duration_seconds",
Can you add the `shoot_.+` metrics to the allowlist for collecting metrics in the performance prometheus in CI? [ref](https://github.com/gardener/gardener/blob/b6b857890afabfa10c75a2016f3f02ddde5762a6/pkg/provider-local/webhook/prometheus/mutator.go#L61)

2025-01-17 14:14 UTC, simcod commented on pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
> +          "legendFormat": "{{workerless}}",
Currently, it is possible to select workerless and non workerless clusters at once. Thus, I used the `workerless` label for clarification, when both are being displayed. Perhaps it would be better not to provide a multi-selection?

2025-01-20 15:08 UTC, timebertt reviewed
Mostly nits left :)

2025-01-20 15:08 UTC, timebertt commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +	reportMetrics(shoot, operationType, r.Clock.Now().UTC().Sub(shoot.CreationTimestamp.Time).Seconds())
We could use the creation timestamp in UTC – just to be sure.
```suggestion
	reportMetrics(shoot, operationType, r.Clock.Now().UTC().Sub(shoot.CreationTimestamp.UTC()).Seconds())
```

2025-01-20 15:08 UTC, timebertt commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +
Nit, remove the empty line at the start of the function (also reported by the linter in `make check`)
```suggestion
```

2025-01-20 15:08 UTC, timebertt commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +func reportMetrics(shoot *gardencorev1beta1.Shoot, operationType gardencorev1beta1.LastOperationType, duration float64) {
I suggest passing the duration as `time.Duration`, which is clearer than expecting the duration in seconds.

2025-01-20 15:08 UTC, timebertt commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +	if shoot.Spec.Hibernation != nil && shoot.Spec.Hibernation.Enabled != nil && *shoot.Spec.Hibernation.Enabled {
`v1beta1helper.HibernationIsEnabled` seems to do the same, you could use the helper function.

2025-01-20 15:08 UTC, timebertt commented on pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
> +          "legendFormat": "{{workerless}}",
Hmm, the legend is not displayed in the guage panel at all.
Probably we can just leave the `legendFormat` unspecified/at its default.

2025-01-20 15:08 UTC, timebertt commented on pkg/component/observability/plutono/dashboards/seed/shoot-operation-duration.json
> +            "true"
Nit: the default values of the `workerless` variable should probably be `false`.

2025-02-04 06:21 UTC, simcod commented
/retest

2025-02-05 06:43 UTC, timebertt approved these changes
Thanks a lot, let's get this in :) 
/retest

2025-02-05 07:30 UTC, LucaBernstein requested changes

2025-02-05 07:30 UTC, LucaBernstein commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +	}
we could replace this with `IifString()`, what do you think? E.g.:

```
var (
    workerless = IifString(v1beta1helper.IsWorkerless(shoot), "true", "false")
    ...
)
```

2025-02-05 07:34 UTC, LucaBernstein reviewed
another nit.

2025-02-05 07:34 UTC, LucaBernstein commented on pkg/provider-local/webhook/prometheus/mutator.go
> +					Regex:        "(up|flow_.+|shoot_.+)",
Comparing with `pkg/utils/flow/metrics.go`, shouldn't this rather be `gardenlet_.+`?
```suggestion
					Regex:        "(up|flow_.+|gardenlet_.+)",
```

2025-02-05 10:54 UTC, simcod commented on pkg/provider-local/webhook/prometheus/mutator.go
> +					Regex:        "(up|flow_.+|shoot_.+)",
I thought it should be `shoot_.+` because of the metric name.
@timebertt What do you think?

2025-02-05 11:50 UTC, timebertt commented on pkg/provider-local/webhook/prometheus/mutator.go
> +					Regex:        "(up|flow_.+|shoot_.+)",
@LucaBernstein is right, the metric names start with `gardener_shoot_`

2025-02-05 19:12 UTC, simcod commented
/retest

2025-02-06 10:39 UTC, timebertt approved these changes

2025-02-06 13:26 UTC, tobschli commented
/hold
until #11317 is merged, as it is quite urgent.

2025-02-06 14:32 UTC, tobschli commented
/unhold
Sorry for the inconvenience.

2025-02-06 15:46 UTC, timebertt commented
/retest

2025-02-06 17:07 UTC, simcod commented
/retest

2025-02-07 13:28 UTC, merged