`token-requestor`: Optionally support injecting CABundle into the secret
gardener/gardener pull request #10988
Opened 2024-12-05 18:10 UTC by maboehm

**How to categorize this PR?**
/area usability
/kind enhancement

**What this PR does / why we need it**:
Adds support for an optional annotation to the `TokenRequestor` ( `serviceaccount.resources.gardener.cloud/inject-ca-bundle` ), which, when set, instructs the `TokenRequestor` to inject the CABundle in addition to the requested token. Either directly into the `kubeconfig`s current cluster, or as a separate secret key `bundle.crt`.

The source of truth is the token requestors own client's CA. During certificate rotation the resource manager itself should restart (since it has a hash annotation for the mounted ca-bundle), and should therefore "fix" all secrets on the next reconciliation.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Part of the Winter Hackathon https://github.com/gardener-community/hackathon/tree/main/2024-12_Schelklingen

**Release note**:
```feature operator
Secrets for the `TokenRequestor` can be additionally annotated with `serviceaccount.resources.gardener.cloud/inject-ca-bundle=true` to get the current CA bundle injected as well
```

2024-12-05 18:14 UTC, maboehm commented on test/integration/resourcemanager/tokenrequestor/tokenrequestor_test.go
> -			Expect(testClient.Get(ctx, client.ObjectKeyFromObject(secret), secret)).To(Succeed())
I believe this was potentially flaky as the secret might not exist yet, when the ServiceAccount is first observed. To I put the entire thing into an `Eventually()` block and decided to wait for the controller to set the renew timestamp as an indicator for it actually being done.

2024-12-05 21:50 UTC, rfranzke commented
/cc @Nuckal777

2024-12-09 13:10 UTC, rfranzke requested changes
/ok-to-test

Can you augment the [docs](https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#tokenrequestor-controller), please?

2024-12-09 13:10 UTC, rfranzke commented on pkg/apis/resources/v1alpha1/types.go
> +	DataKeyCaBundle = "bundle.crt"
```suggestion
	DataKeyCABundle = "bundle.crt"
```

2024-12-09 13:10 UTC, rfranzke commented on pkg/controller/tokenrequestor/reconciler.go
> +	kc, err := decodeKubeconfig(data[resourcesv1alpha1.DataKeyKubeconfig])
```suggestion

	kubeconfig, err := decodeKubeconfig(data[resourcesv1alpha1.DataKeyKubeconfig])
```

2024-12-09 13:10 UTC, rfranzke commented on pkg/controller/tokenrequestor/reconciler.go
> +	cluster, err := getCluster(kc)
```suggestion

	cluster, err := getCluster(kc)
```

2024-12-09 13:10 UTC, rfranzke commented on pkg/controller/tokenrequestor/reconciler.go
> +	return bytes.Equal(cluster.CertificateAuthorityData, r.CAData), nil
```suggestion

	return bytes.Equal(cluster.CertificateAuthorityData, r.CAData), nil
```

2024-12-09 13:10 UTC, rfranzke commented on pkg/controller/tokenrequestor/reconciler.go
> +func (r *Reconciler) isBundleOk(data map[string][]byte) (bool, error) {
```suggestion
func (r *Reconciler) isCABundleUpdated(data map[string][]byte) (bool, error) {
```

WDYT?

2024-12-09 13:10 UTC, rfranzke commented on pkg/controller/tokenrequestor/reconciler.go
> +	return nil, fmt.Errorf("did not find cluster of current context named %s", ctx.Cluster)
```suggestion

	for i, cluster := range kubeconfig.Clusters {
		if cluster.Name == ctx.Cluster {
			return &kubeconfig.Clusters[i].Cluster, nil
		}
	}

	return nil, fmt.Errorf("did not find cluster of current context named %s", ctx.Cluster)
```

2024-12-09 15:34 UTC, maboehm commented
`pull-gardener-e2e-kind-operator-seed` failed twice but at completely different points. Dont think my change affects any e2e tests, assuming they are just flakes
/retest

2024-12-10 08:14 UTC, rfranzke commented on docs/concepts/resource-manager.md
> +serviceaccount.resources.gardener.cloud/inject-ca-bundle: "true
```suggestion
serviceaccount.resources.gardener.cloud/inject-ca-bundle: "true"
```

2024-12-10 08:14 UTC, rfranzke commented on docs/concepts/resource-manager.md
> +Otherwise, the bundle is stored in an additional secret key `bundle.crt`
```suggestion
Otherwise, the bundle is stored in an additional secret key `bundle.crt`.
```

2024-12-10 08:30 UTC, rfranzke reviewed
/lgtm
/approve

2024-12-10 14:11 UTC, merged