[node-agent] Perform hosts probing on `RegistryConfig.Hosts` change
gardener/gardener pull request #11008
Opened 2024-12-10 09:24 UTC by dimitar-kostadinov

**How to categorize this PR?**

/area robustness
/kind enhancement

**What this PR does / why we need it**:
There are cases where `RegistryConfig.Hosts` is changed, e.g. `CACerts` is added or rotated, the mirror `URL` is updated, etc. Is such cases the hosts probing should be performed to ensure that new configuration is valid.

**Which issue(s) this PR fixes**:
Part of [gardener-extension-registry-cache/issues/290](https://github.com/gardener/gardener-extension-registry-cache/issues/290)

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
`gardener-node-agent` now performs host probing when `RegistryConfig.Hosts` changes.
```

2024-12-10 09:44 UTC, ialidzhikov commented
/assign

2024-12-13 07:48 UTC, Kostov6 reviewed
Nit

2024-12-13 07:48 UTC, Kostov6 commented on pkg/nodeagent/controller/operatingsystemconfig/changes.go
> +	for i := 0; i < len(newRegistries); i++ {
```suggestion
	for i := range newRegistries {
```

2025-01-06 09:21 UTC, ialidzhikov commented
/remove-lifecycle stale

2025-01-14 12:36 UTC, ialidzhikov requested changes

2025-01-14 12:36 UTC, ialidzhikov commented on pkg/nodeagent/controller/operatingsystemconfig/changes.go
> +}
There should be better ways to do achieve this.

Right now, you are modifying the readinessProbe field of the registry config fetched from the OSC. It looks like hack/anti-pattern to modify the desired state of your object.

Instead:
- You could store in https://github.com/gardener/gardener/blob/1c09b7654a6b5edc6c5223a495e02742fb495c00/pkg/nodeagent/controller/operatingsystemconfig/changes.go#L83 a field with registry upstreams to probe.
- Check how files are being applied - https://github.com/gardener/gardener/blob/1c09b7654a6b5edc6c5223a495e02742fb495c00/pkg/nodeagent/controller/operatingsystemconfig/changes.go#L71. It looks like `changed` files are set to new files on the initial reconciliation. After that, `changed` files contains only the changed files. Can something similar work for registries as well? If yes, we could always probe the changed registries.

2025-01-14 14:12 UTC, ialidzhikov commented on pkg/nodeagent/controller/operatingsystemconfig/changes.go
> +}
https://github.com/ialidzhikov/gardener/tree/enh/node_agent_osc_hosts_probing-poc: PoC for applying the registries similar to how files are applied (the 2nd bullet from https://github.com/gardener/gardener/pull/11008#discussion_r1914745275).

2025-02-06 13:02 UTC, ialidzhikov commented
/remove-lifecycle stale

2025-02-25 10:33 UTC, rfranzke commented
Hi folks, what is the status of this PR?

2025-02-27 14:17 UTC, dimitar-kostadinov commented
/retest-required

2025-03-17 07:41 UTC, ialidzhikov commented
/remove-lifecycle stale

2025-03-25 11:31 UTC, Kostov6 reviewed
I think using a map makes the code more readable
```golang
func computeContainerdRegistryDiffs(newRegistries, oldRegistries []extensionsv1alpha1.RegistryConfig) containerdRegistries {
	r := containerdRegistries{
		Desired: newRegistries,
	}

	// mapping to pointer to be able to modify r.Desired directly
	upstreamToNewRegistry := map[string]*extensionsv1alpha1.RegistryConfig{}
	for _, newRegistry := range newRegistries {
		upstreamToNewRegistry[newRegistry.Upstream] = &newRegistry
	}

	for _, oldRegistry := range oldRegistries {
		if newRegistry, exists := upstreamToNewRegistry[oldRegistry.Upstream]; !exists {
			r.Deleted = append(r.Deleted, oldRegistry)
		} else if ptr.Deref(newRegistry.ReadinessProbe, false) && apiequality.Semantic.DeepEqual(oldRegistry, *newRegistry) {
			// suppress host probing because no changes were detected
			newRegistry.ReadinessProbe = ptr.To(false)
		}
	}

	return r
}
```

2025-04-07 06:35 UTC, ialidzhikov commented
Hi folks,

Sorry for not managing to look into this PR for weeks. I will try to have a look this week.

@rfranzke @timuthy I was unsure about the approach. In https://github.com/gardener/gardener/pull/11008/files#diff-9fc142ed2202852143feba4ee95d1308b41692b51d5452a5ef923b512eea9bacR334-R346, we overwrite the registries readinessProbe field based on whether there is a change in the in the registry config or not. I know that this won't lead to any overwrite or update of the OSC resource in the cluster however I am unsure if it is a best practice or not.

For that reason, in https://github.com/gardener/gardener/pull/11008#discussion_r1914745275 I suggested to do the same we do for applying files - back then only changed files were applied. However, this approach has the drawback that only changed registries are applied on reconciliation and for example if end user deletes manually the hosts.toml file, it won't be recreated by the OSC reconciliation.

Do you have a preference - are you ok with this approach (overwriting the OSC registry config readinessProbe field) or should we track in the struct the changed registries and execute the readinessProbe for them?

2025-04-08 08:23 UTC, timuthy commented
Thanks for the summary @ialidzhikov. How about if we in addition keep track of the changed registries in the `containerdRegistries` struct that should be considered for probing?

2025-04-10 13:58 UTC, dimitar-kostadinov commented
> In https://github.com/gardener/gardener/pull/11008/files#diff-9fc142ed2202852143feba4ee95d1308b41692b51d5452a5ef923b512eea9bacR334-R346, we overwrite the registries readinessProbe field based on whether there is a change in the in the registry config or not.

Just to clarify, we are not actually overwriting the readinessProbe field, but rather generate a slice of desired containerd registers with calculated readinessProbe value. Note that the readinessProbe value has been changed in a copy of RegistryConfig: https://go.dev/tour/moretypes/16.

2025-04-11 08:38 UTC, timuthy commented
Thanks @dimitar-kostadinov, I think that's for sure.

We were more afraid if it's a valid shortcut to take, right @ialidzhikov? WDYT about https://github.com/gardener/gardener/pull/11008#issuecomment-2785637327?

2025-04-11 14:54 UTC, ialidzhikov commented
Hey 👋 

In https://github.com/ialidzhikov/gardener/tree/enh/registry-readiness-probe I did a PoC which is based on the suggestion in https://github.com/gardener/gardener/pull/11008#issuecomment-2785637327. 

See https://github.com/gardener/gardener-extension-registry-cache/pull/391#issuecomment-2796941779 - it turns out that we now need this fix to be able to vendor successfully Gardener v1.116.1 in the registry-cache extension. Another new version of Gardener that breaks registry-cache e2e tests. 🫠

2025-04-16 12:04 UTC, closed without merging