Support CA's priority expander config in `Shoot`s `Worker` spec
gardener/gardener pull request #11045
Opened 2024-12-16 14:06 UTC by tobschli

**How to categorize this PR?**

/area usability
/kind api-change

**What this PR does / why we need it**:
When creating a `Shoot`, it is currently not possible to directly pass the desired priority expander configuration ([ref](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md?rgh-link-date=2024-11-19T15%3A24%3A32Z)) before the first node of a shoot is ready.

This PR adapts the `Shoot` spec in a way, that it is possible to specify the priority of`Worker` groups like the following:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: example-shoot
  namespace: garden-example
spec:
  provider:
    type: local
    workers:
    - name: local
      priority: 40 # priority of this worker group
      machine:
        type: local
    - name: local2
      machine:
        type: local
```

The field is optional.
When no priority is defined within the `Worker` groups, nothing happens and the CA gets deployed as usual.

Only when at least one priority is specified within the `Worker`s,  the `priority-expander` `ConfigMap` is generated and deployed to the `Shoot`.
This also entails, that the `priority` expander is enabled as the first expander in the CA configuration.
For every `Worker` group that has no priority defined, `0` is implied.

For the aforementioned `Shoot` definition, the generated `ConfigMap` will look like this:
```yaml
priorities: |
  "0":
  - shoot--local--local.shoot--local--local-local2
  "40":
  - shoot--local--local.shoot--local--local-local
```

**Which issue(s) this PR fixes**:
Fixes #10683

**Special notes for your reviewer**:
As the passing of the priority information happens through the extension API, the extensions need to be revendored to support this feature.
**Release note**:

```other user
It is now possible to specify the the priority of worker groups with the `Shoot.spec.provider.workers[].priority` field. When at least one priority is specified, the CA will respect this configuration before other expanders.
WARNING: When using this feature, Gardener will overwrite existing configurations that were made manual beforehand.
```

2024-12-16 16:49 UTC, tobschli commented
/retest

2024-12-17 09:08 UTC, plkokanov requested changes
Nice PR!

What about also updating https://github.com/gardener/gardener/blob/fdce0541184cfb42c43b420f544b6ef5cb95f5d8/docs/usage/high-availability/shoot_high_availability_best_practices.md?plain=1#L66 to include the new way with which priorities can be specified?

2024-12-17 09:08 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +	if c.workersHavePriorityConfigured() {
You can assign this to a variable so that the loop is only executed once.

2024-12-17 09:08 UTC, plkokanov commented on pkg/provider-local/controller/worker/machines.go
> +			Priority:                     *pool.Priority,
```suggestion
			Priority:                     ptr.Deref(pool.Priority, 0),
```

And you could remove the `if` check from line 149.

2024-12-17 09:08 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +		expanderMode = "priority," + expanderMode
According to the cluster-autoscaler documentation

> an expander must not appear in the list more than once.

Since people are already using the `priority` expander: https://github.com/gardener/gardener/blob/fdce0541184cfb42c43b420f544b6ef5cb95f5d8/pkg/apis/core/v1beta1/types_shoot.go#L670
This could result in `expanderMode = priority,priority`

I'm not sure if specifying two expanders with the same name will lead to crashes, but if that's the case, we should perhaps reuse the `.clusterAutoscaler.expander` field and create the expander `ConfigMap` only if it is `priority`.

Alternatively, we could add validation to ensure that `expanderMode` is not `priority` when a worker pool has a value for its `.priority` field, which seems a bit misleading to me.

In any case, this should be properly documented.

2024-12-17 09:08 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
> +		workerConfig = []gardencorev1beta1.Worker{
You could also add a test by passing a non-empty `workerConfig` that does not have priorities set.

2024-12-18 13:25 UTC, tobschli commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +		expanderMode = "priority," + expanderMode
Oh, yeah!

I am also not in favor of the validation approach, but on the other hand I also would not want to have the approach that priorities are only respected when the `expanderMode` is set to include the priority expander.

I also don't know a better approach unfortunately.
Maybe @rfranzke has one?

2024-12-20 08:22 UTC, tobschli commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +		expanderMode = "priority," + expanderMode
@rfranzke proposed the idea of checking whether the user has already specified the `priority` expander in the expander option.
- If yes, we do not modify the CLI flag.
- In the case they didn't, we prepend the `priority` expander to the flag.

2025-01-07 11:47 UTC, plkokanov requested changes
Sorry for the late re-review.

Could you add the new `spec.provider.workers[].priority` field as a comment to https://github.com/gardener/gardener/blob/1c6f30a0b8d0eb6cf67971893ec9dd3ecdc69b9b/example/90-shoot.yaml#L31

2025-01-07 11:47 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +	if strings.Contains(expander, string(expanderConfig)) {
This should be the other way around :)
```suggestion
	if strings.Contains(string(expanderConfig), expander) {
```

Could we also add a small test case to cover this function.

2025-01-07 11:47 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +		priorities[machineDeployment.Priority] = append(priorities[machineDeployment.Priority], fmt.Sprintf("%s.%s", c.namespace, machineDeployment.Name))
```suggestion
		priorities[machineDeployment.Priority] = append(priorities[machineDeployment.Priority], fmt.Sprintf("%s\\.%s", c.namespace, machineDeployment.Name))
```

CA expects this to be a regular expression, so shouldn't the `.` be escaped?

2025-01-07 15:32 UTC, tobschli commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +	if strings.Contains(expander, string(expanderConfig)) {
Sorry for that!

I see two options for creating this test case:
1. Export the function and explicitly test it
2. Introduce even more variables in the existing `Deploy` test.

Against the `1.` stands the argument that, other than testing, we do not _need_ to export the function.
But on the other hand `2.` is not a very beautiful solution as well, as the test is already quite complicated and this would make it even harder to understand IMO.

Am I missing a third option / what do you think?

2025-01-08 12:18 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +	if strings.Contains(expander, string(expanderConfig)) {
I was thinking something more towards `2.`. You're right that the test has some complexity issues, but a possible change like this doesn't seem too complex, I think:
```diff
diff --git a/pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go b/pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
index 52f0bb3fd6..19b4525e41 100644
--- a/pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
+++ b/pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
@@ -257,7 +257,7 @@ var _ = Describe("ClusterAutoscaler", func() {
                        },
                        Type: corev1.SecretTypeOpaque,
                }
-               deploymentFor = func(withConfig bool, withWorkerPriority bool) *appsv1.Deployment {
+               deploymentFor = func(withConfig, withWorkerPriority bool) *appsv1.Deployment {
                        var commandConfigFlags []string
 
                        expander := string(configExpander)
@@ -633,11 +633,14 @@ var _ = Describe("ClusterAutoscaler", func() {
 
        Describe("#Deploy", func() {
                Context("should successfully deploy all the resources", func() {
-                       test := func(withConfig bool, withWorkerConfig bool, runtimeVersionGreaterEquals126 bool) {
+                       test := func(withConfig bool, withWorkerConfig bool, runtimeVersionGreaterEquals126, withPriorityExpander bool) {
                                var config *gardencorev1beta1.ClusterAutoscaler
                                var shootWorkerConfig []gardencorev1beta1.Worker
                                if withConfig {
-                                       config = configFull
+                                       // Copy `configFull` so that the test doesn't overwrite it.
+                                       config = configFull.DeepCopy()
+                                       if withPriorityExpander {
+                                               config.Expander = ptr.To(gardencorev1beta1.ClusterAutoscalerExpanderPriority + "," + configExpander)
+                                       }
                                }
 
                                if withWorkerConfig {
@@ -709,11 +712,11 @@ var _ = Describe("ClusterAutoscaler", func() {
                                Expect(actualServiceMonitor).To(DeepEqual(serviceMonitor))
                        }
 
-                       It("w/o config", func() { test(false, false, false) })
-                       It("w/ config, kubernetes version < 1.26", func() { test(true, false, false) })
-                       It("w/ config, kubernetes version >= 1.26", func() { test(true, false, true) })
-                       It("w/ config, w/ workerConfig, kubernetes version >= 1.26", func() { test(true, true, true) })
-
+                       It("w/o config", func() { test(false, false, false, false) })
+                       It("w/ config, kubernetes version < 1.26", func() { test(true, false, false, false) })
+                       It("w/ config, kubernetes version >= 1.26", func() { test(true, false, true, false) })
+                       It("w/ config, w/ workerConfig, kubernetes version >= 1.26", func() { test(true, true, true, false) })
+                       It("w/ config, w/ workerConfig, kubernetes version >= 1.26, w/ 'priority' expander already configured", func() { test(true, true, true, true) })
                })
        })
```

2025-01-08 14:11 UTC, tobschli commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +	if strings.Contains(expander, string(expanderConfig)) {
Alright, sounds good :)
Thank you for the insight!

2025-01-09 14:24 UTC, plkokanov requested changes
What is the expectation if users specify `priority` for worker pools but  the corresponding worker extensions still do not support the required functionality? Is it ok for the priority expander `ConfigMap` to contain all 0s as priorities and also overwrite the user provided `ConfigMap`?

2025-01-09 14:24 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +		expanderMode = ensureExpanderInExpanderConfig("priority", expanderMode)
```suggestion
		expanderMode = ensureExpanderInExpanderConfig(gardencorev1beta1.ClusterAutoscalerExpanderPriority, expanderMode)
```

Let's use this also here.

2025-01-09 14:24 UTC, plkokanov commented on pkg/component/extensions/crds/assets/crd-extensions.gardener.cloud_workers.yaml
> +                  - priority
Sorry that I missed this in the previous reviews. 
`priority` is set to required here which will cause an error during the reconciliation of the `Worker`, if the worker extensions are not deployed with support to manage the `priority` field. Basically, when the `MachineDeployment` status is added to the `Worker`'s status, it will not contain the `priority` field and the update will be rejected.

2025-01-09 14:41 UTC, tobschli commented
> What is the expectation if users specify `priority` for worker pools but the corresponding worker extensions still do not support the required functionality? Is it ok for the priority expander `ConfigMap` to contain all 0s as priorities and also overwrite the user provided `ConfigMap`?

Oh yeah. The point in time where this is available in the Shoot spec, but not the extensions is probably problematic.
Let me talk to the team on how we can handle that.

2025-01-10 11:02 UTC, timuthy commented
> > What is the expectation if users specify `priority` for worker pools but the corresponding worker extensions still do not support the required functionality? Is it ok for the priority expander `ConfigMap` to contain all 0s as priorities and also overwrite the user provided `ConfigMap`?
> 
> Oh yeah. The point in time where this is available in the Shoot spec, but not the extensions is probably problematic. Let me talk to the team on how we can handle that.

The `MachineDeployment` name is deterministic for all known provider extensions ([example](https://github.com/gardener/gardener-extension-provider-aws/blob/7450faae838450d6c1c78968bf19e33ead4f01a3/pkg/controller/worker/machines.go#L235C5-L235C21)).
I suggest that we build in a temporary fall-back that follows this scheme to find the configured priority from the `Shoot` resource, in case the priority is unset in the `Worker`. In case we can't find the priority, we might not put it into the config. WDYT?

2025-01-10 11:09 UTC, tobschli commented
> The `MachineDeployment` name is deterministic for all known provider extensions ([example](https://github.com/gardener/gardener-extension-provider-aws/blob/7450faae838450d6c1c78968bf19e33ead4f01a3/pkg/controller/worker/machines.go#L235C5-L235C21)). I suggest that we build in a temporary fall-back that follows this scheme (`namespace` + "-" + `poolName`) to find the configured priority from the `Shoot` resource, in case the priority is unset in the `Worker`. In case we still can't find the priority, we might not put it into the config. WDYT?

There still is the problem that e.g. this feature gets released and users can specify priorities in their `Shoot` spec, but an the extension is not revendored yet.
I need to take a closer look at this scenario, but I think this will be problematic.

2025-01-14 15:05 UTC, tobschli commented
> I suggest that we build in a temporary fall-back that follows this scheme (`namespace` + "-" + `poolName`) to find the configured priority from the `Shoot` resource, in case the priority is unset in the `Worker`. In case we still can't find the priority, we might not put it into the config. WDYT?

Actually we need to go the opposite way, I think.
We generate the `ConfigMap` when some priority is defined in the workers.

The ClusterAutoscaler deployment component gets both the `Worker` definition as well as the `MachineDeployments` that the extension built.

I made the Priority optional throughout all type definitions now, so we can allow the case that the extensions do not set the priority.

When we _know_ there should be priorities given to the `MachineDeployment`s, so when there are priorities defined in the workers and we do not see priorities, we need to extract the worker name from the `MachineDeployment`.

2025-01-15 08:16 UTC, tobschli commented
/retest

2025-01-23 17:05 UTC, plkokanov requested changes
Just one more optimisation comment

2025-01-23 17:05 UTC, plkokanov commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler.go
> +			for _, pool := range c.workerConfig {
This double loop could be slow for clusters with large number of nodes. What about using a `map[string]int32` from `pool.Name` to `ptr.Deref(pool.Priority, 0)`, then getting the name of the pool from the `machineDeployment.Name` like this:
```
name := strings.TrimPrefix(machineDeployment.Name, c.namespace+"-")
zoneIndex := strings.LastIndex(name, "-z")
if zoneIndex != -1 {
    name = name[:zoneIndex]
}
``` 

and finally retrieving the priority from the map?

2025-01-24 10:25 UTC, tobschli commented
In addition to revendoring the `generic actuator`, the `WorkerDelegates` of the provider extensions need to specifically pass the priority from the worker pools to the `MachineDeployments`.

I will create the respective follow-up PRs for it in the extensions.

2025-01-24 14:00 UTC, oliver-goetz commented
/remove-lifecycle stale

2025-01-28 08:29 UTC, plkokanov reviewed
Thanks for addressing all my comments :) 
/lgtm

2025-01-29 07:56 UTC, timuthy requested changes
Thanks for the contribution 🙂

2025-01-29 07:56 UTC, timuthy commented on docs/usage/high-availability/shoot_high_availability_best_practices.md
> +          type: local
```suggestion
    - name: worker1
      priority: 40 # priority of this worker group
      machine:
        type: local
    - name: worker2
      machine:
        type: local
```
Nit

2025-01-29 07:56 UTC, timuthy commented on docs/usage/high-availability/shoot_high_availability_best_practices.md
> +In addition to that, it is also possible to configure the CA priority expander by adding priorities to the worker groups like this:
Could you explain the consequence of having a priority defined for only a few pools, i.e., what's the default prio for pools not having one?

2025-01-29 07:56 UTC, timuthy commented on docs/usage/high-availability/shoot_high_availability_best_practices.md
> +In addition to that, it is also possible to configure the CA priority expander by adding priorities to the worker groups like this:
```suggestion
In addition to that, it is also possible to configure the [`cluster-autoscaler` priority expander](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/expander/priority/readme.md) by adding priorities to the worker groups like this:
```

2025-01-29 07:56 UTC, timuthy commented on pkg/apis/core/types_shoot.go
> +	// Priority (or weight) is the importance by which this worker group will be scaled by cluster autoscaling.
```suggestion
	// Priority (or weight) is the importance by which this worker pool will be scaled by cluster autoscaling.
```

To remain consistent with other doc strings.

2025-01-29 07:56 UTC, timuthy commented on pkg/apis/core/v1beta1/types_shoot.go
> +	Priority *int32 `json:"priority,omitempty" protobuf:"varint,22,opt,name=priority"`
The feature evolved a lot through discussions in the past and I couldn't follow any detail. However, I'm surprised that the `Priority` field is not part of the `ClusterAutoscalerOptions`. Was this a deliberate decision and if so, could you please link the reasoning, for my own education? 😉

2025-01-29 07:56 UTC, timuthy commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// DefaultWorkerPriority is the default value for Worker Priority
```suggestion
	// DefaultWorkerPriority is the default value for Worker Priority.
```

2025-01-29 07:56 UTC, timuthy commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// Priority (or weight) is the importance by which this machine deployment will be scaled by cluster autoscaling.
```suggestion
	// Priority (or weight) is the importance by which this machine deployment will be scaled by cluster 
autoscaling.
	// +optional
```

2025-01-29 07:56 UTC, timuthy commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	Priority *int32 `json:"priority"`
```suggestion
	Priority *int32 `json:"priority,omitempty"`
```

2025-01-29 07:56 UTC, timuthy commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
> +
```suggestion
```

2025-01-29 07:56 UTC, timuthy commented on pkg/component/autoscaling/clusterautoscaler/cluster_autoscaler_test.go
> +		workerConfig = []gardencorev1beta1.Worker{
Can you also test the fallback case, i.e., priority defined in shoot worker but not yet set in `MachineDeployment`?
In addition, please consider a test case in which the fallback value cannot be found.

2025-01-29 07:56 UTC, timuthy commented on pkg/apis/core/v1beta1/types_shoot.go
> +	DefaultWorkerPriority = int32(0)
Just noticed: This one is unused. Leftover?

2025-01-30 07:54 UTC, tobschli commented on pkg/apis/core/v1beta1/types_shoot.go
> +	Priority *int32 `json:"priority,omitempty" protobuf:"varint,22,opt,name=priority"`
The idea was to not introduce further coupling to the ClusterAutoscaler, as this is something that is not a detail of the ClusterAutoscaler, but used in a variety of autoscaling solutions.
Therefore I decided to not move it into the ClusterAutoscaler field.

2025-01-30 07:55 UTC, timuthy commented on pkg/apis/core/v1beta1/types_shoot.go
> +	Priority *int32 `json:"priority,omitempty" protobuf:"varint,22,opt,name=priority"`
Fair enough, thanks 🙂

2025-01-30 08:52 UTC, tobschli commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// Priority (or weight) is the importance by which this machine deployment will be scaled by cluster autoscaling.
Is the newline for the autoscaling because of the lengthy string?
If yes, I would update this for the other ones as well.

2025-01-30 12:46 UTC, timuthy commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// Priority (or weight) is the importance by which this machine deployment will be scaled by cluster autoscaling.
Nope, only for `// +optional`.

2025-01-30 13:01 UTC, tobschli commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// Priority (or weight) is the importance by which this machine deployment will be scaled by cluster autoscaling.
Alright, thank you!

2025-01-30 14:12 UTC, timuthy reviewed
Nice!
/lgtm

2025-01-31 09:36 UTC, timuthy reviewed
/approve

2025-01-31 10:58 UTC, merged

2025-02-07 08:25 UTC, vlerenc commented
Awesome, didn't notice, thank you @tobschli @timuthy. Which version of Gardener will contain the feature (and [your fix](https://github.com/gardener/gardener/issues/11272), if I see this right @tobschli)?

2025-02-07 09:09 UTC, tobschli commented
> Awesome, didn't notice, thank you @tobschli @timuthy. Which version of Gardener will contain the feature (and [your fix](https://github.com/gardener/gardener/issues/11272), if I see this right @tobschli)?

v1.112 will contain the feature in the completely working state :)
I just confirmed it working during validation of the release.