Update controller runtime to v.0.2.0 beta
gardener/gardener pull request #1106
Opened 2019-06-14 14:15 UTC by adracus

**What this PR does / why we need it**:
This allows us to consume the latest version of the controller runtime in Gardener. As a result, we can then again properly vendor Gardener in our extensions + we get some goodies that came with the new controller-runtime version (patching, `IgnoreNotFound` etc.).

**Special notes for your reviewer**:
cc @rfranzke @timuthy @zanetworker 

**Release note**:

```improvement operator
NONE
```

2019-06-17 07:56 UTC, ialidzhikov commented on pkg/controllermanager/controller/shoot/shoot_control_delete.go
> +			if err := o.K8sSeedClient.Client().List(context.TODO(), &machinev1alpha1.MachineDeploymentList{}, client.UseListOptions(&client.ListOptions{Raw: &metav1.ListOptions{Limit: 1}})); err != nil {
```suggestion
			if err := o.K8sSeedClient.Client().List(context.TODO(), machineDeployments, client.UseListOptions(&client.ListOptions{Raw: &metav1.ListOptions{Limit: 1}})); err != nil {
```

Can we use also `kutil.Limit(1)`?

2019-06-18 07:33 UTC, adracus commented on pkg/controllermanager/controller/shoot/shoot_control_delete.go
> +			if err := o.K8sSeedClient.Client().List(context.TODO(), &machinev1alpha1.MachineDeploymentList{}, client.UseListOptions(&client.ListOptions{Raw: &metav1.ListOptions{Limit: 1}})); err != nil {
Good catch! Done.

2019-06-18 08:29 UTC, zanetworker submitted a review, later dismissed

2019-06-18 08:29 UTC, zanetworker commented on pkg/controllermanager/controller/shoot/shoot_control_delete.go
> +			if err := o.K8sSeedClient.Client().List(context.TODO(), &machinev1alpha1.MachineDeploymentList{}, client.UseListOptions(&client.ListOptions{Raw: &metav1.ListOptions{Limit: 1}})); err != nil {
I guess you can use kutils.Limit here is as well 

```suggestion
			if err := o.K8sSeedClient.Client().List(context.TODO(), &machinev1alpha1.MachineDeploymentList{}, client.UseListOptions(kutils.Limit(1)); err != nil {
```

2019-06-18 08:30 UTC, zanetworker commented on pkg/controllermanager/controller/shoot/shoot_control_delete.go
> +			if err := o.K8sSeedClient.Client().List(context.TODO(), &machinev1alpha1.MachineDeploymentList{}, client.UseListOptions(&client.ListOptions{Raw: &metav1.ListOptions{Limit: 1}})); err != nil {
okay looks like @ialidzhikov addressed that already.

2019-06-18 08:58 UTC, timuthy requested changes

2019-06-18 08:58 UTC, timuthy commented on pkg/operation/botanist/cleanup.go
> +			newOpts = append(newOpts, Finalize)
Finalize options are supposed to be added in `else` branch.

2019-06-18 12:10 UTC, ialidzhikov commented
@adracus , maybe you forgot to force push?

2019-06-19 07:14 UTC, ialidzhikov approved these changes
/approve

2019-06-19 07:25 UTC, rfranzke approved these changes
/lgtm

2019-06-19 07:26 UTC, timuthy approved these changes
/lgtm

2019-06-19 07:34 UTC, merged