Restrict `gardenlet` access for `Seed` resources
gardener/gardener pull request #11062
Opened 2024-12-18 08:15 UTC by rfranzke

**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
See https://github.com/gardener/gardener/issues/11034 for details.

**Which issue(s) this PR fixes**:
Fixes #11034

**Special notes for your reviewer**:
/hold
The last commit should be dropped - I have to revert it once the tests pass. Otherwise, PR is ready for review.

**Release note**:

```feature user
All `Seed`s are now automatically labeled with `seed.gardener.cloud/<name>=true` where `<name>` is their own name, and (if applicable) the name of their parent seed in case they are managed seeds. This label can be used as selector for requests.
```

2024-12-19 12:05 UTC, rfranzke commented
/unhold

e2e tests look good, PR is ready to go.

2025-01-09 07:45 UTC, shafeeqes commented
/remove-lifecycle stale

2025-01-15 09:19 UTC, timuthy commented
/assign

2025-01-17 11:21 UTC, timuthy requested changes

2025-01-17 11:21 UTC, timuthy commented on pkg/controllermanager/controller/shoot/migration/reconciler.go
> +	if shoot.Status.LastOperation != nil && shoot.Status.LastOperation.Type == gardencorev1beta1.LastOperationTypeMigrate {
We should check `ShouldPrepareShootForMigration` here as well. Otherwise there is a chance that the controller never removes the constraint if it misses the migration phase, i.e. when `shoot.Status.LastOperation.Type == gardencorev1beta1.LastOperationTypeMigrate`.

@plkokanov or @oliver-goetz could you double check please? I will push the change if you agree.

2025-01-22 09:35 UTC, timuthy commented
Added fd5ec2f96f8315c7515d06c18a54ee197a0bd75e to address review comment (https://github.com/gardener/gardener/pull/11062#discussion_r1920013798) and rebased PR.

2025-01-22 10:18 UTC, oliver-goetz commented on pkg/controllermanager/controller/shoot/migration/reconciler.go
> +	if shoot.Status.LastOperation != nil && shoot.Status.LastOperation.Type == gardencorev1beta1.LastOperationTypeMigrate {
Puh, I cannot say much about this tbh. 😅

2025-01-22 14:09 UTC, timuthy commented
/retest-required

2025-01-22 20:40 UTC, timuthy commented
/test pull-gardener-e2e-kind-migration

2025-01-27 07:54 UTC, timuthy commented
/test pull-gardener-e2e-kind-ha-multi-zone

2025-01-27 08:27 UTC, ScheererJ commented
/assign

2025-01-27 15:30 UTC, timuthy commented
/test pull-gardener-e2e-kind-operator

2025-01-27 15:33 UTC, ScheererJ approved these changes
Thanks for improving security by reducing the `almighty` gardenlet.

/lgtm
/approve

2025-01-27 17:44 UTC, merged