Accommodate the logs from the early stages of managed control plane lifecycle
gardener/gardener pull request #11082
Opened 2024-12-20 11:15 UTC by nickytd

/area logging
/kind enhancement

This PR enhances the shoot reconcile flow by deploying `vali` as early as possible. When `vali` is instantiated in the beginning of the flow, it is able to accommodate the first logs from the managed control plane components. The state before this PR is that these "early" logs might be missed and not present in the backend. 
The PR also takes care of adapting the containers set of `vali` pod, according to the presence of the gardener-resource-manager and the authentication token used by the log shippers running on the shoots aka `valitail` systemd service.

This PR contains:
- minor refactoring(rename) in botanist
- defines vali `Interface` enhancing  the `component.Deployer`
- initiate vali deployment also in the beginning of the reconcile cycle
- tests

```noteworthy operator
Now "vali" contains the managed control plane logs from the early stages of shoot reconcile.
```

2025-01-08 12:46 UTC, plkokanov commented
/remove-lifecycle stale
/assign

2025-01-10 08:40 UTC, plkokanov requested changes
Thanks for the well structured PR!

2025-01-10 08:40 UTC, plkokanov commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
> +		_ = g.Add(flow.Task{
Does it make sense to make the subsequent tasks dependant on this one? Otherwise this might still be executed rather late.

2025-01-10 08:40 UTC, plkokanov commented on pkg/gardenlet/operation/botanist/logging.go
> +		b.Operation.Logger.Error(err, "Error getting "+v1beta1constants.DeploymentNameGardenerResourceManager+" deployment")
Shouldn't the error be returned here? Some temporary error could occur while trying to get the GRM deployment even if it is already deployed and ready. Then `vali` would end up without the kube rbac proxy container and the shoot would still be successfully reconciled. 

If you return the error, then it will be automatically logged.

2025-01-13 08:35 UTC, plkokanov requested changes

2025-01-13 08:35 UTC, plkokanov commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
> +			Dependencies: flow.NewTaskIDs(deployNamespace, initializeSecretsManagement).InsertIf(shootControlPlaneLoggingEnabled),
```suggestion
			Dependencies: flow.NewTaskIDs(deployNamespace, initializeSecretsManagement),
```

2025-01-13 08:35 UTC, plkokanov commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
> +		initialValiDeployment = g.Add(flow.Task{
I think there was a bit of misunderstanding. What I meant was to add the dependency to the first task that would need the logging stack - e.g. the `"Copying etcd backups to new seed's backup bucket"` during control plane migration restore or `"Deploying main and events etcd"` during normal reconciliation. Note that adding it only to the former would be enough, as the latter depends on it.

2025-01-13 08:35 UTC, plkokanov commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
>  		deploySeedLogging = g.Add(flow.Task{
At a second look could we entirely skip this task (re-deployment of logging) if `shootControlPlaneLoggingEnabled=false`? Everything should already be handled by the first invocation, right?

If you decide that it is ok to skip it, then the dependencies can also be changed to
```
Dependencies: flow.NewTaskIDs(initialValiDeployment, waitUntilGardenerResourceManagerReady),
```

2025-01-13 09:15 UTC, nickytd commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
> +		initialValiDeployment = g.Add(flow.Task{
Imho a `dependency` can be in `order` and also `functional`. The `etcd` does not require a logging stack to run and more importantly the logging stack is entirely skipped when the shoot is of an `evaluation` type. So from my perspective we shall not bring such strong dependency.

2025-01-13 09:24 UTC, nickytd commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
> +			Dependencies: flow.NewTaskIDs(deployNamespace, initializeSecretsManagement).InsertIf(shootControlPlaneLoggingEnabled),
My understanding is that we need InsertIf to cover the "evaluation" type of shoots but I might be wrong.

2025-01-13 10:03 UTC, plkokanov commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
> +			Dependencies: flow.NewTaskIDs(deployNamespace, initializeSecretsManagement).InsertIf(shootControlPlaneLoggingEnabled),
`InsertIf(shootControlPlaneLoggingEnabled)` doesn't do anything as no dependencies are specified in the function call, so nothing will be added to the already existing dependencies specified in `flow.NewTaskIDs(deployNamespace, initializeSecretsManagement)`

`Deploying`/`Destroying` the logging stack (incl. subcomponents) based on the purpose is handled in https://github.com/gardener/gardener/blob/50828b680ca098ed33f617c5bc60bf1dce393124/pkg/gardenlet/operation/botanist/logging.go#L22-L24 and in https://github.com/gardener/gardener/blob/50828b680ca098ed33f617c5bc60bf1dce393124/pkg/gardenlet/operation/botanist/logging.go#L53-L64

2025-01-13 12:02 UTC, nickytd commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
> +			Dependencies: flow.NewTaskIDs(deployNamespace, initializeSecretsManagement).InsertIf(shootControlPlaneLoggingEnabled),
I see, Thanks. Perhaps it was introduced in the past but it is obsolete in the current implementation of the flow task. I will add the commit suggestion.

2025-01-13 12:25 UTC, nickytd commented on pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go
>  		deploySeedLogging = g.Add(flow.Task{
Thanks the proposal has been added to this PR.

2025-01-13 13:30 UTC, nickytd commented
/retest

2025-01-14 12:05 UTC, plkokanov reviewed
/lgtm
/approve

2025-01-14 12:44 UTC, nickytd commented
/retest

2025-01-14 13:28 UTC, merged