Separate `apis/<api>/[ver]/helper/helper.go` into different `helper_<resource>.go` files
gardener/gardener pull request #11083
Opened 2024-12-20 15:19 UTC by RadaBDimitrova

**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
Separates logic in `apis/<api>/[ver]/helper/helper.go` in order to have easier access to helper functions of the same logical group.

**Which issue(s) this PR fixes**:
Fixes #10426 

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

2024-12-20 15:53 UTC, RadaBDimitrova commented
/retest

2024-12-30 09:01 UTC, Kostov6 commented
/retest

2024-12-30 10:12 UTC, RadaBDimitrova commented
/retest

2024-12-30 11:22 UTC, RadaBDimitrova commented
/retest

2024-12-30 12:49 UTC, RadaBDimitrova commented
/retest

2025-01-10 11:35 UTC, plkokanov commented
/assign

2025-01-14 07:48 UTC, ialidzhikov commented
/assign

2025-01-14 09:25 UTC, Kostov6 reviewed
Surface level old comments

2025-01-14 09:25 UTC, Kostov6 commented on pkg/apis/core/v1beta1/helper/helper_shoot.go
> +func ReadManagedSeedAPIServer(shoot *gardencorev1beta1.Shoot) (*ManagedSeedAPIServer, error) {
It's more relevant in context of `helper_managedseed.go`

2025-01-14 09:25 UTC, Kostov6 commented on pkg/apis/core/v1beta1/helper/helper_shoot.go
> +func GetNodeLocalDNS(systemComponents *gardencorev1beta1.SystemComponents) *gardencorev1beta1.NodeLocalDNS {
I think we can replace this function with just `systemComponents.NodeLocalDNS`. It's nowhere used
https://sourcegraph.com/search?q=context:global+repo:github.com/gardener+GetNodeLocalDNS&patternType=standard&sm=1

2025-01-14 10:01 UTC, ialidzhikov requested changes

2025-01-14 10:01 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/backupbucket.go
> +func BackupBucketIsErroneous(bb *gardencorev1beta1.BackupBucket) (bool, string) {
Could you also split the unit tests to dedicated files?

For example, move the unit test `BackupBucketIsErroneous` from `pkg/apis/core/v1beta1/helper/helper_test.go` to `pkg/apis/core/v1beta1/helper/backupbucket_test.go`.

The same pattern is followed for the types. See `pkg/apis/core/v1beta1/types_seed.go` and `pkg/apis/core/v1beta1/types_seed_test.go`.

2025-01-14 10:01 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/cloudprofile.go
> +}
This should rather belong to the Shoot. It is being used to fetch a resource from the Shoot `spec.resources`. Or am I missing something?

2025-01-14 10:01 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/shoot.go
> +}
I would move it to the Seed-specific file.

2025-01-14 10:01 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/backupbucket.go
> +	gardencorev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
I see you already covered the external helper funcs and internal helper funcs are not modified.

The same pattern should be applicable for the internal helper files - `./pkg/apis/core/helper/helpers.go` and maybe there are others.

Would you agree?

2025-01-14 10:01 UTC, ialidzhikov commented on pkg/apis/seedmanagement/v1alpha1/helper/gardenlet.go
> -	seedmanagementv1alpha1 "github.com/gardener/gardener/pkg/apis/seedmanagement/v1alpha1"
Isn't better to name `pkg/apis/resources/v1alpha1/helper/managedresource.go` instead of `pkg/apis/resources/v1alpha1/helper/resourcemanager.go`?

2025-01-14 10:03 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/helper_shoot.go
> +func GetNodeLocalDNS(systemComponents *gardencorev1beta1.SystemComponents) *gardencorev1beta1.NodeLocalDNS {
I would avoid to do such refactorings in this PR and I would prefer to keep the PR as simple as moving only funcs from one file to dedicated files. YOu could address such suggestions in follow-up PRs.
Right now, the api-diff check on PR level makes sure that there are no breaking changes with the PR. I would prefer to keep this check green for this PR to make sure that there is no missed func or a typo somewhere.

2025-01-14 11:20 UTC, Kostov6 commented on pkg/apis/core/v1beta1/helper/backupbucket.go
> +	gardencorev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
I think you should keep in mind https://github.com/gardener/gardener/issues/11043 when splitting the internal helper files

2025-01-14 12:28 UTC, plkokanov requested changes

2025-01-14 12:28 UTC, plkokanov commented on pkg/apis/core/v1beta1/helper/common.go
> +func ShootHasOperationType(lastOperation *gardencorev1beta1.LastOperation, lastOperationType gardencorev1beta1.LastOperationType) bool {
This should eventually be renamed to `HasOperationType`, but it is better to do it in a separate PR.
Apart from @ialidzhikov's suggestions, rest looks good.

Note that I selected request changes instead of simply "comment"-ing 😅

2025-01-14 15:30 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/helper_shoot.go
> +func GetNodeLocalDNS(systemComponents *gardencorev1beta1.SystemComponents) *gardencorev1beta1.NodeLocalDNS {
I was naive to assume that a passing job on PR level means a successful run. I now see that the job is constantly failing with an error. See https://github.com/gardener/gardener/issues/11166.

2025-01-15 05:45 UTC, ialidzhikov commented
/test pull-gardener-apidiff

2025-01-15 14:49 UTC, RadaBDimitrova commented
`Error: bad file 'hack/../example/gardener-local/gardenlet/operator/patch-imagevector-overwrite.yaml': yaml: line 13: could not find expected ':'`

`Error: UPGRADE FAILED: update: failed to update: Internal error occurred: failed calling webhook "validate-kubeconfig-secrets.gardener.cloud": failed to call webhook: Post "[https://gardener-admission-controller.garden.svc:443/webhooks/validate-kubeconfig-secrets?timeout=10s](https://gardener-admission-controller.garden.svc/webhooks/validate-kubeconfig-secrets?timeout=10s)": dial tcp 10.2.2.10:443: connect: connection refused`

`  [FAILED] Timed out after 5.001s.
  The function passed to Eventually failed at /home/prow/go/src/github.com/gardener/gardener/test/integration/scheduler/shoot/shoot_test.go:88 with:
  Expected
      <*v1beta1.LastOperation | 0xc006245950>: {
          Description: "Failed to schedule Shoot: none of the 1 seeds is valid for scheduling (not deleting, visible and ready)",
          LastUpdateTime: {
              Time: 2025-01-15T13:55:49Z,
          },
          Progress: 0,
          State: "Pending",
          Type: "Create",
      }
  to be nil
  In [It] at: /home/prow/go/src/github.com/gardener/gardener/test/integration/scheduler/shoot/shoot_test.go:89 @ 01/15/25 13:55:54.393`
 /retest

2025-01-15 14:51 UTC, RadaBDimitrova commented on pkg/apis/core/v1beta1/helper/backupbucket.go
> +	gardencorev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
This will be done in another PR to keep things minimal and easier to review in this one.

2025-01-15 17:58 UTC, RadaBDimitrova commented
/retest

2025-01-20 15:39 UTC, ialidzhikov reviewed
Final cosmetic suggestions from my side, otherwise lgtm

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/common_test.go
> +	Describe("Version helper", func() {
Why version helper in common tests? Maybe a copy-paster error?

```suggestion
```

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/common.go
> +func AccessRestrictionsAreSupported(seedAccessRestrictions []gardencorev1beta1.AccessRestriction, shootAccessRestrictions []gardencorev1beta1.AccessRestrictionWithOptions) bool {
I would move it to Shoot helpers.

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/managedseed_test.go
> +var _ = Describe("#ReadManagedSeedAPIServer", func() {
For consistency with the other tests structure:
```suggestion
var _ = Describe("Helper", func() {

	Describe("#ReadManagedSeedAPIServer", func() {
```

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/shoot_test.go
> +	DescribeTable("#SystemComponentsAllowed",
```suggestion
	)

	DescribeTable("#SystemComponentsAllowed",
```

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/shoot_test.go
> +var _ = Describe("Helper", func() {
As we talked offline, you could order the describe blocks to match the order of the funcs in the original file.

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/extensions/v1alpha1/helper/dnsrecord_test.go
> +var _ = Describe("helper", func() {
For consistency with the core API group helper tests:
```suggestion
var _ = Describe("Helper", func() {
```

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/extensions/v1alpha1/helper/network_test.go
> +var _ = Describe("helper", func() {
```suggestion
var _ = Describe("Helper", func() {
```

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/extensions/v1alpha1/helper/operatingsystemconfig_test.go
> +var _ = Describe("helper", func() {
```suggestion
var _ = Describe("Helper", func() {
```

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/extensions/v1alpha1/helper/operatingsystemconfig_test.go
> +var _ = Describe("helper", func() {
```suggestion
var _ = Describe("Helper", func() {
```

2025-01-20 15:39 UTC, ialidzhikov commented on pkg/apis/extensions/v1alpha1/helper/worker_test.go
> +var _ = Describe("helper", func() {
```suggestion
var _ = Describe("Helper", func() {
```

2025-01-21 08:05 UTC, ialidzhikov reviewed
/lgtm

2025-01-21 08:59 UTC, RadaBDimitrova commented
/retest

2025-01-21 13:38 UTC, plkokanov reviewed
/lgtm

2025-01-21 17:08 UTC, ialidzhikov approved these changes

2025-01-21 18:26 UTC, merged