Clean up deprecated kubernetes methods
gardener/gardener pull request #1140
Opened 2019-06-24 21:49 UTC by ialidzhikov

**What this PR does / why we need it**:
With #583 (staring from 0.16.0) some methods from `pkg/client/kubernetes` were deprecated in favour of controller-runtime client. This PR cleans up the deprecated methods and uses controller-runtime client as replacement.

/kind api-change
/kind cleanup

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Deprecated methods from `pkg/client/kubernetes` are now removed. Consider to switch your invocations to [kubernetes-sigs/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) client (`.Client()`) or [kubernetes/client-go](https://github.com/kubernetes/client-go) (`.Kubernetes()`).
```

2019-06-26 08:32 UTC, rfranzke requested changes

2019-06-26 08:32 UTC, rfranzke commented on pkg/operation/garden/garden.go
> +		if err := kutil.CreateOrUpdate(context.TODO(), k8sGardenClient.Client(), configMap, func() error {
```suggestion
		return kutil.CreateOrUpdate(context.TODO(), k8sGardenClient.Client(), configMap, func() error {
```

2019-06-26 08:32 UTC, rfranzke commented on pkg/operation/hybridbotanist/addons.go
> -	heapsterDeployments, err := b.K8sShootClient.ListDeployments(metav1.NamespaceSystem, metav1.ListOptions{
I think this code is removed in `master`, please rebase

2019-06-26 08:32 UTC, rfranzke commented on pkg/operation/hybridbotanist/addons.go
> +		fmt.Println("inside 2")
leftover

2019-06-26 08:32 UTC, rfranzke commented on pkg/operation/hybridbotanist/addons.go
> +		fmt.Println("inside")
leftover

2019-06-26 08:32 UTC, rfranzke commented on pkg/operation/hybridbotanist/cloud_config.go
> +		if err := kutil.CreateOrUpdate(context.TODO(), b.K8sShootClient.Client(), secret, func() error {
```suggestion
		err := kutil.CreateOrUpdate(context.TODO(), b.K8sShootClient.Client(), secret, func() error {
			...
		}
		return secret, err
```

2019-06-26 08:32 UTC, rfranzke commented on pkg/operation/hybridbotanist/controlplane.go
> +		service := &corev1.Service{
Can you remove this whole `DeleteService` code? It's no longer needed, it was needed a few months ago during a migration.

2019-06-26 08:32 UTC, rfranzke commented on pkg/operation/hybridbotanist/controlplane.go
>  	if err != nil {
These functions here are removed, please rebase

2019-06-27 07:17 UTC, ialidzhikov commented
Thank you for your review! Applied the suggestions.
Just found an issue with the PR, let me try to resolve it.

/hold

2019-06-27 13:24 UTC, ialidzhikov commented on pkg/operation/botanist/secrets.go
> +	if err := b.K8sSeedClient.Client().List(context.TODO(), secretList); err != nil {
This sould be
```suggestion
	if err := b.K8sSeedClient.Client().List(context.TODO(), secretList, client.InNamespace(b.Shoot.SeedNamespace)); err != nil {
```

2019-06-27 14:10 UTC, ialidzhikov commented
/hold cancel

2019-06-27 14:37 UTC, rfranzke approved these changes
/lgtm

2019-06-27 14:38 UTC, merged