Drop support for Kubernetes 1.10
gardener/gardener pull request #1166
Opened 2019-07-02 15:56 UTC by ialidzhikov

**What this PR does / why we need it**:
Drop support for Kubernetes v1.10. 
Ref https://github.com/gardener/gardener/issues/1118#issuecomment-506496883

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```action user
:warning: Gardener does no longer support Kubernetes v1.10. You must upgrade all shoot cluster to at least Kubernetes v1.11 before upgrading Gardener. This also means that no seed clusters with versions prior to v1.11 are supported anymore. Please upgrade all seed clusters to at least v1.11 as well before upgrading Gardener cluster itself to v1.11.
```

2019-07-02 15:56 UTC, ialidzhikov commented
/hold

2019-07-04 12:17 UTC, rfranzke requested changes
* Remove https://github.com/gardener/gardener/blob/master/pkg/apis/garden/types.go#L1296 and https://github.com/gardener/gardener/blob/master/pkg/apis/garden/v1beta1/types.go#L1297
* [This test](https://github.com/gardener/gardener/blob/master/pkg/apis/garden/validation/validation_test.go#L5103-L5112) can be simplified/merged into the previous test case now that we do not longer need to distinguish between versions < 1.11.
* Adapt https://github.com/gardener/gardener/blob/master/pkg/controllermanager/apis/config/types.go#L156-L157 and https://github.com/gardener/gardener/blob/master/pkg/controllermanager/apis/config/v1alpha1/types.go#L160-L161

2019-07-04 12:17 UTC, rfranzke commented on pkg/apis/garden/types.go
> -	DHCPDomain *string
Don't remove the field entirely without a proper deprecation period. Mark it rather as "deprecated" and don't use it anymore anywhere.

2019-07-04 12:17 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> -	DHCPDomain *string `json:"dhcpDomain,omitempty"`
Don't remove the field entirely without a proper deprecation period. Mark it rather as "deprecated" and don't use it anymore anywhere.

2019-07-08 09:16 UTC, ialidzhikov commented
Thank you for the review! Applied the suggestions.

2019-08-14 14:39 UTC, ialidzhikov commented
Closing for now.

2019-08-14 14:39 UTC, closed without merging