Add gardener reconcilation test after update
gardener/gardener pull request #1202
Opened 2019-07-11 10:23 UTC by schrodit

**What this PR does / why we need it**:
Added an test that checks if all shoots are successfully reconciled after an gardener update.

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Added a test that checks if all shoots are successfully reconciled after an gardener update
```

2019-07-11 12:20 UTC, adracus requested changes
Minor nits

2019-07-11 12:20 UTC, adracus commented on test/integration/gardener/reconcile/gardener_reconcile_test.go
> +			if len(shoots.Items) == 0 {
You don't need this check since the operation you're doing afterwards is cheap.

2019-07-11 12:20 UTC, adracus commented on test/integration/gardener/reconcile/gardener_reconcile_test.go
> +				return retry.NotOk()
Try not to use `NotOk` - rather do a `MinorError` with the message you have in your `Infof`

2019-07-13 21:23 UTC, ialidzhikov reviewed
Minor nits.

2019-07-13 21:23 UTC, ialidzhikov commented on test/integration/gardener/reconcile/gardener_reconcile_test.go
> +	testLogger *logrus.Logger
You could move it to the describe.

2019-07-13 21:23 UTC, ialidzhikov commented on test/integration/gardener/reconcile/gardener_reconcile_suite_test.go
> +func TestReconcile(t *testing.T) {
You can update `docs/testing/integration_tests.md` (if needed).

2019-07-13 21:23 UTC, ialidzhikov commented on test/integration/gardener/reconcile/gardener_reconcile_test.go
> +	"time"
`goimports -w test/integration/gardener/reconcile`

2019-07-15 21:00 UTC, ialidzhikov approved these changes
/approve

2019-07-16 11:37 UTC, timuthy commented
@adracus PTAL.

2019-07-19 09:38 UTC, adracus approved these changes
/lgtm

2019-07-19 09:38 UTC, merged