Initial commit of CNCF conformance test scripts
gardener/gardener pull request #123
Opened 2018-04-09 15:41 UTC by rolpat

2018-04-09 17:11 UTC, msohn requested changes

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +TRUE=0
declare these variables to be constant ?

readonly TRUE=0

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +  echo "run-conformance-test-ci <garden-kubeconfig> <garden-namespace> <cloud-provider> <secret-binding> <shoot-domain>"
use a document and add some more text to improve readability ?
```bash
cat << EOF
Usage: 
run-conformance-test-ci <garden-kubeconfig> <garden-namespace> <cloud-provider> <secret-binding> <shoot-domain>

Parameters:
  <garden-kubeconfig>: path to kubeconfig of Garden cluster
  <garden-namespace>: string, e.g. garden-mytest. Naming convention: garden-<project>
  <cloud-provider>: string, one of (${VALID_CLOUD_PROVIDERS})
  <secret-binding>: string, name of the secret binding to be used in the shoot manifest
  <shoot-domain>: string, name of the domain to be used in the shoot manifest, e.g. example.com

Description: Runs kubernetes conformance tests

Example:
   run-conformance-test-ci ./foo/kubeconfig garden-mytest aws aws-secret-binding example.com
EOF
```

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +  echo  "INFO: Wait until the pod sonobuoy/sonobuoy cecomes available ... or MAX_RETRY_TIME="$MAX_RETRY_TIME "s exceeded"
s/cecomes/becomes/

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +  # Deploy and run conformance test
extract this into functions deploy_test and run_test ?

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +  # Copy the test result to local drive
extract into function copy_test_results

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +  # Examine e2e.log
extract into function check_test_result ?

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +  echo "INFO: Conformance test NOT successfully finished"
how about this: Conformance test FAILED

2018-04-09 17:11 UTC, msohn commented on .ci/shoot-utils
> +    # Check status.lastOperation.status
extract into function check_last_operation_status ?

2018-04-09 17:11 UTC, msohn commented on .ci/shoot-utils
> +# create_shoot
why is the function name repeated here ?

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +# Helper functions
this comment doesn't seem to add value

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +# trap_handler
unnecessary comment

2018-04-09 17:11 UTC, msohn commented on .ci/run-conformance-test-ci
> +# run_conformance_tests
unnecessary repetition ?

2018-04-10 06:11 UTC, rfranzke commented
Apart from @msohn's comments I don't have any more feedback for the code itself yet (as discussed, we plan to replace the test scripts with Golang anyway at some point in time).
Regarding the integration test, @dkistner does not plan to use any of your "new" functionality but he will just replenish the old script (as also this test script will be rewritten in Go instead of mixed bash/python).

Therefore, you can move the functions which you put in a separate file (`shoot-utils`) in the original test script and do not need to source any more. Moreover, let's rename the whole script from `run-conformance-test-ci` to `conformance-test` or `k8s-conformance-test`, please.

Thank you a lot, @rolpat!!

2018-04-10 10:11 UTC, rfranzke commented
Could you please squash the commits?

2018-04-10 12:18 UTC, rfranzke commented on .ci/k8s-conformance-test
> +   run-conformance-test-ci ./foo/kubeconfig garden-mytest aws aws-secret-binding example.com
Rename `run-conformance-test-ci` into `k8s-conformance-test`.

2018-04-10 12:18 UTC, rfranzke commented on .ci/k8s-conformance-test
> +run-conformance-test-ci <garden-kubeconfig> <garden-namespace> <cloud-provider> <secret-binding> <shoot-domain>
Rename `run-conformance-test-ci` into `k8s-conformance-test`.

2018-04-10 13:25 UTC, rfranzke approved these changes

2018-04-10 13:25 UTC, merged