Added configurable nodeCIDRMaskSize flag to Shoot spec
gardener/gardener pull request #1280
Opened 2019-08-02 15:21 UTC by afritzler

**What this PR does / why we need it**:
Allows to set the optional `--node-cidr-mask-size` flag on the `kube-controller-manager` which specifies how large the Pod CIDR range for a node can be (default is 24).

**Which issue(s) this PR fixes**:
Fixes #1107

**Special notes for your reviewer**:
/cc @KesavanKing

**Release note**:
```improvement operator
Added configurable nodeCIDRMaskSize flag to Shoot spec
```

2019-08-05 12:37 UTC, timuthy requested changes
Just some nits.

Additionally, is this option intended to be mutable, i.e. does this work correctly especially if you try to shrink the CIDR range?

2019-08-05 12:37 UTC, timuthy commented on pkg/apis/garden/validation/validation.go
> +			fldPath = fldPath.Child("nodeCIDRMaskSize")
You don't need this here since you already use `fldPath.Child("nodeCIDRMaskSize")` in line 1703.

2019-08-05 12:37 UTC, timuthy commented on pkg/operation/hybridbotanist/controlplane.go
> +			defaultValues["nodeCIDRMaskSize"] = controllerManagerConfig.NodeCIDRMaskSize
```suggestion
			defaultValues["nodeCIDRMaskSize"] = *controllerManagerConfig.NodeCIDRMaskSize
```

2019-08-05 13:05 UTC, afritzler commented
Thanks @timuthy! I made the suggested changes. Also fixed the another issue I had in the `validation_test`.

2019-08-05 13:06 UTC, afritzler commented
OK still need to squash.

2019-08-05 13:21 UTC, rfranzke commented on pkg/apis/garden/validation/validation_test.go
> +				Expect(errorList).ToNot(BeEmpty())
Can you also check that really this field is the problematic one (like we do in the other tests)?

2019-08-05 15:19 UTC, afritzler commented
@timuthy actually shrinking the node CIDR is not supported at the moment. There is currently an unresolved bug in Kubernetes on that https://github.com/kubernetes/kubernetes/issues/70957

2019-08-05 15:19 UTC, afritzler commented
I guess we should make this field immutable once set.

2019-08-05 15:22 UTC, rfranzke submitted a review, later dismissed
/lgtm

2019-08-05 15:31 UTC, rfranzke commented
> I guess we should make this field immutable once set.

Yes, can you please implement this (together with a test), please?

2019-08-06 11:25 UTC, afritzler commented
Ok, I set the field now immutable and added some tests to the validation.

2019-08-06 11:29 UTC, rfranzke approved these changes
/lgtm

2019-08-06 12:53 UTC, merged