[WIP] Introduce new cloud specific ControlPlane resource in shoot control flow
gardener/gardener pull request #1313
Opened 2019-08-12 07:57 UTC by svetlinas

**What this PR does / why we need it**:
Create/Delete new cloud specific ControlPlane resource with `purpose` set to `exposure`. It triggers the new control plane controllers for the exposure settings. 

**Which issue(s) this PR fixes**:
Fixes gardener/gardener-extensions#233 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Introduce new cloud specific ControlPlane resource in shoot control flow
```

2019-08-12 17:51 UTC, rfranzke requested changes
Please also remove:

* https://github.com/gardener/gardener/blob/master/charts/images.yaml#L33-L36
* https://github.com/gardener/gardener/tree/master/charts/seed-controlplane/charts/aws-lb-readvertiser
* https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/secrets.go#L185-L204
* https://github.com/gardener/gardener/blob/master/pkg/operation/common/types.go#L212-L214
* https://github.com/gardener/gardener/blob/master/pkg/operation/common/types.go#L460-L462
* Everything related to the botanist health check that checks the `aws-lb-readvertiser` deployment (`pkg/operation/botanist/health_check.go`)
* Rename https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/kubernetes_test.go#L279-L280

2019-08-12 17:51 UTC, rfranzke commented on pkg/controllermanager/controller/shoot/shoot_control_delete.go
> +		destroyCloudSpecificControlPlane = g.Add(flow.Task{
I think we should delete it after the kube-apiserver deployment is deleted. It's relevant for the kube-apiserver exposure, and if it is gone then we can safely delete all exposure-relevant components.

2019-08-12 17:51 UTC, rfranzke commented on pkg/controllermanager/controller/shoot/shoot_control_reconcile.go
> +		// TODO all the methods are now duplicated for the 2 control plane resources
What do you mean by "duplicated"?

2019-08-12 17:51 UTC, rfranzke commented on pkg/operation/botanist/controlplane.go
> +				// TODO by adding suffix we can understand quickly with control plane for what scenario is
I like the suffix approach. The current name is fine, I guess :)

2019-08-12 17:51 UTC, rfranzke commented on pkg/operation/botanist/controlplane.go
> +func (b *Botanist) DeployCloudSpecificControlPlane(ctx context.Context) error {
```suggestion
func (b *Botanist) DeployControlPlaneExposure(ctx context.Context) error {
```

(adapt other names accordingly, please)

2019-08-13 11:28 UTC, svetlinas commented
> * Rename https://github.com/gardener/gardener/blob/master/pkg/utils/kubernetes/kubernetes_test.go#L279-L280

Why should this tests be renamed? They are validating a method ValidDeploymentContainerImageVersion(...) which I do not think is related to the AWS components (the method is not used in gardener/gardener project). The test data is named "aws-lb-readvertiser". What about rename the test data?

2019-08-13 11:57 UTC, rfranzke commented
Yes, I meant renaming the test data, sorry for being not accurate enough. :)

2019-08-14 07:13 UTC, rfranzke reviewed
Could you please add a document (`docs/extensions/controlplane-exposure.md`) (similar to https://github.com/gardener/gardener/blob/master/docs/extensions/controlplane.md) that explains the purpose of this resource, why it exists, what it can be used for, how it works, and a maybe a reference to the AWS implementation as an example?

2019-08-15 04:29 UTC, rfranzke commented on docs/extensions/controlplane-exposure.md
> +Its purpose is to trigger the deployment of such provider-specific components in the shoot namespace in the seed cluster that are need for the seed cluster.
```suggestion
Its purpose is to trigger the deployment of such provider-specific components in the shoot namespace in the seed cluster that are needed to expose the kube-apiserver.
The shoot cluster's kube-apiserver are exposed via a `Service of type `LoadBalancer`. This load balancer is part of the seed provider's infrastructure. As the seed provider might differ from the shoot provider (you may run the control plane of an Azure shoot in a GCP seed) it's the seed provider extension controller that should act on the `ControlPlane` resources with purpose `exposure`.
```

2019-08-15 04:29 UTC, rfranzke commented on docs/extensions/controlplane-exposure.md
> +The `.spec.secretRef` contains a reference to the provider secret pointing to the account that shall be used for the shoot cluster. The `.spec.region` contains the region of the seed cluster.
```suggestion
The `.spec.secretRef` contains a reference to the provider secret pointing to the account that shall be used for the shoot cluster.
It is most likely not needed, however, still added for some potential corner cases.
If you don't need it then just ignore it.
The `.spec.region` contains the region of the seed cluster.
```

2019-08-16 13:16 UTC, rfranzke approved these changes
/lgtm

2019-08-16 13:18 UTC, merged