Added dashboards for the seed monitoring
gardener/gardener pull request #1343
Opened 2019-08-16 12:19 UTC by wyb1

**What this PR does / why we need it**:
This PR adds dashboards for the seeds. These dashboards are intended for operators. Each seed will now have a grafana that contains information about the seed. This includes:
* `CPU`,`Memory`,`Network I/O` of the extensions
* Alerts from all shoots on the seed
* Resource usage overview for the entire seed
* Basic overview of each control plane on the seed (API Server count, node count, CPU/Memory)

This grafana is accessible through an ingress. Basic auth credentials can be found in the secret `seed-monitoring-ingress-credentials` in the garden namespace of the seed.

⚠️ This feature is temporary and will most likely be removed in the future.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Operators now have access to dashboards that collect information about the seed. The dashboards also have aggregated information about the shoots running on the seed. ⚠️ This feature is temporary and will most likely be removed in the future.
```

2019-08-16 12:28 UTC, rfranzke requested changes

2019-08-16 12:28 UTC, rfranzke commented on charts/seed-bootstrap/templates/grafana/grafana-deployment.yaml
> +      labels:
You need checksum annotations for `grafana-dashboards`, `grafana-datasources`, `grafana-dashboard-providers` config maps

2019-08-16 12:28 UTC, rfranzke commented on charts/seed-bootstrap/templates/grafana/ingress-auth-secret.yaml
> +  name: grafana-ingress-credentials-basic-auth
The logging secret is called `kibana-basic-auth`, so please call this `grafana-basic-auth`

2019-08-16 12:28 UTC, rfranzke commented on charts/seed-bootstrap/templates/grafana/ingress.yaml
> +    nginx.ingress.kubernetes.io/auth-secret: grafana-ingress-credentials-basic-auth
See above renaming suggestion

2019-08-16 13:03 UTC, wyb1 commented
Thanks @rfranzke! I applied the changes.

2019-08-16 13:06 UTC, rfranzke submitted a review, later dismissed
/lgtm

2019-08-20 11:34 UTC, dkistner approved these changes
/lgtm

Just a short side note. We should probably mention in the release notes that we plan to generalise this for a Gardener installation, means we want to archive a holistic view on the entire installation and we will then not longer need dedicated dashboards for the Seeds.

2019-08-20 11:36 UTC, rfranzke commented
Thanks @dkistner, merging then. @wyb1 please adapt the release note according to @dkistner's suggestion.

2019-08-20 11:36 UTC, merged