Adapt gardener-controller-manager to work with `core.gardener.cloud/v1alpha1` resources
gardener/gardener pull request #1453
Opened 2019-09-24 10:04 UTC by rfranzke

**What this PR does / why we need it**:
With this PR the `gardener-controller-manager` is adapted to only work with the `core.gardener.cloud/v1alpha1` resources. 

**Special notes for your reviewer**:
* Part of #1376

**Release note**:

```noteworthy developer
The `gardener-controller-manager` is now working only with `core.gardener.cloud/v1alpha1` instead of `garden.sapcloud.io/v1beta1` resources.
```
```noteworthy developer
The `Cluster` resource in the seed clusters will now contain the `core.gardener.cloud/v1alpha1` version of the `CloudProfile`, `Seed`, and `Shoot` resource. Extension controllers should be made capable of supporting/understanding both for at least one release until all shoots have been reconciled. (Existing `Cluster` resource of not-yet-reconciled shoots will still contain the `garden.sapcloud.io/v1beta1` version).
```
```noteworthy developer
The `shoot.garden.sapcloud.io/uid` as well as the `shoot.garden.sapcloud.io/hibernated` annotation on the shoot namespace in the seed cluster are deprecated and will be removed in a future version. You should consider using the `Cluster` resource instead.
```
```noteworthy user
The long deprecated `kube-lego` and `kube2iam` addons are now finally removed. They will remain in the `garden.sapcloud.io/v1beta1.Shoot` API but won't have any effect anymore.
```
```noteworthy user
As part of the final removal of the long deprecated `kube2iam` addon it will be deprovisioned of all existing `Shoot`s that still enable it. Also, all IAM roles created by Gardener for the `kube2iam` addon will be deleted.
```

2019-09-24 10:46 UTC, swapnilgm commented
/do-not-merge till 0.30.0 released.

2019-10-01 11:45 UTC, danielfoehrKn requested changes
Code comments only. Still testing with the integration tests

2019-10-01 11:45 UTC, danielfoehrKn commented on pkg/controllermanager/controller/seed/seed_control.go
>  	// By default, we assume the seed.Spec.Backup.Provider matches the seed.Spec.Backup.Cloud as per the validation logic.
Instead: "By default, we assume the seed.Spec.Backup.Provider matches the seed.Spec.Provider.Type as per the validation logic."

2019-10-01 11:45 UTC, danielfoehrKn commented on pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
> +		// continue execution to allow the machine image version update
```suggestion
		// continue execution to allow the kubernetes version update
```

2019-10-01 16:11 UTC, danielfoehrKn submitted a review, later dismissed

2019-10-01 16:11 UTC, danielfoehrKn commented on pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
> +			gardencorev1alpha1helper.UpdateMachineImages(shoot.Spec.Provider.Workers, updatedMachineImages)
```suggestion
			gardencorev1alpha1helper.UpdateMachineImages(s.Spec.Provider.Workers, updatedMachineImages)
```

2019-10-01 16:11 UTC, danielfoehrKn commented on pkg/controllermanager/controller/shoot/shoot_maintenance_control.go
> +			shoot.Spec.Kubernetes.Version = *updatedKubernetesVersion
```suggestion
			s.Spec.Kubernetes.Version = *updatedKubernetesVersion
```

Please fix. Otherwise no k8 and machine image update are being conducted.

2019-10-02 10:50 UTC, timuthy requested changes

2019-10-02 10:50 UTC, timuthy commented on pkg/operation/botanist/controlplane.go
> +		v1alpha1constants.DeprecatedShootHibernated: string(uid),
```suggestion
		v1alpha1constants.DeprecatedShootUID: string(uid),
```

2019-10-02 11:16 UTC, danielfoehrKn commented
Another issue with Seed Hibernation with hvpa:

The Seed client does not have [hvpa in its scheme](https://github.com/gardener/gardener/blob/4d9e8b956cf4c9f7cc1673be4cda42abcd0e60ca/pkg/operation/botanist/controlplane.go#L306). When gardener wants to hibernate a cluster, it tries to scale down hvpa & that fails.

I will push the branch to fix it along of the other issues opened by me.

@ggaurav10

2019-10-02 15:10 UTC, timuthy approved these changes

2019-10-02 15:14 UTC, merged

2019-10-02 21:24 UTC, ialidzhikov commented
Can we now remove also the <provider>-backup charts?

2019-10-03 05:54 UTC, swapnilgm commented
Yes.

2019-10-03 07:51 UTC, ialidzhikov commented
Proposed #1481.