Enhance gardener user
gardener/gardener pull request #1524
Opened 2019-10-21 19:36 UTC by KristianZH

**What this PR does / why we need it**:

Moves the logic from this PR in `gardener-extensions`: https://github.com/gardener/gardener-extensions/pull/372 here.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@rfranzke @vpnachev 

**Release note**:

```improvement operator
NONE
```

2019-10-21 19:50 UTC, vpnachev requested changes
Thanks!
Just a small formatting issue must be fixed.

2019-10-21 19:50 UTC, vpnachev commented on pkg/operation/botanist/operatingsystemconfig.go
> +		"sshKey": string(sshKey),
```suggestion
		"sshKey":        string(sshKey),
```

2019-10-22 06:20 UTC, rfranzke submitted a review, later dismissed

2019-10-22 06:39 UTC, vpnachev commented
You might consider to remove the constant `OperatingSystemConfigUnitNameGardenerUserService` because it seems it is not used anywhere:
https://github.com/gardener/gardener/blob/c6f1ec73e444853971940a694185b65e20069dd5/pkg/apis/core/v1alpha1/constants/types_constants.go#L235-L236

2019-10-22 07:55 UTC, ialidzhikov commented
@KristianZH, could you please rebase to get the `.ci/check` fix by @vpnachev ?

2019-10-22 09:01 UTC, vpnachev approved these changes
thanks!
/approve

2019-10-22 11:30 UTC, merged