Vendor sigs.k8s.io/controller-runtime@v0.2.0-beta.5
gardener/gardener pull request #1548
Opened 2019-10-27 11:51 UTC by ialidzhikov

**What this PR does / why we need it**:
Vendor sigs.k8s.io/controller-runtime@v0.2.0-beta.5.

**Which issue(s) this PR fixes**:
Fixes #1349

**Special notes for your reviewer**:

**Release note**:

```improvement developer
`sigs.k8s.io/controller-runtime` is updated to `v0.2.0-beta.5`.
```

2019-10-28 05:36 UTC, rfranzke commented
Let's not merge it before a new release is cut.

2019-10-28 06:45 UTC, rfranzke requested changes
Nice, thank you!
Also, please rebase! :)

2019-10-28 06:45 UTC, rfranzke commented on pkg/operation/botanist/worker.go
>  	return nil
```suggestion
	return client.IgnoreNotFound(b.K8sSeedClient.Client().Delete(ctx, worker))
```

2019-10-28 18:12 UTC, ialidzhikov commented
> Let's not merge it before a new release is cut.

Yep, sure, let's consider it after 0.31.0.

2019-10-30 13:53 UTC, rfranzke commented
Can you please rebase?

2019-11-04 07:04 UTC, rfranzke approved these changes

2019-11-04 07:05 UTC, merged