Add scheduler e2e tests
gardener/gardener pull request #1620
Opened 2019-11-14 17:40 UTC by mvladev

**What this PR does / why we need it**:

Adds scheduler e2e tests

**Which issue(s) this PR fixes**:
Related to #1610 #1551 

**Special notes for your reviewer**:

n/a

**Release note**:

```improvement operator
NONE
```

2019-11-15 07:19 UTC, schrodit requested changes
just some testdef related things.
The test is lgtm

2019-11-15 07:19 UTC, schrodit commented on .test-defs/ShootControlPlaneTest.yaml
> +  labels: ["default", "release", "shoot"]
please do not label untestet tests as `release`.
We first want to see if the test is stable enough to be a release blocker.

2019-11-15 07:19 UTC, schrodit commented on .test-defs/ShootControlPlaneTest.yaml
> +  owner: gardener-oq@listserv.sap.com
Please set yourself or a more specialized team as owner

2019-11-15 07:19 UTC, schrodit commented on .test-defs/ShootControlPlaneTest.yaml
> +  activeDeadlineSeconds: 1800
30 minutes seem a little long for test.
I think 10 or 5 minutes is enough?

2019-11-15 07:23 UTC, mvladev commented
@schrodit updated the test defs. Have another look

2019-11-15 10:20 UTC, vlerenc commented
Hmm... I skimmed through the code, but what is it testing? I don't see much, the description is not helping, neither for the PR nor in the test def.

2019-11-15 10:26 UTC, ialidzhikov commented
You do only get the kube-scheduler configMap and verify its content. Can't we do this with simple unit test? Why we need integration test for it?

2019-11-15 13:49 UTC, ialidzhikov requested changes
As a said I don't see much added value in this test. It won't catch issues as the ones #1610. And if it even fails for some reason, then probably the kube-scheduler will be down which will block the Shoot creation.
@mvladev wdyt? Can we rework/close this PR?

2019-11-18 07:46 UTC, rfranzke commented
> You do only get the kube-scheduler configMap and verify its content. Can't we do this with simple unit test? Why we need integration test for it?

Good point, a unit test for the [`DeployKubeScheduler`](https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/controlplane.go#L1000) function would be good enough, I think.

> It won't catch issues as the ones #1610. 

Why are you saying that this wouldn't have covered #1610? Actually, it would, right?

> And if it even fails for some reason, then probably the kube-scheduler will be down which will block the Shoot creation.

WDYM here?

2019-11-18 07:53 UTC, ialidzhikov commented
> Why are you saying that this wouldn't have covered #1610? Actually, it would, right?

You are just verifying configMap content. You don't verify any scheduling behaviour actually. After 2 days I can go and put my algorithm `foo` and adapt the test to check for it.

2019-11-18 07:59 UTC, rfranzke commented
Yes, but it would have covered the problem that was introduced. True point regarding actually testing the scheduling behavior, hence, let’s make it a unit test instead of an integration test.
I don’t understand the second sentence. Of course, simply adapting the test must be carefully reviewed and only be allowed if it makes sense. That’s always true, for every test we have.

2019-11-18 08:01 UTC, ialidzhikov commented
> WDYM here?

Do you have a case when this test will fail and the Shoot creation won't be failed?

2019-11-18 08:06 UTC, rfranzke commented
I don’t understand the discussion. Let’s make it a unit test and then we should be good to go. It’s valuable in the sense that it would catch the problem introduced last week. Yes, it’s not perfect as it doesn’t test actual scheduling behavior, though, I consider it valuable. It’s better than nothing ;-)

2019-11-18 08:16 UTC, ialidzhikov commented
> Let’s make it a unit test and then we should be good to go

+1

2019-11-25 12:52 UTC, mvladev commented
I've made it a e2e test to validate that the actual content of the `ConfigMap` is correct. A `MutatingWebhookConfiguration` could be present and modify the content - which is something that we don't want.

2019-11-25 12:59 UTC, ialidzhikov commented
> I've made it a e2e test to validate that the actual content of the `ConfigMap` is correct. A `MutatingWebhookConfiguration` could be present and modify the content - which is something that we don't want.

wtf, I don't think it a valid argument. Then lets write a bunch of tests that validates the content of kube-proxy configMap, the kube-apiserver configMap, etcd.

2019-11-27 15:03 UTC, rfranzke commented
How do we proceed here? @mvladev will you adapt to a unit test as part of this PR or should we close it in favour of a new one?

2019-12-02 04:42 UTC, rfranzke commented
Closing for now, please re-open once adapted as discussed.

2019-12-02 04:42 UTC, closed without merging