Adapt all components to `core.gardener.cloud/v1beta1` API group
gardener/gardener pull request #1763
Opened 2019-12-20 13:18 UTC by rfranzke

**What this PR does / why we need it**:
Adapt all components to `core.gardener.cloud/v1beta1` API group.

**Release note**:

```action operator
All Gardener components now work with the `core.gardener.cloud/v1beta1` API group (instead of `core.gardener.cloud/v1alpha1`). Please make sure that all extension controllers can understand both the `v1alpha1` and `v1beta1` version to ensure a smooth update.
```

2020-01-07 07:08 UTC, rfranzke commented
ping @timuthy @ialidzhikov @vpnachev

2020-01-07 08:47 UTC, timuthy requested changes
Nice, just 2 nits

2020-01-07 08:47 UTC, timuthy commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	// LabelAPIServer is a constant for a label for the kube-controller-manager.
Changed by mistake?

2020-01-07 08:47 UTC, timuthy commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	// LabelAPIServer is a constant for a label for the kube-scheduler.
Changed by mistake?

2020-01-07 08:50 UTC, rfranzke commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	// LabelAPIServer is a constant for a label for the kube-controller-manager.
Yes, nice catch, fixed, thanks.

2020-01-07 08:50 UTC, rfranzke commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	// LabelAPIServer is a constant for a label for the kube-scheduler.
Yes, nice catch, fixed, thanks.

2020-01-07 08:55 UTC, timuthy approved these changes
/lgtm

2020-01-07 10:18 UTC, merged

2020-01-08 10:22 UTC, ialidzhikov commented
/cc @vpnachev @swilen-iwanow 

> Please make sure that all extension controllers can understand both the `v1alpha1` and `v1beta1` version to ensure a smooth update.