Fix project-member ClusterRole aggregation
gardener/gardener pull request #1836
Opened 2020-01-22 14:23 UTC by petersutter

**What this PR does / why we need it**:
Since the introduction of #1601 the web terminal feature of the gardener dashboard does not work anymore for endusers, as the project-member ClusterRole aggregation does not work as intended: The `gardener.cloud:system:project-member` rolebinding has a roleRef to ClusterRole `gardener.cloud:system:project-member` instead of a roleRef to the ClusterRole `gardener.cloud:system:project-member-aggregation`. 

The roleRef cannot be changed without recreating the rolebinding (which can't be done easily).

Instead, this PR switches the ClusterRole `gardener.cloud:system:project-member` with `gardener.cloud:system:project-member-aggregation`, so that the `gardener.cloud:system:project-member` now contains the `aggregationRule` part and `gardener.cloud:system:project-member-aggregation` contains the `rules` part.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2020-01-22 14:28 UTC, rfranzke requested changes
Can you do the same with the `project-viewer` role, please?

2020-01-22 14:28 UTC, rfranzke commented
cc @mvladev - thanks for the suggestion

2020-01-22 14:42 UTC, petersutter commented
> Can you do the same with the `project-viewer` role, please?

done, I have reordered the ClusterRoles so that the comment above the ClusterRole still makes sense

2020-01-22 14:43 UTC, rfranzke approved these changes

2020-01-22 14:44 UTC, rfranzke commented
@petersutter can you clarify the change in the release note?

2020-01-22 15:02 UTC, petersutter commented
added a release note for users, PTAL

2020-01-23 06:39 UTC, timebertt approved these changes

2020-01-23 09:37 UTC, merged