Add ownerReference to the ShootState resource on creation
gardener/gardener pull request #1855
Opened 2020-01-24 14:23 UTC by swilen-iwanow

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2020-01-24 14:25 UTC, plkokanov commented
Looks good, could you just add a release note?

2020-01-24 14:45 UTC, plkokanov requested changes

2020-01-24 14:45 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/shootstate/common_sync.go
> +			s.log.Error("Couldn't retrieve Shoot %s from namespace %s. Extension %s state with name %s and purpose %v was NOT synced: %v", shootName, projectNamespace, kind, name, purpose, err)
```suggestion
			s.log.Errorf("Couldn't retrieve Shoot %s from namespace %s. Extension %s state with name %s and purpose %v was NOT synced: %v", shootName, projectNamespace, kind, name, purpose, err)
```

2020-01-24 15:21 UTC, swilen-iwanow commented
@rfranzke sorry for the delay, fixing my local setup took some effort 😌

2020-01-27 08:26 UTC, plkokanov commented
/lgtm on my side.

2020-01-27 08:30 UTC, rfranzke approved these changes

2020-01-27 08:30 UTC, merged