update kyma-addon to kyma 1.10
gardener/gardener pull request #1935
Opened 2020-02-14 08:58 UTC by a-thaler

**What this PR does / why we need it**:
Updates the kyma addon to Kyma 1.10 with the following benefits:
- Support for kubernetes 1.16
- Gardener certificate logic removed from addon as it is part of kyma-installer
- Kyma version has improvements in stability

**Which issue(s) this PR fixes**:
Follow-Up on #1754

**Special notes for your reviewer**:
Only GCP and Azure are supported. 

**Release note**:
```improvement operator
Update of the temporary, experimental Kyma addon to latest Kyma version 1.10. It can be installed onto shoot clusters out-of-the-box by annotating the `Shoot` with `experimental.addons.shoot.gardener.cloud/kyma=enabled`. Be aware that we won't provide upgrades or customization, and that this addon is temporary and will be removed in a future version of Gardener again. Its purpose is to ease the Kyma installation and to show-case which features it provides. It is by no means a production-ready setup. Also, please note that, once enabled, the Kyma addon can never be disabled again. The only way to get rid of it is to delete the shoot cluster. You can check the status of the installation by using `kubectl get installation/kyma-installation -o jsonpath="{'Status: '}{.status.state}{', description: '}{.status.description}"`.
```

2020-02-14 09:00 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=1935) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=1935) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=1935) it.</sub>

2020-02-14 09:08 UTC, rfranzke commented
If we would merge this we would automatically roll out this version to existing Kyma installations. AFAIK Kyma is not upgradeable as of today, correct? Or would this work?

2020-02-14 09:28 UTC, a-thaler commented
Kyma can be upgraded as long as you do it one by another 1.8.x -> 1.9.x -> 1.10.x
As the upgrade should be triggered conscious (deprecated things might be removed) I prefer to keep the clusters in the version they are, the owners can trigger the update manual at any time.
So a re-apply of the addon will happen on changing the addon version? Are there other triggers for a re-apply?

2020-02-14 09:35 UTC, vpnachev reviewed
How is this PR aligned with the release note of #1754 `...Be aware that we won't provide upgrades or customization...`  ?

2020-02-14 20:37 UTC, a-thaler commented
@vpnachev Indeed my goal is just to provide a newer base version for new clusters. Otherwise, the addon has no value at all as it will be based on some outdated version.
I don't want that existing installations are getting upgraded automatically, if people want an upgrade they can do it in a manual way.
It was good feedback by @rfranzke that an automatic apply of the templates will happen.
I will add a check to not deploy the kyma-installer in case of an existing installation.

2020-02-16 19:56 UTC, a-thaler commented
I assured that a re-apply will work by having the job names unique per version.
I labeled the jobs with the version and added an `if` to the job logic to not execute if there is a different version installed already.
With that, no automatic upgrade will happen but new clusters will get 1.10 version.
Please have another look.

2020-02-17 08:43 UTC, suleymanakbas91 requested changes

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/values.yaml
> +  version: "1.10.0"
This is used as a job name above. This won't work. Kubernetes object names must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character.

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/tiller.sh
> +fi
missing new line

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/installation.sh
> +fi
missing new line

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/installation.sh
> +    echo "---> Skipping Kyma installation as there is a Kyma installation already"
```suggestion
    echo "---> Skip Kyma installation as there is already a Kyma installation"
```

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/installation.sh
> +    echo "---> Applying Kyma-Installer for ${KYMA_VERSION}"
```suggestion
    echo "---> Apply Kyma-Installer for Kyma ${KYMA_VERSION}"
```

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/tiller.sh
> +    echo "---> Applying Tiller for ${KYMA_VERSION}"
```suggestion
    echo "---> Apply Tiller for Kyma ${KYMA_VERSION}"
```

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/tiller.sh
> +    echo "---> Skipping Tiller installation as there is a Kyma installation already"
```suggestion
    echo "---> Skip Tiller installation as there is already a Kyma installation"
```

2020-02-17 08:43 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/values.yaml
> +    extensions: "shoot-cert-service,shoot-dns-service"
missing new line

2020-02-17 08:55 UTC, suleymanakbas91 requested changes

2020-02-17 08:55 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/tiller.sh
> +if [ -z "$(kubectl -n kyma-installer get job -l app=kyma-initializer,version!=${KYMA_VERSION})" ]; then
```suggestion
if [ -z "$(kubectl -n kyma-installer get job -l app=kyma-initializer,version!=${KYMA_VERSION} --ignore-not-found)" ]; then
```

2020-02-17 08:55 UTC, suleymanakbas91 commented on charts/shoot-addons-kyma/charts/kyma/files/installation.sh
> +if [ -z "$(kubectl -n kyma-installer get job -l app=kyma-initializer,version!=${KYMA_VERSION})" ]; then
```suggestion
if [ -z "$(kubectl -n kyma-installer get job -l app=kyma-initializer,version!=${KYMA_VERSION} --ignore-not-found)" ]; then
```

2020-02-17 13:22 UTC, suleymanakbas91 submitted a review, later dismissed

2020-02-17 17:33 UTC, rfranzke commented
Puh, I can't overlook this, I can't really judge whether it's doing what it should. I assume you tested that existing Kyma installations are not upgraded and new installations get the new versions. As @suleymanakbas91 approved already and as the addon is experimental only /lgtm from my side as well (without deeply looking into the changes).
Can you please squash your commits so that we can get it merged?

2020-02-18 11:47 UTC, rfranzke approved these changes

2020-02-18 11:47 UTC, merged