Allow sha256 image tags in imagevector
gardener/gardener pull request #1937
Opened 2020-02-14 09:56 UTC by rfranzke

**What this PR does / why we need it**:
The image vector now supports sha256 image tags. Along the way, I fixed a bug in the scoring and improved it so that equal matches lead to a higher score than `>=` or `<=` matches.

**Special notes for your reviewer**:
/cc @timuthy @ccwienk @AndreasBurger @RaphaelVogel @vlerenc 

**Release note**:

```improvement operator
The imagevector does now support `sha256` image tags.
```

2020-02-17 07:13 UTC, timebertt submitted a review, later dismissed
/lgtm
Just a small suggestion from my side.

2020-02-17 07:13 UTC, timebertt commented on charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
> +        {{- end }}
If I see it correctly, the only difference between the if/else branch is the `:`/`@` delimiter.
WDYT about adding a small helper template (in `utils-templates`?) that takes a image struct and prints either `repository:tag` or `repository@sha256:abcdef...`?

2020-02-17 07:24 UTC, timuthy requested changes
Nice! Just a few comments. LGTM otherwise.

2020-02-17 07:24 UTC, timuthy commented on charts/gardener/controlplane/charts/runtime/templates/apiserver/deployment.yaml
> +        {{- end }}
This nicely fits to the utils charts as a template function. WDYT?

2020-02-17 07:24 UTC, timuthy commented on pkg/operation/operation.go
> +		return *o.Seed.Info.Status.KubernetesVersion
Did you add this for a specific reason / use case?
I don't see a clear benefit because now it depends on the reconciliation of the seed resource whereas `o.K8sSeedClient.Version()` always holds the version read from the seed's api server.

2020-02-17 18:06 UTC, rfranzke commented on pkg/operation/operation.go
> +		return *o.Seed.Info.Status.KubernetesVersion
No specific reason. I thought I can get rid of some unneeded call for the version here, but it is anyway cached and stored at the client, so I reverted this change. Thanks for asking back.

2020-02-18 06:29 UTC, timuthy approved these changes

2020-02-18 11:22 UTC, timebertt approved these changes
/lgtm

2020-02-18 11:29 UTC, merged