Adapt PSP RBAC naming and more constants
gardener/gardener pull request #1940
Opened 2020-02-14 14:15 UTC by ialidzhikov

**What this PR does / why we need it**:
Adapt PSP RBAC naming and more constants to the new API group.

**Which issue(s) this PR fixes**:
Ref gardener/gardener#1649

**Special notes for your reviewer**:
I think I will need 1 more PR for deprecated labels/annotations handling in the charts.

**Release note**:

```improvement operator
Two more annotations  from to the old API group have now equivalents in the new API group as follows:

`shoot.garden.sapcloud.io/use-as-seed` -> `shoot.gardener.cloud/use-as-seed`
`shoot.garden.sapcloud.io/ignore-alerts` -> `shoot.gardener.cloud/ignore-alerts`
```

2020-02-17 07:48 UTC, timebertt requested changes
Overall /lgtm
Just some minor nits in the error messages

2020-02-17 07:48 UTC, tim-ebert commented on pkg/gardenlet/controller/backupbucket/backup_bucket_reconciler.go
> +			backupBucketLogger.Errorf("Could not remove deprecated finalizer from Secret referenced in SecretBinding: %s", err.Error())
```suggestion
			backupBucketLogger.Errorf("Could not remove deprecated finalizer from Secret referenced in BackupBucket: %s", err.Error())
```
Copy paste, I guess ;)

2020-02-17 07:48 UTC, tim-ebert commented on pkg/gardenlet/controller/backupbucket/backup_bucket_reconciler.go
> +			backupBucketLogger.Errorf("Failed to remove deprecated external gardener finalizer on referred secret: %+v", err)
```suggestion
			backupBucketLogger.Errorf("Failed to remove deprecated external gardener finalizer on referenced secret: %+v", err)
```

2020-02-17 09:47 UTC, ialidzhikov commented on pkg/gardenlet/controller/backupbucket/backup_bucket_reconciler.go
> +			backupBucketLogger.Errorf("Could not remove deprecated finalizer from Secret referenced in SecretBinding: %s", err.Error())
Nice catch! Thank you.

2020-02-17 09:56 UTC, timebertt submitted a review, later dismissed
Thanks!
/approve

2020-02-17 17:54 UTC, rfranzke submitted a review, later dismissed
/lgtm

2020-02-17 17:55 UTC, rfranzke commented
Can you please rebase? Should we add to the release note that the deprecated `persistentvolume` annotations for `Seed` resources are now deleted?

2020-02-17 22:40 UTC, ialidzhikov commented
> Should we add to the release note that the deprecated persistentvolume annotations for Seed resources are now deleted?

As an end user/operator I would rather assume that with the removal of the old API group, annotations associated with it are also removed. Basically there was only a left-over validation about one of them and they are not used for something else. WDYT?

2020-02-18 05:57 UTC, rfranzke approved these changes
> As an end user/operator I would rather assume that with the removal of the old API group, annotations associated with it are also removed. Basically there was only a left-over validation about one of them and they are not used for something else. WDYT?

Yes, agreed, makes sense. Thank you!

/lgtm

2020-02-18 05:58 UTC, merged