Sync etcd encryption config from garden cluster
gardener/gardener pull request #1978
Opened 2020-02-26 14:25 UTC by plkokanov

**What this PR does / why we need it**:
This PR makes it so that if there is no etcd encryption secret in the Shoot cluster's control plane, but an encryption config has already been created it is synced from the Shoot's namespace in the garden cluster.

This is a quick temporary fix as it will later on be handled by the ShootState.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This might be necessary soon (@timuthy) and I am not sure when the feature to keep ETCD encryption config data in the ShootState will be merged.

**Release note**:

```improvement operator
Shoot's ETCD encryption configuration is synced from the Garden cluster if it does not exist in the Shoot's control plane
```

2020-02-26 14:26 UTC, timuthy commented
/cc @majst01

2020-02-26 15:02 UTC, timuthy requested changes
Thanks a lot for the fix. Looks good in general, just two concerns.

2020-02-26 15:02 UTC, timuthy commented on pkg/operation/botanist/etcdencryption.go
> +func (b *Botanist) encryptionSecretFromGardenSecret(gardenSecret *corev1.Secret) *corev1.Secret {
Can you make it a func without the Botanist pointer receiver and just pass the `SeedNamespace` additionally?

2020-02-26 15:02 UTC, timuthy commented on pkg/operation/botanist/etcdencryption.go
> +	conf, forcePlainTextSecrets, err := b.createOrUpdateEncryptionConfiguration(ctx)
Instead of returning another type, can you just return the whole secret and pass it to `b.syncEncryptionConfigurationToGarden`?

2020-02-27 03:15 UTC, rfranzke approved these changes

2020-02-27 07:25 UTC, timuthy approved these changes

2020-02-27 07:42 UTC, merged