Allow injecting image vector overwrite into etcd-druid
gardener/gardener pull request #2036
Opened 2020-03-11 13:50 UTC by rfranzke

**What this PR does / why we need it**:
With #1762 we have introduced the etcd-druid in `v0.1.3` which is responsible for deploying the etcd `StatefulSet`s, `ConfigMap`s, etc. However, we are still controlling both etcd and the backup-restore sidecar image versions in our `charts/images.yaml`. This is quite dangerous as these versions might not fit to the manifests/configuration applied by the etcd-druid. Instead, it's better to let the etcd-druid control the versions.

@georgekuruvillak is working on etcd-druid side to also support an image vector, similar to Gardener. Consequently, it would also support an image vector overwrite in case an operator wants to customize the image locations. However, so far there is no mechanism to provide such an image vector overwrite to components that are deployed by Gardener.

This PR allows to specify image vector overwrites for components directly deployed by Gardenlet that support image vector overwritings (planned only for etcd-druid, right now).

**Special notes for your reviewer**:
In its current `v0.1.3` version, the etcd-druid is not yet capable of picking up the images from the provided overwrite. @georgekuruvillak is working on introducing the same, and once a new etcd-druid lands in g/g we can remove both `etcd` and `backup-restore` images from our `charts/images.yaml`. Together with this change the `Etcd` will no longer contain `.spec.etcd.image` and `.spec.backup.image` - instead, the druid will implicitly control which images are deployed.

**Release note**:

```improvement operator
It is now possible to specify an image vector overwrite for image vectors of components directly deployed by Gardener (e.g., the etcd-druid will have its own image vector in the future that operators might want to overwrite with custom image locations). Please consult [this document](https://github.com/gardener/gardener/blob/master/docs/deployment/image_vector.md#image-vectors-for-dependent-components) to get more information.
```

2020-03-12 11:58 UTC, timebertt requested changes
/lgtm overall, just a few nits

2020-03-12 11:58 UTC, tim-ebert commented on charts/seed-bootstrap/charts/etcd-druid/templates/configmap-imagevector-overwrite.yaml
> +  namespace: garden
```suggestion
  namespace: {{ .Release.Namespace }}
```

2020-03-12 11:58 UTC, tim-ebert commented on charts/seed-bootstrap/charts/etcd-druid/templates/configmap-imagevector-overwrite.yaml
> +  {{ toYaml .Values.labels | indent 4 }}
```suggestion
{{ toYaml .Values.labels | indent 4 }}
```

2020-03-12 11:58 UTC, tim-ebert commented on pkg/operation/operation.go
> +		ComponentImageVectors:  componentImageVectors,
To me it seems like `Operation.ComponentImageVectors` is not used anywhere.

```suggestion
```

2020-03-12 11:58 UTC, tim-ebert commented on pkg/operation/types.go
> +	ComponentImageVectors     imagevector.ComponentImageVectors
not used, see above

2020-03-13 07:39 UTC, timebertt submitted a review, later dismissed
Thanks, Mr. Rafael.
/approve

2020-03-13 16:01 UTC, danielfoehrKn submitted a review, later dismissed
Looks good

2020-03-13 16:01 UTC, danielfoehrKn commented on pkg/utils/imagevector/imagevector_components.go
> +// Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```suggestion
// Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```

2020-03-13 16:01 UTC, danielfoehrKn commented on pkg/utils/imagevector/imagevector_components_test.go
> +// Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```suggestion
// Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```

2020-03-13 16:01 UTC, danielfoehrKn commented on pkg/utils/imagevector/imagevector_components_test.go
> +	Describe("> ComponentImageVectors", func() {
```suggestion
	Describe("#ComponentImageVectors", func() {
```

2020-03-13 17:32 UTC, rfranzke commented
Adressed all comments, merging after CI passes.

2020-03-13 17:51 UTC, merged