Added new metric to monitor CPU throttling
gardener/gardener pull request #2046
Opened 2020-03-14 03:03 UTC by ggaurav10

**What this PR does / why we need it**:
Added new metric to monitor CPU throttling

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Added new metric to monitor CPU throttling
```

2020-03-14 11:09 UTC, vpnachev commented
@ggaurav10 could you explain why these metrics are needed?
My concern is to not overload prometheus performance.

2020-03-14 11:44 UTC, rfranzke submitted a review, later dismissed

2020-03-14 13:35 UTC, ggaurav10 commented
yes @vpnachev, this was my concern as well, hence the delay between making the change and raising a PR :)
Recent issue in our seeds, and a possibility of CPU throttling was the motivation behind finally raising this PR. This would help in figuring out if any of the pods are/were cpu throttled. I am not sure if there is any other way this could be figured out, since unlike memory (oomkills) there is no other trace of cpu throttling.

2020-03-15 10:01 UTC, amshuman-kr requested changes
@ggaurav10 Thanks for adding the metric.

Can you please also add seed-wide aggregate metrics (sum, sum_by_container and sum_cp) [here](https://github.com/gardener/gardener/blob/master/charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml)?

LGTM otherwise.

2020-03-16 08:53 UTC, amshuman-kr reviewed
Is the aggregation based on rate appropriate?

2020-03-16 08:53 UTC, amshuman-kr commented on charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
> +    expr: sum(rate(container_cpu_cfs_throttled_seconds_total[5m])) by (container)
Does is make sense to aggregate the rate? `container_cpu_cfs_throttled_seconds_total` is not about how much CPU cores are throttled, right?

2020-03-16 08:53 UTC, amshuman-kr commented on charts/seed-bootstrap/prometheus-rules/recording-rules.rules.yaml
> +    expr: sum(rate(container_cpu_cfs_throttled_periods_total[5m])) by (container)
Same as above.

2020-03-16 09:30 UTC, amshuman-kr approved these changes
Thanks @ggaurav10 for the links.

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/expression/
https://opensource.zalando.com/skipper/operation/operation/

2020-03-16 13:18 UTC, wyb1 approved these changes
/lgtm

2020-03-16 13:22 UTC, vpnachev approved these changes
/approve

2020-03-16 13:28 UTC, merged

2020-03-23 10:27 UTC, mwennrich commented
So this will be in the next release?

2020-03-23 10:39 UTC, rfranzke commented
@mwennrich yes, planned for this week.