Enable ScheduleDaemonSetPods featuregate by default for v1.11
gardener/gardener pull request #2077
Opened 2020-03-20 12:46 UTC by zanetworker

**What this PR does / why we need it**:
For < 1.12 shoot clusters the daemon set pods are not scheduled by the kube-scheduler but by the kube-controller-manager. This can lead to situations where pods with a high priority cannot be started properly. This PR adds `ScheduleDaemonSetPods` by default for  v1.11 clusters. 

**Which issue(s) this PR fixes**:
Fixes #2076 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
ScheduleDaemonSetPods feature gate is now enabled by default to ensure correct scheduling of system-critical-pods
```

2020-03-20 15:09 UTC, rfranzke requested changes

2020-03-20 15:09 UTC, rfranzke commented on charts/seed-controlplane/charts/kube-scheduler/templates/_helpers.tpl
> +{{- end }}
```suggestion
{{- if semverCompare "1.11.x" .Values.kubernetesVersion }}
- --feature-gates=ScheduleDaemonSetPods=true
{{- end }}
{{- end -}}
```

2020-03-20 15:09 UTC, rfranzke commented on charts/seed-controlplane/charts/kube-controller-manager/templates/_helpers.tpl
> +{{- if semverCompare "1.11" .Values.kubernetesVersion }}
```suggestion
{{- if semverCompare "1.11.x" .Values.kubernetesVersion }}
```

2020-03-21 10:55 UTC, rfranzke approved these changes
/lgtm

2020-03-21 10:55 UTC, rfranzke commented on charts/seed-controlplane/charts/kube-apiserver/templates/_helpers.tpl
> +{{- if semverCompare "1.11.x" .Values.kubernetesVersion }}
nice catch! :)

2020-03-21 13:18 UTC, rfranzke commented
/hold, identified further issues when the feature gate is enabled that need to be investigated first.

2020-03-23 04:54 UTC, rfranzke commented
@zanetworker we have seen for a 1.11.10 cluster having this feature gate enabled that the kube-scheduler does not schedule the DaemonSet pods for newly created nodes with the reasoning "node not ready". However, for the node to get ready the DaemonSet pods for kube-proxy + calico need to be installed (both running in host network). But as the kube-scheduler does not schedule them the node can never get ready.

2020-03-23 09:49 UTC, zanetworker commented
Closing this PR based on our discussion. 

For 1.10 and 1.11 clusters enabling this feature-gate won't help much as the `kube-scheduler` takes node readiness into consideration  and fails to schedule Networking pods (e.g., Calico) which will result in a broken setup due to `FailedPlacement`.  As a result, we recommend upgrading to higher versions of kubernetes for clusters with these issues where the feature-gate is enabled by default.

2020-03-23 09:49 UTC, closed without merging