increase timeout for care test
gardener/gardener pull request #2094
Opened 2020-03-25 11:54 UTC by danielfoehrKn

**What this PR does / why we need it**:
Increases the timeout for the care-controller integration test and flags the test as beta() and serial().

This is to avoid failures in case the condition is not met within the current timeout (5 minutes).
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

@schrodit @dguendisch 
Can you let me know if that helps?
**Release note**:

```improvement operator

```

2020-03-25 11:57 UTC, schrodit requested changes

2020-03-25 11:57 UTC, schrodit commented on test/integration/shoots/care/shoot_care.go
> +	timeout = 20 * time.Minute
We should increase to at least 30min? as line 81 and line 65 have at least 30 minutes timeout

2020-03-27 07:46 UTC, rfranzke commented
As discussed, let's close the PR - the test's purpose is actually to succeed only if the shoot condition is properly set to `False` after a short time. If it takes longer then either our code or the test is buggy.

Please open a new PR with either fixes to the code or to the test.

2020-03-27 07:46 UTC, closed without merging

2020-03-27 07:56 UTC, dguendisch commented
Recall that this PR also set the Beta label to the test, so keep in mind that without further changes, the next gardener release will fail in integration tests.

2020-03-27 07:59 UTC, rfranzke commented
@danielfoehrKn can you first please create a separate PR only for labelling the test as beta to not hold the release?