Add OpenStack Designate dns provider
gardener/gardener pull request #215
Opened 2018-06-12 10:54 UTC by databus23

This PR adds support for OpenStack Designate as a dns provider.

Manually tested and verified to work on Converged Cloud EE.

Let me know what you think.

/cc @vasu1124 @BugRoger

2018-06-12 10:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=215) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=215) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: databus23<br/>:x: BugRoger<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=215) it.</sub>

2018-06-13 07:11 UTC, rfranzke requested changes
Thank you a lot for your efforts @databus23 and @BugRoger, it looks very good!
Could you please add the mentioned example configuration/manifests and a small test in the admission controller before we get this merged?

2018-06-13 07:11 UTC, rfranzke commented on charts/gardener/templates/secret-default-domain.yaml
> +{{- if eq $domain.provider "aws-route53" }}
Could you please also give a hint that `openstack-designate` is supported and which keys are required [here](https://github.com/gardener/gardener/blob/master/charts/gardener/values.yaml#L76) (similar to `google-clouddns`)? Can you please also add an example manifest [here](https://github.com/gardener/gardener/blob/master/example/10-secret-default-domain.yaml)?

2018-06-13 07:11 UTC, rfranzke commented on charts/gardener/templates/secret-internal-domain.yaml
> +{{- if eq .Values.controller.internalDomain.provider "aws-route53" }}
Could you please also give a hint that `openstack-designate` is supported and which keys are required [here](https://github.com/gardener/gardener/blob/master/charts/gardener/values.yaml#L65) (similar to `google-clouddns`)? Can you please also add an example manifest [here](https://github.com/gardener/gardener/blob/master/example/10-secret-internal-domain.yaml)?

2018-06-13 07:11 UTC, rfranzke commented on plugin/pkg/shoot/dnshostedzone/admission.go
> +	case garden.DNSOpenstackDesignate:
Could you please add a test for the OpenStack case (similar to [that](https://github.com/gardener/gardener/blob/master/plugin/pkg/shoot/dnshostedzone/admission_test.go#L210) and [that](https://github.com/gardener/gardener/blob/master/plugin/pkg/shoot/dnshostedzone/admission_test.go#L175))?

2018-06-13 09:11 UTC, databus23 commented
@rfranzke I updated the PR according to your feedback.

2018-06-13 10:05 UTC, rfranzke approved these changes
LGTM, thank you!

2018-06-13 10:05 UTC, merged