Add elastic-search-service-account
gardener/gardener pull request #2171
Opened 2020-04-09 16:54 UTC by vlvasilev

**What this PR does / why we need it**:
With this PR we add dedicated service account for the elastic-search pods.
**Which issue(s) this PR fixes**:
Fixes [#1975](https://github.com/gardener/gardener/issues/1975)

**Release note**:

```noteworthy operator
- add ServiceAccount for elastic-search
```

2020-04-09 17:03 UTC, vpnachev requested changes
Thanks!
Some minor nits

2020-04-09 17:03 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/statefulset.yaml
> +      serviceAccount: elasticsearch-logging
```suggestion
```

> DeprecatedServiceAccount is a depreciated alias for ServiceAccountName. Deprecated: Use serviceAccountName instead.

2020-04-09 17:03 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/statefulset.yaml
> +      automountServiceAccountToken: true
```suggestion
```
It is enabled by default.

2020-04-09 17:03 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-service-account.yaml
> +    garden.sapcloud.io/role: logging
use `gardener.cloud/role`

2020-04-09 17:03 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-role.yaml
> +    garden.sapcloud.io/role: logging
```suggestion
    gardener.cloud/role: logging
```

2020-04-09 17:03 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-role-binding.yaml
> +    garden.sapcloud.io/role: logging
```suggestion
    gardenre.cloud/role: logging
```

2020-04-09 18:30 UTC, ialidzhikov submitted a review, later dismissed
```
rm pkg/apis/protoc-3.7.1-linux-x86_64.zip
```

2020-04-13 11:11 UTC, vpnachev requested changes
I was wrong with my previous reviews, you still need to use the old key for the labels.
It used for the deletion of the logging resources here https://github.com/gardener/gardener/blob/248ac836e5177852c570dfbac323690a802ae754/pkg/operation/common/utils.go#L326-L338.

Also, you have to extended this list with `Roles` and `RoleBindings`.

2020-04-13 11:11 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-role-binding.yaml
> +    gardener.cloud/role: logging
Please, add the old label key `garden.sapcloud.io`, too.
It is needed for the deletion of the logging resources.

2020-04-13 11:11 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-role.yaml
> +    gardener.cloud/role: logging
Please, add the old label key `garden.sapcloud.io`, too.
It is needed for the deletion of the logging resources.

2020-04-13 11:11 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-service-account.yaml
> +    gardener.cloud/role: logging
Please, add the old label key `garden.sapcloud.io`, too.
It is needed for the deletion of the logging resources.

2020-04-13 11:11 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/statefulset.yaml
> +    gardener.cloud/role: logging
Please, add the old label key `garden.sapcloud.io`, too.
It is needed for the deletion of the logging resources.

2020-04-14 12:33 UTC, vpnachev requested changes
nit

2020-04-14 12:33 UTC, vpnachev commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/elasticsearch/elasticsearch-logging-role.yaml
> +   garden.sapcloud.io/role: logging
```suggestion
    garden.sapcloud.io/role: logging
```

2020-04-14 13:07 UTC, vpnachev approved these changes
/lgtm

2020-04-14 13:52 UTC, merged