Refactor create shoot test to make it reuseable
gardener/gardener pull request #2177
Opened 2020-04-14 12:32 UTC by tim-ebert

**What this PR does / why we need it**:
This PR refactors the `CreateShoot` integration test to make it reusable in other tests.
Other test can now leverage the new `ShootCreationFramework` to easily create a Shoot just like the `CreateShoot` test does.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc @schrodit 

**Release note**:

```improvement operator
NONE
```

2020-04-14 19:10 UTC, dguendisch submitted a review, later dismissed

2020-04-15 06:03 UTC, schrodit requested changes
Rest is lgtm

2020-04-15 06:03 UTC, schrodit commented on test/framework/shoot_utils.go
> +	shoot.Annotations[v1beta1constants.AnnotationShootIgnoreAlerts] = "true"
```suggestion
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1.SetMetaDataAnnotation(&shoot.ObjectMeta, v1beta1constants.AnnotationShootIgnoreAlerts, "true")
```

2020-04-15 06:14 UTC, tim-ebert commented on test/framework/shoot_utils.go
> +	shoot.Annotations[v1beta1constants.AnnotationShootIgnoreAlerts] = "true"
Done, PTAL :)

2020-04-15 06:18 UTC, schrodit approved these changes

2020-04-15 08:25 UTC, tim-ebert commented
Hmm, I can't merge this PR as @gardener/test-infra-maintainers don't have write access to g/g anymore, so their reviews don't count towards mergeability...

2020-04-15 08:30 UTC, rfranzke commented
They never had 😉What about now?

2020-04-15 08:43 UTC, tim-ebert commented
Ah, I thought they had, because that's the reason github was telling me, why the checkmark wasn't green 😄

2020-04-15 08:43 UTC, merged