Add alert if backup sidecar metrics are not scrapped
gardener/gardener pull request #2189
Opened 2020-04-16 08:56 UTC by swapnilgm

Signed-off-by: Swapnil Mhamane <swapnil.mhamane@sap.com>

**What this PR does / why we need it**:
In case the backup sidecar is configured wrongly, or metrics data points are not update by backup sidecar due to some reason. Then it could mean that backups are not being processed.
Alert-manager with current rule don't raise alerts in above case.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc @wyb1 agreed to add alerting rule test for this new alert.
@shreyas-s-rao check if alerting expression in fine from etcd-backup-restore point of view.
 
**Release note**:

```improvement operator
None
```

2020-04-16 08:57 UTC, swapnilgm commented
/assign @wyb1 @shreyas-s-rao

2020-04-16 09:02 UTC, rfranzke commented
Ideally, all of the etcd specific alerts should be moved to etcd-druid and out of g/g. There is a contract how to contribute alerts/dashboards/scrape config: https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md

WDYT?

2020-04-16 11:29 UTC, shreyas-s-rao requested changes
@swapnilgm  Thanks for the PR. The current alert expression works for a general shoot, wouldn't work in the case where there are no shoot operations, because of which there are no updates to etcd. You would have to use the `etcd_debugging_mvcc_current_revision` to check if there's been an etcd update yet the `etcdbr_snapshot_required` metric is absent. Also add `etcd_debugging_mvcc_current_revision` to the list of allowed KubeETCD3 metrics in prometheus `values.yaml`.

2020-04-16 11:29 UTC, shreyas-s-rao commented on charts/seed-monitoring/charts/core/charts/prometheus/rules/kube-etcd3.rules.yaml
> +    expr: absent(etcdbr_snapshot_required{job="kube-etcd3-backup-restore",role="main"}) == 1
```suggestion
    expr: (absent(etcdbr_snapshot_required{job="kube-etcd3-backup-restore",role="main"}) == bool 1) + (changes(etcd_debugging_mvcc_current_revision{job="kube-etcd3",role="main"}) >= bool 1) == 2
```

2020-04-17 04:44 UTC, swapnilgm commented
> Ideally, all of the etcd specific alerts should be moved to etcd-druid and out of g/g. There is a contract how to contribute alerts/dashboards/scrape config: https://github.com/gardener/gardener/blob/master/docs/extensions/logging-and-monitoring.md
> 
> WDYT?

Makes sense to me. But lets just go ahead with this PR. And take this as separate task.

2020-04-17 05:34 UTC, rfranzke approved these changes
Sure. @shreyas-s-rao, please review/approve.

2020-04-17 06:35 UTC, shreyas-s-rao commented
/lgtm

2020-04-17 06:37 UTC, merged