Adding gVisor Integration tests
gardener/gardener pull request #2220
Opened 2020-04-22 16:10 UTC by danielfoehrKn

**What this PR does / why we need it**:
Adding integration tests for the gVisor container runtime integration in Gardener.

To test for the first release of [gVisor extension](https://github.com/gardener/gardener-extension-runtime-gvisor) .

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Has the same suboptimal behaviour as discussed in this [PR](https://github.com/gardener/gardener/pull/2201#discussion_r411907231) - is restricted to Ubuntu OS. 
I think we can still go ahead with this PR as the already existing containerd integration test is configured the same way. As soon as there is a solution, these two integration tests can be easily adjusted. 

**Release note**:

```improvement operator

```

2020-04-22 16:13 UTC, ialidzhikov requested changes

2020-04-22 16:13 UTC, ialidzhikov commented on test/integration/shoots/operations/containerruntime.go
> +	id, err := gardenerutils.GenerateRandomStringFromCharset(3, allowedCharacters)
You could use .metadata.generateName for the Pod name.

2020-04-22 16:18 UTC, danielfoehrKn commented on test/integration/shoots/operations/containerruntime.go
> +	id, err := gardenerutils.GenerateRandomStringFromCharset(3, allowedCharacters)
true, then I ll also adjust that in the test-framework where it is used similarely.

2020-04-23 06:44 UTC, tim-ebert commented on pkg/apis/core/types_shoot.go
> +	ContainerRuntimeGVisor ContainerRuntimeName = "gvisor"
Why is this here?
I don't think, there should be any known provider names in Gardener's API...
Btw, isn't this a clear case for an integration test, that should be part of the respective Extension repo?

2020-04-23 07:39 UTC, dguendisch approved these changes
integrationtest-wise lgtm

2020-04-23 09:47 UTC, ialidzhikov commented on test/integration/shoots/operations/containerruntime.go
> +					TerminationMessagePolicy: corev1.TerminationMessageReadFile,
These are the default values for `Resources`, `TerminationMessagePath` and  `TerminationMessagePolicy `, right? You could remove them.

2020-04-23 09:47 UTC, danielfoehrKn commented
Decided that this integration test rather belongs [in the respective extension repo](https://github.com/gardener/gardener-extension-runtime-gvisor).

2020-04-23 09:47 UTC, closed without merging

2020-04-23 11:48 UTC, danielfoehrKn commented
Opened in the [gVisor-extension.](https://github.com/gardener/gardener-extension-runtime-gvisor/pull/6)