Fix retry cycle time for shoots
gardener/gardener pull request #2324
Opened 2020-05-13 15:13 UTC by timuthy

**What this PR does / why we need it**:
This PR fixes an issue which reset the `.status.retryCycleStartTime` in several cases too often and thus prevented erroneous shoot clusters from transitioning to a `Failed` state.

The feature `confineSpecUpdateRollout` (https://github.com/gardener/gardener/pull/2233) for shoots in a failed state is now respected as well. Normally a `.spec` update resets the failed status and with `confineSpecUpdateRollout` this should only happen in the maintenance time window.

Additionally, @rfranzke and I suggest to decrease the default value for the Gardenlet setting `retryDuration` from 24h to 12h with the assumption that shoots failing for ~12h most often need an intervention by the shoot owner, i.e. it isn't reasonable to retry for another 12h w/o any spec update.

**Release note**:

```improvement operator
An issue has been fixed with prevented failed shoots from being excluded from reconciliation after the [retryDuration](https://github.com/gardener/gardener/blob/a46946fdce6bf75e0ce18272e7762f5765cced39/example/20-componentconfig-gardenlet.yaml#L33) is exceeded.
```
```noteworthy operator
The default value for [retryDuration](https://github.com/gardener/gardener/blob/a46946fdce6bf75e0ce18272e7762f5765cced39/example/20-componentconfig-gardenlet.yaml#L33) has been changed from 24h to 12h. Hence, Gardenlet tries to reconcile shoots with erroneous operations for 12 hours (by default). After this period of time only the `retry` operation, a `.spec` change, or a rollout of a new Gardenlet version re-triggers a reconciliation.
```

2020-05-13 17:48 UTC, rfranzke commented
/area/robustness
/kind/bug
/needs/review
/size/xs

2020-05-13 17:57 UTC, rfranzke requested changes

2020-05-13 17:57 UTC, rfranzke commented on plugin/pkg/shoot/validator/admission.go
> +	if shoot.Spec.Maintenance != nil && utils.IsTrue(shoot.Spec.Maintenance.ConfineSpecUpdateRollout) &&
Can you add a test case for this?

2020-05-13 17:57 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
> +	fmt.Printf("RetryCycleStartTime %v, Generation %v, ObservedGeneration %v, Gardener status version %v, Gardener version %v, Last Operation %v\n",
Left over, can you remove it?

2020-05-14 05:43 UTC, timebertt reviewed
/lgtm apart from @rfranzke's comments

2020-05-14 06:43 UTC, rfranzke commented
/area/robustness
/kind/bug
/needs/review
/size/xs

2020-05-14 07:02 UTC, rfranzke approved these changes
/lgtm
/needs/second-opinion

2020-05-14 07:08 UTC, timebertt approved these changes
/lgtm

2020-05-14 12:55 UTC, merged