Support gcm webhooks in nodeless setup
gardener/gardener pull request #2363
Opened 2020-05-20 15:52 UTC by tim-ebert

**How to categorize this PR?**

/area dev-productivity
/kind bug
/priority normal

**What this PR does / why we need it**:
With `./hack/local-development/dev-setup-register-gardener --with-webhooks` you can register gcm's validating webhooks in your local dev-setup.
Previously, this was not working for the nodeless dev-setup, because the gcm service was not properly configured.
This issue is fixed with this PR.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Can someone who doesn't you the nodeless setup check, that the changed scripts still work for the other cases?

**Release note**:

```improvement developer
If you are using the [nodeless dev-setup](https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md#start-a-local-kubernetes-cluster), you can now register `gardener-controller-manager`'s validating webhooks by running `hack/local-development/dev-setup-register-gardener --with-webhooks`.
```

2020-05-22 07:06 UTC, rfranzke commented
/assign @timuthy @zanetworker 
/needs review

2020-05-25 08:16 UTC, timuthy requested changes
Nice fix. Just nits.

2020-05-25 08:16 UTC, timuthy commented on hack/local-development/dev-setup-register-gardener
> +  CONTROLLER_MANAGER_PORT_STRING="      port: $CONTROLLER_MANAGER_SERVICE_PORT"
I suspect it wouldn't hurt to set this every time (not only for a nodeless setup) and leave out line 35. WDYT?

2020-05-25 08:16 UTC, timuthy commented on hack/local-development/dev-setup-register-gardener
>      port: 443
```suggestion
    port: $CONTROLLER_MANAGER_SERVICE_PORT
```

2020-05-25 14:08 UTC, tim-ebert commented
Thanks for your review, I applied your suggestions. PTAL :)

2020-05-27 07:31 UTC, timuthy commented
```
make dev-setup
Found Nodeless Kubernetes ...
namespace/garden unchanged
namespace/garden-dev unchanged
service/gardener-apiserver unchanged
The Service "gardener-controller-manager" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services
make: *** [dev-setup] Error 1
```
This error occurs if you've have ever run `make dev-setup` or `make dev-setup-register-gardener` before this fix. Maybe we can run `k -n garden delete svc $CONTROLLER_MANAGER_SERVICE_NAME` right before applying the service or do a `k replace`?

2020-05-28 07:23 UTC, rfranzke commented
/needs rebase

2020-05-28 13:01 UTC, tim-ebert commented
@timuthy good catch, thanks for finding!
Actually, we already deleted `$CONTROLLER_MANAGER_SERVICE_NAME` but just not in the `garden` namespace...
I adapted, should be good now, can you check again, please?

/remove needs/rebase

2020-05-28 14:27 UTC, timuthy submitted a review, later dismissed
/lgtm

2020-05-28 14:43 UTC, tim-ebert commented
Force pushed to retrigger failing CI tests

2020-05-28 16:51 UTC, vpnachev commented
You can use

/cla

to re-trigger it :smile:

2020-05-28 16:51 UTC, gardener-botmanager commented
@vpnachev I reached out successfully to the cla-assistant to recheck this pull request.

2020-05-28 17:12 UTC, tim-ebert commented
Yeah, not the cla assistant, but the ginkgo tests were failing (unrelated to this PR) 😉

2020-05-28 17:12 UTC, rfranzke approved these changes
/lgtm

2020-05-28 17:17 UTC, merged