Removed testgrid links for azure and openstack cluster < 1.15
gardener/gardener pull request #2485
Opened 2020-06-22 14:39 UTC by schrodit

Removed the testgrid links for Azure and Openstack clusters with K8s version < 1.15 and added a disclaimer

**How to categorize this PR?**

/area Documentation
/priority small

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

2020-06-22 14:50 UTC, dguendisch requested changes
After this PR please also update https://github.com/gardener/gardener-extension-provider-azure

2020-06-22 14:50 UTC, dguendisch commented on README.md
> +[1] Version is technically supported but not activly tested. Therefore, the usage of this version is at your own risk.
Would add `no longer` to indicate that we tested them in the past but don't see value for testing anymore.
Would rephrase the second sentence as everything in public gardener is used at "your own risk".
How about that?
```suggestion
[1] Version is technically supported but no longer actively tested. Regressions will go unnoticed.
```

2020-06-23 05:52 UTC, rfranzke approved these changes

2020-06-23 07:47 UTC, vpnachev approved these changes
/lgtm

2020-06-23 08:12 UTC, dguendisch approved these changes

2020-06-23 08:13 UTC, merged