Use controller runtime for federated seed controllers
gardener/gardener pull request #2516
Opened 2020-06-25 16:09 UTC by timuthy

**How to categorize this PR?**

/area control-plane
/area dev-productivity
/kind enhancement
/priority normal

**What this PR does / why we need it**:
This PR changes makes the federated seed controller (extensions workers) use the [Controller-Runtime](https://github.com/kubernetes-sigs/controller-runtime) manager and controllers in favor of the generated informers. It's a further and consequent step towards the Controller-Runtime and allows to get rid of any third party generated client code (e.g. from external-dns-management) which turned out to be a blocker for #2489.

**Special notes for your reviewer**:
I tested several scenarios, e.g. shoot creation/deletion, adding/removing workers with "new" OS type, seed creation/deletion, provoking errors in the extension controllers, etc.. It'd be nice if you could double check the state reconciliation as well (/cc @plkokanov @swilen-iwanow).

The controller manager that is built for each seed now uses the client/informer cache introduced by @tim-ebert.

**Release note**:

```improvement operator
NONE
```

2020-06-26 05:33 UTC, tim-ebert commented
/assign

2020-06-26 06:12 UTC, timuthy commented
Update:
- Resolved golang-ci issues
- File renaming
- Small channel improvements

2020-06-26 07:41 UTC, timuthy commented
/retest

2020-06-26 08:42 UTC, plkokanov commented
/assign

2020-06-26 11:34 UTC, timebertt reviewed
Looks quite good!

I haven't looked into it in detail, but I am slightly worried about how that will play together with invalidating the seed client in the client map. I.e. if the Seed's kubernetes version is upgraded, the client will be invalidated automatically, which means that all the informers/watches will be stopped. That in turn means, that the controllers you have here won't receive any watch events anymore.
Have you tested this scenario?

2020-06-26 14:21 UTC, timuthy commented
> I haven't looked into it in detail, but I am slightly worried about how that will play together with invalidating the seed client in the client map. I.e. if the Seed's kubernetes version is upgraded, the client will be invalidated automatically, which means that all the informers/watches will be stopped. That in turn means, that the controllers you have here won't receive any watch events anymore.

Nice scenario but no, I didn't test this. Let me check again and come back. But it will probably take me some days since I'm out of office next week.

2020-06-29 06:19 UTC, plkokanov commented
> Looks quite good!
> 
> I haven't looked into it in detail, but I am slightly worried about how that will play together with invalidating the seed client in the client map. I.e. if the Seed's kubernetes version is upgraded, the client will be invalidated automatically, which means that all the informers/watches will be stopped. That in turn means, that the controllers you have here won't receive any watch events anymore.
> Have you tested this scenario?

Not sure if the gardenlet leader election mechanism uses the same clients. If so invalidating the client would cause the federated controllers to shut down and gardenlet to restart.
So to cover the cases where one gardenlet manages multiple seeds maybe we should implement a federated leader-election mechanism for the federated controllers?

2020-06-29 06:27 UTC, tim-ebert commented
> Not sure if the gardenlet leader election mechanism uses the same clients. If so invalidating the client would cause the federated controllers to shut down and gardenlet to restart.

Nope, the leader election is using its own client:

https://github.com/gardener/gardener/blob/398870a9a2db8eb5eaf4489538a64f20ff6cd7fd/cmd/gardenlet/app/gardenlet.go#L316-L323

> So to cover the cases where one gardenlet manages multiple seeds maybe we should implement a federated leader-election mechanism for the federated controllers?

Hmm, I'm not sure what you mean by "federated leader-election". Can you elaborate?
(Anyhow, using the gardenlet for multiple seeds is not recommended and mostly only a development scenario)

2020-06-29 13:31 UTC, plkokanov commented
Currently (afaik) there is no way to stop a federated controller's control loop  from running for a particular seed (unless the seed is deleted). So in the case of one gardenlet managing multiple seeds you could have a scenario where a particular seed should no longer be managed by the same gardenlet, but by another. You would want to have a mechanism which can stop the federated controller for that seed and start it in the new gardenlet.

But as you mentioned, this is not a recommended setup and will most likely be encountered only in a development scenario. Also I believe we're side tracking a bit from the PR :).

Anyway, the PR looks good. 
I'll test it out as well a bit later today.

2020-06-30 06:46 UTC, tim-ebert commented
/hold until `v1.7` is released

2020-07-03 11:46 UTC, rfranzke commented
/unhold as v1.7.0 is released

2020-07-06 07:55 UTC, plkokanov commented
Ran the PR locally but the `Infrastructure` and `Worker` resources are not synced to the `ShootState`

2020-07-06 08:12 UTC, plkokanov requested changes
This should fix the issue that I mentioned about syncing the state to the `ShootState`

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.BackupEntryResource, func() runtime.Object { return &extensionsv1alpha1.BackupEntryList{} }),
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.BackupEntryResource, func() runtime.Object { return &extensionsv1alpha1.BackupEntry{} }),
```

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.ContainerRuntimeResource, func() runtime.Object { return &extensionsv1alpha1.ContainerRuntimeList{} }),
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.ContainerRuntimeResource, func() runtime.Object { return &extensionsv1alpha1.ContainerRuntime{} }),
```

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.ControlPlaneResource, func() runtime.Object { return &extensionsv1alpha1.ControlPlaneList{} }),
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.ControlPlaneResource, func() runtime.Object { return &extensionsv1alpha1.ControlPlane{} }),
```

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.ExtensionResource, func() runtime.Object { return &extensionsv1alpha1.ExtensionList{} }),
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.ExtensionResource, func() runtime.Object { return &extensionsv1alpha1.Extension{} }),
```

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.InfrastructureResource, func() runtime.Object { return &extensionsv1alpha1.InfrastructureList{} }),
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.InfrastructureResource, func() runtime.Object { return &extensionsv1alpha1.Infrastructure{} }),
```

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.NetworkResource, func() runtime.Object { return &extensionsv1alpha1.NetworkList{} }),
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.NetworkResource, func() runtime.Object { return &extensionsv1alpha1.Network{} }),
```

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.OperatingSystemConfigResource, func() runtime.Object { return &extensionsv1alpha1.OperatingSystemConfig
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.OperatingSystemConfigResource, func() runtime.Object { return &extensionsv1alpha1.OperatingSystemConfig{} }),
```

2020-07-06 08:12 UTC, plkokanov commented on pkg/gardenlet/controller/federatedseed/extensions/add.go
> +				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.WorkerResource, func() runtime.Object { return &extensionsv1alpha1.WorkerList{} }),
```suggestion
				reconciler:          stateControl.createShootStateSyncReconcileFunc(ctx, extensionsv1alpha1.WorkerResource, func() runtime.Object { return &extensionsv1alpha1.Worker{} }),
```

2020-07-09 13:26 UTC, timuthy commented
> I haven't looked into it in detail, but I am slightly worried about how that will play together with invalidating the seed client in the client map. I.e. if the Seed's kubernetes version is upgraded, the client will be invalidated automatically, which means that all the informers/watches will be stopped.

I just talked to @tim-ebert and he's going to address this case in a separate PR because it needs to be handled more generically.

@plkokanov many thanks for testing and reviewing this PR. I'll address your comments asap.

2020-07-14 14:14 UTC, timuthy commented
PR is closed in favor of #2588 which uses the cached informers directly.

2020-07-14 14:14 UTC, closed without merging