Fix replica computation for kube-controller-manager
gardener/gardener pull request #2518
Opened 2020-06-26 08:06 UTC by rfranzke

**How to categorize this PR?**

/area control-plane
/kind technical-debt
/priority normal

**What this PR does / why we need it**:
This PR fixes the computation of the replica count for KCM which is under control by DWD. Earlier, the logic had the implicit assumption that DWD will scale up KCM for newly created shoots. However, this is a dependency which we don't want to have.

**Special notes for your reviewer**:
/invite @dguendisch @schrodit @ggaurav10 @amshuman-kr 

**Release note**:

```improvement operator
NONE
```

2020-06-26 08:14 UTC, dguendisch submitted a review, later dismissed
Thank you!

2020-06-26 08:36 UTC, ggaurav10 requested changes

2020-06-26 08:36 UTC, ggaurav10 commented on pkg/operation/botanist/controlplane.go
> +		if b.Shoot.HibernationEnabled && b.Shoot.Info.Status.IsHibernated {
Should it be `==` instead of `&&`?

2020-06-26 15:38 UTC, vpnachev submitted a review, later dismissed
/lgtm

2020-06-29 06:07 UTC, rfranzke commented on pkg/operation/botanist/controlplane.go
> +		if b.Shoot.HibernationEnabled && b.Shoot.Info.Status.IsHibernated {
Yes, nice catch, thanks. PTAL

2020-06-29 06:08 UTC, timebertt approved these changes
/lgtm

2020-06-29 06:16 UTC, ggaurav10 approved these changes

2020-06-29 06:18 UTC, schrodit approved these changes

2020-06-29 07:19 UTC, merged