Local Garden Dev on Windows
gardener/gardener pull request #2578
Opened 2020-07-11 06:59 UTC by guydaichs

**How to categorize this PR?**
/area dev-productivity
/kind enhancement
/priority normal

**What this PR does / why we need it**:

Fixes local-garden containers' [host machine address](https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds) and api-server binding, such that the nodeless gardener dev env will work on [WSL2 ](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index) with [WSL2-integrated docker for windows](https://docs.docker.com/docker-for-windows/wsl/). 

**Release note**:
```improvement developer
The Nodeless Development Environment also works on windows, using WSL2 and docker for windows
```

2020-07-11 07:55 UTC, vpnachev commented
Thanks for the contribution of support for local setup running on windows.

Could you add some info about it in the [local setup](https://github.com/gardener/gardener/blob/master/docs/development/local_setup.md). Basically a disclaimer that windows is supported for local development (we have not declared so far that it was working only on MacOS and Linux distros, this will have to be mentioned, too)
Also, list the limitations and prerequisites, if any.

2020-07-13 06:15 UTC, timebertt submitted a review, later dismissed
Thanks for enabling the local setup on WSL!
/lgtm from a code perspective, but I can't test it on windows...

/ok-to-test

2020-07-13 08:38 UTC, vpnachev commented
/ok-to-test

2020-07-13 11:10 UTC, vpnachev requested changes
Just a minor improvement of the documentation.
Otherwise looks good to me as I am also not able to validate it.

2020-07-13 11:10 UTC, vpnachev commented on docs/development/local_setup.md
> +The local gardener setup can also run on the Windows Subsystem for Linux 2.
```suggestion
Apart from Linux distributions and  MacOS, the local gardener setup can also run on the Windows Subsystem for Linux 2. 
```

2020-07-14 08:09 UTC, tim-ebert commented
/status author-action

2020-07-14 15:10 UTC, danielfoehrKn commented
@mandelsoft are you able to test this as to my knowledge you at least have a windows machine?

2020-07-16 05:41 UTC, guydaichs commented
There is one issue that I didn't manage to solve: gardenlet fails to establish the VPN tunnel to the shoot. I'm not sure if it's a general limitation, or something related to the firewall setup on my machine. It's not critical, as you can still develop most g/g features locally without this. Would you like me to add some disclaimer? Maybe label this option as best-effort/experimental ?

2020-07-16 05:56 UTC, tim-ebert commented
> There is one issue that I didn't manage to solve: gardenlet fails to establish the VPN tunnel to the shoot. I'm not sure if it's a general limitation, or something related to the firewall setup on my machine. It's not critical, as you can still develop most g/g features locally without this. Would you like me to add some disclaimer? Maybe label this option as best-effort/experimental ?

What do you mean by that? The gardenlet doesn't establish a VPN tunnel to the shoots, only the kube-apiserver does (if the `KonnectivityTunnel` feature gate is disabled). Do you mean the step in the Shoot reconciliation where gardenlet tries to check, if the VPN/tunnel connection works?
I'm not sure, but I think this shouldn't be related to your firewall setup, as this is just a plain REST call to the `/proxy` subresource on the VPN pod with SPDY transport (I think).

2020-07-16 06:46 UTC, vpnachev submitted a review, later dismissed
/lgtm
/reviewed ok-to-test

2020-07-16 07:19 UTC, timebertt approved these changes
@guydaichs and I checked offline and the problem was not due to the WSL setup and rather misconfiguration in the Shoot's networking section.
So, not related this PR :)
/lgtm
/approve

2020-07-16 07:21 UTC, timebertt requested changes
Can you run `git commit --amend --reset-author` to kick out `Gardener CI/CD` as commiter?

2020-07-16 08:11 UTC, guydaichs commented
Thanks @tim-ebert. Indeed, the entire local dev env works after fixing my misconfiguration. I fixed the commit author as well.

2020-07-16 08:17 UTC, timebertt approved these changes
Thanks!
/lgtm

2020-07-16 08:23 UTC, vpnachev approved these changes
/lgtm

2020-07-16 08:45 UTC, merged