Wait until deployment/mcm is updated
gardener/gardener pull request #2579
Opened 2020-07-13 08:26 UTC by prashanth26

#**How to categorize this PR?**

/area quality
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Currently, the deployment of MCM pod and it's machine CRs (machine deployments and machine classes) occurs done in parallel. However, it is desirable in some situations (like migration/fixes) where the new MCM is deployed first before deploying the new/updated machine CRs. 

This especially will help the migration of machinesClasses from `ProviderMachineClasses` to `MachineClasses`, where only the MCM updated first and only after which the new CRs are deployed to avoid rolling updates of machines.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
I have added some unit tests and kept the methods generic enough to be reused in the future. 

**Release note**:

```improvement operator
Wait until MCM deployment is rolled out before proceeding with other reconciliation tasks.
```

2020-07-13 08:27 UTC, prashanth26 commented
/assign @hardikdr @danielfoehrKn

2020-07-13 08:28 UTC, prashanth26 commented
/size xs

2020-07-14 14:41 UTC, danielfoehrKn requested changes
Thanks, looks great! Only nits.

2020-07-14 14:41 UTC, danielfoehrKn commented on extensions/pkg/util/deployments_test.go
> +			var ()
```suggestion
```

2020-07-14 14:41 UTC, danielfoehrKn commented on extensions/pkg/util/deployments_test.go
> +				availableReplicas int32 = replicas - 1
```suggestion
				updatedReplicas   = replicas - 1
				availableReplicas = updatedReplicas
```

2020-07-14 14:45 UTC, prashanth26 commented
Thanks for the review @danielfoehrKn . I have accepted your commit suggestions into a commit.

2020-07-14 14:48 UTC, danielfoehrKn submitted a review, later dismissed

2020-07-15 05:23 UTC, prashanth26 commented
Hi @danielfoehrKn ,

There were some `gofmt` issues that I have fixed. Also have squashed all the commits into one.

2020-07-15 05:29 UTC, hardikdr submitted a review, later dismissed
/lgtm

2020-07-15 05:29 UTC, hardikdr commented on extensions/pkg/util/deployments.go
> +	return retry.UntilTimeout(ctx, intervel, timeout, func(ctx context.Context) (done bool, err error) {
```suggestion
	return retry.UntilTimeout(ctx, interval, timeout, func(ctx context.Context) (done bool, err error) {
```

Typo probably?

2020-07-15 08:59 UTC, danielfoehrKn commented
Waiting until hardik's suggestion is in and them it looks good from my side.

2020-07-16 10:24 UTC, prashanth26 commented
Hi @hardikdr @danielfoehrKn ,

I have made the requested changes.

2020-07-17 03:48 UTC, hardikdr approved these changes

2020-07-17 14:35 UTC, danielfoehrKn approved these changes

2020-07-17 14:35 UTC, merged