fix vpa chart values
gardener/gardener pull request #2716
Opened 2020-08-11 15:42 UTC by danielfoehrKn

**How to categorize this PR?**

/kind bug
/priority normal

**What this PR does / why we need it**:

`make verify`  on the current master throws a chart render error.

```
walk.go:74: found symbolic link in path: /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/loki/charts/utils-templates resolves to /Users/d060239/go/src/github.com/gardener/gardener/charts/utils-templates
walk.go:74: found symbolic link in path: /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/utils-templates resolves to /Users/d060239/go/src/github.com/gardener/gardener/charts/utils-templates
walk.go:74: found symbolic link in path: /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/vpa/charts/application/charts/utils-templates resolves to /Users/d060239/go/src/github.com/gardener/gardener/charts/utils-templates
walk.go:74: found symbolic link in path: /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/vpa/charts/application/values.yaml resolves to /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/vpa/values.yaml
walk.go:74: found symbolic link in path: /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/vpa/charts/runtime/charts/utils-templates resolves to /Users/d060239/go/src/github.com/gardener/gardener/charts/utils-templates
walk.go:74: found symbolic link in path: /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/vpa/charts/runtime/values.yaml resolves to /Users/d060239/go/src/github.com/gardener/gardener/charts/seed-bootstrap/charts/vpa/values.yaml
Error: YAML parse error on seed-bootstrap/charts/vpa/charts/runtime/templates/deployment-admission-controller.yaml: error converting YAML to JSON: yaml: line 9: could not find expected ':'

Use --debug flag to render out invalid YAML
```
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

@timuthy 
**Release note**:

```improvement operator

```

2020-08-11 15:52 UTC, ialidzhikov commented
`make verify` on the master branch is fine. Also locally:
```
$ make verify
> Check
Executing golangci-lint
Executing go vet
Executing gofmt/goimports
All checks successful
> Check Helm charts
Checking for chart symlink errors
Checking whether all charts can be rendered
All checks successful
> Format
> Test
```

It is also failing after `make install-requirements`?

2020-08-11 16:18 UTC, rfranzke commented
/status author-action

2020-08-11 17:11 UTC, danielfoehrKn commented
Thanks @ialidzhikov , I had helm > v3 installed so downgrading fixed the issue.
Nonetheless, `deploymentLabels` is referenced in the helm chart so should also be added in the values.yaml to be consistent?
When upgrading to helm v3 this will also throw a chart rendering error.

2020-08-11 17:29 UTC, ialidzhikov requested changes

2020-08-11 17:29 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/vpa/values.yaml
> +  gardener.cloud/role: seed
We don't need this. Please adapt the 

```
{{ toYaml .Values.deploymentLabels | indent 4 }}
```

usage with 

```
{{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
{{- end }}
```

to make helm3 happy.

2020-08-11 17:30 UTC, ialidzhikov commented
/remove king/bug

2020-08-11 19:35 UTC, ialidzhikov approved these changes
Thank you!

/lgtm

2020-08-12 05:15 UTC, timuthy approved these changes
Thank you!

2020-08-12 05:15 UTC, merged