Upgrade fluent-bit to version 0.26.0
gardener/gardener pull request #2846
Opened 2020-09-11 14:10 UTC by vlvasilev

**How to categorize this PR?**

/area logging
/kind enhancement
/priority normal

**What this PR does / why we need it**:
With this PR we upgrade fluent-bit to version 0.26.0.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Upgrade fluent-bit to version 0.26.0
```

2020-09-11 17:08 UTC, vpnachev requested changes
I have copied the release notes from #2845. but please fix the one that you have added. You are running on fluent-bit v1.5.4 - https://github.com/gardener/logging/blob/v0.26.0/fluent-bit-to-loki/Dockerfile#L9.

/invite @Kristian-ZH 
/assign @Kristian-ZH

2020-09-11 17:08 UTC, vpnachev commented on charts/images.yaml
> +  tag: "v0.26.0"
Well, you are not upgrading fluent-bit, but the custom plugin to this version. Please fix the release note.

2020-09-11 17:08 UTC, vpnachev commented on charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-configmap.yaml
> +
Remove one empty line.
```suggestion
```

2020-09-14 07:12 UTC, vpnachev approved these changes
/lgtm
/ping @Kristian-ZH

2020-09-14 07:14 UTC, Kristian-ZH approved these changes
/lgtm

2020-09-14 08:16 UTC, merged