Ignore gardener-specific labels while balancing node-groups in autoscaler
gardener/gardener pull request #2869
Opened 2020-09-21 10:22 UTC by hardikdr

**How to categorize this PR?**

/area autoscaler
/kind usability
/priority normal

**What this PR does / why we need it**: Autoscaler balances similar node-groups by comparing the labels on the nodes belonging to diff node-groups. We need to configure autoscaler to ignore gardener-specific labels for functionality to work properly, the PR does the same.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
```

2020-09-21 10:25 UTC, hardikdr commented
We need to /hold this PR until the latest version of Autoscaler is released. 
The changes are open for review already.

2020-09-21 10:27 UTC, rfranzke requested changes

2020-09-21 10:27 UTC, rfranzke commented on charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
> +        - --balancing-ignore-label=ignoreLabel
```suggestion
        - --balancing-ignore-label= {{ $ignoreLabel }}
```

2020-09-21 12:13 UTC, hardikdr commented on charts/seed-controlplane/charts/cluster-autoscaler/templates/deployment.yaml
> +        - --balancing-ignore-label=ignoreLabel
Thanks for the suggestion.

2020-09-21 15:21 UTC, rfranzke commented
Please rebase on `master` now that #2858 is merged

2020-09-22 08:24 UTC, rfranzke commented
/status author-action

2020-10-27 05:32 UTC, hardikdr commented
/close , I'll open one later, probably on autoscaler rather.

2020-10-27 05:32 UTC, closed without merging