Add steps for Shoot creation to docs/development/local_setup.md
gardener/gardener pull request #2870
Opened 2020-09-21 10:28 UTC by ialidzhikov

**How to categorize this PR?**

/area dev-productivity
/kind documentation
/priority normal

**What this PR does / why we need it**:
Add steps for Shoot creation to `docs/development/local_setup.md`.

**Release note**:

```improvement operator
NONE
```

2020-09-21 13:19 UTC, rfranzke commented on docs/usage/shoot_network_policies.md
> +In addition to deploying network policies [into the Seed](https://github.com/gardener/gardener/tree/master/docs/development/seed_network_policies.md),
```suggestion
In addition to deploying network policies [into the Seed](../development/seed_network_policies.md),
```

2020-09-21 13:19 UTC, rfranzke commented on docs/development/seed_network_policies.md
> +For network policies deployed into the Shoot `kube-system` namespace, please see the [usage section](https://github.com/gardener/gardener/tree/master/docs/usage/shoot_network_policies.md).
```suggestion
For network policies deployed into the Shoot `kube-system` namespace, please see the [usage section](../usage/shoot_network_policies.md).
```

2020-09-21 13:21 UTC, danielfoehrKn submitted a review, later dismissed

2020-09-22 05:57 UTC, rfranzke requested changes

2020-09-22 05:57 UTC, rfranzke commented on docs/development/local_setup.md
> +[Known Extension Implementations](../../README.md#infrastructure-provider) contains a list of available extension implementations. You need to create a ControllerRegistration for at least one infrast
```suggestion
The "[Known Extension Implementations](../../README.md#infrastructure-provider)" section contains a list of available extension implementations. You need to create a ControllerRegistration for at least one infrastructure provider, dns provider (if the DNS for the Seed is not disabled), at least one operating system extension and at least one network plugin extension.
```

dead link

2020-09-22 05:57 UTC, rfranzke commented on docs/development/local_setup.md
> +#### 5. Create a Seed
Should we call this "Register a Seed" to make more clear that Gardener does not create the seeds itself?

2020-09-22 05:57 UTC, rfranzke commented on docs/development/local_setup.md
> +- The communication between the Seed and the Shoot Clusters uses VPN tunnel. In this setup tunnels are not needed since all components run on localhost.
Can this section be removed now?

2020-09-23 04:52 UTC, rfranzke approved these changes
/lgtm

2020-09-23 04:52 UTC, merged