Care Controller: Remove evicted pods in Shoots control plane namespace on a Seed.
gardener/gardener pull request #294
Opened 2018-07-25 13:22 UTC by dkistner

**What this PR does / why we need it**:
The care controller removes evicted pods in the Shoot control plane of a Seed.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Checkout the PR and run the Gardener locally. Deploy a cluster and wait until it is created.
Then deploy a pod, which consumes plenty of memory e. g. via ``dd bs=8G if=/dev/zero of=/dev/null``, in the Shoot namespace on the Seed cluster.

**Release note**:

```improvement operator
The care controller of the Garden controller manager determine and delete evicted pods in the Shoot control plane namespace on the hosting Seed cluster within every control iteration.
```

2018-07-25 14:12 UTC, vlerenc commented
Thanks! I would rephrase the release note a bit (hide the implementation details and add the benefit):

> There was an issue where evicted control plane pods in the shoot cluster namespace confused the health check into assuming the shoot cluster control plane is broken. Gardener will now delete these evicted pods prior to its actual health check and thereby avoid false alarms.

2018-07-25 14:49 UTC, dkistner commented
Thanks @vlerenc. I took it in the text :)

2018-07-26 13:38 UTC, dkistner commented
@mvladev Could you please also have a look?

2018-07-30 08:26 UTC, mvladev requested changes
Just a small change needed

2018-07-30 08:26 UTC, mvladev commented on pkg/operation/botanist/garbage_collection.go
> +	err := b.deleteEvictedPods(b.K8sShootClient, metav1.NamespaceSystem)
This can be shortened to `return b.deleteEvictedPods(b.K8sShootClient, metav1.NamespaceSystem)`

2018-07-30 14:07 UTC, mvladev approved these changes

2018-07-30 14:07 UTC, merged