Do not deploy control plane exposure when hibernated
gardener/gardener pull request #2954
Opened 2020-10-08 09:52 UTC by mvladev

**How to categorize this PR?**

/area control-plane
/kind bug
/priority normal

**What this PR does / why we need it**:

Control plane exposure should only be created when the cluster is not hibernated or is not using SNI.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

2020-10-08 10:03 UTC, ialidzhikov commented
Well, I am not able to reproduce the issue to judge for myself whether this PR helps or not. Can you share steps to reproduce?

/invite @timuthy

2020-10-08 11:48 UTC, timuthy commented
The general problem with excluding steps during hibernation is that when you delete a hibernated cluster and you changed the deployment in the meantime, the resource (here cp exposure) is not up-to-date. That struck us in the past especially if the clusters were hibernated for a longer period of time, i.e. you never really know when migration code is supposed to be removed (/cc @ialidzhikov). Also see https://github.com/gardener/gardener/issues/1240.

2020-10-08 13:14 UTC, mvladev commented
> you changed the deployment in the meantime, the resource (here cp exposure) is not up-to-date.

This is another problem which should be fixed in the deletion flow - you must recreate/update all resources which are relevant to the cluster deletion. Kube apiserver / service / kubecontroller manager and so must all be up.

2020-10-08 15:24 UTC, timuthy commented
Can you still explain why this PR is of kind bug and what the bug is actually about, as @ialidzhikov already asked?

2020-10-09 06:04 UTC, mvladev commented
I'm not able to reproduce it, but I've seen the following error:

>  Normal   Hibernated      11h                   gardener-controller-manager  Hibernating cluster due to schedule
>  Normal   Reconciling     11h (x6 over 12h)     gardenlet                    Reconciling Shoot cluster state
>  Normal   Reconciled      11h (x5 over 12h)     gardenlet                    Reconciled Shoot cluster state
>  Warning  ReconcileError  11h                   gardenlet                    Flow "Shoot cluster reconciliation" encountered task errors: [task "Deploying internal domain DNS record" failed: Failed to create "internal" DNS record: "retry failed with context deadline exceeded, last error: dnsentries.dns.gardener.cloud \"internal\" not found" (status=Deleting, message=entry is scheduled to be deleted) task "Deploying external domain DNS record" failed: Failed to create "external" DNS record: "retry failed with context deadline exceeded, last error: dnsentries.dns.gardener.cloud \"external\" not found" (status=Deleting, message=entry is scheduled to be deleted) task "Waiting until Shoot control plane exposure has been reconciled" failed: Error while waiting for ControlPlane shoot--foo/foo-exposure to become ready: extension encountered error during reconciliation: Error reconciling controlplane: could not get kube-apiserver service load balancer address: Service "kube-apiserver" not found]

Which I don't know how it would happen in a normal reconcilation, but the `Waiting until Shoot control plane exposure has been reconciled` should not be executed if the cluster is hibernated or SNI is enabled.

2020-10-14 08:03 UTC, timuthy requested changes
After iterating over the changes again, I reluctantly want to merge those changes for the following reason:
- By design, we've never deleted extension resources when the cluster was hibernated. Instead, we apply it again and the extension controllers are supposed to deal with the hibernation state of the cluster. This PR changes the behavior profoundly (even if it sounds reasonable) and thus can have unforeseeable side effects because we don't control every extension.
- >Which I don't know how it would happen in a normal reconcilation, but the Waiting until Shoot control plane exposure has been reconciled should not be executed if the cluster is hibernated or SNI is enabled.

Extension resources are supposed to be deployed **on every reconciliation** as there might be migration logic in a Gardener release and as said, it's the extension's tasks to deal with the hibernation state. Otherwise you could argue to not reconcile at all while the cluster is hibernated.

2020-10-16 08:10 UTC, timuthy commented
Any further opinions @mvladev @gardener/gardener-maintainers?

2020-10-16 08:58 UTC, timebertt commented
Not really, I don't fully get the problem with keeping the way it is atm and tend to agree with @timuthy.

2020-10-19 11:25 UTC, rfranzke commented
I agree with the colleagues, the main argument is

> By design, we've never deleted extension resources when the cluster was hibernated. Instead, we apply it again and the extension controllers are supposed to deal with the hibernation state of the cluster. This PR changes the behavior profoundly (even if it sounds reasonable) and thus can have unforeseeable side effects because we don't control every extension.

As we aren't even sure if this PR helps with the above seen problem and we don't have any reproduction steps, I'd suggest to close the PR for now and revisit it when we have more details/information on it?

2020-10-21 06:43 UTC, rfranzke commented
OK, if nobody objects until EOB today, let's close the PR then.

2020-10-22 08:05 UTC, rfranzke commented
/close

2020-10-22 08:05 UTC, closed without merging