Delete VolumeAttachments on hibernation
gardener/gardener pull request #2963
Opened 2020-10-10 20:51 UTC by ialidzhikov

**How to categorize this PR?**

/area quality
/kind bug
/priority normal

**What this PR does / why we need it**:
Delete VolumeAttachments on hibernation.

**Which issue(s) this PR fixes**:
Fixes #2545
Fixes https://github.com/gardener/gardener-extension-provider-gcp/issues/172
Fixes #2958

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2020-10-11 10:46 UTC, vpnachev approved these changes, later dismissed
/lgtm

2020-10-13 15:03 UTC, timuthy requested changes
Are there any known issues/disadvantages using this approach? Can we be sure that the external-attacher removes the finalizer even though the machine is gone?

2020-10-13 15:03 UTC, timuthy commented on pkg/operation/botanist/volumeattachments.go
> +}
Can you rather pass the client instead of using the pointer receiver and write some unit tests?

2020-10-14 06:37 UTC, ialidzhikov commented
> Are there any known issues/disadvantages using this approach?

Well, I went through the CSI KEP, performed local testing, deployed this change on our dev env and haven't observed issues so far. I known that this does not look safe but we should do something to prevent volume leak on some infrastructures (see  #2958). 

> Can we be sure that the external-attacher removes the finalizer even though the machine is gone?

I hit no issues wrt to that so far. After the machine deletion on cloud provider side, volumes transition to available as they are detached on cloud provider side during the deletion (at least this is the case for aws and I would expect the same for other other providers in mcm). And external-attacher should not fail to detach a Volume which is already available.

2020-10-14 12:51 UTC, ialidzhikov commented
> Can we be sure that the external-attacher removes the finalizer even though the machine is gone?

I did a testing and I see that external-attacher is always calling `ControllerUnpublishVolume` of the csi-driver. The good thing is that the csi-driver handle this case.

Example logs of aws-ebs-csi-driver:

```
I1014 08:06:57.029891       1 controller.go:297] ControllerUnpublishVolume: called with args {VolumeId:vol-08ec22df22d730a9f NodeId:i-049b9e089d66121b2 Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
W1014 08:06:57.113975       1 cloud.go:404] DetachDisk called on non-attached volume: vol-08ec22df22d731234
```

Ref https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v0.7.0/pkg/cloud/cloud.go#L390-L427


I tested locally on aws, gcp, openstack, alicloud (for azure the CSI is postponed to k/k@v1.20) and the clean up of VolumeAttachments on hibernation worked well (-> the PV was able to be successfully deleted after wake up).

2020-10-15 05:43 UTC, timuthy approved these changes
/lgtm
Thank you also for the thorough research!

2020-10-15 06:42 UTC, merged