Shoot deletion from hinberation improvements
gardener/gardener pull request #2967
Opened 2020-10-13 09:59 UTC by mvladev

**How to categorize this PR?**

/area control-plane
/kind technical-debt
/priority normal

**What this PR does / why we need it**:

- Now all control plane-related steps from the standard reconciliation are executed
- Remove `WakeUpControlPlane` method

`WakeUpControlPlane` was attempting to do everything related to waking up a control plane of the cluster, but it was not doing things in parallel or any errors would cause the entire function to be executed from the start. There was quite a lot of duplication and missing steps which would result in a situations where the deletion would fail e.g. missing `DeployReferencedResources` step.

**Which issue(s) this PR fixes**:
Fixes # n/a

**Special notes for your reviewer**:

A similar `WakeUpKubeAPIServer` method exists which would be fixed in the same manner in another PR. 

**Release note**:

```improvement operator
NONE
```

2020-10-13 10:15 UTC, timuthy commented
/assign

2020-10-19 10:37 UTC, rfranzke commented
/assign

2020-10-19 13:45 UTC, timuthy requested changes
Some tests with your changes went well for me, just one comment.

2020-10-19 13:45 UTC, timuthy commented on pkg/gardenlet/controller/shoot/shoot_control_delete.go
> +			Fn:           flow.TaskFn(botanist.ScaleKubeAPIServerToOne).RetryUntilTimeout(defaultInterval, defaultTimeout).DoIf(cleanupShootResources),
This means that we downscale the KAS in case the shoot was not hibernated before which we shouldn't need to do, right? Also for the other up-scale calls, we should only invoke them if a hibernated cluster is deleted.

2020-10-21 06:36 UTC, rfranzke commented
/status author-action

2020-10-23 07:24 UTC, rfranzke commented
ping @mvladev

2020-10-23 12:39 UTC, rfranzke approved these changes, later dismissed
/lgtm
/needs second-opinion
/invite @timuthy

2020-10-23 12:39 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot_control_delete.go
> +				DoIf(cleanupShootResources && kubeAPIServerDeploymentReplicas == 0),
cc @dguendisch  - I guess this also fixes the problem that we sporadically see in the integration tests (KAPI scaled down to 0)

2020-10-23 13:13 UTC, timuthy approved these changes
/lgtm

2020-10-23 13:18 UTC, merged