added ability to restrict addons-nginx-ingress with loadBalancerSourc…
gardener/gardener pull request #298
Opened 2018-07-26 13:50 UTC by cihangirbesiktas

…eRanges regarding issue-269

**What this PR does / why we need it**:
This PR adds the ability to pass list of source ranges to the addon chart that deploy addons-nginx-ingress-controller so that it will be possible to restrict access to the exposed services in shoot clusters.

**Which issue(s) this PR fixes**:
Fixes # issue 269

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2018-07-26 13:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=298) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=298) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=298) it.</sub>

2018-07-26 14:15 UTC, cihangirbesiktas commented
I tested the changes on a shoot cluster created in Azure, and it successfully configured `loadBalancerSourceRanges` of the `addons-nginx-ingress-controller` service resource.

2018-07-26 14:32 UTC, luisdavim commented
this fixes #269

2018-07-26 16:50 UTC, bergerx commented on pkg/openapi/openapi_generated.go
> +			},
This doesn't seem relevant to the PR.

This question is more to the owners, any idea about why this was missing before?

2018-07-26 16:50 UTC, bergerx commented on pkg/apis/garden/types.go
> +	LoadBalancerSourceRanges []string
Can you fix the indent of the comment?

2018-07-27 10:46 UTC, bergerx approved these changes

2018-07-27 11:47 UTC, mvladev requested changes
Looks good. Just a small change for `// +optional` tag is required

2018-07-27 11:47 UTC, mvladev commented on pkg/apis/garden/v1beta1/types.go
> +	// LoadBalancerSourceRanges is list of whitelist IP sources for NginxIngress
optional fields must have a `// +optional` tag
Check https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required for more info

2018-07-27 11:47 UTC, mvladev commented on pkg/openapi/openapi_generated.go
> +			},
OpenAPI generation was broken in k8s 1.11. I've made a PR to fix it in #295

2018-07-27 11:47 UTC, mvladev commented on pkg/apis/garden/types.go
> +	LoadBalancerSourceRanges []string
You should run `go fmt ./...`

2018-07-30 14:00 UTC, mvladev approved these changes
/lgtm @dkistner can you have a look?

2018-07-31 08:16 UTC, rfranzke requested changes
I made a few suggestions, please take a look and address them. After doing that, please squash your commits to get the PR ready to be merged.

2018-07-31 08:16 UTC, rfranzke commented on pkg/operation/botanist/addons.go
>  func (b *Botanist) GenerateNginxIngressConfig() (map[string]interface{}, error) {
Any change here is not needed (actually, can you please remove the whole method (it is not called anywhere and a left over of previous versions)).

2018-07-31 08:16 UTC, rfranzke commented on pkg/operation/cloudbotanist/awsbotanist/addons.go
> +			"service": map[string]interface{}{
As transporting the `loadBalancerSourceRanges` to the Helm chart seems to be not cloud specific, please move this part to https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/addons.go#L147 and keep the cloud specific implementations untouched.

2018-07-31 08:16 UTC, rfranzke commented on pkg/operation/cloudbotanist/azurebotanist/addons.go
> +	return common.GenerateAddonConfig(map[string]interface{}{
As transporting the `loadBalancerSourceRanges` to the Helm chart seems to be not cloud specific, please move this part to https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/addons.go#L147 and keep the cloud specific implementations untouched.

2018-07-31 08:16 UTC, rfranzke commented on pkg/operation/cloudbotanist/gcpbotanist/addons.go
> +	return common.GenerateAddonConfig(map[string]interface{}{
As transporting the `loadBalancerSourceRanges` to the Helm chart seems to be not cloud specific, please move this part to https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/addons.go#L147 and keep the cloud specific implementations untouched.

2018-07-31 08:16 UTC, rfranzke commented on pkg/operation/cloudbotanist/localbotanist/addons.go
> -	return common.GenerateAddonConfig(nil, b.Shoot.Info.Spec.Addons.NginxIngress.Enabled), nil
As transporting the `loadBalancerSourceRanges` to the Helm chart seems to be not cloud specific, please move this part to https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/addons.go#L147 and keep the cloud specific implementations untouched.

2018-07-31 08:16 UTC, rfranzke commented on pkg/operation/cloudbotanist/openstackbotanist/addons.go
> -	return common.GenerateAddonConfig(nil, b.Shoot.NginxIngressEnabled()), nil
As transporting the `loadBalancerSourceRanges` to the Helm chart seems to be not cloud specific, please move this part to https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/addons.go#L147 and keep the cloud specific implementations untouched.

2018-07-31 17:22 UTC, rfranzke commented
Thanks. Looks ready **after** rebasing and squashing.

2018-08-01 16:23 UTC, rfranzke approved these changes
LGTM

2018-08-01 16:23 UTC, merged