Do not set Shoot status to Failed top early when operation cannot be initialized
gardener/gardener pull request #3106
Opened 2020-11-04 09:00 UTC by ialidzhikov

**How to categorize this PR?**

/area quality
/kind bug
/priority normal
**Which issue(s) this PR fixes**:
Fixes #3018

**Release note**:

```improvement operator
gardenlet no longer sets the Shoots status to Failed too early when operation cannot be initialized
```

2020-11-04 09:26 UTC, rfranzke approved these changes, later dismissed
/lgtm
/invite @timuthy 
/needs second-opinion

2020-11-04 13:35 UTC, timuthy commented
/assign

2020-11-04 13:57 UTC, timuthy requested changes
Hm, I don't see this https://github.com/gardener/gardener/issues/3018#issuecomment-721075772 / https://github.com/gardener/gardener/issues/3018#issuecomment-721094915 being handled in the PR, am I right? Let's suppose you create a new shoot with some arbitrary domain (`.spec.dns.domain: shoot.foo.bar`) but w/o a provider -> operation initialization will fail but Gardener will enqueue the shoot again because `HasNonRetryableErrorCode` is `false`.

2020-11-04 14:10 UTC, ialidzhikov commented
> Hm, I don't see this #3018 (comment) / #3018 (comment) being handled in the PR, am I right? Let's suppose you create a new shoot with some arbitrary domain (.spec.dns.domain: shoot.foo.bar) but w/o a provider -> operation initialization will fail but Gardener will enqueue the shoot again because HasNonRetryableErrorCode is false.

You are right, currently the initializeOperation errors caused by configuration problems are not handled with error code. I will have a look. Do you have in mind other cases (except wrongly configured `.spec.dns.domain`) that need such handling?

2020-11-04 14:36 UTC, timuthy commented
> You are right, currently the initializeOperation errors caused by configuration problems are not handled with error code. I will have a look. Do you have in mind other cases (except wrongly configured .spec.dns.domain) that need such handling?

Thanks @ialidzhikov. I think generally every case that leads to an error when initializing the operation. These are and will be most probably configuration problems from users.

2020-11-06 14:10 UTC, ialidzhikov commented
@timuthy , I checked now and it seems that we have in place the handling for incomplete dns config. Ref https://github.com/gardener/gardener/blob/v1.12.5/pkg/gardenlet/controller/shoot/shoot_control.go#L626-L638
Creation of such Shoot is flagged with ERR_CONFIGURATION_PROBLEM and set to Failed immediately:

```yaml
status:
  lastErrors:
  - codes:
    - ERR_CONFIGURATION_PROBLEM
    description: unable to figure out which secret should be used for dns
    taskID: initializeOperation
  lastOperation:
    description: 'Could not initialize a new operation for Shoot reconciliation: unable
      to figure out which secret should be used for dns'
    lastUpdateTime: "2020-11-06T13:36:03Z"
    progress: 0
    state: Failed
    type: Create
  observedGeneration: 1
```

> I think generally every case that leads to an error when initializing the operation.

This confused me a little bit. 😅   For example the error `cannot calculate required extensions for shoot my-shoot: the server has received too many requests and has asked us to try again later (get controllerregistrations.core.gardener.cloud)` can be also returned from the `initializeOperation` func and we rather want to retry on such error. My understanding is that we introduce errors like `IncompleteDNSConfigError` for known user configuration problems and add handling for them with error code. Otherwise on generic error we allow retry for `retryDuration`. That's why I also asked whether there are other cases that need such handling.

PS. Sorry, I wanted to add this comment to the PR, but wrongly added it to the issue previously.

2020-11-06 14:37 UTC, timuthy commented
I see, good point @ialidzhikov. Then we have to differentiate between retry-able errors and configuration errors here as well :(

2020-11-06 17:10 UTC, ialidzhikov commented
I think this is already in place. Do you see any error currently in `initializeOperation` func that needs to be a configuration error -> we won't retry such Shoot? It seems good to me.

2020-11-09 07:29 UTC, timuthy commented
IIUC, `updateShootStatusOperationStart` deletes the `initializeOperation` from the `lastErrors` [here](https://github.com/gardener/gardener/blob/c320f104698977e82ab22a63c968a66a99326ecd/pkg/gardenlet/controller/shoot/shoot_control.go#L539), so that the [error handling](https://github.com/gardener/gardener/blob/c320f104698977e82ab22a63c968a66a99326ecd/pkg/gardenlet/controller/shoot/shoot_control_migrate.go#L76) for `c.initializeOperation` won't have a non-retryable error. Can you double check?

2020-11-17 16:59 UTC, timebertt commented
/author-action

2020-11-17 21:32 UTC, ialidzhikov commented
> IIUC, `updateShootStatusOperationStart` deletes the `initializeOperation` from the `lastErrors` [here](https://github.com/gardener/gardener/blob/c320f104698977e82ab22a63c968a66a99326ecd/pkg/gardenlet/controller/shoot/shoot_control.go#L539), so that the [error handling](https://github.com/gardener/gardener/blob/c320f104698977e82ab22a63c968a66a99326ecd/pkg/gardenlet/controller/shoot/shoot_control_migrate.go#L76) for `c.initializeOperation` won't have a non-retryable error. Can you double check?

In https://github.com/gardener/gardener/blob/559cd2126eac4e2e685550f21a2d3fd8f035e776/pkg/gardenlet/controller/shoot/shoot_control.go#L329 

hence in 

https://github.com/gardener/gardener/blob/559cd2126eac4e2e685550f21a2d3fd8f035e776/pkg/gardenlet/controller/shoot/shoot_control.go#L643-L655

we have the implicit check for non-retryable error and if we have such error we upsert it the the lastErrors.

2020-11-18 06:39 UTC, timuthy commented
Thanks for the investigation @ialidzhikov. I agree, `lastErrorsOperationInitializationFailure` is the savior 👍

2020-11-18 06:39 UTC, timuthy approved these changes
/lgtm

2020-11-18 06:40 UTC, merged