Refactor etcd deployment
gardener/gardener pull request #3129
Opened 2020-11-09 08:04 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity quality robustness
/kind technical-debt test
/priority normal
/topology seed
/platform all
/exp intermediate

**What this PR does / why we need it**:
This PR refactors the deployment for the etcd and adopts the component concept. Consequently, it eliminates the Helm chart and adds full unit tests, instead. This improves several aspects and the overall code quality.

**Which issue(s) this PR fixes**:
Part of #2754 

/cc @shreyas-s-rao @amshuman-kr 
ℹ️ Similar refactoring for etcd-druid: #3099

**Release note**:

```improvement operator
NONE
```

2020-11-10 14:22 UTC, danielfoehrKn requested changes
Compared to the master branch, the etcd mains CRD changed in the following way:
- the field backup.store.prefix value is missing the "/etcd-main" suffix
- the field etcd.quota of 8Gi is missing

This causes the etcd pods to restart. 
Also the prefix determines to my knowledge the bath in the object store - I am not sure if it is safe to change it.

2020-11-10 14:22 UTC, danielfoehrKn commented on pkg/operation/botanist/etcd.go
> +	return b.Shoot.Components.ControlPlane.EtcdEvents.Deploy(ctx)
Can both the deployment of etcd-main and etcd-events be parallized?

2020-11-10 14:22 UTC, danielfoehrKn commented on pkg/operation/botanist/controlplane/etcd/etcd.go
> +	// TODO: Separate function?!
```suggestion
```

2020-11-10 14:22 UTC, danielfoehrKn commented on pkg/operation/botanist/controlplane/etcd/etcd.go
> +func (e *etcd) getExisting(ctx context.Context, name string, obj runtime.Object) (runtime.Object, bool, error) {
```suggestion
func (e *etcd) getExistingResource(ctx context.Context, name string, obj runtime.Object) (runtime.Object, bool, error) {
```

2020-11-10 14:22 UTC, danielfoehrKn commented on pkg/operation/botanist/controlplane/etcd/waiter.go
> +		logger.Info("Waiting until the both etcds are ready...")
```suggestion
		logger.Info("Waiting until both the etcds are ready...")
```

2020-11-10 14:43 UTC, rfranzke commented
Thanks @danielfoehrKn for the review! I've addressed the comments and pushed a dedicated commit so that it's easier for you to check.

> the field backup.store.prefix value is missing the "/etcd-main" suffix

That's a nice catch, thank you a lot!

> the field etcd.quota of 8Gi is missing

Yes, actually it was wrong how it was before: https://github.com/gardener/gardener/blob/master/charts/seed-controlplane/charts/etcd/templates/etcd.yaml#L60, the `.spec.backup.quota` field does not exist, see https://github.com/gardener/etcd-druid/blob/master/api/v1alpha1/etcd_types.go#L69-L100. However, the `.spec.etcd.quota` field exists (see https://github.com/gardener/etcd-druid/blob/master/api/v1alpha1/etcd_types.go#L103-L106) and I guessed that it was intended to set this one, so I fixed it in this PR. /cc @shreyas-s-rao @amshuman-kr

2020-11-11 10:04 UTC, wyb1 reviewed
Prometheus cannot scrape etcd. The config looks fine and is scraping the right target and ports. Not sure what the issue is

![image](https://user-images.githubusercontent.com/8710621/98786822-f12f3400-23fe-11eb-8c92-831e5c285124.png)

2020-11-11 10:15 UTC, wyb1 commented
I deleted all my network policies and let it reconcile and now it works. I must have had a network policy preventing the traffic. Perhaps we should add a network policy that will specifically allow traffic from prometheus to etcd? I see that etcd doesn't have the label `networking.gardener.cloud/from-prometheus: allowed`

2020-11-11 10:24 UTC, rfranzke commented
Thanks @wyb1, I've found the problem in the `NetworkPolicy` and fixed it (see dedicated commit for it).
In this PR I don't want to introduce changes, I just want to refactor the way how etcd is being deployed. I agree that all these network policies are not optimal yet and that we should refactor them as well at a later point in time.

2020-11-11 10:39 UTC, danielfoehrKn approved these changes, later dismissed

2020-11-11 14:35 UTC, wyb1 requested changes
The etcd memory dashboard contains no data. It still contains the old job name

![image](https://user-images.githubusercontent.com/8710621/98824235-5ac93580-2433-11eb-8a76-535670d56f90.png)

2020-11-12 06:46 UTC, rfranzke commented
@wyb1 Well, in our chat you mentioned that the dashboards don't need to be adapted, so I didn't even look after them 😉 Anyways, I've made the changes now, please check.

2020-11-12 12:40 UTC, wyb1 approved these changes, later dismissed
I didn't think that any of the dashboards would be affected but I was wrong 😄 
Thanks for fixing!
/lgtm

2020-11-16 12:20 UTC, ialidzhikov commented on pkg/operation/botanist/etcd_test.go
> +		Context("no shooted seed", func() {
There is already a context with the same name in L100.

```suggestion
		Context("for shooted seed", func() {
```

2020-11-16 12:20 UTC, ialidzhikov commented on pkg/operation/botanist/controlplane/etcd/monitoring_alertingrules_important_with_backup.test.yaml
> +rule_files:
You could move the `*.test.yaml` files into `testdata`? Ref https://github.com/golang/go/issues/14715
```diff
- pkg/operation/botanist/controlplane/etcd/monitoring_alertingrules_important_with_backup.test.yaml
+ pkg/operation/botanist/controlplane/etcd/testdata/monitoring_alertingrules_important_with_backup.test.yaml
```

2020-11-17 12:44 UTC, ialidzhikov reviewed
Looks good to me in general. I tried some operations like creation/deletion/hibernation and it worked well. Minor nits inline.

/needs second-opinion

2020-11-17 12:44 UTC, ialidzhikov commented on pkg/operation/botanist/component/types.go
> +	// ScrapeConfigs are the scrape configurations for centtral Prometheus.
```suggestion
	// ScrapeConfigs are the scrape configurations for central Prometheus.
```

2020-11-17 12:44 UTC, ialidzhikov commented on pkg/operation/botanist/controlplane/etcd/etcd.go
> +			UpdateModeMaintenanceWindow = hvpav1alpha1.UpdateModeMaintenanceWindow
```suggestion
			updateModeMaintenanceWindow = hvpav1alpha1.UpdateModeMaintenanceWindow
```

2020-11-17 12:44 UTC, ialidzhikov commented on pkg/operation/botanist/controlplane/etcd/monitoring.go
> +// AlertConfig returns the alerting configuration for AlertManager.
```suggestion
// AlertingRules returns the alerting configuration for AlertManager.
```

2020-11-17 12:44 UTC, ialidzhikov commented on pkg/operation/botanist/controlplane/etcd/waiter.go
> +	logger *logrus.Entry,
```suggestion
	logger logrus.FieldLogger,
```

2020-11-17 15:58 UTC, rfranzke commented
Thanks @ialidzhikov, done!

2020-11-18 08:17 UTC, ialidzhikov approved these changes
I have no other comments,

/lgtm

2020-11-18 11:37 UTC, merged