Add documentation for support of CP migration by extensions
gardener/gardener pull request #3157
Opened 2020-11-12 16:26 UTC by stoyanr

**How to categorize this PR?**

/area control-plane-migration
/area documentation
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Adds documentation for support of control plane migration by extensions.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

2020-11-12 16:28 UTC, stoyanr commented
/cc @plkokanov @kris94 @rfranzke

2020-11-12 18:20 UTC, plkokanov requested changes
Thanks, looks pretty good and informative, I have just a couple remarks.

2020-11-12 18:20 UTC, plkokanov commented on docs/extensions/migration.md
> +As with the [reconcile operation](https://github.com/gardener/gardener/blob/master/docs/extensions/reconcile-trigger.md), extension controllers must remove the `gardener.cloud/operation` annotation a
Just a note here: It should be `unlike` the reconcile annotation as it is removed at the start of the operation, whereas the migrate and restore annotations are removed after a successful operation.

2020-11-12 18:20 UTC, plkokanov commented on docs/extensions/migration.md
> +
Should we also add the `status.Resources` field which can be referred to by entries in the `status.State` field, for more clarity (sadly the infrastructure resource won't be appropriate for it)

2020-11-13 09:08 UTC, stoyanr commented on docs/extensions/migration.md
> +
Done

2020-11-13 09:08 UTC, stoyanr commented on docs/extensions/migration.md
> +As with the [reconcile operation](https://github.com/gardener/gardener/blob/master/docs/extensions/reconcile-trigger.md), extension controllers must remove the `gardener.cloud/operation` annotation a
Done

2020-11-13 09:17 UTC, plkokanov approved these changes
/lgtm

2020-11-13 15:18 UTC, rfranzke approved these changes
/lgtm

2020-11-13 15:19 UTC, merged