Add Pod scheduler name webhook in seed-admission-controller
gardener/gardener pull request #3199
Opened 2020-11-20 16:02 UTC by mvladev

**How to categorize this PR?**

/area control-plane
/area scalability
/area cost
/kind enhancement
/priority normal

**What this PR does / why we need it**:

First part of https://github.com/gardener/gardener/issues/2873

The idea is to have a `MutatingWebhookConfiguration` which would apply to Pods part of the control plane of Shoot clusters. The webhook sets the  Pod's `spec.schedulerName` to `gardener-shoot-controlplane-scheduler`.  This `MutatingWebhookConfiguration` and `kube-scheduler` with custom configuration would be added in a separate PR.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

This is a separate commit, because the `gardener-seed-admission-controller` is deployed in as part of the cluster bootstrap and the code which adds the  custom scheduler cannot be merged before this PR.

**Release note**:

```improvement operator
NONE
```

2020-11-20 16:24 UTC, rfranzke commented
/hold until v1.13 is released

2020-11-23 12:24 UTC, rfranzke commented
/unhold as v1.13 is released

2020-11-23 13:24 UTC, rfranzke reviewed
Nice PR, also the webhook test, great, thank you @mvladev.

2020-11-23 13:24 UTC, rfranzke commented on cmd/gardener-seed-admission-controller/app/gardener_seed_admission_controller.go
> +		jsonpatch.NewPatch("replace", "/spec/schedulerName", "gardener-shoot-controlplane-scheduler"),
Can you make this name a constant (it will be needed later anyways as well)?

2020-11-24 06:02 UTC, rfranzke submitted a review, later dismissed
/lgtm

2020-11-24 07:50 UTC, timebertt commented
/assign

2020-11-24 08:19 UTC, timebertt requested changes
Only nits from my side.

2020-11-24 08:19 UTC, timebertt commented on cmd/gardener-seed-admission-controller/app/app_suite_test.go
> +		err := dummyK8SServer.ListenAndServe()
```suggestion
		defer GinkgoRecover()
		err := dummyK8SServer.ListenAndServe()
```

2020-11-24 08:19 UTC, timebertt commented on cmd/gardener-seed-admission-controller/app/app_suite_test.go
> +		o.run(stopCtx)
```suggestion
		defer GinkgoRecover()
		o.run(stopCtx)
```

2020-11-24 08:19 UTC, timebertt commented on cmd/gardener-seed-admission-controller/app/app_suite_test.go
> +	It("it adds extra environment variable", func() {
```suggestion
	It("it adds .Spec.SchedulerName", func() {
```

2020-11-24 08:19 UTC, timebertt commented on cmd/gardener-seed-admission-controller/app/app_suite_test.go
> +	It("it adds extra environment variable", func() {
Can you add a test case for ensuring, that the webhook doesn't mutate on `UPDATE`?

2020-11-24 12:15 UTC, mvladev commented
I've updated the PR and made the following change - the webhook address is now `/webhooks/default-pod-scheduler-name/{scheduler-name}` with `gardener-shoot-controlplane-scheduler` being the only `{scheduler-name}` possible at the moment. This would allow later in the future to have multiple schedulers for different control plane components and only one handler which would use `{scheduler-name}` as a parameter for `spec.schedulerName`.

2020-11-24 16:03 UTC, timebertt approved these changes
/lgtm

2020-11-24 17:54 UTC, merged