Add alerts for the custom metrics
gardener/gardener pull request #3283
Opened 2020-12-09 12:32 UTC by Kristian-ZH

**How to categorize this PR?**

/area logging
/kind enhancement
/priority normal

**What this PR does / why we need it**:
Graphs in the fluent-bit dashboard show `podName`.
Add alerts for the custom metrics.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@wyb1 
@istvanballok 
@vlvasilev 

**Release note**:

```other operator
Alerts are added for the custom metrics for fluent-bit `GardenerLoki` plugin
```

2020-12-09 14:22 UTC, vlvasilev submitted a review, later dismissed
/lgtm

2020-12-09 16:08 UTC, wyb1 commented on charts/seed-bootstrap/aggregate-prometheus-rules/fluent-bit.rules.yaml
> +    expr: sum(increase(fluentbit_loki_gardener_logs_without_metadata_total[4m])) by (pod) > 0
To improve readability you can split up the expression. This isn't done for the other existing metrics, but we can start here :)
```suggestion
    expr: |
      sum by (pod) (
        increase(
          fluentbit_loki_gardener_logs_without_metadata_total[4m]
         )
       ) > 0
```

2020-12-09 16:10 UTC, wyb1 reviewed
Overall looks good. Just one minor comment regarding the formatting. I'll have another look tomorrow

2020-12-11 09:04 UTC, wyb1 requested changes
Looks good except for the typo :)

2020-12-11 09:04 UTC, wyb1 commented on charts/seed-bootstrap/dashboards/fluent-bit-dashboard.json
> +          "legendFormat": "Dropt Logs-{{pod}}",
Typo?

2020-12-11 11:13 UTC, Kristian-ZH commented on charts/seed-bootstrap/dashboards/fluent-bit-dashboard.json
> +          "legendFormat": "Dropt Logs-{{pod}}",
yes, fixed :)

2020-12-11 11:22 UTC, wyb1 submitted a review, later dismissed

2020-12-11 13:52 UTC, istvanballok submitted a review, later dismissed
minor suggestion: https://github.com/Kristian-ZH/gardener/pull/1/files

2020-12-11 14:21 UTC, rfranzke submitted a review, later dismissed

2020-12-11 14:47 UTC, rfranzke approved these changes

2020-12-11 15:14 UTC, istvanballok approved these changes
/lgtm

2020-12-14 11:07 UTC, merged