Cache client capabilities upon first request in chart renderer
gardener/gardener pull request #335
Opened 2018-08-22 16:58 UTC by afritzler

**What this PR does / why we need it**:
Cache client capabilities upon first request in chart renderer

**Release note**:

```improvement operator

```

2018-08-23 05:58 UTC, rfranzke requested changes

2018-08-23 05:58 UTC, rfranzke commented on pkg/chartrenderer/default.go
> +		logger.Logger.Errorf("failed to get kubernetes server version %v", err)
We should return an error here instead of logging and continuing.

2018-08-23 06:20 UTC, afritzler commented on pkg/chartrenderer/default.go
> +		logger.Logger.Errorf("failed to get kubernetes server version %v", err)
I will propagate the error. However this will affect a lot of files.

2018-08-23 08:03 UTC, afritzler commented
Alright, I updated the PR. The error should now be propagated.

2018-08-23 14:23 UTC, rfranzke requested changes

2018-08-23 14:23 UTC, rfranzke commented on pkg/operation/botanist/dns.go
> +	op, err := terraformer.NewFromOperation(b.Operation, terraformerPurpose)
Please replace ALL occurrences of `op` with `tf` (`terraformer.New()` and `terraformer.NewFromOperation` return a `*Terraformer` object, and not an `*Operation` object).

2018-08-23 14:40 UTC, afritzler commented on pkg/operation/botanist/dns.go
> +	op, err := terraformer.NewFromOperation(b.Operation, terraformerPurpose)
Good point.

2018-08-23 14:54 UTC, afritzler commented on pkg/operation/botanist/dns.go
> +	op, err := terraformer.NewFromOperation(b.Operation, terraformerPurpose)
Done!

2018-08-24 05:57 UTC, rfranzke approved these changes
LGTM

2018-08-24 05:57 UTC, merged