Set revisionHistoryLimit to 1 for deployments
gardener/gardener pull request #3374
Opened 2021-01-11 14:00 UTC by rfranzke

**How to categorize this PR?**

/area ops-productivity
/kind enhancement
/priority normal

**What this PR does / why we need it**:
This PR increases the `.spec.revisionHistoryLimit` for `Deployment`s to `1`.

**Which issue(s) this PR fixes**:
Fixes #3325

**Special notes for your reviewer**:
This will lead to some DB size increase in etcd, though, probably not too much.

**Release note**:

```feature operator
The `.spec.revisionHistoryLimit` is now set to `1` for `Deployment`s.
```

2021-01-11 14:20 UTC, timebertt reviewed
I'm wondering: did you consider adding a mutating webhook to the seed-admission-controller for setting the `revisionHistoryLimit`?
Setting this by hand will lead to inconsistent settings, I guess. And the webhook approach would have the benefit, that it also applies to deployments not managed by gardener, e.g. `cloud-controller-manager`.

2021-01-11 14:24 UTC, rfranzke commented
I thought about it, but quickly discarded it again because there are a gazillion of other examples were extensions can theoretically deviate, maybe for good reasons. For example, we would like to have a `VPA` for all the components or checksum annotations for mounted volumes, etc. etc.
For now, to save some time and effort, I simply changed the values similar to how we early set them all to `0`.

2021-01-11 14:51 UTC, vpnachev requested changes
Please, change it also
-  here https://github.com/gardener/gardener/blob/085d163e1cbd73397aa6b31197714729f8bf7c53/pkg/gardenlet/controller/shoot/seed_registration_control.go#L739
- here https://github.com/gardener/gardener/blob/085d163e1cbd73397aa6b31197714729f8bf7c53/pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler.go#L172
- here https://github.com/gardener/gardener/blob/085d163e1cbd73397aa6b31197714729f8bf7c53/pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go#L175
- and here https://github.com/gardener/gardener/blob/085d163e1cbd73397aa6b31197714729f8bf7c53/pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler.go#L171

2021-01-12 07:13 UTC, timebertt approved these changes
/lgtm

2021-01-12 15:48 UTC, rfranzke commented
ping @vpnachev

2021-01-12 16:15 UTC, vpnachev approved these changes
/lgtm

2021-01-12 16:33 UTC, merged