Enhance webhook constraints checks
gardener/gardener pull request #3413
Opened 2021-01-15 09:33 UTC by timebertt

**How to categorize this PR?**

/area quality ops-productivity
/kind enhancement
/priority normal

**What this PR does / why we need it**:

This PR enhances the webhook constraints checks in the following ways:
- webhooks with `FailurePolicy=Ignore` but `TimeoutSeconds>15` are now also marked as problematic (long timeouts are discouraged by the [k8s documentation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts) and can cause problems on wakeup as well
- webhooks that act on `configmaps` in the `kube-system` namespace are now also marked as problematic (older versions of k8s control plane components used leader election via `configmaps`)
- the webhook matchers assumed a label `role=kube-system` on the `kube-system` namespace for shoots, although there is no such label, [ref](https://github.com/gardener/gardener/blob/3a403423130b8a52028b94ef756d97afa4963089/pkg/operation/botanist/systemcomponents/namespaces/namespaces.go#L82), that assumption is corrected

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other user
Webhooks acting on `configmaps` in the `kube-system` namespace and webhooks with a `TimeoutSeconds>15` for problematic resources are now also blocking `Maintenance` and `Hibernation` operations.
```

2021-01-15 12:52 UTC, timuthy requested changes
Some minor suggestion, looks good otherwise.

2021-01-15 12:52 UTC, timuthy commented on pkg/operation/botanist/constraints_check.go
> +	return fmt.Sprintf("%s %q is problematic: webhook %q with failurePolicy %q %smight prevent worker nodes from properly joining the shoot cluster",
```suggestion
	return fmt.Sprintf("%s %q is problematic: webhook %q with failurePolicy %q %s might prevent worker nodes from properly joining the shoot cluster",
```

Nit, as it's easier to read.

2021-01-15 12:52 UTC, timuthy commented on pkg/operation/botanist/constraints_check.go
> +	timeoutSeconds *int32,
How about passing the entire webhook instance?

2021-01-15 12:52 UTC, timuthy commented on pkg/operation/botanist/constraints_check.go
> +		if timeoutSeconds != nil && *timeoutSeconds <= 15 {
Can you create a `const` with expressive naming?

2021-01-15 12:52 UTC, timuthy commented on pkg/operation/botanist/constraints_check.go
> +			// https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts
Nice explanation. What do you think about rather adding it to `docs/usage/shoot_status.md` to explain in more detail to the user why this timeout is bad?

2021-01-15 12:52 UTC, timuthy commented on pkg/operation/botanist/constraints_check.go
> +	timeoutString := "and unset timeoutSeconds "
```suggestion
	timeoutString := "and unset timeoutSeconds"
```

2021-01-15 12:52 UTC, timuthy commented on pkg/operation/botanist/constraints_check.go
> +		timeoutString = fmt.Sprintf("and %ds timeout ", *timeoutSeconds)
```suggestion
		timeoutString = fmt.Sprintf("and %ds timeout", *timeoutSeconds)
```

2021-01-15 15:00 UTC, timebertt commented on pkg/operation/botanist/constraints_check.go
> +	timeoutSeconds *int32,
Unfortunately, that's not possible, as there are different types for `ValidatingWebhook` and `MutatingWebhook`.
There's `webhook.{NewValidatingWebhookAccessor,NewMutatingWebhookAccessor} ` for this purpose, though I dropped it as part of https://github.com/gardener/gardener/pull/2370/files#diff-a62189d77ddf4b67cfac7ebccc31708acf390d2826fbb07cd2c28d9c43898b94L69, because they only accept the `v1` types, which we can't use as of now.

2021-01-15 15:00 UTC, timebertt commented on pkg/operation/botanist/constraints_check.go
> +	return fmt.Sprintf("%s %q is problematic: webhook %q with failurePolicy %q %smight prevent worker nodes from properly joining the shoot cluster",
Ah sure, it was a leftover.

2021-01-15 15:46 UTC, timebertt commented
Thanks @timuthy for your suggestions, I addressed them.
I took the chance to overhall the documentation about the hibernation constraint to better explain to users why we have it and how they should properly configure their webhooks.

2021-01-15 16:01 UTC, timuthy approved these changes, later dismissed
Thanks for revising the documentation as well.
/lgtm

2021-01-19 10:04 UTC, rfranzke commented
/rebase

2021-01-20 08:12 UTC, timebertt commented
Done, PTAL.

2021-01-20 08:18 UTC, rfranzke approved these changes
/lgtm

2021-01-20 09:37 UTC, timuthy approved these changes

2021-01-20 09:37 UTC, merged

2021-01-20 21:55 UTC, ialidzhikov commented
Hi, team. I wanted to share that this PR is kind of breaking my local setup with 

```
error: shoots.core.gardener.cloud "aws-local" could not be patched: shoots.core.gardener.cloud "aws-local" is forbidden: MutatingWebhookConfiguration "gardener-extension-provider-aws-shoot" is problematic: webhook "shoot.aws.extensions.gardener.cloud" with failurePolicy "Ignore" and 30s timeout might prevent worker nodes from properly joining the shoot cluster
```

Shouldn't we first fix our webhooks' timeouts before enabling such constraints?

2021-01-21 06:55 UTC, timebertt commented
Uhh, good catch. Thanks for reporting.
Should we then revert the change and fix our shoot webhooks first?
Or should we add some rules to ingore extension shoot webhooks (and lower the timeout nevertheless)?