Refactor OperatingSystemConfig deployment into component
gardener/gardener pull request #3454
Opened 2021-01-25 15:47 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity quality robustness
/kind technical-debt test
/priority normal
/topology seed
/platform all
/exp expert
/merge squash

**What this PR does / why we need it**:
This PR refactors the deployment for the `OperatingSystemConfig` extension resource and adopts the component concept, similar to #3222 and others. This improves several aspects and the overall code quality.

Unlike to other refactoring PRs for extension resources, the `OperatingSystemConfig` was applied as part of the `seed-operatingsystemconfig` chart. Hence, I had to refactor this in its entirety and decided to eliminate the whole chart, eventually. As a result, the PR is quite large, however, we now have unit tests for the vast majority of this part of the the code.

**Which issue(s) this PR fixes**:
Part of #2754

**Special notes for your reviewer**:
- ❗ Due to the large size of the PR I've split it into a bunch of separate, self-contained commits to make the review process very easy. Consider reviewing the various commits individually.
- The `OperatingSystemConfig` resource was the last extension resource that was required to refactor into a component. This allows us to get rid of some control plane migration code and to simply the respective function invocations.
- I'm introducing the `github.com/go-bindata/go-bindata` as new dev tool. With Golang 1.16 we can probably get rid of it in favor of `//go:embed`.
- I have moved some functions to hopefully better places (e.g., from the extensions library to the new `operatingsystemconfig` package) to improve the package dependency graph.
- I have slightly refactored a few of the scripts that we apply in the `original` `OperatingSystemConfig` because we are now injecting Golang constants into them, hence, we don't need Bash variables for certain paths anymore.
- The `operatingsystemconfig/original/components/logrotate` component does not implement the new `operatingsystemconfig/original/components.Component` interface because it is just a "helper component" for both `docker` and `containerd`.
- I am aware of a few inconsistencies in the handling/implementation of the various components for extension resources and I plan to address them in future PRs.

**Release note**:

```breaking dependency
The `FileContentInlineCodec` and `UnitSerializer ` interfaces have been moved from `extensions/pkg/webhook/controlplane` to `pkg/operation/botanist/extensions/operatingsystemconfig/utils`.
```
```breaking dependency
The `KubeletConfigCodec ` interface has been moved from `extensions/pkg/webhook/controlplane` to `pkg/operation/botanist/extensions/operatingsystemconfig/original/components/kubelet`.
```
```breaking developer
The `CopyValues ` function has been moved from `pkg/utils/chart` to `pkg/utils` and was renamed to `ShallowCopyMapStringInterface`.
```
```breaking developer
The `ImageMapToValues ` function has been moved from `pkg/utils/chart` to `pkg/utils/imagevector`.
```
```feature developer
The `pkg/utils/kubernetes` does now have a new `DeleteObjectsFromListConditionally` utility function.
```

2021-01-27 06:58 UTC, rfranzke commented
After the merge of #3449 I've now rebased this PR and it's ready for review.
/cc @vpnachev

2021-01-27 10:18 UTC, vpnachev commented
/assign

2021-01-28 12:11 UTC, vpnachev approved these changes, later dismissed
/lgtm

I have one change request, but if you want, it can be contributed with some other PR.

Personally, I would prefer to keep the commits - this was very helpful for me to go through the changes. If we need to re-check later what was changed, it will be again nice to have everything split in the dedicated commits.

2021-01-28 12:11 UTC, vpnachev commented on pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
>  			Name:         "Computing operating system specific configuration for shoot workers",
```suggestion
			Name:         "Deployibg operating system specific configuration for shoot workers",
```

2021-01-28 13:12 UTC, rfranzke commented
Thanks for your review @vpnachev!

> I have one change request, but if you want, it can be contributed with some other PR.

Sure, let's wait if there are other comments and if yes then I'll combine it when addressing them.

> Personally, I would prefer to keep the commits - this was very helpful for me to go through the changes. If we need to re-check later what was changed, it will be again nice to have everything split in the dedicated commits.

Sure, OK for me, no strong opinion. If you prefer to keep them then let's do it. @gardener/gardener-maintainers anybody else planning a review and having a preference here as well?

2021-01-29 10:45 UTC, ialidzhikov commented
/assign @ialidzhikov

2021-01-29 15:09 UTC, ialidzhikov requested changes
Looks good to me in general. Minor nits inline.

2021-01-29 15:09 UTC, ialidzhikov commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/docker/component.go
> +	err                  error
You could move this to the init func below. No need to make it a pkg var.

```suggestion
```

2021-01-29 15:09 UTC, ialidzhikov commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/containerd/component.go
> +	err                  error
You could move below to the init func.

```suggestion
```

2021-01-29 15:09 UTC, ialidzhikov commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/kubelet.go
> +// KubeletCLIFlagsFromCoreV1beta1KubeletConfig computes the ConfigurableKubeletConfigParameters based on the provided
```suggestion
// KubeletConfigParametersFromCoreV1beta1KubeletConfig computes the ConfigurableKubeletConfigParameters based on the provided
```

2021-01-29 15:09 UTC, ialidzhikov commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/kubelet/component.go
> +	err                  error
```suggestion
```

2021-01-29 15:09 UTC, ialidzhikov commented on pkg/operation/botanist/extensions/operatingsystemconfig/downloader/downloader.go
> +	err     error
```suggestion
```

2021-01-29 15:09 UTC, ialidzhikov commented on pkg/operation/botanist/extensions/operatingsystemconfig/executor/executor.go
> +	err     error
```suggestion
```

2021-01-29 15:09 UTC, ialidzhikov commented on pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
> +	CRINameContainerD CRIName = "containerd"
`test/integration/shoots/operations/containerruntime.go` needs to be adapted as it is using `CRINameContainerD` to assert the node the Node label `worker.gardener.cloud/cri-name` value.

```
• Failure [277.286 seconds]
Shoot container runtime testing
/Users/i331370/go/src/github.com/gardener/gardener/test/integration/shoots/operations/containerruntime.go:30
  [DEFAULT] [SERIAL] [SHOOT] should add worker pool with containerd [It]
  /Users/i331370/go/src/github.com/gardener/gardener/test/framework/gingko_utils.go:26

  Expected
      <string>: containerd
  to equal
      <v1alpha1.CRIName>: containerd

  /Users/i331370/go/src/github.com/gardener/gardener/test/integration/shoots/operations/containerruntime.go:98
```

2021-01-29 19:19 UTC, vpnachev submitted a review, later dismissed
/lgtm

2021-02-01 06:56 UTC, ialidzhikov approved these changes, later dismissed
/lgtm

2021-02-01 07:07 UTC, rfranzke commented
Thanks for approving. I guess, we can merge the PR then. @ialidzhikov (and others, if interested), do you also have an opinion about squash vs. keep-commits?

2021-02-01 07:51 UTC, ialidzhikov commented
> Thanks for approving. I guess, we can merge the PR then. @ialidzhikov (and others, if interested), do you also have an opinion about squash vs. keep-commits?

I would also vote for keeping the commits as it was also very helpful for me to go through separate commits while checking this PR.
A rebase is needed meanwhile.

2021-02-01 08:18 UTC, rfranzke commented
OK, then let's do it like this. I have rebased and squashed the "address PR review feedback" commits into the original commits now.

/remove merge/squash
/add merge/keep-commits

2021-02-01 08:29 UTC, vpnachev approved these changes, later dismissed
/lgtm

2021-02-01 13:47 UTC, danielfoehrKn commented
/assign looking into it atm and will finish EOB

2021-02-01 17:04 UTC, danielfoehrKn requested changes, later dismissed
Really nice refactoring. 

Just some minor remarks. Will test it tomorrow morning if that is ok, I know the PR has been open for quite a while.

2021-02-01 17:04 UTC, danielfoehrKn commented on pkg/operation/botanist/extensions/operatingsystemconfig/operatingsystemconfig.go
> +		kubeletConfigParameters: kubeletConfigParameters,
```suggestion
		globalKubeletConfigParameters: kubeletConfigParameters,
```

Makes it a bit more clear?

2021-02-01 17:04 UTC, danielfoehrKn commented on pkg/operation/botanist/extensions/operatingsystemconfig/operatingsystemconfig.go
> +	client    client.Client
```suggestion
	seedClient    client.Client
```

2021-02-01 17:04 UTC, danielfoehrKn commented on pkg/operation/botanist/extensions/operatingsystemconfig/operatingsystemconfig.go
> +	key       string
Can we adjust the naming or add a comment to make more clear what this "key" is? 
This is the unique key based on the worker name and K8s version and 
 - is the name of the secret containing the cloud-config-execution script for a worker pool
 - serves a  unique prefix for the OSC resource name which consists of: <key>-<original/downloader>

2021-02-01 17:04 UTC, danielfoehrKn commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
> +			"--container-runtime-endpoint=unix:///run/containerd/containerd.sock",
Have socket as a constant? Currently we do not allow to change it.

2021-02-01 17:04 UTC, danielfoehrKn commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/components.go
> +	Name() string
Does not seem to be used anywhere, can we remove it then?

2021-02-02 08:54 UTC, rfranzke commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/components.go
> +	Name() string
I used it here https://github.com/rfranzke/gardener/commit/740d911b34ea0794208f056e38f48c74500d03b3#diff-c8b75044fad4e522e6c5fff61acba3554798a4c78e4a649a779b5520d72dd9aaR108-R143 to test the correct order of the components. Yes, the `Name() string` function is not used in the "production" code, however, it's very lightweight, so I guess it's fine. If you have better proposals for the test, feel free to shout it out.

2021-02-02 08:56 UTC, rfranzke commented on pkg/operation/botanist/extensions/operatingsystemconfig/operatingsystemconfig.go
> +	key       string
Hm, I don't really want to add such comment here. It is used in various places and there is already a comment here https://github.com/rfranzke/gardener/commit/a28511722bf04a9803978834894e11fa60682dcb#diff-a4b93797c6ef59074974f40fbc4b8b7d15661a91b978bcce5637ebfd3de83e38R593.

2021-02-02 08:56 UTC, rfranzke commented on pkg/operation/botanist/extensions/operatingsystemconfig/operatingsystemconfig.go
> +	client    client.Client
Hm, no, it's called `client` everywhere (also in other components, e.g. https://github.com/gardener/gardener/blob/master/pkg/operation/botanist/extensions/controlplane/controlplane.go#L91), so let's keep it like this.

2021-02-02 08:57 UTC, rfranzke commented on pkg/operation/botanist/extensions/operatingsystemconfig/operatingsystemconfig.go
> +		kubeletConfigParameters: kubeletConfigParameters,
Not sure, I would like to keep it similar to the `kubeletCLIFlags` field.

2021-02-02 08:57 UTC, rfranzke commented on pkg/operation/botanist/extensions/operatingsystemconfig/original/components/kubelet/cliflags.go
> +			"--container-runtime-endpoint=unix:///run/containerd/containerd.sock",
Yes, makes sense, done.

2021-02-02 08:58 UTC, rfranzke commented
> Just some minor remarks. Will test it tomorrow morning if that is ok, I know the PR has been open for quite a while.

Well, indeed. It actually was already approved earlier and ready to merge.

2021-02-02 09:01 UTC, vpnachev approved these changes
/lgtm

2021-02-02 09:28 UTC, merged