Alicloud API enhancement
gardener/gardener pull request #349
Opened 2018-09-04 06:57 UTC by jia-jerry

**What this PR does / why we need it**:
This PR is for Alicloud foucusing on API server. It includes new type of CloudProfile, Shoot and etc.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Alicloud is planned to be supported by Gardener. This PR includes API changes in data structure and example yamls. 
**Release note**:
NONE

2018-09-04 07:24 UTC, rfranzke reviewed
Great, thank's for the PR!
Looks good, just a suggestions/question about the `CloudProfile` specification.

2018-09-04 07:24 UTC, rfranzke commented on example/30-cloudprofile-alicloud.yaml
> +        class: cloud_efficiency
Usually, we only have `standard` and `premium` as volume classes. Could you adapt, please?

2018-09-04 07:24 UTC, rfranzke commented on example/30-cloudprofile-alicloud.yaml
> +        zoneContraints:
Hm, instead of having `zoneContraints` here, wouldn't it be nicer/cleaner to add the zones in which a specific machine type is available directly to the machine type?

I mean:

```yaml
machineTypes:
- name: ecs.t5-lc1m1.small
  cpu: "1"
  gpu: "0"
  memory: 1Gi
  zones:
  - cn-beijing-f
```

Same for `volumeTypes`.

The `zones` would look like this:

```yaml
zones:
- region: cn-beijing
  names:
  - cn-beijing-f
```

What do you think?

2018-09-04 07:31 UTC, jia-jerry commented on example/30-cloudprofile-alicloud.yaml
> +        class: cloud_efficiency
Sure. But there are actually 4 types of volume for Alicloud and only 2 classes are available now. How shall we do the mapping?

2018-09-04 07:37 UTC, rfranzke commented on example/30-cloudprofile-alicloud.yaml
> +        class: cloud_efficiency
The volume classes are used for `Quota`s (https://github.com/gardener/gardener/blob/f6f8e2382143d9179d8ec13657515e46ffc97669/example/60-quota.yaml#L16-L17).
I guess `cloud_efficiency` and `ssd` would be `premium` while `cloud` would be `standard`?! You have to decide that, I don't know Alicloud very well.

2018-09-04 07:39 UTC, jia-jerry commented on example/30-cloudprofile-alicloud.yaml
> +        zoneContraints:
Agree. To support a new type only one place will be changed.

2018-09-04 08:07 UTC, jia-jerry commented on example/30-cloudprofile-alicloud.yaml
> +        class: cloud_efficiency
Yes. Double checked in Alicloud, there are 3 types of volumes and 2 of them are commonly supported. They are *cloud_efficiency* and *ssd*. Even we still have a class storage.basic to match *cloud* type.

2018-09-07 06:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=349) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=349) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jia-jerry<br/>:x: minchaow<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=349) it.</sub>

2018-09-07 07:20 UTC, rfranzke requested changes
Thank you for updating, kindly address the mentioned comments. Also, please do rebase your branch on the latest `master` and squash your commits.

2018-09-07 07:20 UTC, rfranzke commented on hack/templates/resources/90-shoot.yaml.tpl
> +      zones: ${value("spec.cloud.aws.zones", ["cn-beijing-f"])}
Replace `aws` with `alicloud`

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/types.go
> +	MachineImage AlicloudMachineImage
Should be a pointer as it's optional: `*AlicloudMachineImage`

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +	MachineImage AlicloudMachineImage `json:"machineImage,omitempty"`
Should be a pointer as it's optional: `*AlicloudMachineImage`

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, validateAlicloudMachineTypeConstraints(spec.Alicloud.Constraints, fldPath.Child("alicloud", "constraints"))...)
Minor suggestion: Why not passing `.spec.Alicloud.Constraints.MachineTypes` and `.spec.Alicloud.Constraints.Zones` instead of the whole `.spec.Alicloud.Constraints` object.

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, validateAlicloudVolumeTypeConstraints(spec.Alicloud.Constraints, fldPath.Child("alicloud", "constraints"))...)
Minor suggestion: Why not passing `.spec.Alicloud.Constraints.MachineTypes` and `.spec.Alicloud.Constraints.Zones` instead of the whole `.spec.Alicloud.Constraints` object.

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/types.go
> +	// Verison is the version of image.
typo

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
> +			existed := false
s/existed/existing

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +	// Verison is the version of image.
typo

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +//AlicloudVolumeType defines
space after `//`

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +//AlicloudMachineType defines certain machine type combining original defined MachineType and new defined Zones
space after `//`

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/types.go
> +//AlicloudVolumeType defines
space after `//`, missing doc string

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/types.go
> +//AlicloudMachineType defines certain machine type combining original defined MachineType and new defined Zones
space after `//`

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
> +	for i, image := range machineImages {
Why aren't you validating the `Version` field?

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, validateAlicloudMachineTypeConstraints(spec.Alicloud.Constraints, fldPath.Child("alicloud", "constraints"))...)
Minor suggestion: Why not passing `.spec.Alicloud.Constraints.MachineTypes` and `.spec.Alicloud.Constraints.Zones` instead of the whole `.spec.Alicloud.Constraints` object.

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +//AlicloudVolumeType defines
space after `//`, missing docstring

2018-09-07 07:20 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +//AlicloudVolumeType defines
space after `//`

2018-09-07 07:30 UTC, jia-jerry commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, validateAlicloudMachineTypeConstraints(spec.Alicloud.Constraints, fldPath.Child("alicloud", "constraints"))...)
This is because we need zones information from alicloud.contraints.zones. They are used to do valid check.

2018-09-07 07:32 UTC, jia-jerry commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, validateAlicloudMachineTypeConstraints(spec.Alicloud.Constraints, fldPath.Child("alicloud", "constraints"))...)
OK. It is more expressive.

2018-09-07 07:32 UTC, jia-jerry commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, validateAlicloudVolumeTypeConstraints(spec.Alicloud.Constraints, fldPath.Child("alicloud", "constraints"))...)
OK. It is more expressive.

2018-09-07 07:47 UTC, jia-jerry commented on hack/templates/resources/90-shoot.yaml.tpl
> +      zones: ${value("spec.cloud.aws.zones", ["cn-beijing-f"])}
Thanks for your careful check. Will follow up soon.

2018-09-07 08:45 UTC, jia-jerry commented on pkg/apis/garden/validation/validation.go
> +	for i, image := range machineImages {
Version is an optional field and just for information. I will change the Version declaration as optional.

2018-09-07 10:59 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
> +	for i, image := range machineImages {
If it's optional and just for information then let's only have it in the CloudProfile, but not in the Shoot manifest, or not at all at both resources.

2018-09-07 12:56 UTC, jia-jerry commented on pkg/apis/garden/validation/validation.go
> +	for i, image := range machineImages {
OK. Just remove it as we could deduce its version from the image ID simply.

2018-09-07 13:22 UTC, closed without merging