Update set_dependency_version
gardener/gardener pull request #3528
Opened 2021-02-09 13:35 UTC by AndreasBurger

**How to categorize this PR?**
/kind cleanup
/priority normal

**What this PR does / why we need it**:
Removes set_dependency_version's dependency towards cc-utils product.model (which is to be removed at some point in the future).

2021-02-12 13:45 UTC, rfranzke commented
@AndreasBurger what about this PR? Can you please ask @ccwienk via other communication channels to review it?

2021-02-16 16:00 UTC, ccwienk approved these changes

2021-02-16 16:01 UTC, ccwienk commented on hack/.ci/set_dependency_version
> +name = dependency_name.split('/')[2]
to be a bit more robust:
```
dependency_name.strip('/').split('/')[-1]
```

2021-02-16 16:01 UTC, ccwienk requested changes
see inline comment

2021-02-16 16:05 UTC, ccwienk approved these changes, later dismissed

2021-02-16 16:06 UTC, AndreasBurger commented
Implemented the suggestion

2021-02-16 16:08 UTC, rfranzke approved these changes, later dismissed
/lgtm

/hold until v1.17 is released

2021-02-17 07:29 UTC, rfranzke approved these changes
/unhold

2021-02-17 07:29 UTC, merged