_versions file is now a separate chart
gardener/gardener pull request #363
Opened 2018-09-13 14:32 UTC by mvladev

Symlinking the `_versions` file causes issues when having a requirements.yaml in some charts. This file is now moved to a seprate `api-versions` chart and all other charts can require it via `requirements.yaml`.

Whenever this chart is modified, `make helm-dep-update` must be called to update helm dependencies.

**What this PR does / why we need it**: Symlinking is broken and very hard to do correctly.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**: I've uncommented all `infa` charts - I don't think that it's a problem

**Release note**:

```improvement operator
NONE
```

2018-09-13 14:53 UTC, rfranzke commented
Can you elaborate on the problems?
Are you really sure that uncommenting the values in the infra charts is safe?
Have you tested the changes for all Kubernetes versions we are supporting?

2018-09-14 19:24 UTC, mvladev commented
> Can you elaborate on the problems?

If you have symlink in one chart called `foo-chart` and then require this chart with `repository: file://../foo-chart` then in the resulting tar ball the symlinked file will be put in at path `Users/MY_USER/GO_PATH../github.com/gardener/gardener/chart/foo-chart/templates/SYMLINKED-FILE`

2018-09-20 07:55 UTC, rfranzke commented
OK. Can you please rebase your branch? What about the remaining open questions from my previous comment?

2018-09-25 07:57 UTC, rfranzke commented
ping

2018-09-25 14:46 UTC, mvladev commented
@rfranzke I've all of the Infra charts have their default values overwritten in their respected  `.go` files.

2018-10-10 10:19 UTC, mvladev commented
@rfranzke rebased to latest changes

2018-10-10 11:52 UTC, mvladev commented
⚠️ #428 introduces a new symlink

2018-10-12 14:58 UTC, zanetworker commented
@mvladev I have ran some tests locally and it seems that the machine-controller-manager is crashlooping because of missing permissions  `machine-controller-manager 0/1       CrashLoopBackOff  `. Also found that the machine-controller-manager addon is not specified in the **requirements.yaml.**

```
- name: machine-controller-manager
  repository: file://addons/machine-controller-manager
  version: 0.1.0
```

Can you please run another test and confirm?

2018-10-12 15:00 UTC, rfranzke commented
FYI: Due to @zanetworker's analysis (changes needed) I have now merged other PRs, e.g., #428 which you were pointing add, @mvladev. Please also rebase and adapt your changes! Thank you!

2018-10-12 15:25 UTC, rfranzke commented
> Can you please run another test and confirm?

@mvladev, did you even test it yourself? I mean, when checking out the branch and creating a cluster it doesn't even come up. You would have seen this...
Instead, @zanetworker did now spend his time reviewing something that was not validated beforehand by the author itself...
Especially in our current situation (having very less output qualification) we should optimize this process. Please do at least at a base level test by creating a new cluster and updating an existing one.

2018-10-14 20:03 UTC, mvladev commented
@rfranzke I've tested it, but I recall that the cluster was created with no problem.

The problem might be with reading in runtime of the `charts` folder. I often switch branches - I probably ran controller with my local `_versions` branch and switched to some other branch - the `charts` dir was checkout-ed and It rendered correctly.
As a workaround and to ensure stability and reliability, when the controller is started, we might want to copy the entire `charts` folder in a temporary dir and read charts from it.

Sorry for the wasted time @zanetworker.

2018-10-15 05:19 UTC, rfranzke commented
Thanks @mvladev, no problem, I just wanted to raise the awareness.
@Adracus came up with https://github.com/kevinburke/go-bindata, what do you think about that?

2018-10-15 10:25 UTC, zanetworker commented
@mvladev no worries :)

2018-10-15 15:40 UTC, zanetworker submitted a review, later dismissed

2018-10-15 17:08 UTC, mvladev commented
All issues should be fixed now - the cluster was created without any problems in 5ebf6b9 

The only problem seems to be that after every single `make helm-dep-update` all archived tars are updated. This is a new behavior - in the previous versions they remained unchanged.

2018-10-15 17:41 UTC, rfranzke commented
OK, thanks. Running `make dep-helm-update` is only needed if the `api-versions` chart itself changes, right? Hence, shouldn't happen too often, I guess.

2018-10-15 17:43 UTC, mvladev commented
@rfranzke it'll be needed also if you change one of the `shoot-addons` as well.

2018-10-15 17:45 UTC, rfranzke commented
Oh ok, why?

2018-10-16 06:15 UTC, rfranzke requested changes
One small issue, otherwise looks good.
However, I really don't like that all the `tgz` files get modified on each and every single `make helm-dep-update` run. Can't this be worked around somehow? 😕

2018-10-16 06:15 UTC, rfranzke commented on charts/shoot-addons/requirements.yaml
>    condition: kubernetes-dashboard.enabled
copy-paste mistake?

2018-10-16 08:37 UTC, mvladev commented on charts/shoot-addons/requirements.yaml
>    condition: kubernetes-dashboard.enabled
Yeah. This entire char should not be there in the first place. I've moved it to `shoot-core`

2018-10-16 08:43 UTC, mvladev commented
> @rfranzke it'll be needed also if you change one of the shoot-addons as well.
> Oh ok, why?

Because, when using conditions in `requirements.yaml`, you can't reference them locally.:

```yaml
dependencies:
- name: cluster-autoscaler
  repository: file://charts/cluster-autoscaler
  version: 0.1.0
  condition: cluster-autoscaler.enabled
```

This returns an error. 

> However, I really don't like that all the tgz files get modified on each and every single make helm-dep-update run. Can't this be worked around somehow? 

Unfortunately, I'm not aware of way to do so.

2018-10-16 08:47 UTC, mvladev commented
What we can do is not to check them in and when the controller-manager is started to build them dynamically

2018-10-16 08:49 UTC, rfranzke commented
Hm yeah, but this would increase start-up time significantly, right? And, for local development purposes we need them to be checked in, don't we?

2018-10-16 08:57 UTC, mvladev commented
What about -

1. We don't check them in git
1. When a developer clones the repo `make helm-dep-update` must be called.
1. The controller-manager can start as before
1. On change in `charts` -> `make helm-dep-update`
1. On build for release -> `make helm dep-update`

2018-10-16 13:33 UTC, rfranzke commented
Yes, we could do this. However, I especially don't like the fourth point. Can we get to a state where we ONLY need to run `make helm-dep-update` if we change the `api-versions` chart? I don't want to run it for each and every change. That requirement is highly error-prone, especially with local files ignored by git (the tgz's).

2018-10-17 18:23 UTC, rfranzke commented
Short summary of a conversation with @mvladev: Martin will write a small program that gets called when using `make helm-dep-update`. It will be able to identify whether the Helm dependencies need to be updated or not, and will then only trigger the update for those requiring it.

2018-10-19 18:51 UTC, mvladev commented
⚠️  PR has been updated with the new implementation. Checks for broken symlinks and template rendering have been added.

PR description has been changed to match with new changes

2018-10-22 05:41 UTC, rfranzke approved these changes
/lgtm

2018-10-22 05:41 UTC, rfranzke commented on .ci/check
> +# Render chart dirs
Nice, thank you!

2018-10-22 05:41 UTC, rfranzke commented on pkg/client/kubernetes/base/base.go
> +			StatefulSets:              {"apis", "apps", "v1"},
You should fix your editor settings regarding auto-formatting, `make fmt/verify` shows formatting changes.

2018-10-22 05:41 UTC, rfranzke commented on pkg/client/kubernetes/base/base.go
> +			StatefulSets:              {"apis", "apps", "v1"},
You should fix your editor settings regarding auto-formatting, `make fmt/verify` shows formatting changes.

2018-10-22 05:41 UTC, rfranzke commented on .ci/check
> +# Render chart dirs
Nice, thank you!

2018-10-22 05:41 UTC, rfranzke commented on pkg/client/kubernetes/base/base.go
> +			StatefulSets:              {"apis", "apps", "v1"},
You should fix your editor settings regarding auto-formatting, `make fmt/verify` shows formatting changes.

2018-10-22 05:41 UTC, rfranzke commented on pkg/utils/secrets/certificates.go
> +			KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
You should fix your editor settings regarding auto-formatting, `make fmt/verify` shows formatting changes.

2018-10-22 05:41 UTC, rfranzke commented on pkg/client/kubernetes/base/base.go
> +			StatefulSets:              {"apis", "apps", "v1"},
You should fix your editor settings regarding auto-formatting, `make fmt/verify` shows formatting changes.

2018-10-22 05:41 UTC, rfranzke commented on pkg/client/kubernetes/base/base.go
> +			StatefulSets:              {"apis", "apps", "v1"},
You should fix your editor settings regarding auto-formatting, `make fmt/verify` shows formatting changes.

2018-10-22 05:41 UTC, rfranzke commented on pkg/client/kubernetes/base/base.go
> +			StatefulSets:              {"apis", "apps", "v1"},
You should fix your editor settings regarding auto-formatting, `make fmt/verify` shows formatting changes.

2018-10-22 05:41 UTC, rfranzke approved these changes
/lgtm

2018-10-22 05:50 UTC, rfranzke approved these changes
/lgtm

2018-10-22 05:50 UTC, rfranzke commented on .ci/check
> +# Render chart dirs
Nice, thank you!

2018-10-22 05:50 UTC, rfranzke commented on .ci/check
> +# Render chart dirs
Nice, thank you!

2018-10-22 05:50 UTC, rfranzke commented on pkg/utils/secrets/certificates.go
> +			KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
You should fix your editor formatting settings.

2018-10-22 05:50 UTC, rfranzke commented on pkg/client/kubernetes/base/base.go
> +			StatefulSets:              {"apis", "apps", "v1"},
You should fix your editor formatting settings.

2018-10-22 05:50 UTC, rfranzke commented on pkg/utils/secrets/certificates.go
> +			KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
You should fix your editor formatting settings.

2018-10-22 05:50 UTC, rfranzke approved these changes
/lgtm

2018-10-22 05:52 UTC, rfranzke commented
LGTM! Thank's for the check whether templates can be rendered!
PS: You should fix your editor formatting settings.

2018-10-22 05:52 UTC, rfranzke commented
LGTM! Thank's for the check whether templates can be rendered!
PS: You should fix your editor formatting settings.

2018-10-22 05:53 UTC, rfranzke commented
LGTM! Thank's for the check whether templates can be rendered!
PS: You should fix your editor formatting settings.

2018-10-22 06:32 UTC, rfranzke commented
/lgtm

2018-10-22 06:32 UTC, merged

2018-10-22 07:19 UTC, mvladev commented
This PR is merged, but for some reason github doesn't recognize it as such.
Closing it.