VPA minAllowed configuration for metrics-server.
gardener/gardener pull request #3682
Opened 2021-03-10 06:11 UTC by amshuman-kr

**How to categorize this PR?**

/area control-plane high-availability robustness scalability
/kind enhancement
/priority normal

**What this PR does / why we need it**:
VPA minAllowed configuration for metrics-server.

**Which issue(s) this PR fixes**:
Fixes #3619 

**Special notes for your reviewer**:

**Release note**:

```other operator
VPA minAllowed configuration for metrics-server.
```

2021-03-10 06:12 UTC, amshuman-kr commented
/hold Testing. Will mark it ready for review shortly.

2021-03-11 18:57 UTC, amshuman-kr commented
cc @vpnachev @plkokanov @danielfoehrKn

2021-03-11 19:07 UTC, vpnachev requested changes
You need to adapt the unit test here https://github.com/gardener/gardener/blob/7c4351f32447b9596b577e610495b785d952cb0a/pkg/operation/botanist/component/metricsserver/metrics_server_test.go

2021-03-11 21:31 UTC, vpnachev commented
I guess `make test` locally will is failing, too.

2021-03-12 02:56 UTC, amshuman-kr commented
> I guess running make test locally is failing, too.

Hmm... strange the test worked locally. I will check again.

2021-03-12 03:05 UTC, amshuman-kr commented
> Hmm... strange the test worked locally. I will check again.

Forgetting to remove the focused test was the culprit locally 🤦 Now the build should go through 🤞

2021-03-12 06:30 UTC, vpnachev approved these changes
/lgtm

2021-03-12 06:42 UTC, plkokanov approved these changes
/lgtm

2021-03-12 06:49 UTC, rfranzke approved these changes
/lgtm

2021-03-12 06:51 UTC, rfranzke commented
> /hold Testing. Will mark it ready for review shortly.

Can this be merged now?

2021-03-12 09:49 UTC, amshuman-kr commented
> Can this be merged now?

Yes.

/unhold

2021-03-12 09:51 UTC, merged