Switch shoot.Status.SeedName at start of the reconcile process
gardener/gardener pull request #3723
Opened 2021-03-17 12:49 UTC by kris94

**How to categorize this PR?**

/area control-plane-migration
/kind enhancement
/priority normal

**What this PR does / why we need it**:
This PR sets the correct `shoot.Status.SeedName` at the start of the  shoot operation process. This needs to be done at the start of a CPM process where the `spec.SeedName` is different from the `shoot.Status.SeedName`. It also adds description messages for operation `Migrate` and operation `Restore`.
**Which issue(s) this PR fixes**:
Fixes 

**Special notes for your reviewer**:
Part of #1631 
**Release note**:

```other operator
NONE
```

2021-03-17 12:49 UTC, kris94 commented
/assign @plkokanov

2021-03-17 13:41 UTC, timebertt commented
/hold
until the `v1.19.0` release is cut.

2021-03-18 14:03 UTC, timebertt commented
/unhold

2021-03-18 16:21 UTC, rfranzke requested changes

2021-03-18 16:21 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot_control.go
> +			if shoot.Status.SeedName != shoot.Spec.SeedName && operationType != gardencorev1beta1.LastOperationTypeMigrate {
```suggestion
			if !apiequality.Semantic.DeepEqual(shoot.Status.SeedName, shoot.Spec.SeedName) && operationType != gardencorev1beta1.LastOperationTypeMigrate {
```

2021-03-22 15:36 UTC, rfranzke approved these changes
/lgtm

2021-03-22 15:36 UTC, merged