Add CP dependency to OSConfig
gardener/gardener pull request #3761
Opened 2021-03-23 15:11 UTC by kon-angelo

**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
Fixes a race condition encountered for an Azure cluster where the `OperatingSystemConfig` would be created before the `ControlPlane`. 

This PR aims to delay the deployment of `OperatingSystemConfig` until after the deployment of CP. In certain extensions (Azure)  

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other developer
The `OperatingSystemConfig` is now created after `ControlPlane` has been deployed
```

2021-03-23 15:14 UTC, vpnachev commented
Could give an example for such race condition or actual problem?

2021-03-23 15:32 UTC, vpnachev commented
In chat with @kon-angelo it turns out that `EnsureKubeletCloudProviderConfig` has some difficulties at the moment.
My opinion is that the kubelet and OSC mutators should be moved out of the `ControlPlane` handler and rather have their own that mutates the `OperatingSystemConfig` resources on `create`/`update`.

2021-03-23 17:47 UTC, rfranzke commented
@vpnachev I don't understand your proposal/concerns. The issue @kon-angelo tries to fix here is not related to the fact that kubelet and OSC related mutators are part of the `controlplane` webhook, is it? The `ControlPlane` extension resource typically generates the cloud-provider configuration. The kubelet sometimes needs this configuration, hence, the task which "deploys" the kubelet must be dependent on a successful `ControlPlane` reconciliation to ensure the needed cloud-provider configuration exists in the system.

2021-03-23 17:48 UTC, rfranzke requested changes

2021-03-23 17:48 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot_control_reconcile.go
> +			Dependencies: flow.NewTaskIDs(deployReferencedResources, waitUntilInfrastructureReady, deployControlPlane),
```suggestion
			Dependencies: flow.NewTaskIDs(deployReferencedResources, waitUntilInfrastructureReady, waitUntilControlPlaneReady),
```

2021-03-25 07:03 UTC, rfranzke approved these changes
/lgtm
/invite @vpnachev

2021-03-25 08:54 UTC, vpnachev approved these changes
/lgtm

2021-03-25 09:03 UTC, merged