Add fine-grained RBACs for gardenlet in the seed cluster
gardener/gardener pull request #3763
Opened 2021-03-23 19:50 UTC by vpnachev

**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:
Configures `gardenlet` with more fine-grained permissions in the seed cluster.

**Which issue(s) this PR fixes**:
Part of #1724 

**Special notes for your reviewer**:

**Release note**:

```other operator
The RBACs for the `gardenlet` in the seed cluster are now fine-grained defined and limited as much as possible.
```

2021-03-24 06:37 UTC, rfranzke reviewed
/assign
/invite @stoyanr

2021-03-24 06:39 UTC, rfranzke reviewed
Can you prefix all roles/rolebindings with `gardener.cloud:system:gardenlet:`?

2021-03-24 06:46 UTC, ialidzhikov commented
/assign @ialidzhikov

2021-03-24 15:40 UTC, vpnachev commented
> Can you prefix all roles/rolebindings with `gardener.cloud:system:gardenlet:`?

Done.

2021-03-26 13:28 UTC, ialidzhikov reviewed
Thank you for your hard work on this topic! Appreciate it!
It seems that I will need more time than I initially expected to setup a proper env to try out this change.
I am leaving few comments inline for now.

2021-03-26 13:28 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/rbac.yaml
> +# For now, we provide escalation privileges required by gardener resoruce manager.
This file now contains 12 resources. According to the helm best practices (ref https://helm.sh/docs/chart_best_practices/templates/):

> Each resource definition should be in its own template file.

Does it make sense to split this huge template file into dedicated template files. WDYT?
I find it hard to follow when everything is in single template file 😅 .

2021-03-26 13:28 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/rbac.yaml
> +  - update
When the Seed is with

```yaml
spec:
  settings:
    verticalPodAutoscaler:
      enabled: false
```

then gardenlet will try to delete this webhook. 

https://github.com/gardener/gardener/blob/9df08ae3ae865f96db4161eb4ad01ced73107f3e/pkg/operation/common/utils.go#L280.

```
time="2021-03-26T13:56:05+02:00" level=error msg="seed is not yet ready: condition \"Bootstrapped\" has invalid status False (expected True) due to BootstrappingFailed: mutatingwebhookconfigurations.admissionregistration.k8s.io \"vpa-webhook-config-seed\" is forbidden: User \"system:serviceaccount:garden:gardenlet\" cannot delete resource \"mutatingwebhookconfigurations\" in API group \"admissionregistration.k8s.io\" at the cluster scope" operation=reconcile shoot=garden-foo/aws-local
```

```suggestion
  - vpa-webhook-config-seed
  verbs:
  - get
  - update
  - delete
```

2021-03-26 13:28 UTC, ialidzhikov commented on pkg/gardenlet/controller/managedseed/managedseed_actuator.go
> +	return err
```suggestion
	_, err := controllerutil.CreateOrUpdate(ctx, shootClient.Client(), sniIngressNamespace, func() error {
		return nil
	})

	return err
```

2021-03-26 16:02 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/rbac.yaml
> +  - statefulsets
gardenlet should be able to list replicasets and get kube-apiserver Pod logs. Ref https://github.com/gardener/gardener/pull/3353.

```
time="2021-03-26T16:46:08+02:00" level=error msg=Error error="failure to find the newest pod for deployment to read the logs: replicasets.apps is forbidden: User \"system:serviceaccount:garden:gardenlet\" cannot list resource \"replicasets\" in API group \"apps\" in the namespace \"shoot--foo--bar\": retry failed with context deadline exceeded, last error: kube-apiserver deployment has outdated replicas" flow="Shoot cluster reconciliation" operation=reconcile shoot=garden-foo/bar task="Waiting until Kubernetes API server reports readiness"
```

You can reproduce this by specifying a wrong feature gate for the kube-apiserver.

2021-03-26 16:02 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/rbac.yaml
> +  - delete
gardenlet needs deletecollection for pods. 

https://github.com/gardener/gardener/blob/9df08ae3ae865f96db4161eb4ad01ced73107f3e/pkg/operation/botanist/controlplane.go#L1015-L1023

```
time="2021-03-26T17:17:37+02:00" level=error msg=Error error="pods is forbidden: User \"system:serviceaccount:garden:gardenlet\" cannot deletecollection resource \"pods\" in API group \"\" in the namespace \"shoot--foo--bar\"" flow="Shoot cluster reconciliation" operation=reconcile shoot=garden-foo/bar task="Restart control plane pods"
```

2021-03-31 07:43 UTC, stoyanr requested changes

2021-03-31 07:43 UTC, stoyanr commented on pkg/gardenlet/controller/managedseed/managedseed_actuator.go
>  	// Prepare gardenlet chart values
Shouldn't we check `gardenletConfig.SNI.Ingress.Namespace` is non-nil before dereferencing it (see above)?

What is this namespace supposed to contain? Typically namespace deletion may take some time, e.g. deletion of the `garden` namespace takes sometimes > 5 minutes. Should we ensure it's deleted before the managed seed itself is deleted, like for the `garden` namespace?

Note: I plan to refactor the deletion code in the near future to get rid of the current requeue-through-error behavior. So I could also take care to wait for this namespace if you would rather not do it in this PR, just let me know if you think it's a good idea.

2021-03-31 07:43 UTC, stoyanr commented on pkg/gardenlet/controller/managedseed/managedseed_actuator.go
> +	if err := a.createSNIIngressNamespace(ctx, shootClient, *gardenletConfig.SNI.Ingress.Namespace); err != nil {
Shouldn't we check `gardenletConfig.SNI.Ingress.Namespace` is non-nil before dereferencing it? Actually, `SNI` and `Ingress` are also pointers and should be checked as well I believe. Perhaps you could introduce a helper function to properly get this namespace?

It's true that the resource has defaults to always set this. However, these defaults are only applied when an actual resource is created, but not when the resource is deserialized as part of a template - like in this case. So all of these pointers could well be nil I believe.

2021-03-31 07:43 UTC, stoyanr commented on pkg/gardenlet/controller/managedseed/managedseed_actuator.go
> +	return err
I also think what @ialidzhikov proposes should be better.

2021-03-31 13:54 UTC, vpnachev commented on pkg/gardenlet/controller/managedseed/managedseed_actuator.go
> +	return err
This is done on purpose. In some cases the Istio installation is managed by other component, not by gardener and I do not want to touch the namespace at all. This why this create call must be invoked only once only if the namesapce does not exist.

2021-04-07 18:43 UTC, vpnachev commented
/merge squash

2021-04-09 08:23 UTC, ialidzhikov commented
Thanks for updating the PR. I will soon go over it once again. Sorry for the delay.

2021-04-09 10:40 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/clusterrole-gardenlet.yaml
> +{{- end }}
You could add an empty line to the end of the file.

2021-04-09 10:40 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/rolebinding-default-gardenlet.yaml
> +{{- end }}
You could add an empty line to the end of the file.

2021-04-09 10:40 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/rolebinding-garden-gardenlet.yaml
> +{{- end }}
You could add an empty line to the end of the file.

2021-04-09 10:40 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/clusterrole-gardenlet.yaml
> +rules:
https://github.com/gardener/gardener/pull/3811 was recently merged and it lists all Seed nodes to decide on seed-admission-controller Deployment replicas.

```suggestion
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
```

```
time="2021-04-09T13:16:29+03:00" level=error msg="seed is not yet ready: condition \"Bootstrapped\" has invalid status False (expected True) due to BootstrappingFailed: 1 error occurred:\n\t* task \"Deploying gardener-seed-admission-controller\" failed: nodes is forbidden: User \"system:serviceaccount:garden:gardenlet\" cannot list resource \"nodes\" in API group \"\" at the cluster scope\n\n" operation=reconcile shoot=garden-foo/aws-local
```

2021-04-09 10:40 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/clusterrole-gardenlet.yaml
> +  - replicasets
The case described in https://github.com/gardener/gardener/pull/3763#discussion_r602357037 still fails:

```
time="2021-04-09T13:37:03+03:00" level=error msg="Failed to reconcile Shoot \"aws-local\": flow \"Shoot cluster reconciliation\" encountered task errors: [task \"Waiting until Kubernetes API server reports readiness\" failed: failure to read the logs: pods \"kube-apiserver-7968db85fd-gtd45\" is forbidden: User \"system:serviceaccount:garden:gardenlet\" cannot get resource \"pods/log\" in API group \"\" in the namespace \"shoot--foo--aws-local\": retry failed with context deadline exceeded, last error: kube-apiserver deployment has outdated replicas]" operation=reconcile shoot=garden-foo/aws-local
```

2021-04-09 10:57 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/clusterrole-gardenlet.yaml
> +{{- if .Values.global.gardenlet.enabled }}
With https://github.com/gardener/gardener/pull/3535 the default resource lock was changed to leases. Currently I don't see any rule for leases. I think we should add a rule like:

```yaml
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - gardenlet-leader-election
  verbs:
  - get
  - watch
  - update
```

2021-04-09 21:03 UTC, vpnachev commented
/status author-action

I found some more things that need to be done, but will not be able to work on it next.
Will update here when it is ready for next review round.

2021-04-13 16:02 UTC, danielfoehrKn reviewed
I think this related [part of the documentation](https://github.com/gardener/gardener/blob/69efab1bd8a415cb4b280699e6bd62149a7ecd67/docs/deployment/deploy_gardenlet_manually.md#kubeconfig-for-the-seed-cluster) needs an update as no longer admin privileges are required in the Seed cluster.

2021-04-21 06:34 UTC, ialidzhikov commented on charts/gardener/gardenlet/charts/runtime/templates/clusterrole-gardenlet.yaml
> +  - loki
FYI, https://github.com/gardener/gardener/pull/3903 (if merged before this PR) would require extending this list:

```suggestion
  resourceNames:
  - etcd-events
  - etcd-main
  - kube-apiserver
  - loki
  - aggregate-prometheus
  - prometheus
```

2021-05-21 05:51 UTC, rfranzke commented
What is the status of this PR?

2021-05-21 07:00 UTC, vpnachev commented
I am out of capacity last days, and probably will be so in the next 2-3 weeks.
Therefore I am closing it for now and will re-open once I address the comments.

2021-05-21 07:00 UTC, closed without merging