Calico 3.2
gardener/gardener pull request #380
Opened 2018-09-24 10:08 UTC by databus23

I bumped the images and merged in the template changes from the official calico manifests trying to minimise whitespace and ordering changes.

**Which issue(s) this PR fixes**:
Fixes #376

**Special notes for your reviewer**:
The mtu is now configured centrally in the configmap. See https://github.com/projectcalico/calico/pull/1770.
This will change the CNI MTU from `1500` to `1440` (see diff). Not sure if it was different on purpose.

This change is not tested as I don't have access to a gardner dev setup and don't have the time to set one up right now.

**Release note**:
```improvement operator
Update to calico v3.2.1.
```

2018-09-24 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=380) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=380) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=380) it.</sub>

2018-09-24 10:12 UTC, databus23 commented
/cc @afritzler @vlerenc @BugRoger

2018-09-24 12:25 UTC, rfranzke requested changes
Hi @databus23, wow, that was fast, thank you very much! Just found a small rendering problem, PTAL.

2018-09-24 12:25 UTC, rfranzke commented on charts/shoot-core/charts/calico/templates/config.yaml
> +  calico_backend: {{- if ne .Values.cloudProvider "azure" }}"bird"{{ else }}"none"{{ end }}
Can you remove the `-` please? The rendered result is:

```
  # Configure the Calico backend to use.
  calico_backend:"bird"
```

This configmap can't be applied to the cluster: `error: error converting YAML to JSON: yaml: line 15: could not find expected ':'`

2018-09-24 17:52 UTC, databus23 commented on charts/shoot-core/charts/calico/templates/config.yaml
> +  calico_backend: {{- if ne .Values.cloudProvider "azure" }}"bird"{{ else }}"none"{{ end }}
Thanks! Good catch.

2018-09-24 17:53 UTC, databus23 commented
Rebased. They CI seems to be napping atm.

2018-09-24 18:59 UTC, mvladev commented
Isn't `1500`  the default MTU value? https://docs.projectcalico.org/v3.2/usage/configuration/mtu

2018-09-24 19:03 UTC, vlerenc commented
Yes @mvladev, but it's not the right value for all infrastructures. We agreed to go with 1440 for now for all infrastructures, see https://github.com/gardener/gardener/issues/159.

2018-09-24 20:33 UTC, databus23 commented
@mvladev It might be programatically, but `1440` is what the official manifests are shipped with:
https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

Thats were I got it from. When scanning through the diffs I noticed that gardener uses `mtu: 1500` for the calico CNI config while `FELIX_IPINIPMTU` was set to `1440`. In the upstream manifests both values match. I'm not familiar with the networking setup I just wanted to point out that this PR aligns the chart with the upstream manifests (both values match).

2018-09-25 04:20 UTC, vlerenc commented
Yes, 1440 fits as lowest common denominator (see also GCP requirements). When we have completed the extensibility epic, it will become possible to tune it independently (per infrastructure), but for now we wanted to pick the lowest common denominator with #159, but even better if this PRs already deals with it.

2018-09-25 06:03 UTC, rfranzke approved these changes

2018-09-25 06:03 UTC, merged