Correct Shoot deletion flow
gardener/gardener pull request #386
Opened 2018-09-25 13:49 UTC by rfranzke

**What this PR does / why we need it**: Gardener needs to restart the components in the Seed which have information about the cloud provider secret (kube-controller-manager, cloud-controller-manager) because these components have to delete all the infrastructure resources they have created when the cluster shall be deleted.

This PR contains two improvements:

1. Gardener has already correctly refreshed the secret in the Seeds but it sometimes did accidentally restart the components although it was not necessary.
1. Gardener did neither wait nor check that the controllers are really active. We have often seen the case that Gardener did delete e.g., `Service`s whose delete event was not observed by the controllers. Now, we wait actively to be sure that the controllers are running before cleaning up the cluster.

PS: The only reason why we have to wait is that some Kubernetes objects don't have finalizers. We can remove this functionality once finalizers are implemented for at least all objects resulting in infrastructure artefacts.

**Release note**:
```improvement user
Gardener does now wait until all needed controllers are active before cleaning the Kubernetes resources when deleting a Shoot.
```

2018-09-25 14:26 UTC, adracus requested changes

2018-09-25 14:26 UTC, adracus commented on pkg/operation/botanist/waiter.go
> +					errorList = append(errorList, err)
This unsynchronized access to the errorList may cause race conditions, better use channels etc. here

2018-09-25 14:26 UTC, adracus commented on pkg/operation/botanist/waiter.go
> +			errorList = make([]error, 0, len(controllers))
use `multierror` instead of custom accumulation of errors

2018-09-25 14:26 UTC, adracus commented on pkg/operation/botanist/waiter.go
> +					readyControllers.Insert(controller.name)
What about the case we previously talked about (controller c1 is ready at t1 but then becomes unhealthy again at t2 while controller c2 is unhealthy at t1 and healthy at t2)? What are the semantics we want to enforce here? Do we want all controllers to be healthy after one iteration? If yes, then how about rather using channels + response objects to determine that all of them are ready other than writing into a non-goroutine scoped store (in this case the `sets.String`)

2018-09-25 15:02 UTC, rfranzke commented
Thanks @Adracus, we have addressed your suggestions. PTAL.

2018-09-25 16:14 UTC, adracus approved these changes
LGTM

2018-09-25 16:29 UTC, merged

2018-09-26 12:46 UTC, vlerenc commented
@rfranzke Or we finally do give up on "playing it nice" and ask the botanists to do proper cleanup. Kops, GKE, I guess most others simply delete everything in their way and don't care about the consequences. Our thoughtful/considerate approach may have been a strategic mistake (on my behalf).

2018-09-26 14:19 UTC, rfranzke commented
Maybe, but I'd say we shouldn't do it before the extensibility epic is finished, at least the infrastructure part.

2018-09-26 14:23 UTC, vlerenc commented
Yes, neither would I. We just might have to, if we can't contain the situation, but for now, let's not put more tasks in between were we stand now and where we want to be with the extensibility.