Refactor global-network-policies and control plane network policies into component
gardener/gardener pull request #3886
Opened 2021-04-16 14:40 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity quality robustness
/kind technical-debt test
/priority 3
/topology seed
/platform all
/exp intermediate

**What this PR does / why we need it**:
This PR refactors the deployment for the global and shoot control plane specific network policies. It adopts the component concept. Consequently, it eliminates the Helm chart and adds full unit tests, instead. This improves several aspects and the overall code quality.

**Which issue(s) this PR fixes**:
Part of #2754

/squash

**Release note**:

```improvement operator
NONE
```

2021-04-19 13:22 UTC, BeckerMax commented
/assign

2021-04-24 13:10 UTC, BeckerMax requested changes
Generally looks very good! When I tested it only the formating changed as mentioned in the comments.

Do you also plan to refactor the other netpols (i.e. in the shoot kubesystem ns)?

2021-04-24 13:10 UTC, BeckerMax commented on pkg/operation/botanist/component/networkpolicies/global.go
> +	transformers = append(transformers,
why not:
```
transformers := []networkPolicyTransformer{...,...}

2021-04-24 13:10 UTC, BeckerMax commented on pkg/operation/botanist/component/networkpolicies/global.go
> +					obj.Annotations = map[string]string{v1beta1constants.GardenerDescription: fmt.Sprintf("Allows Egress from pods labeled with '%s=%s' to CloudProvider's specific metadata service IP.", v1beta1cons
split line?

2021-04-24 13:10 UTC, BeckerMax commented on pkg/operation/botanist/component/networkpolicies/peers.go
> +// // `networks` and whose ipBlock.except points to `except`.
one `//` too much

2021-04-24 13:10 UTC, BeckerMax commented on pkg/operation/botanist/component/networkpolicies/bootstrap.go
> +var TimeoutWaitForManagedResource = 2 * time.Minute
I understand that you make this public for testing but it gives me a bad feeling. Shouldn't that be bound to a bootstrapper instance and not a public variable to avoid side effects?

2021-04-24 13:10 UTC, BeckerMax commented on pkg/operation/botanist/networkpolicies.go
> +	return NewNetworkPoliciesDeployer(
use networkpolicies.New() ?

2021-04-24 13:10 UTC, BeckerMax commented on pkg/operation/botanist/component/networkpolicies/global.go
> +					obj.Annotations = map[string]string{v1beta1constants.GardenerDescription: fmt.Sprintf("Allows Egress from pods labeled with '%s=%s' to the aggregate-prometheus.", v1beta1constants.LabelNetworkPo
Did you consider that the description annotation changed from formated with newlines to unformated:
```
  metadata:
    annotations:
      gardener.cloud/description: |
        Allows Egress from pods labeled with 'networking.gardener.cloud/to-public-networks=allowed'
        to all Public network IPs, except for
        - Private networks (RFC1918)
        - Carrier-grade NAT (RFC6598)

```
to
```
  metadata:
    annotations:
      gardener.cloud/description: Allows Egress from pods labeled with 'networking.gardener.cloud/to-public-networks=allowed'
        to all Public network IPs, except for (1) Private networks (RFC1918), (2)
        Carrier-grade NAT (RFC6598), (3) CloudProvider's specific metadata service

```
Unsure if this bothers someone. But wanted to ask if it was intentional.

2021-04-24 13:10 UTC, BeckerMax requested changes
Generally looks very good! When I tested it only the formating changed as mentioned in the comments.

Do you also plan to refactor the other netpols (i.e. in the shoot kubesystem ns)?

2021-04-24 13:43 UTC, rfranzke commented on pkg/operation/botanist/component/networkpolicies/bootstrap.go
> +var TimeoutWaitForManagedResource = 2 * time.Minute
Maybe, but this is how it’s done for all other components using `ManagedResource`s, so let’s keep it as is for now (the impact / potential for side effects seems quite low). Still, if we decide that we want/need to change it then let’s rather do it for all together.

2021-04-24 13:43 UTC, rfranzke commented on pkg/operation/botanist/networkpolicies.go
> +	return NewNetworkPoliciesDeployer(
The `NewNetworkPoliciesDeployer` is an alias for `networkpolicies.New`, see line 25. This is done for testing.

2021-04-24 13:43 UTC, rfranzke commented on pkg/operation/botanist/component/networkpolicies/global.go
> +					obj.Annotations = map[string]string{v1beta1constants.GardenerDescription: fmt.Sprintf("Allows Egress from pods labeled with '%s=%s' to the aggregate-prometheus.", v1beta1constants.LabelNetworkPo
I guess it doesn’t matter. The description is anyways applied in the seed (hence, only visible to operators). I consider it still perfectly readable. :)

2021-04-24 13:44 UTC, rfranzke commented
@BeckerMax Thanks for the review, I’ve addressed some of the suggestions with b3c2b78804b03ae9acf6d433f1f23314e2122336 and answered to some others. Please take another look :)

2021-04-24 16:56 UTC, BeckerMax commented on pkg/operation/botanist/component/networkpolicies/global.go
> +					obj.Annotations = map[string]string{v1beta1constants.GardenerDescription: fmt.Sprintf("Allows Egress from pods labeled with '%s=%s' to the aggregate-prometheus.", v1beta1constants.LabelNetworkPo
fine for me

2021-04-24 17:02 UTC, BeckerMax commented on pkg/operation/botanist/component/networkpolicies/bootstrap.go
> +var TimeoutWaitForManagedResource = 2 * time.Minute
ok, I can live with it right now as we only place to call this bootstrapper. A separate refactoring makes sense I think. Can put it on my list.

2021-04-24 17:20 UTC, BeckerMax commented
/lgtm

2021-04-24 17:20 UTC, BeckerMax approved these changes

2021-04-26 06:27 UTC, merged