Add envtest suite for Seed
gardener/gardener pull request #3904
Opened 2021-04-20 13:56 UTC by danielfoehrKn

**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:

Add an envtest setup for the Seed cluster, similar to the existing Garden cluster envtest suite.

Adds CRD's typically deployed during the SeedBootstrap
 - Gardener Extension CRDs (Worker, Infrastructure, ...)
 - Istio CRDs
 - VPA CRDs
 - HVPA CRD

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

Includes copied of the HVPA & VPA CRDs in the `resources` sub-directory as they contain helm-specific templating instructions in the `chart` folder.
Alternatively, these resources could also be rendered to a `temp` directory and then applied.

I wanted to use this functionality with PR #3893 to test the federated seed controller.

**Release note**:

```other operator

```

2021-04-21 06:42 UTC, rfranzke commented
Hm, why do we need this dedicated testenv for the seed? It's not quite similar to the garden - here, we need to run the `gardener-apiserver` in order to be able to create Gardener-managed resources.

For your use-case the standard testenv provided by ctrl-runtime can be used, or? It seems that you only want some helper functions that properly prepare the environment by installing the CRDs, etc.?

> Alternatively, these resources could also be rendered to a temp directory and then applied.

+1, let's try to not duplicate them if not really necessary. Also, you shouldn't need to render them to a temporary directory - couldn't you directly apply them?

2021-04-21 08:07 UTC, danielfoehrKn commented
> Hm, why do we need this dedicated testenv for the seed?

For reuse in tests that need a Seed cluster e.g for the federated seed controllers.

> For your use-case the standard testenv provided by ctrl-runtime can be used, or? It seems that you only want some helper functions that properly prepare the environment by installing the CRDs, etc.?

Yes, it is only a wrapper around ctrl-runtime envtest with installed CRDs. 

>  It seems that you only want some helper functions that properly prepare the environment by installing the CRDs, etc.?

Is this not a valid reason?

2021-04-21 08:13 UTC, rfranzke commented
OK, I was just wondering about the general approach to wrap the envtest entirely. Maybe it's simpler/good enough/less code to just define some helper functions in the `pkg/utils/test` package? I don't have a strong opinion, just wanted to chat about it, cc @timebertt who is much more into this.

2021-04-21 09:31 UTC, timebertt commented
/assign
Will take a look

2021-04-22 08:43 UTC, timebertt requested changes

2021-04-22 08:43 UTC, timebertt commented on pkg/envtest/seed/environment.go
> +	e.Environment.ErrorIfCRDPathMissing = true
I totally agree with @rfranzke. I don't think the wrapper brings any real value in comparison to some helper funcs.
The only "new" code in this wrapper is the few lines which determine the paths to the relevant CRDs.

Please extract this part into a helper func which can be called by test suites that want to test against some resources on a seed. The func can render CRDs if necessary (and not done upfront already) and return some paths or objects to apply.

2021-04-22 09:09 UTC, danielfoehrKn commented
/close as reviewers determined that it should instead by just a helper function

2021-04-22 09:09 UTC, closed without merging