Do not use hostport for konnectivity-server
gardener/gardener pull request #3997
Opened 2021-05-05 05:55 UTC by majst01

/area control-plane
/kind  bug

**What this PR does / why we need it**:
If APIServerSNI is not enabled, but a shoot has konnectivity-tunnel feature flag set, the kube-api-server in the shoot namespace can not start anymore with:

```
shoot--pz9cjf--...            15m         Warning   FailedScheduling               pod/kube-apiserver-6f5cb7d4f-7h8rh                                            0/3 nodes are available: 1 Insufficient cpu, 3 node(s) didn't have free ports for the requested pod ports

```
This is the case since g/g 1.16.x and was introduced with https://github.com/gardener/gardener/pull/3267

The Reason is that the konnectivity-server sidecar is started with hostport for admin and health endpoint, which only allows one kube-api-server to be started on one seed worker node.

2021-05-05 05:59 UTC, timuthy commented
/invite @MartinWeindel @DockToFuture

2021-05-05 07:14 UTC, rfranzke reviewed
/assign @ScheererJ @DockToFuture 
/invite  @ScheererJ @DockToFuture

2021-05-05 12:20 UTC, ScheererJ commented
@majst01 Could you please add corresponding changes also in `pkg/operation/botanist/component/konnectivity/konnectivity_server.go` (around line 262 and 280)? Those additional changes were necessary for me to make it run.

2021-05-05 12:21 UTC, ScheererJ requested changes
`pkg/operation/botanist/component/konnectivity/konnectivity_server.go` need to be adapted as well. Please also adapt the tests next to it as well.

2021-05-05 12:55 UTC, majst01 commented
> @majst01 Could you please add corresponding changes also in `pkg/operation/botanist/component/konnectivity/konnectivity_server.go` (around line 262 and 280)? Those additional changes were necessary for me to make it run.

Interestingly the deployments there differ from the chart, there are more ports configured as hostport. Changed all of them there

2021-05-05 13:07 UTC, ScheererJ approved these changes
/lgtm

2021-05-05 13:11 UTC, rfranzke approved these changes
/lgtm
/reviewed ok-to-test

2021-05-06 05:45 UTC, merged

2021-05-06 06:02 UTC, majst01 commented
Thanks guys, this was fast !