Disable etcd scale down for shoot clusters with purpose "production".
gardener/gardener pull request #4016
Opened 2021-05-10 14:07 UTC by amshuman-kr

**How to categorize this PR?**

/area control-plane cost
/kind postmortem

**What this PR does / why we need it**:

Disable etcd scale down for shoot clusters with purpose "production". This avoids multiple etcd restarts during the shoot's maintenance time window if VPA recommendation for scale down is inappropriate.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

cc @vlerenc @rfranzke @dguendisch 

**Release note**:

```other operator
Disable etcd scale down for shoot clusters with purpose "production". This avoids multiple etcd restarts during the shoot's maintenance time window if VPA recommendation for scale down is inappropriate.
```

2021-05-10 14:08 UTC, vlerenc commented
Thank you @amshuman-kr !

/cc @dguendisch

2021-05-10 14:52 UTC, amshuman-kr commented
The failing test case seems to be unrelated to the changes in this PR.
```
• Failure [26.150 seconds]
BackupBucket
/go/src/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/backupbucket_test.go:55
  should successfully create and delete a BackupBucket (respecting operation annotation) [It]
  /go/src/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/backupbucket_test.go:64

  Expected success, but got an error:
      <*errors.StatusError | 0xc0009f2280>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "etcdserver: request timed out",
              Reason: "",
              Details: nil,
              Code: 500,
          },
      }
      etcdserver: request timed out

  /go/src/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/backupbucket_test.go:200
------------------------------
STEP: running cleanup actions
STEP: delete backupbucket
STEP: delete secret
Failure [17.308 seconds]
[AfterSuite] AfterSuite 
/go/src/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/backupbucket_suite_test.go:68

  Expected success, but got an error:
      <*errors.StatusError | 0xc00120e500>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "secrets \"cloudprovider\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "cloudprovider",
                  Group: "",
                  Kind: "secrets",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      secrets "cloudprovider" not found

  /go/src/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/backupbucket_test.go:187
------------------------------


Summarizing 1 Failure:

[Fail] BackupBucket [It] should successfully create and delete a BackupBucket (respecting operation annotation) 
/go/src/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/backupbucket_test.go:200

Ran 2 of 2 Specs in 132.375 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped
```

2021-05-10 15:01 UTC, rfranzke requested changes

2021-05-10 15:01 UTC, rfranzke commented on pkg/operation/botanist/etcd.go
> +	}
Can you do this already in the `DefaultEtcd` function? Then you don't need to extend the interface with `GetHVPAConfig`?

2021-05-10 15:01 UTC, ialidzhikov commented
@amshuman-kr , could you please update `./docs/shoot_purposes.md` (the document that describes the behavioral differences between the Shoot purposes)?

2021-05-10 17:48 UTC, amshuman-kr commented
@rfranzke @ialidzhikov I have made the changes you suggested. Can you PTAL?

2021-05-11 06:16 UTC, rfranzke commented on pkg/operation/botanist/etcd.go
> +func (b *Botanist) DefaultEtcd(role string, class etcd.Class, purpose gardencorev1beta1.ShootPurpose) (etcd.Etcd, error) {
```suggestion
func (b *Botanist) DefaultEtcd(role string, class etcd.Class) (etcd.Etcd, error) {
```

2021-05-11 06:16 UTC, rfranzke commented on pkg/operation/botanist/etcd.go
> +	if class == etcd.ClassImportant && purpose == gardencorev1beta1.ShootPurposeProduction {
```suggestion
	if class == etcd.ClassImportant && b.Shoot.Purpose == gardencorev1beta1.ShootPurposeProduction {
```

2021-05-11 06:16 UTC, rfranzke commented on pkg/operation/botanist/etcd.go
> +	}
```suggestion
	}

```

2021-05-11 06:16 UTC, rfranzke commented on pkg/operation/botanist/component/etcd/etcd.go
> +			scaleDownUpdateMode = e.hvpaConfig.ScaleDownUpdateMode
Is this variable helpful? It seems `e.hvpaConfig.ScaleDownUpdateMode` can be used directly in line 427?

2021-05-11 06:16 UTC, rfranzke commented on pkg/operation/botanist/botanist.go
> +	o.Shoot.Components.ControlPlane.EtcdMain, err = b.DefaultEtcd(v1beta1constants.ETCDRoleMain, etcd.ClassImportant, o.Shoot.Purpose)
```suggestion
	o.Shoot.Components.ControlPlane.EtcdMain, err = b.DefaultEtcd(v1beta1constants.ETCDRoleMain, etcd.ClassImportant)
```

2021-05-11 06:16 UTC, rfranzke commented on pkg/operation/botanist/botanist.go
> +	o.Shoot.Components.ControlPlane.EtcdEvents, err = b.DefaultEtcd(v1beta1constants.ETCDRoleEvents, etcd.ClassNormal, o.Shoot.Purpose)
```suggestion
	o.Shoot.Components.ControlPlane.EtcdEvents, err = b.DefaultEtcd(v1beta1constants.ETCDRoleEvents, etcd.ClassNormal)
```

2021-05-11 06:40 UTC, amshuman-kr commented
/hold Accepted the suggested changes. Will unhold once I adapt the tests.

2021-05-11 06:59 UTC, amshuman-kr commented
/unhold

@rfranzke I have applied your suggestion, fixed the tests and squashed the commits. Can you please PTAL? Hopefully, one last time 😅

2021-05-11 07:02 UTC, rfranzke approved these changes
/lgtm

2021-05-11 08:41 UTC, merged