Added --external-hostname flag to the default kapi server config
gardener/gardener pull request #4067
Opened 2021-05-17 11:13 UTC by dimityrmirchev

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR adds the `--external-hostname` flag to the kube-api server configuration.
**Which issue(s) this PR fixes**:
Fixes #4023

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2021-05-17 11:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=4067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=4067) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=4067) it.</sub>

2021-05-17 11:15 UTC, dimityrmirchev commented
/assign @mvladev

2021-05-17 11:17 UTC, kris94 commented
/assign @mvladev

2021-05-17 12:11 UTC, vpnachev commented
/reviewed ok-to-test

2021-05-17 15:14 UTC, ialidzhikov commented
@dimityrmirchev , could you please add more details? 

The PR description currently: 

> This PR adds the --external-hostname flag to the kube-api server configuration.

I mean I can see this from the PR diff and this comment does not help much. Can you provider explanation how this change is helping to fix https://github.com/gardener/gardener/issues/4023?
Did you executed the corresponding failing tests against this change? Can you provider sample logs of successful `go test` run?

2021-05-18 04:36 UTC, rfranzke requested changes
I guess this won't play well together with provider extensions setting this flag via the `controlplane` mutator? See for example: https://github.com/gardener/gardener-extension-provider-azure/blob/197488d2a032ad7a83e908c6094524a6e65e8164/pkg/webhook/controlplaneexposure/ensurer.go#L97

2021-05-18 04:44 UTC, mvladev commented
> I guess this won't play well together with provider extensions setting this flag via the `controlplane` mutator? See for example: https://github.com/gardener/gardener-extension-provider-azure/blob/197488d2a032ad7a83e908c6094524a6e65e8164/pkg/webhook/controlplaneexposure/ensurer.go#L97

This is something that needs to fixed in the azure extension provider. I don't see any reason to block the PR?

2021-05-18 04:49 UTC, rfranzke commented
@mvladev I just want to clarify the consequences if this PR was merged (wrt compatibility/functionality). Is there anything that needs to be taken care of? Particularly, what does it mean for provider extensions (like Azure) if they no longer overwrite this flag in the future (I assume this is the plan)? Basically, similar to https://github.com/gardener/gardener/pull/4067#issuecomment-842407842, more information about this change is required.

2021-05-18 08:13 UTC, dimityrmirchev commented
@ialidzhikov @rfranzke I updated the PR description with some additional info and test execution logs.

2021-05-19 07:16 UTC, ialidzhikov commented
> I guess this won't play well together with provider extensions setting this flag via the `controlplane` mutator? See for example: https://github.com/gardener/gardener-extension-provider-azure/blob/197488d2a032ad7a83e908c6094524a6e65e8164/pkg/webhook/controlplaneexposure/ensurer.go#L97

Nice catch. As far as I see the azure `controlplane` mutator is setting this `--external-hostname` flag to the kube-apiserver Service `.status.loadBalancer.ingress[].(hostname|ip)`. On the other side this PR sets the flag to the internal or external apiserver domain. So there is a behavioural difference.
`extensionswebhook.EnsureStringWithPrefix` func can override the flag value if the flag already exists. So if the azure `controlplane` mutator needs to give a different value to this flag, then I think this is already in place today. 
The part I am missing is why only azure `controlplane` sets/overrides this flag? If it really needs to do it, then I think it should be fine with the already existing handling in `extensionswebhook.EnsureStringWithPrefix`. So if the azure `controlplane` needs to override this flag because of a special handling, then I don't see any required adaptations on extesnions side and this PR should be ok from compatibility/functionality perspective. WDYT?

2021-05-19 07:29 UTC, rfranzke commented
> The part I am missing is why only azure controlplane sets/overrides this flag?

I don't know, honestly. I think these two flags were added as part of the initial Azure support contribution by @dkistner @AndreasBurger more than `4y` back. Maybe they can tell. However, I suspect that we might not need this anymore, meanwhile, and can remove it from the Azure extension. Just a guess, though.

> If it really needs to do it, then I think it should be fine with the already existing handling in extensionswebhook.EnsureStringWithPrefix. So if the azure controlplane needs to override this flag because of a special handling, then I don't see any required adaptations on extesnions side and this PR should be ok from compatibility/functionality perspective. WDYT?

Hm, is it? What about the currently failing conformance test (https://github.com/kubernetes/kubernetes/blob/v1.21.0/test/e2e/auth/service_accounts.go#L683)? Will it already work with the current implementation fo Azure?

2021-05-19 07:32 UTC, vpnachev commented
> , I suspect that we might not need this anymore, meanwhile, and can remove it from the Azure extension. Just a guess, though.

By the way, with `APISeverSNI=true` the `kube-apiserver` service is of type `ClusterIP` and there is no `.status.loadBalancer.ingress[]`, so the `--external-hostname=` is not set at all by the extension.

2021-05-19 07:33 UTC, ialidzhikov commented
> I don't know, honestly. I think these two flags were added as part of the initial Azure support contribution by @dkistner @AndreasBurger more than 4y back. Maybe they can tell. However, I suspect that we might not need this anymore, meanwhile, and can remove it from the Azure extension. Just a guess, though.

@dkistner , @AndreasBurger I would appreciate if you can comment on this question and do a follow-up (i.e clean up this flag) if it is no longer required.

> Hm, is it? What about the currently failing conformance test (https://github.com/kubernetes/kubernetes/blob/v1.21.0/test/e2e/auth/service_accounts.go#L683)? Will it already work with the current implementation fo Azure?

Let's first see the reply from @dkistner and @AndreasBurger . If we no longer need the flag, then this question will be obsolete.

2021-05-19 11:37 UTC, dkistner commented
Actually I do not recall why we needed the `--external-hostname` flag. But like @vpnachev said with `APISeverSNI=true` it is not set and there are afaik no known issues. So I assume it is not required anymore. I will file a PR to remove it.
cc @AndreasBurger

2021-05-21 05:40 UTC, rfranzke approved these changes
/lgtm
/invite @ialidzhikov @dkistner

2021-05-21 06:34 UTC, ialidzhikov approved these changes
/lgtm

2021-05-21 06:58 UTC, dkistner approved these changes
/lgtm

2021-05-21 06:59 UTC, merged