Add a new metric for coredns and extend coredns dashboard
gardener/gardener pull request #4115
Opened 2021-05-27 09:02 UTC by DockToFuture

Co-authored-by: johannes scheerer <johannes.scheerer@sap.com>

**How to categorize this PR?**

  /area networking
  /area monitoring
 /kind enhancement

**What this PR does / why we need it**:
Add a new metric for coredns and extend coredns dashboard

**Special notes for your reviewer**:

**Release note**:

```other operator
none
```

2021-05-27 09:02 UTC, DockToFuture commented
/cc: @wyb1

2021-05-27 12:37 UTC, rfranzke commented
/invite @wyb1 @istvanballok

2021-05-27 13:31 UTC, wyb1 commented
Please add a screenshot of the updated dashboard to the PR description.

2021-05-27 13:35 UTC, wyb1 requested changes
Some of the panels do not have data for me. The panels with missing data do not have a regex to match the variable. Make sure that all panels are using regex.

```
{pod=~"$pod"}
```

2021-05-27 14:11 UTC, DockToFuture commented
I've updated the PR and added the screenshots.

2021-05-28 09:50 UTC, DockToFuture commented
I've also added a regex to filter only for `coredns` pods since we also want to add a dashboard for node-local-dns in the future.

2021-05-31 08:00 UTC, wyb1 requested changes
> I've also added a regex to filter only for coredns pods since we also want to add a dashboard for node-local-dns in the future.

Thanks! Let's keep it like this for now since the dashboard is called `CoreDNS`. 

Note for the future: We could also consider removing the regex and then it would be possible to select interesting `CoreDNS`pods, `node-local` pods or a combination of both. However, this will become cumbersome if there is a large number of nodes. I have some ideas on how we can do this in an elegant way, but let's discuss it when we iterate over this dashboard again.

I see that you've added a panel for the rate of cache hits and misses. Please make it clear that one panel is a rate and the other is the real number of hits/misses. You can add a unit or add it to the title.

![image](https://user-images.githubusercontent.com/8710621/120160446-8c022b00-c1f6-11eb-9770-b0d65aa16f6f.png)

2021-05-31 08:25 UTC, DockToFuture commented
We haven't added a panel for the rate of cache hits and misses. It was already there. We would also like to keep the regex, since it is a nice way of only showing the relevant pods, which we would like to see here in the dashboard.

2021-05-31 08:50 UTC, DockToFuture commented
The units were added.

2021-05-31 08:54 UTC, wyb1 approved these changes
/lgtm

2021-06-01 08:23 UTC, rfranzke approved these changes
/lgtm
/accepted

2021-06-01 08:24 UTC, merged