[WIP] Delete project resources if the corresponding namespace is missing
gardener/gardener pull request #416
Opened 2018-10-04 08:24 UTC by rfranzke

**What this PR does / why we need it**: The project controller does now delete stale `Project` resources (i.e., those without a corresponding `Namespace` object).

**Which issue(s) this PR fixes**:
Fixes #409 

**Release note**:

```improvement user
If a `Project` resource exists without the corresponding `Namespace` then Gardener will delete it.
```

2018-10-04 08:57 UTC, mvladev requested changes
This breaks the entire contract - the idea for the `Project` resource is to control the `Namespaces` and `(Cluster)RoleBindings`.

It's like when a `ReplicaSet` is removed, the deployment controller to remove a `Deployment`

2018-10-04 09:12 UTC, timuthy approved these changes

2018-10-04 09:15 UTC, rfranzke commented
There is an admission controller which is responsible for creating the namespace on project creation. If a project exists without the namespace then the namespace was deleted at the same time the project got created (race condition, see #409). In the normal case (no race) the namespace deletion is prevent by the webhook.

2018-10-04 09:35 UTC, mvladev commented
> There is an admission controller which is responsible for creating the namespace on project creation. If a project exists without the namespace then the namespace was deleted at the same time the project got created (race condition, see #409). In the normal case (no race) the namespace deletion is prevent by the webhook.

The project [admission controller](https://github.com/gardener/gardener/blob/21c17b3de227ae6e00c5caa5b58a1bf85d1b90aa/plugin/pkg/project/namespace/admission.go#L170-L177) should not create namespaces in the first place - this is what the project controller in the gardener controller manager (should be) is responsible for.

2018-10-04 10:09 UTC, mvladev commented
To put it simply - in an admission controller, only the resource which is being admitted SHOULD be modified (if mutation is required). No side-effects.

Otherwise if down the admission chain another admission controller rejects this resource it'll leave the system in inconsistent state.

2018-10-04 10:18 UTC, Adracus commented on pkg/controller/project/project_control.go
> +			return c.k8sGardenClient.GardenClientset().GardenV1beta1().Projects().Delete(project.Name, &metav1.DeleteOptions{})
Don't we need the deletion confirmation annotation here?

2018-10-08 07:36 UTC, rfranzke commented
FYI: Postponed until a sync with the dashboard team next week about the `Project` resources in general.

2018-10-24 20:06 UTC, rfranzke commented
Closed in favour of #480.

2018-10-24 20:06 UTC, closed without merging