Fixed bug in node local dns implementation.
gardener/gardener pull request #4168
Opened 2021-06-07 08:21 UTC by ScheererJ

The networking policy in the seed need to refer to the dns server of the seed.

Co-authored-by: Sebastian Stauch <sebastian.stauch@sap.com>

**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
This is one step to getting node local dns ready for actual use.

**Which issue(s) this PR fixes**:
The networking policy in the seed need to refer to the dns server of the seed instead of the dns server of the shoot.

**Special notes for your reviewer**:

**Release note**:

```other operator
None
```

2021-06-07 10:19 UTC, timuthy approved these changes, later dismissed
/lgtm

2021-06-07 10:20 UTC, timuthy commented
Can you add a release note about this bug fix?

2021-06-07 10:58 UTC, ScheererJ commented
Added release note.

2021-06-07 14:43 UTC, rfranzke requested changes
Nit suggestions in the variable naming, but please fix the unit tests

2021-06-07 14:43 UTC, rfranzke commented on pkg/operation/botanist/networkpolicies.go
> +	seedCoreDNS, err := common.ComputeOffsetIP(seedSvc, 10)
```suggestion
	seedDNSServerAddress, err := common.ComputeOffsetIP(seedSvc, 10)
```

2021-06-07 14:43 UTC, rfranzke commented on pkg/operation/botanist/networkpolicies.go
> +	_, seedSvc, err := net.ParseCIDR(b.Seed.Info.Spec.Networks.Services)
```suggestion
	_, seedServiceCIDR, err := net.ParseCIDR(b.Seed.Info.Spec.Networks.Services)
```

2021-06-07 14:52 UTC, ScheererJ commented on pkg/operation/botanist/networkpolicies.go
> +	seedCoreDNS, err := common.ComputeOffsetIP(seedSvc, 10)
Adapted with latest commit.

2021-06-07 14:52 UTC, ScheererJ commented on pkg/operation/botanist/networkpolicies.go
> +	_, seedSvc, err := net.ParseCIDR(b.Seed.Info.Spec.Networks.Services)
Adapted with latest commit.

2021-06-08 04:19 UTC, rfranzke reviewed
Thanks, still, the unit tests need to be fixed.

2021-06-08 07:05 UTC, ScheererJ commented
Tests have been adapted as well.

2021-06-08 07:07 UTC, rfranzke approved these changes
/lgtm

2021-06-08 07:10 UTC, timuthy approved these changes

2021-06-08 07:49 UTC, merged