Enh/stable worker hash
gardener/gardener pull request #4237
Opened 2021-06-21 14:21 UTC by voelzmo

**How to categorize this PR?**
 /kind enhancement

**What this PR does / why we need it**:
Exclude cri.name `docker` from worker hash calculation

Worker pools with `CRI==nil` use `docker` as their container runtime. Changing to an explicit configuration of `docker` should not trigger a node rollout. Therefore, we need to keep the Worker hash stable by excluding the `cri.name` property from hash calculation in this case.

Part of #4110

**Special notes for your reviewer**:
Marked as draft as it depends on #4218 .

**Release note**:
```other operator
Do not trigger a node rollout when switching from `CRI.Name==nil` to `CRI.Name==docker`.
```

cc @BeckerMax

2021-06-23 15:22 UTC, rfranzke commented on extensions/pkg/controller/worker/machines.go
> +	"github.com/gardener/gardener/pkg/apis/core/v1beta1"
```suggestion
	gardencorev1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
```

2021-06-24 12:52 UTC, vpnachev requested changes
Just a small improvement to avoid one nested if block.

2021-06-24 12:52 UTC, vpnachev commented on extensions/pkg/controller/worker/machines.go
> +				}
```suggestion
			if w.CRI != nil && w.CRI.Name != gardencorev1beta1.CRINameDocker {
```

2021-06-25 14:01 UTC, voelzmo commented on extensions/pkg/controller/worker/machines.go
> +				}
done

2021-06-25 14:03 UTC, vpnachev approved these changes
/lgtm
/squash

2021-06-25 14:48 UTC, merged