Add docs for monitoring connectivity
gardener/gardener pull request #4296
Opened 2021-07-01 11:05 UTC by wyb1

**How to categorize this PR?**

/area monitoring
/kind documentation

**What this PR does / why we need it**:

Add some documentation for the difference between seed and shoot connectivity.

![image](https://user-images.githubusercontent.com/8710621/124114453-e1875d00-da6c-11eb-8416-54cdc4e2a4e6.png)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2021-07-01 13:21 UTC, dguendisch requested changes
only nit, thanks for adding the doc

2021-07-01 13:21 UTC, dguendisch commented on docs/monitoring/connectivity.md
> +In addition to the shoot connectivity, we also measure the seed connectivty. This means trying to reach the API Server from the seed via its load balancer. The connectivity is also displayed in the a
```suggestion
In addition to the shoot connectivity, we also measure the seed connectivity. This means trying to reach the API Server from the seed via its load balancer. The connectivity is also displayed in the above panel as the `seed` line. Both `seed` and `shoot` connectivity are shown below.
```

2021-07-02 07:11 UTC, wyb1 commented on docs/monitoring/connectivity.md
> +In addition to the shoot connectivity, we also measure the seed connectivty. This means trying to reach the API Server from the seed via its load balancer. The connectivity is also displayed in the a
Thanks! Fixed!

2021-07-02 10:32 UTC, dguendisch submitted a review, later dismissed
/lgtm

2021-07-05 15:11 UTC, vpnachev submitted a review, later dismissed
/lgtm

2021-07-06 07:00 UTC, rfranzke reviewed
Can you please extend the index (https://github.com/gardener/gardener/blob/master/docs/README.md#monitoring)?

2021-07-08 08:50 UTC, rfranzke approved these changes

2021-07-08 08:50 UTC, merged