Refactoring unit tests for the project activity controller
gardener/gardener pull request #4485
Opened 2021-08-10 07:33 UTC by kris94

**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
The unit tests of the `Project Activity Controller` are refactored as suggested in the last comments from [PR 4447](https://github.com/gardener/gardener/pull/4447).
Also, the documentation is fixed to follow the semantics. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2021-08-10 07:39 UTC, kris94 commented
/invite @vpnachev

2021-08-17 12:18 UTC, ialidzhikov requested changes

2021-08-17 12:18 UTC, ialidzhikov commented on pkg/controllermanager/controller/project/project_activity_control_test.go
> +			fmt.Printf("%v", project.Status)
Looks like a leftover.

```suggestion
```

2021-08-17 12:18 UTC, ialidzhikov commented on pkg/controllermanager/controller/project/project_activity_control_test.go
> +		It("Should update the creation timestamp", func() {
```suggestion
		It("should update the creation timestamp", func() {
```

You can use lowercase everywhere.

2021-08-17 12:18 UTC, ialidzhikov commented on pkg/controllermanager/controller/project/project_activity_control_test.go
> +			_, result := reconciler.Reconcile(ctx, request)
```suggestion
			_, err := reconciler.Reconcile(ctx, request)
```

2021-08-17 12:18 UTC, ialidzhikov commented on pkg/controllermanager/controller/project/project_activity_control_test.go
> +			Expect(result).To(Succeed())
```suggestion
			Expect(err).ToNot(HaveOccurred())
```

2021-08-17 12:18 UTC, ialidzhikov commented on pkg/controllermanager/controller/project/project_activity_control_test.go
> +		It("Should NOT update the creation timestamp since the shoot is created before the last activity", func() {
```suggestion
		It("should not update the creation timestamp since the shoot is created before the last activity", func() {
```

2021-08-17 12:18 UTC, ialidzhikov commented on pkg/controllermanager/controller/project/project_activity_control_test.go
> +			Expect(result).To(Succeed())
```suggestion
			_, err := reconciler.Reconcile(ctx, request)
			Expect(err).ToNot(HaveOccurred())
```

2021-08-17 13:23 UTC, ialidzhikov submitted a review, later dismissed
/lgtm

2021-08-17 18:21 UTC, vpnachev commented on pkg/controllermanager/controller/project/project_activity_control_test.go
> +		})
This test should not be in the group `Unsuccessful reconciles due to different errors`.

2021-08-18 08:45 UTC, vpnachev approved these changes
/lgtm

2021-08-18 10:42 UTC, merged