Fixed broken relative links
gardener/gardener pull request #4571
Opened 2021-08-27 13:03 UTC by n-boshnakov

**What this PR does / why we need it**:
This PR fixes the broken relative links found in the external Gardener website.
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

2021-08-27 13:03 UTC, n-boshnakov commented
/review @Kristian-ZH

2021-08-27 13:06 UTC, Kristian-ZH approved these changes

2021-08-27 13:10 UTC, Kristian-ZH requested changes

2021-08-27 13:10 UTC, Kristian-ZH commented on docs/deployment/aks.md
> +([`example/30-cloudprofile-azure.yaml`](../../example/30-cloudprofile.yaml)):
```suggestion
([`example/30-cloudprofile.yaml`](../../example/30-cloudprofile.yaml)):
```

2021-08-27 13:10 UTC, Kristian-ZH commented on docs/deployment/aks.md
> +[`example/40-secret-seed-azure.yaml`](../../example/40-secret-seed.yaml)
```suggestion
[`example/40-secret-seed.yaml`](../../example/40-secret-seed.yaml)
```

2021-08-27 13:10 UTC, Kristian-ZH commented on docs/deployment/aks.md
> +[`example/50-seed-azure.yaml`](../../example/50-seed.yaml) file and
```suggestion
[`example/50-seed.yaml`](../../example/50-seed.yaml) file and
```

2021-08-27 13:10 UTC, Kristian-ZH commented on docs/deployment/aks.md
> +[`example/40-secret-seed-azure.yaml`](../../example/40-secret-seed.yaml),
```suggestion
[`example/40-secret-seed.yaml`](../../example/40-secret-seed.yaml),
```

2021-08-27 13:10 UTC, Kristian-ZH commented on docs/deployment/aks.md
> +[`example/70-secret-cloudprovider-azure.yaml`](../../example/70-secret-cloudprovider.yaml)
```suggestion
[`example/70-secret-cloudprovider.yaml`](../../example/70-secret-cloudprovider.yaml)
```

2021-08-27 13:10 UTC, Kristian-ZH commented on docs/deployment/aks.md
> +([`example/80-secretbinding-cloudprovider-azure.yaml`](../../example/80-secretbinding-cloudprovider.yaml)):
```suggestion
([`example/80-secretbinding-cloudprovider.yaml`](../../example/80-secretbinding-cloudprovider.yaml)):
```

2021-08-27 13:10 UTC, Kristian-ZH commented on docs/deployment/aks.md
> +Update the fields in [`example/90-deprecated-shoot-azure.yaml`](../../example/90-deprecated-shoot.yaml):
```suggestion
Update the fields in [`example/90-deprecated-shoot.yaml`](../../example/90-deprecated-shoot.yaml):
```

2021-08-30 11:43 UTC, rfranzke reviewed
Honestly, I think we can delete this `aks.md` document entirely. It is heavily outdated and obviously not in-use.

2021-08-31 08:48 UTC, n-boshnakov commented
> Honestly, I think we can delete this `aks.md` document entirely. It is heavily outdated and obviously not in-use.

File was deleted in the [Deleted aks.md file](https://github.com/gardener/gardener/pull/4571/commits/de433c99ba71e0c2f16d7144967bdc50b39b71fc) commit.

2021-08-31 09:03 UTC, rfranzke requested changes
Please also delete it from here:
https://github.com/gardener/gardener/blob/master/docs/README.md#deployment

/squash

2021-08-31 09:44 UTC, n-boshnakov commented
> Please also delete it from here:
> https://github.com/gardener/gardener/blob/master/docs/README.md#deployment
> 
> /squash

Removed reference to AKS in [Removed reference to deleted file](https://github.com/gardener/gardener/pull/4571/commits/e35e6c8c085f728d71da381f237df49a8e8d1274).

2021-08-31 11:46 UTC, rfranzke approved these changes
/lgtm
/reviewed ok-to-test

2021-09-01 06:42 UTC, merged