Add metrics/v1beta1 types to shoot scheme
gardener/gardener pull request #4602
Opened 2021-09-02 15:31 UTC by stoyanr

**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
Adds `metrics/v1beta1` types to shoot scheme to prevent integration test failures such as:
```
no kind is registered for the type v1beta1.PodMetrics in scheme "pkg/client/kubernetes/types.go:56"
```

For reference, the `metricsv1beta1.PodMetrics` type is used in https://github.com/gardener/gardener/blob/2d32009b705de07803f66e95f52bdb61dabddee9/test/integration/shoots/applications/metrics.go#L87-L88.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2021-09-02 15:33 UTC, stoyanr commented
/invite @timebertt This might be related to #4592 since this file was changed by that PR as well.

2021-09-02 15:43 UTC, timuthy requested changes
/lgtm

2021-09-02 15:43 UTC, timuthy approved these changes

2021-09-03 06:10 UTC, timebertt approved these changes
> This might be related to #4592 since this file was changed by that PR as well.

Indeed, I missed to add the metrics scheme required by the integration tests to the shoot scheme when switching over to that: https://github.com/gardener/gardener/pull/4592/commits/cf92b85bf1ca15f1f52f68dc86b9353f99fe6750#diff-f5d5a6d7e4db503e8ffdc9ae65d843302002604b50b6505de24bce6f7205718eL219

Sorry for that and thanks for fixing!
/lgtm

2021-09-03 06:39 UTC, merged