Add goleak where applicable, fix one more goroutine leak
gardener/gardener pull request #4641
Opened 2021-09-10 14:00 UTC by timebertt

**How to categorize this PR?**

/area robustness quality
/kind bugfix

**What this PR does / why we need it**:

Follow up on https://github.com/gardener/gardener/pull/4628 and https://github.com/gardener/gardener/issues/4609#issuecomment-915223191:
- add goleak verification to unit test suites that test code with concurrency (i.e. that start goroutines)
  - unfortunately we are lacking unit tests for some concurrent functions
  - goleak should be used in all new unit tests for concurrent functions from now on
- add a unit test for `flow.ParallelExitOnError` which can currently leak goroutines (the leak has been present since introduction of the func in https://github.com/gardener/gardener/commit/6c7da31077068a51aa752e4daa3a0136d5535a41)
- fix the goroutine leak in `flow.ParallelExitOnError`

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/4609

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Another memory leak in gardenlet has been fixed.
```

2021-09-10 14:06 UTC, rfranzke reviewed
/invite @BeckerMax 
/assign @BeckerMax

2021-09-10 14:07 UTC, rfranzke commented
/squash

2021-09-14 07:18 UTC, vpnachev reviewed
Some minor nits from my side

2021-09-14 07:18 UTC, vpnachev commented on pkg/client/kubernetes/cache/cache.go
> +	// There is no way of waiting for caches to stop, so we there's no point in waiting for the following
```suggestion
	// There is no way of waiting for caches to stop, so there's no point in waiting for the following
```

2021-09-14 07:18 UTC, vpnachev commented on pkg/healthz/periodic_test.go
>  				p.Start()
It should be stopped not be fore it is started, isn't it?
```suggestion
				p.Start()
				defer p.Stop()

```

2021-09-14 07:59 UTC, BeckerMax requested changes
just a nit and one question to your comment.
Overall the test support for parallel functions is super awesome! I also executed the unit tests with the leak included and the error message of the failed test was very readable 👍🏼

2021-09-14 07:59 UTC, BeckerMax commented on pkg/utils/flow/taskfn_test.go
> +		It("should execute the functions in parallel", func() {
we don't really test whether they are executed in parallel, or? Just wether they all get executed(sequentially or parallel).

2021-09-14 07:59 UTC, BeckerMax commented on pkg/client/kubernetes/cache/cache.go
> +	// NB: this function might leak goroutines, when the context for this aggregator cache is cancelled.
What means `NB` ?

2021-09-14 07:59 UTC, BeckerMax commented on pkg/client/kubernetes/cache/cache.go
> +	// NB: this function might leak goroutines, when the context for this aggregator cache is cancelled.
sorry I can't follow. The cache gets the aggregator context passed through - so if the context gets cancelled also the caches should stop, right?

2021-09-14 11:57 UTC, timebertt commented on pkg/utils/flow/taskfn_test.go
> +		It("should execute the functions in parallel", func() {
True. I improved both tests for `Parallel` and `ParallelExitOnError` to actually test parallelism.

2021-09-14 12:00 UTC, timebertt commented on pkg/client/kubernetes/cache/cache.go
> +	// NB: this function might leak goroutines, when the context for this aggregator cache is cancelled.
> What means `NB` ?

["nota bene"](https://github.com/gardener/gardener/pull/4641#discussion_r707967153)

> The cache gets the aggregator context passed through - so if the context gets cancelled also the caches should stop, right?

Yes, that's true. However, the cache implementation doesn't wait for the caches to actually be stopped. `Start` immediately returns once the context is cancelled (so the caches might actually still be running in the background): https://github.com/gardener/gardener/blob/6806495376b1de8b760b10cf5bc5cf9445f30b06/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go#L66-L72

2021-09-14 12:03 UTC, timebertt commented
Thank you @vpnachev @BeckerMax for your feedback! I improved the tests accordingly.
PTAL :)

2021-09-14 12:48 UTC, vpnachev commented
/lgtm
/needs second-opinion

2021-09-16 07:30 UTC, BeckerMax commented
/lgtm

2021-09-16 07:30 UTC, BeckerMax approved these changes, later dismissed

2021-09-16 08:15 UTC, rfranzke commented
/assign @vpnachev for milestone

2021-09-17 21:16 UTC, vpnachev approved these changes
/lgtm

2021-09-17 21:40 UTC, merged