Add Etcd validation
gardener/gardener pull request #4664
Opened 2021-09-14 13:37 UTC by vanjiii

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Include the Etcd validation into the webhook for extension resources.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer:**
Currently it uses etcd-druid dependency from `github.com/vanjiii/etcd-druid` fork due to newly introduce logic there. After https://github.com/gardener/etcd-druid/pull/230 is merged this PR will be updated and ready for merging.

2021-09-14 13:49 UTC, vanjiii commented
/cc @stoyanr

2021-09-17 10:42 UTC, stoyanr approved these changes, later dismissed
/lgtm
/hold Until the gardener `etcd-druid` (instead of the fork) is vendored.

In case you haven't done it, I would recommend testing an actual reconciliation of a shoot with changed gardenlet code to deliberately generate wrong store prefixes in `Etcd` resources, to check if the validation would actually fail in such cases and prevent the shoot from being reconciled.

2021-09-17 10:43 UTC, stoyanr commented
/squash

2021-09-23 16:17 UTC, stoyanr commented
Found two issues while testing this PR:
* The `etcds` resource is missing in the corresponding `validatingwebhookconfiguration`.
* The group / version of the `etcd` resource returned by the `gvr` function in `admission.go` are also wrong.

2021-09-23 16:18 UTC, stoyanr requested changes

2021-09-23 16:18 UTC, stoyanr commented on pkg/seedadmissioncontroller/webhooks/admission/extensionresources/admission.go
> +		gvr("etcds"): {
This function will return the wrong resource group and version, you could create e.g. `gvrDruid` to return the correct ones.

2021-09-23 16:42 UTC, stoyanr commented
Please also move the line:
```
h.logger.Info("Invalid extension resource detected", "operation", request.Operation, "error", err.Error())
```
before the if statement that currently contains it. It would then be possible to spot validation issues by analysing logs even if `--allow-invalid-extension-resources` is `false`.

2021-09-24 12:07 UTC, stoyanr requested changes
Please adjust https://github.com/gardener/gardener/blob/38ad556a7dec689b35c3ee6dd3cf59bd64b5c705/pkg/operation/botanist/component/seedadmissioncontroller/seedadmissioncontroller.go#L399-L419

2021-09-24 12:07 UTC, stoyanr commented on pkg/seedadmissioncontroller/webhooks/admission/extensionresources/admission.go
> +		gvr("etcds", gvrWithGroup(druidv1alpha1.GroupVersion.Group)): {
You must set both the group and version to `druidv1alpha1.GroupVersion.Group` and `druidv1alpha1.GroupVersion.Version`. Yes, the version happens to be `v1alpha1` in both cases, but this is accidental and should not be relied upon.

Though I have no strong objections, I am not a big fan of the options approach in this case. I think using a function such as `gvrDruid` is simpler and therefore better.

2021-09-24 12:07 UTC, stoyanr commented on example/seed-admission-controller/10-validatingwebhookconfiguration.yaml
> +      - druid.gardener.cloud
This must be a separate rule with only `etcds` as resource.

2021-09-24 15:51 UTC, stoyanr reviewed
/lgtm
Can be approved and merged once `gardener/etcd-druid` is properly vendored.

2021-10-06 15:14 UTC, stoyanr approved these changes
/lgtm

From my perspective this could be merged now. Thanks!

2021-10-07 10:37 UTC, rfranzke approved these changes

2021-10-07 10:38 UTC, rfranzke commented
/unhold

2021-10-07 10:38 UTC, merged