Support for Kubernetes v1.12
gardener/gardener pull request #474
Opened 2018-10-23 06:48 UTC by rfranzke

**What this PR does / why we need it**: Support of Kubernetes v1.12

**Which issue(s) this PR fixes**:
Fixes #400 

**Special notes for your reviewer**: I have successfully validated the functionality for all cloud providers and all older versions:
- :white_check_mark: Reconcile old clusters in all versions (1.9, 1.10, 1.11) with this branch
- :white_check_mark: Create new clusters with versions < 1.12
- :white_check_mark: Create new clusters with version  = 1.12
- :white_check_mark: Upgrade old clusters from version 1.11 to version 1.12
- :white_check_mark: Delete clusters with versions < 1.12
- :white_check_mark: Delete clusters with version  = 1.12

**Release note**:

```noteworthy user
Gardener does now support Shoot clusters with Kubernetes version 1.12 (beginning with 1.12.1; [further details](https://github.com/gardener/gardener/blob/master/docs/usage/supported_k8s_versions.md)). You should consider the [Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md) before upgrading to 1.12. 
```

2018-10-23 09:17 UTC, mvladev commented
/lgtm

Just one thing which can be fixed in a subsequent PR - `kube-controller-manager` and `cloud-controller-manager` are still serving `HTTP`. There is a hidden (since 1.9) flag `--port`.
This needs to be fixed in Prometheus as well.

2018-10-23 09:19 UTC, rfranzke commented
You mean that we should configure CCM and KCM with `--port=1025X`?
What needs to be fixed in Prometheus? You mean that it is no longer using the insecure port but the secure port?

2018-10-23 09:59 UTC, mvladev commented
> You mean that we should configure CCM and KCM with --port=1025X?

No in a later PR this flag should be set to `--port=0` to disable `HTTP` serving.

> What needs to be fixed in Prometheus? You mean that it is no longer using the insecure port but the secure port?

For K8S >= 1.12, Prometheus should use the `HTTPS` port and also `client-cert` for scraping `/metrics` on both `CCM` and `KCM`.

Again - this should be done in a separate PR.

2018-10-23 10:45 UTC, rfranzke commented
Thanks @mvladev, I opened https://github.com/gardener/gardener/issues/476 to keep track of the Prometheus change.

2018-10-23 13:59 UTC, timuthy requested changes

2018-10-23 13:59 UTC, timuthy commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +				<-ctx.Done()
The executed run method already waits for `ctx chan` to be closed.

2018-10-23 13:59 UTC, timuthy commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +	go run(ctx)
What's the reason we execute the `run` method in a Go routine? It causes the method to exit not gracefully any more.

2018-10-23 13:59 UTC, timuthy commented on hack/templates/resources/90-shoot.yaml.tpl
> +  #     usernameClaim: username-claim
`usernameClaim` seems to be duplicated now (see line 234). Is there any reason?

2018-10-23 13:59 UTC, timuthy commented on hack/templates/resources/90-shoot.yaml.tpl
> +  #     usernamePrefix: username-prefix
`usernamePrefix` seems to be duplicated now (see line 235). Is there any reason?

2018-10-23 13:59 UTC, timuthy commented on hack/templates/resources/90-shoot.yaml.tpl
>    #     signingAlgs: RS256,some-other-algorithm
Can be removed since it's already in line 229?

2018-10-23 13:59 UTC, timuthy commented on pkg/apis/garden/validation/validation.go
> +					allErrs = append(allErrs, field.Invalid(fldPath.Child("initialReadinessDelay"), *hpa.InitialReadinessDelay, "initial readiness delay be greater than 0"))
typo

2018-10-23 13:59 UTC, timuthy commented on pkg/controller/factory.go
> -	os.Exit(0)
Since this has been removed, stopping the controllers w/o leader election will cause a panic.

2018-10-23 13:59 UTC, timuthy commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +				<-ctx.Done()
`run(ctx)` already waits for the channel to be closed. Do we really have to it here again?

2018-10-23 13:59 UTC, timuthy commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +	go run(ctx)
Why do we start `run(ctx)` in a Go Routine now? This prevents the function from returning gracefully.

2018-10-23 13:59 UTC, timuthy commented on hack/templates/resources/90-shoot.yaml.tpl
> +  #     usernameClaim: username-claim
`usernameClaim` seems to be duplicated now (see 234)

2018-10-23 13:59 UTC, timuthy commented on hack/templates/resources/90-shoot.yaml.tpl
> +  #     usernamePrefix: username-prefix
`usernamePrefix` seems to be duplicated now (see 235)

2018-10-23 13:59 UTC, timuthy commented on hack/templates/resources/90-shoot.yaml.tpl
>    #     signingAlgs: RS256,some-other-algorithm
Can this be removed since we already have it in line 229?

2018-10-23 15:43 UTC, rfranzke commented
@timuthy I addressed all your comments, PTAL!

2018-10-23 15:59 UTC, timuthy approved these changes
LGTM! Thanks for the quick response!

2018-10-23 16:23 UTC, merged

2018-10-24 03:57 UTC, vlerenc commented
Great that it's done/in so fast, but also a great test plan you have there!

If we don't have that documented yet, it may make sense to have a description of what usually needs to be done starting from the release notes (especially the noteworthy section with changes) up to the test plan in the end.

2018-10-24 06:01 UTC, rfranzke commented
I have updated the description in #400 for now to keep it bundled, but maybe we can find a better place?