Adapt Project resource according to latest decisions
gardener/gardener pull request #480
Opened 2018-10-24 20:01 UTC by rfranzke

**What this PR does / why we need it**:
We have added the `Project` resource to the Garden API with #330. However, it was not possible to manage the members of a project directly with the resource. Moreover, the implementation was violating some best-practices and conventions of Kubernetes (e.g., an admission controller created resources, effectively causing side-effects).

**Which issue(s) this PR fixes**:
Fixes #357
Fixes #409

**Special notes for your reviewer**:
With this change we
1. add a new optional field `.spec.createdBy` (`*rbacv1.Subject`, immutable).
1. add a new optional field `.spec.members` (`[]rbacv1.Subject`, resulting in `RoleBinding`s in the corresponding `Namespace` that binds the members to the "project-member" `ClusterRole` (this was done by the Dashboard before)).
1. change a required field to an optional field `.spec.owner` (`*rbacv1.Subject`).
1. do no longer generate conditions for `Project`s (`.status.conditions` removed).
1. do generate `Events` for `Project`s and write its state into `.status.phase` (one of `Pending`, `Ready`, `Terminating`, `Failed`).
1. remove the introduced admission controller that was creating `Namespace`s for `Project`s.
1. move all responsibilities/logic for creating, reconciling, and deleting `Project`s to the `Project` controller (we are now leveraging Kubernetes' optimistic concurrency controls to prevent race conditions).
1. remove the migration loop that was automatically creating `Project` resources out of properly labelled `Namespace`s before starting the "shoot" controller.
1. remove the "project-namespace controller" that was automatically creating `Project` resources out of properly labelled `Namespace`s (during runtime).
1. migrate all existing `RoleBinding`s created by prior versions of Gardener dashboard, i.e. we add all the subjects to the new `.spec.members` field of the corresponding `Project` (after that we delete these legacy `RoleBinding`s).

:warning: The Gardener dashboard is finalizing the [adaptation](https://github.com/gardener/dashboard/tree/project) of these changes. Hence, once this is merged the next Gardener version won't work with dashboard versions < 1.23.

**Release note**:
```noteworthy operator
The `Project` resource has been changed to support management of project members (by setting `.spec.members`, please take a look at the [example `Project` resource](https://github.com/gardener/gardener/blob/master/example/05-project-dev.yaml)).
```
```action operator
:warning: The migration logic for automatically creating `Project` resource out of properly labelled `Namespace`s has been removed. Upgrading from a Gardener version prior 0.11.0 is not supported. Also, this Gardener version is not compatible with Gardener Dashboard versions prior 1.23.0.
```

2018-10-30 08:21 UTC, zanetworker commented on Makefile
> +	@./hack/generate-examples
Maybe separate them into two steps for two reasons: 
- if I just want to execute one independently
- if one fails we don't need to execute the other 

```makefile
generate-code:
     @./hack/generate-code

generate-examples: generate-code 
     @./hack/generate-examples
```

2018-10-30 08:21 UTC, zanetworker commented on pkg/apis/garden/v1beta1/defaults.go
> +		case rbacv1.GroupKind:
you can use a multi-value switch here: 

```go 
	switch obj.Spec.Owner.Kind {
		case rbacv1.ServiceAccountKind:
			obj.Spec.Owner.APIGroup = ""
		case rbacv1.UserKind, rbacv1.GroupKind:
                       obj.Spec.Owner.APIGroup = rbacv1.GroupName
```

2018-10-30 08:21 UTC, zanetworker commented on pkg/apis/garden/v1beta1/types.go
> +	CreatedBy rbacv1.Subject `json:"createdBy,omitempty"`
are you missing an +optional here?

2018-10-30 08:21 UTC, zanetworker commented on pkg/apis/garden/v1beta1/types.go
> +	Members []rbacv1.Subject `json:"members,omitempty"`
here as well?

2018-10-30 08:21 UTC, zanetworker commented on pkg/apis/garden/validation/validation.go
>  		allErrs = append(allErrs, apivalidation.ValidateImmutableField(newProject.Spec.Namespace, oldProject.Spec.Namespace, field.NewPath("spec", "namespace"))...)
same check in two places?  maybe just use the check in ValidateImmutableFied(..) and remove the `&&` ?

2018-10-30 08:44 UTC, rfranzke commented on Makefile
> +	@./hack/generate-examples
It's safer to have one command that generates both to keep the results in sync (e.g., if the API and the examples have changed but the generation was not yet run).
If only one generation may be executed then  just `./hack/generate-{code,examples}` can be called.

2018-10-30 08:46 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
>  		allErrs = append(allErrs, apivalidation.ValidateImmutableField(newProject.Spec.Namespace, oldProject.Spec.Namespace, field.NewPath("spec", "namespace"))...)
Do you suggest

```golang
if oldProject.Spec.Namespace != nil {
  allErrs = append(allErrs, apivalidation.ValidateImmutableField(newProject.Spec.Namespace, oldProject.Spec.Namespace, field.NewPath("spec", "namespace"))...)
}
```
?

I guess this makes sense, thank you, will do.

2018-10-30 08:47 UTC, rfranzke commented on pkg/apis/garden/v1beta1/defaults.go
> +		case rbacv1.GroupKind:
I've copied the validation from Kubernetes itself. Let's keep it as it is, this way it's also easier to read.

2018-10-30 08:53 UTC, timuthy requested changes

2018-10-30 08:53 UTC, timuthy commented on pkg/controller/project/project_control_delete.go
> +	if namespace.DeletionTimestamp != nil {
I'd prefer to do this check before checking for label equality.

2018-10-30 09:13 UTC, zanetworker commented on charts/garden-project/charts/project-rbac/templates/clusterrolebinding-project-admin.yaml
> +    name: "{{ .Values.project.name }}"
use the  ```{{ .Values.project.name |  quote }}``` ?

2018-10-30 09:13 UTC, zanetworker commented on charts/garden-project/charts/project-rbac/templates/clusterrolebinding-project-admin.yaml
> +    uid: "{{ .Values.project.uid }}"
use the {{ .Values.project.name | quote }} ?

2018-10-30 09:13 UTC, zanetworker commented on charts/garden-project/charts/project-rbac/templates/clusterrolebinding-project-members.yaml
> +    name: "{{ .Values.project.name }}"
same, use `quote` function?

2018-10-30 09:13 UTC, zanetworker commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, field.Invalid(field.NewPath("spec", "owner"), newProject.Spec.Owner, "owner cannot be reset"))
Maybe use the same message all over for immutable fields, for example "owner field is immutable"?

2018-10-30 09:13 UTC, zanetworker commented on pkg/apis/garden/validation/validation.go
> +	if len(oldProject.Status.Phase) > 0 && len(newProject.Status.Phase) == 0 {
maybe use "phase cannot be s/set/updated/g to an empty string"

2018-10-30 09:13 UTC, zanetworker commented on pkg/controller/project/project_control_delete.go
> +func (c *defaultControl) delete(project *gardenv1beta1.Project, projectLogger logrus.FieldLogger) (bool, error) {
we  can be consistent and put comments on all private functions?

2018-10-30 09:13 UTC, zanetworker commented on pkg/controller/project/project_control_reconcile.go
> +	namespace, err := c.reconcileNamespace(project)
reconcileNamespaceForProject()?

2018-10-30 09:52 UTC, rfranzke commented on pkg/apis/garden/validation/validation.go
> +		allErrs = append(allErrs, field.Invalid(field.NewPath("spec", "owner"), newProject.Spec.Owner, "owner cannot be reset"))
But it is mutable. It's just not allowed to "reset" it, i.e. setting it to `nil`.

2018-10-30 09:53 UTC, rfranzke commented on pkg/controller/project/project_control_delete.go
> +func (c *defaultControl) delete(project *gardenv1beta1.Project, projectLogger logrus.FieldLogger) (bool, error) {
What for? It's clear what this function does, isn't it?

2018-10-30 10:00 UTC, rfranzke commented
Thanks for the feedback, I've addressed it and rebased the branch.

2018-10-30 10:52 UTC, timuthy submitted a review, later dismissed

2018-10-31 09:43 UTC, Adracus commented on pkg/controller/project/project.go
> +		utils.Retry(10*time.Second, 10*time.Minute, func() (ok, severe bool, err error) {
Move logging of the project migration function to here and log only once.

2018-10-31 09:43 UTC, Adracus commented on pkg/controller/project/project.go
> +		logger.Logger.Errorf("[ROLEBINDING MIGRATION] Error fetching projects: %+v", err)
Remove logging / use error wrapping to have a pretty message (`go/x/errors` package).

2018-10-31 09:43 UTC, Adracus commented on pkg/controller/project/project.go
> +				continue
Maybe accumulate the errors in a `multierror` and return the accumulated error in the end?

2018-10-31 09:43 UTC, Adracus commented on plugin/pkg/global/deletionconfirmation/admission.go
> +			if err != nil {
why not just immediately return the value of the function (the 'cast' should happen implicitly)

2018-10-31 09:43 UTC, Adracus commented on plugin/pkg/global/deletionconfirmation/admission.go
> +			shoot, err := d.gardenClient.Garden().Shoots(a.GetNamespace()).Get(a.GetName(), metav1.GetOptions{})
Same as above

2018-10-31 09:43 UTC, Adracus commented on plugin/pkg/global/deletionconfirmation/admission.go
> +	if cacheLookup == nil || liveLookup == nil {
Use default case instead to indicate that the kind is unknown and also print it

2018-11-02 12:02 UTC, merged