Add static `ServiceAccount` token invalidator
gardener/gardener pull request #4817
Opened 2021-10-08 15:35 UTC by rfranzke

**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
With https://github.com/gardener/gardener/issues/4659, https://github.com/gardener/gardener/issues/4660, and https://github.com/gardener/gardener/issues/4661 we strive to use expiring and auto-rotating JWT tokens for our components in order to authenticate with the respective `kube-apiserver`s.

However, even when using them, the static `ServiceAccount` token secrets are still generated and valid. As of Kubernetes v1.22, there is neither a way of preventing `kube-controller-manager` to generate such static tokens, nor a way to proactively remove or invalidate them, see https://github.com/kubernetes/kubernetes/issues/77599 and https://github.com/kubernetes/kubernetes/issues/77600.

This is where the _TokenInvalidator_ comes into play: Since it is not possible to prevent `kube-controller-manager` from generating static `ServiceAccount` secrets, the _TokenInvalidator_ is - as its name suggests - just invalidates these tokens.
It considers all such `Secret`s belonging to `ServiceAccount`s with `.automountServiceAccountToken=false`.

**Special notes for your reviewer**:
I have added some document which can help understanding the purpose of this _TokenInvalidator_.

**Release note**:

```breaking operator
`gardener-resource-manager` now requires operators to provide a TLS certificate and key for its webhook server. The respective directory can be configured with `--tls-cert-dir`, bind address and port can be configured with `--bind-address` and `--port`, respectively.
```
```feature operator
`gardener-resource-manager` can now make sure static `ServiceAccount` tokens are invalidated. This might be helpful to enforce usage of Kubernetes' upstream [`ServiceAccount` Token Volume Projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) feature. Please consult [this document](https://github.com/gardener/gardener/tree/master/docs/concepts/resource-manager.md#tokeninvalidator) for more information.
```

2021-10-08 15:35 UTC, rfranzke commented
/cc @BeckerMax @timebertt

2021-10-11 08:18 UTC, BeckerMax commented
/assign

2021-10-14 11:20 UTC, vanjiii commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +		return reconcile.Result{}, fmt.Errorf("could not fetch Secret: %+v", err)
Do you think it is better to embed the errors with `%w` instead of `%+v`?

2021-10-14 11:27 UTC, vanjiii commented on pkg/resourcemanager/webhook/tokeninvalidator/handler.go
> +func (w *tokenInvalidator) Handle(_ context.Context, req admission.Request) admission.Response {
In some of our other webhooks there is timeout ([here](https://github.com/gardener/gardener/blob/424290b2b3b8a005bce7cbabdc1a8cb10688ead2/pkg/seedadmissioncontroller/webhooks/admission/extensioncrds/admission.go#L72) for example). Do you think it is helpful here as well?

2021-10-14 11:31 UTC, vanjiii commented on pkg/resourcemanager/webhook/tokeninvalidator/handler.go
> +		return admission.Errored(http.StatusBadRequest, err)
Do you think `http.StatusUnprocessableEntity` is more suitable here?

2021-10-14 12:44 UTC, timebertt commented
/assign

2021-10-14 14:51 UTC, timebertt commented on docs/concepts/resource-manager.md
> +      kubernetes.io/service-account.uid: 86e98645-2e05-11e9-863a-b2d4d086dd5a)
```suggestion
      kubernetes.io/service-account.uid: 86e98645-2e05-11e9-863a-b2d4d086dd5a
```

2021-10-15 06:50 UTC, rfranzke commented on pkg/resourcemanager/webhook/tokeninvalidator/handler.go
> +func (w *tokenInvalidator) Handle(_ context.Context, req admission.Request) admission.Response {
Nice catch and good suggestion! I think in this case it's not yet needed since the function is not using the context in any way, though.

2021-10-15 08:18 UTC, rfranzke commented
Thanks for your reviews, I've addressed the feedback with a16c893.

Also, after a long discussion with @timebertt yesterday, the following changes were made:
- 04c15ac makes the namespace of the "target cluster" configurable. This is so that we can restrict the GRM running in the shoot namespaces to only watch static service account token secrets in the `kube-system` namespace.
- 3a1c43a drops the special handling for invalidating the `default` service account token secrets. We figured that this doesn't quite fit into this PR and should rather be handled separately.
- 0f14ad3 extends the controller logic such that it checks for existing `Pod`s still using the static token before invalidating it. This is to ensure a smooth migration for existing clusters.

Please have another look! :)

2021-10-18 08:41 UTC, BeckerMax requested changes
Really well readable documentation!! Thanks for the PR!

2021-10-18 08:41 UTC, BeckerMax commented on docs/concepts/resource-manager.md
> +Since it is not possible to prevent `kube-controller-manager` from generating static `ServiceAccount` `Secret`s, the _TokenInvalidator_ is - as its name suggests - just invalidates these tokens.
```suggestion
Since it is not possible to prevent `kube-controller-manager` from generating static `ServiceAccount` `Secret`s, the _TokenInvalidator_ is - as its name suggests - just invalidating these tokens.
```

2021-10-18 08:41 UTC, BeckerMax commented on docs/concepts/resource-manager.md
> +It considers all such `Secret`s belonging to `ServiceAccount`s with `.automountServiceAccountToken=false`:
Should we mention here that you can define a target namespace so that only those secrets in the namespace are considered?

2021-10-18 08:41 UTC, BeckerMax commented on docs/concepts/resource-manager.md
> +> By default, the _TokenInvalidator_ also invalidates the static token of the `kube-system/default` `ServiceAccount`. This behaviour cannot be disabled. If you want it to consider the `default` `Serv
``` suggestion
```

2021-10-18 08:41 UTC, BeckerMax commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +func (r *reconciler) Reconcile(ctx context.Context, request reconcile.Request) (reconcile.Result, error) {
Docstring

2021-10-18 08:41 UTC, BeckerMax commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler_test.go
> +			})
what about AutomountServiceAccountToken=nil and skip label =true

2021-10-18 08:41 UTC, BeckerMax commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +				return reconcile.Result{Requeue: true}, nil
Can't it happen that a shoot owner mounts the secret himself to a pod while using `AutomountServiceAccountToken` to `false` ? Then this would loop endlessly, right?

2021-10-18 08:41 UTC, BeckerMax commented on pkg/resourcemanager/webhook/tokeninvalidator/handler_test.go
> +		It("should allow if secret data is nil", func() {
Add envtest in regard to `target-namespace`?

2021-10-18 08:51 UTC, rfranzke commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +func (r *reconciler) Reconcile(ctx context.Context, request reconcile.Request) (reconcile.Result, error) {
Not needed since `reconciler` is private.

2021-10-18 08:52 UTC, rfranzke commented on pkg/resourcemanager/webhook/tokeninvalidator/handler_test.go
> +		It("should allow if secret data is nil", func() {
This is not easily possible since the manager is only setup once. I'd have to create a new suite just for this case. Given that it's quite trivial I would refrain from doing so for the time being.

2021-10-18 08:52 UTC, rfranzke commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +				return reconcile.Result{Requeue: true}, nil
Yes and yes, it would requeue with exponential backoff and wait/try again.

2021-10-18 14:42 UTC, timebertt requested changes
Very nice!
Love the controller-runtime stuff (so simple) and the envtest as well 😉 

Some feedback from my side inline. Most of it are minor things, except the first one 😄

2021-10-18 14:42 UTC, timebertt commented on pkg/resourcemanager/controller/tokeninvalidator/add.go
> +			Reconciler:              NewReconciler(mgr.GetClient(), conf.InvalidateAllDefaultServiceAccounts),
Don't we need the target here instead of the manager's client?

2021-10-18 14:42 UTC, timebertt commented on pkg/resourcemanager/controller/tokeninvalidator/add.go
> +const ControllerName = "token-invalidator-controller"
```suggestion
const ControllerName = "token-invalidator"
```
?

2021-10-18 14:42 UTC, timebertt commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +	log := log.FromContext(ctx)
`Variable 'log' collides with imported package name`
```suggestion
	log := logf.FromContext(ctx)
```

2021-10-18 14:42 UTC, timebertt commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +	return r.targetClient.Patch(ctx, secret, patch)
This should use optimistic locking. Otherwise, we might wrongly add the label because of a stale cache read.

2021-10-18 14:42 UTC, timebertt commented on pkg/resourcemanager/webhook/tokeninvalidator/add.go
> +	server.Register(WebhookPath, &webhook.Admission{Handler: NewHandler()})
Now, that GRM is serving webhooks we should consider running it in an HA-manner, i.e. multiple replicas, PDB, etc.
(probably not for every shoot, but at least on the seed)

2021-10-18 14:42 UTC, timebertt commented on test/integration/envtest/resourcemanager/tokeninvalidator/tokeninvalidator_suite_test.go
> +	framework.RunCleanupActions()
I don't see any cleanup actions.

2021-10-18 14:42 UTC, timebertt commented on test/integration/envtest/resourcemanager/tokeninvalidator/tokeninvalidator_test.go
> +		ctx = context.Background()
There's already a `ctx`

2021-10-18 14:42 UTC, timebertt commented on test/integration/envtest/resourcemanager/tokeninvalidator/tokeninvalidator_test.go
> +			copy := secret.DeepCopy()
`Variable 'copy' collides with the builtin function`

2021-10-18 14:42 UTC, timebertt commented on cmd/gardener-resource-manager/app/app.go
> +				tokeninvalidatorwebhook.AddToManager,
What about adding `mgr.GetWebhookServer().StartedChecker()` as an `readyz` check to prevent sending webhook requests to unready grm pods? (`readinessProbe` has to be added to chart as well)

2021-10-18 14:42 UTC, timebertt commented on pkg/resourcemanager/cmd/target.go
> +	fs.StringVar(&o.namespace, "target-namespace", "", "namespace in which objects should be cached (defaults to all namespaces)")
This is not only about the cache but generally about the watches, right? E.g. if `--target-namespace` is set to `default` also the token invalidator will only touch service accounts/secrets in the `default` namespace, correct?

2021-10-18 14:42 UTC, timebertt commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +	if err := r.targetClient.List(ctx, podList, client.InNamespace(secret.Namespace)); err != nil {
This will in the end watch+cache all Pods on Seed clusters, right?
I remember, we considered using an `APIReader` but only doing the list if necessary.

2021-10-18 15:39 UTC, rfranzke commented on pkg/resourcemanager/webhook/tokeninvalidator/add.go
> +	server.Register(WebhookPath, &webhook.Admission{Handler: NewHandler()})
Yes, we will take care about it in a separate PR (once we start making use of these new features). :)

2021-10-18 15:40 UTC, rfranzke commented on test/integration/envtest/resourcemanager/tokeninvalidator/tokeninvalidator_suite_test.go
> +	framework.RunCleanupActions()
True. Though, do you mind if we just leave it? I think we can have it in the `AfterSuite` function for all our envtests by default in case somebody adds cleanup actions in the future.

2021-10-18 15:41 UTC, rfranzke commented on pkg/resourcemanager/cmd/target.go
> +	fs.StringVar(&o.namespace, "target-namespace", "", "namespace in which objects should be cached (defaults to all namespaces)")
Yes, right. However, the webhook needs to be properly configured outside of the scope of this code (while registering it with a Kubernetes cluster).

2021-10-19 06:44 UTC, timebertt commented on test/integration/envtest/resourcemanager/tokeninvalidator/tokeninvalidator_suite_test.go
> +	framework.RunCleanupActions()
Ok, fine

2021-10-19 06:46 UTC, timebertt commented on pkg/resourcemanager/cmd/target.go
> +	fs.StringVar(&o.namespace, "target-namespace", "", "namespace in which objects should be cached (defaults to all namespaces)")
Ok, what do you think about changing the help string to something like `namespace in which controllers for the target cluster act on objects` then?

2021-10-19 06:58 UTC, timebertt reviewed
Two more suggestions for making the controller more efficient at scale.
The rest looks really good, I like it! :)

2021-10-19 06:58 UTC, timebertt commented on cmd/gardener-resource-manager/app/app.go
> +			targetCluster, err := cluster.New(targetClusterOpts.Completed().Config, func(o *cluster.Options) { o.Namespace = targetClusterOpts.Completed().Namespace })
I just noticed, we are now spinning up two caches for the target cluster.
We should remove our own client creation coding in `pkg/resourcemanager/cmd/target.go` and create only a single `Cluster` object holding clients and caches.

2021-10-19 06:58 UTC, timebertt commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +	if err := r.targetReader.List(ctx, podList, client.InNamespace(secret.Namespace)); err != nil {
WDYT about skipping this list call if the secret already has the `consider` label to save network transfer?

2021-10-21 05:21 UTC, BeckerMax commented on pkg/resourcemanager/controller/tokeninvalidator/reconciler.go
> +				return reconcile.Result{Requeue: true}, nil
As we only watch secrets in the kube-system namespace I guess this is not very likely to happen. 
Good to know that it uses exponential backoff 👍🏼

2021-10-21 05:32 UTC, BeckerMax commented on pkg/resourcemanager/webhook/tokeninvalidator/handler_test.go
> +		It("should allow if secret data is nil", func() {
As discussed maybe you could add the controllerOpts and starting the manager in the beforeEach instead of in the suite and see how that looks.

2021-10-21 10:27 UTC, BeckerMax commented
Thanks for addressing the concerns @rfranzke 
/unassign /lgtm

2021-10-21 10:27 UTC, BeckerMax submitted a review, later dismissed

2021-10-21 15:52 UTC, rfranzke commented
@timebertt Could you have a final look, please? :)

2021-10-22 06:09 UTC, vanjiii commented
/lgtm

2021-10-22 07:25 UTC, timebertt approved these changes
Love it, thanks for addressing my suggestions!
/lgtm

2021-10-22 07:26 UTC, merged

2021-10-27 14:50 UTC, ira-gordin-sap commented
@rfranzke thank you so much🧡
Which configuration is required in shoot in order to make sure static `ServiceAccount` tokens are invalidated?

2021-10-27 15:04 UTC, rfranzke commented
Hi @ira-gordin-sap, this functionality is not yet activated for the seeds/shoots, this is still to be built. Also, during the implementation we figured that there is a certain complexity in making it also usable for end-users, so we have created a dedicated issue for it (https://github.com/gardener/gardener/issues/4924) which you can follow. However, I'm not yet too sure when we will get to it since we will first focus on the other items listed in https://github.com/gardener/gardener/issues/4878.