Remove creation of static node bootstrapToken
gardener/gardener pull request #4824
Opened 2021-10-12 06:04 UTC by BeckerMax

**How to categorize this PR?**

  /area security
  /kind cleanup

**What this PR does / why we need it**:

This commit is part of issue [#3898](https://github.com/gardener/gardener/issues/3898)
which replaces the long-valid bootstrap-token shared between nodes with a
short-lived token unique for each node.

The new flow of using smaller-scoped, short-lived tokens was already active
once you updated to compatible versions of the infrastructure-extension,
operatingsystem-extension and of gardener/gardener.

With this commit we are now removing the old secret from the Shoot
which means you need to run supported versions of the os-extensions
and the infrastructure-provider-extensions when
upgrading gardener to this version.

A compatibility matrix is added to the documentation which includes the required versions needed.

**Which issue(s) this PR fixes**:
Fixes #3898 

**Release note**:

```breaking operator
Remove creation of shared and long-valid node bootstrapTokens. Instead use short-lived tokens unique for each node. You are required to update to a version of the operatingsystem-extension and the infrastructure extension that support creating bootstrap-tokens. Please see the [compatibility matrix](https://github.com/gardener/gardener/blob/master/docs/extensions/operatingsystemconfig.md#compatibility-matrix-for-node-bootstrap-token) before updating gardener.
```

2021-10-14 06:20 UTC, rfranzke commented
/assign

2021-10-14 08:30 UTC, rfranzke requested changes
Nice, thanks! A few nit improvements for the docs, otherwise lgtm

2021-10-14 08:30 UTC, rfranzke commented on docs/extensions/operatingsystemconfig.md
> +With gardener v1.23 we replaced the long-valid bootstrap-token shared between nodes with a short-lived token unique for each node, ref:  [#3898](https://github.com/gardener/gardener/issues/3898).
```suggestion
With Gardener v1.23, we replaced the long-valid bootstrap-token shared between nodes with a short-lived token unique for each node, ref: [#3898](https://github.com/gardener/gardener/issues/3898).
```

2021-10-14 08:30 UTC, rfranzke commented on docs/extensions/operatingsystemconfig.md
> +❗ When updating to gardener version >=1.34 the old bootstrap-token will be removed. You are required to update your extensions to the following versions when updating gardener:
```suggestion
❗ When updating to Gardener version >=1.34 the old bootstrap-token will be removed. You are required to update your extensions to the following versions when updating Gardener:
```

2021-10-14 08:30 UTC, rfranzke commented on docs/extensions/operatingsystemconfig.md
> +| Extension   | version   | releaseDate   | PR |
```suggestion
| Extension   | Version   | Release Date   | Pull Request |
```

2021-10-14 08:30 UTC, rfranzke commented on docs/extensions/operatingsystemconfig.md
> +⚠️ If you use an infrastructure provider extension that does not use Machine Controller Manager (MCM) you need to implement the functionality of creating a temporary bootstrap-token before updating t
```suggestion
⚠️ If you run a provider extension that does not use Machine Controller Manager (MCM) you need to implement the functionality of creating a temporary bootstrap-token before updating your Gardener version to v1.34 or higher.
```

2021-10-14 08:30 UTC, rfranzke commented on docs/extensions/operatingsystemconfig.md
> +All extension-providers in https://github.com/gardener/ use MCM.
```suggestion
All provider extensions maintained in https://github.com/gardener/ use MCM.
```

2021-10-18 05:24 UTC, BeckerMax commented
/merge squash

2021-10-18 05:25 UTC, BeckerMax commented
Thank you very much for the review. I applied your suggestions.

2021-10-18 06:13 UTC, timebertt commented
/rebase 
ref #4822

2021-10-18 08:58 UTC, rfranzke submitted a review, later dismissed
/lgtm

2021-10-18 08:59 UTC, rfranzke commented on docs/extensions/operatingsystemconfig.md
> +❗ When updating to Gardener version >=1.34 the old bootstrap-token will be removed. You are required to update your extensions to the following versions when updating Gardener:
Just saw the release milestone got created, so:
```suggestion
❗ When updating to Gardener version >=1.35 the old bootstrap-token will be removed. You are required to update your extensions to the following versions when updating Gardener:
```

2021-10-18 08:59 UTC, rfranzke commented on docs/extensions/operatingsystemconfig.md
> +⚠️ If you run a provider extension that does not use Machine Controller Manager (MCM) you need to implement the functionality of creating a temporary bootstrap-token before updating your Gardener ver
```suggestion
⚠️ If you run a provider extension that does not use Machine Controller Manager (MCM) you need to implement the functionality of creating a temporary bootstrap-token before updating your Gardener version to v1.35 or higher.
```

2021-10-20 11:38 UTC, rfranzke approved these changes

2021-10-21 15:39 UTC, merged