add doc for controllerregistration controller
gardener/gardener pull request #4830
Opened 2021-10-13 04:41 UTC by shafeeqes

**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
Added doc for controllerregistration controller
Part of https://github.com/gardener/gardener/issues/3405
CC: @rfranzke 
**Release note**:

```other operator
NONE
```

2021-10-13 04:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=4830) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=4830) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=4830) it.</sub>

2021-10-14 06:20 UTC, rfranzke commented
/assign

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +The `ControllerRegistration` controller is responsible for ensuring that the required extensions can be satisfied by the [`Controllerregistration`s](https://github.com/gardener/gardener/blob/master/d
Which required extensions? What does "can be satisified" mean?

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +The controller has three reconciliation loops.
```suggestion
The controller has three reconciliation loops.

```

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `ControllerRegistration` resource and adds finalizers to it when they are created. In case a deletion request comes in for the resource, ie; if  a `DeletionTimest
```suggestion
This reconciliation loop watches the `ControllerRegistration` resource and adds finalizers to it when they are created. In case a deletion request comes in for the resource, i.e., if a `.metadata.deletionTimestamp` is set, it actively scans for a `ControllerInstallation` resource using this `ControllerRegistration`, and decides whether the deletion can be allowed. In case no related `ControllerInstallation` is present, it removes the finalizer present and marks it for deletion.
```

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `ControllerRegistration` resource and adds finalizers to it when they are created. In case a deletion request comes in for the resource, ie; if  a `DeletionTimest
Actually, the "main reconciler" of this controller is the next one, the "ControllerRegistrationSeed" Reconciler. So maybe swap the headlines and change above one to "`ControllerRegistration` Reconciler".

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `Seed` object and determines which `ControllerRegistrations` are required for the seed and installs or deletes them to reach the determined state. To begin with,
```suggestion
This reconciliation loop watches the `Seed` object and determines which `ControllerRegistrations` are required for the seed and installs or deletes them to reach the determined state. To begin with, it computes the kind/type combinations of extensions required for the Seed. For example, it examines the Shoots running on the Seed and deducts kind/types like `Infrastructure/gcp`. It also decides whether they should always be deployed based on the `.spec.deployment.policy`.
```

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +Based on these required combinations, each of them are mapped to existing `ControllerRegistration` objects and then to its corresponding `ControllerInstallation` object. The controller then deploys t
```suggestion
Based on these required combinations, each of them is mapped to potentially existing `ControllerRegistration` objects and then to their corresponding `ControllerInstallation` object. The controller then deploys the required `ControllerInstallation` objects for the given seed if they are not present, or updates them if they are present and offboards the old extension. It also deletes every existing `ControllerInstallation` whose referenced `ControllerRegistration` is not part of the required list. For example, if the `Shoot`s in the `Seed` are no longer using the cloud provider `aws`, then the controller proceeds to delete its installation object.
```

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `Seed` object and determines which `ControllerRegistrations` are required for the seed and installs or deletes them to reach the determined state. To begin with,
Do you also want to mention which other objects are examined to find the full list of required kind/type combinations?

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +Based on these required combinations, each of them are mapped to existing `ControllerRegistration` objects and then to its corresponding `ControllerInstallation` object. The controller then deploys t
> or updates them if they are present and offboards the old extension.

What do you mean by this?

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +Based on these required combinations, each of them are mapped to existing `ControllerRegistration` objects and then to its corresponding `ControllerInstallation` object. The controller then deploys t
Style nit: Sometimes you write "seed", sometimes to write "`Seed`".

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +Based on these required combinations, each of them are mapped to existing `ControllerRegistration` objects and then to its corresponding `ControllerInstallation` object. The controller then deploys t
> For example, if the `Shoot`s in the `Seed` are no longer using the cloud provider `aws`, then the controller proceeds to delete its installation object.

That's correct, but maybe make another example with DNS provider and `aws-route53`. Otherwise, it might be confusing for people not too familiar with Gardener systems (typically, a seed is always specific for a certain cloud provider, so if your example above can cause confusion).

2021-10-14 09:21 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This loop also watches the `Seed` object and adds finalizers to it at creation. If a `DeletionTimestamp` is set for the seed, then the controller checks for existing `ControllerInstallation` objects
```suggestion
This loop also watches the `Seed` object and adds finalizers to it at creation. If a `.metadata.deletionTimestamp` is set for the `Seed` then the controller checks for existing `ControllerInstallation` objects which reference this `Seed`. If no such objects exist then it removes the finalizer and allows the deletion.
```

2021-10-14 09:34 UTC, shafeeqes commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `ControllerRegistration` resource and adds finalizers to it when they are created. In case a deletion request comes in for the resource, ie; if  a `DeletionTimest
Okay. Then maybe I'll put the Main reconciler above this one

2021-10-14 09:36 UTC, shafeeqes commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `Seed` object and determines which `ControllerRegistrations` are required for the seed and installs or deletes them to reach the determined state. To begin with,
I could do that.

2021-10-19 06:27 UTC, rfranzke reviewed
Thanks, now it's in a good shape already. While reading again I found a few more nits, please correct them so that we can approve and merge it :)

2021-10-19 06:27 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +The `ControllerRegistration` controller makes sure that the requried [Gardener extensions](hhttps://github.com/gardener/gardener/tree/master/docs#extensions) specified by the [`Controllerregistration
```suggestion
The `ControllerRegistration` controller makes sure that the required [Gardener extensions](https://github.com/gardener/gardener/tree/master/docs#extensions) specified by the [`ControllerRegistration`](https://github.com/gardener/gardener/blob/master/docs/extensions/controllerregistration.md) resources are present in the seed clusters. It also takes care of the creation and deletion of `ControllerInstallation` objects in the seed cluster.
```

2021-10-19 06:27 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `Seed` objects and determines which `ControllerRegistrations` are required for them and installs or deletes them to reach the determined state. To begin with, it
> and installs or deletes them to reach the determined state

Technically, it does not "install/delete a `ControllerRegistration`. You can either write that it creates/deletes a corresponding `ControllerInstallation`, or that it creates/deletes the corresponding extension controller.

2021-10-19 06:27 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +Based on these required combinations, each of them are mapped to existing `ControllerRegistration` objects and then to its corresponding `ControllerInstallation` object. The controller then deploys t
```suggestion
Based on these required combinations, each of them are mapped to `ControllerRegistration` objects and then to their corresponding `ControllerInstallation` objects (if existing). The controller then creates or updates the required `ControllerInstallation` objects for the given seed. It also deletes every existing `ControllerInstallation` whose referenced `ControllerRegistration` is not part of the required list. For example, if the shoots in the seed are no longer using the DNS provider `aws-route53`, then the controller proceeds to delete the respective `ControllerInstallation` object.
```

2021-10-19 06:27 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This reconciliation loop watches the `ControllerRegistration` resource and adds finalizers to it when they are created. In case a deletion request comes in for the resource, i.e., if a `.metadata.del
```suggestion
This reconciliation loop watches the `ControllerRegistration` resource and adds finalizers to it when they are created. In case a deletion request comes in for the resource, i.e., if a `.metadata.deletionTimestamp` is set, it actively scans for a `ControllerInstallation` resource using this `ControllerRegistration`, and decides whether the deletion can be allowed. In case no related `ControllerInstallation` is present, it removes the finalizer and marks it for deletion.
```

2021-10-19 06:27 UTC, rfranzke commented on docs/concepts/controller-manager.md
> +This loop also watches the `Seed` object and adds finalizers to it at creation. If a `.metadata.deletionTimestamp` is set for the seed, then the controller checks for existing `ControllerInstallation
```suggestion
This loop also watches the `Seed` object and adds finalizers to it at creation. If a `.metadata.deletionTimestamp` is set for the seed then the controller checks for existing `ControllerInstallation` objects which reference this seed. If no such objects exist then it removes the finalizer and allows the deletion.
```

2021-10-20 11:38 UTC, rfranzke reviewed
Looks good now @shafeeqes, thanks!
Can you please rebase this PR on latest `master` to allow the CI pipeline to pass?

2021-10-20 12:44 UTC, rfranzke submitted a review, later dismissed
/lgtm

2021-10-20 13:07 UTC, ialidzhikov requested changes

2021-10-20 13:07 UTC, ialidzhikov commented on docs/concepts/controller-manager.md
> +The `ControllerRegistration` controller makes sure that the required [Gardener extensions](https://github.com/gardener/gardener/tree/master/docs#extensions) specified by the [`ControllerRegistration`
Can you use relative links? See background info - https://github.com/gardener/gardener/pull/4837#discussion_r728873197.

2021-10-20 13:07 UTC, ialidzhikov commented on docs/concepts/controller-manager.md
> +For the configuration options, please see this [section](https://github.com/gardener/gardener/blob/master/docs/extensions/controllerregistration.md#deployment-configuration-options).
Can you use relative link?

2021-10-20 13:41 UTC, ialidzhikov commented on docs/concepts/controller-manager.md
> +The `ControllerRegistration` controller makes sure that the required [Gardener extensions](https://github.com/gardener/gardener/tree/master/docs#extensions) specified by the [`ControllerRegistration`
Written as "[...] `ControllerInstallation` objects in the seed cluster." it sounds like the ControllerInstallation is created in the Seed cluster itself. We rather mean that the `ControllerInstallation` is created for a given Seed cluster, right?

```suggestion
The `ControllerRegistration` controller makes sure that the required [Gardener extensions](https://github.com/gardener/gardener/tree/master/docs#extensions) specified by the [`ControllerRegistration`](https://github.com/gardener/gardener/blob/master/docs/extensions/controllerregistration.md) resources are present in the seed clusters. It also takes care of the creation and deletion of `ControllerInstallation` objects for  a given seed cluster.
```

2021-10-20 13:52 UTC, ialidzhikov submitted a review, later dismissed
/lgtm
/squash

2021-10-21 08:29 UTC, rfranzke approved these changes

2021-10-21 15:41 UTC, merged