Mimic k/k's upstream rootcacertpublisher controller
gardener/gardener pull request #4832
Opened 2021-10-13 09:02 UTC by vanjiii

**How to categorize this PR?**

/area security
/kind enhancement
/priority 3

**What this PR does / why we need it**:
This PR mimics the behavior of the [rootcapublisher](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/rootcacertpublisher/publisher.go) because we have clusters with version `< 1.20` and we do not wish to trigger alpha feature gates.

Also our new `rootcapublisher` will not interfere with the one from k8s for versions ` >= 1.20`.

**Which issue(s) this PR fixes**:
Fixes #4801 
/cc @rfranzke 
/cc @BeckerMax

2021-10-14 06:19 UTC, rfranzke commented
/assign

2021-10-14 08:40 UTC, rfranzke requested changes

2021-10-14 08:40 UTC, rfranzke commented on cmd/gardener-resource-manager/app/app.go
> +	rootcaControllerOpts := &rootcacontroller.ControllerOptions{}
```suggestion
	rootCAControllerOpts := &rootcacontroller.ControllerOptions{}
```

2021-10-14 08:40 UTC, rfranzke commented on hack/local-development/start-resource-manager
> +	    --health-max-concurrent-workers=10
Why this change?

2021-10-14 08:40 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +const ControllerName = "root-ca-controller"
```suggestion
const ControllerName = "root-ca-publisher"
```

2021-10-14 08:40 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +	if conf.RootCAPath == "" {
```suggestion
	if conf.RootCAPath == "" || conf.MaxConcurrentWorkers == 0 {
```

2021-10-14 08:40 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +func isActive(obj client.Object) bool {
```suggestion
func isNamespaceActive(obj client.Object) bool {
```

2021-10-14 08:40 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +	fs.IntVar(&o.maxConcurrentWorkers, "rootcapublisher-max-concurrent-workers", 0, "number of worker threads for concurrent rootcapublisher reconciliation of resources")
```suggestion
	fs.IntVar(&o.maxConcurrentWorkers, "root-ca-publisher-max-concurrent-workers", 0, "number of worker threads for concurrent rootcapublisher reconciliation of resources")
```

2021-10-14 08:40 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +func (o *ControllerOptions) AddFlags(fs *pflag.FlagSet) {
Can you please also extend the Helm chart (https://github.com/gardener/gardener/tree/master/charts/gardener/gardener-resource-manager) with the new options?

2021-10-14 08:40 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/rootca_suite_test.go
> +	RunSpecs(t, "RootCA Publisher Controller Suite")
```suggestion
	RunSpecs(t, "Root CA Publisher Controller Suite")
```

2021-10-14 08:40 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/dummy.crt
> +    -----BEGIN CERTIFICATE-----
Can you move this file into a new directory called `testdata` (`test/integration/envtest/rootcapublisher/testdata/ca.crt`)?

2021-10-14 08:40 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_suite_test.go
> +		RootCAPath:           "dummy.crt",
See above; you might need to adapt the path here.

2021-10-14 08:40 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +	//
What about those?

2021-10-14 08:41 UTC, rfranzke commented
The `verify` step is failing. Can you check why? Running `make verify` locally before committing can help :)

2021-10-14 11:57 UTC, BeckerMax commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +	//
I think we can leave that test out and remove the comment

2021-10-14 11:58 UTC, BeckerMax commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +	It("should successfully create a config map on creating a namespace", func() {})
Here the content is still missing. But I remember we had a test for that.

2021-10-14 12:45 UTC, vanjiii commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +	It("should successfully create a config map on creating a namespace", func() {})
I refactor a bit the tests. The content that you are referring now is in the `BeforeEach` part

2021-10-15 06:39 UTC, rfranzke requested changes

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +	It("should successfully create a config map on creating a namespace", func() {})
According to the description I would have expected a check for an existing `ConfigMap`. However, in the `BeforeEach` only the existence of a `Namespace` is checked. Am I missing something?

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		By("Deleting the secret")
Which secret? You are deleting a `ConfigMap`

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*300, time.Millisecond*10).Should(Succeed())
Why is this checked twice?

2021-10-15 06:39 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +func isRelevantConfigMap(obj client.Object) bool {
Nit: For better readability, move this function after `AddToManager`.

2021-10-15 06:39 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +func (o *ControllerOptions) AddFlags(fs *pflag.FlagSet) {
I think this is still missing.

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		By("Updating the secret")
Again, which secret?

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +			}
Why are you not using `Expect(...).To(Succeed())` here? Instead of your function returning `bool`, you could also make it `map[string]string` and return `configMap.Data`. Then your assertion can check for `Should(Not(BeNil()))`.

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*500, time.Millisecond*10).Should(Succeed())
Why do we need all these custom timeouts/interval settings for the `Eventually` calls?

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		By("Ignoring annotating configmap")
This description is quite inaccurate/confusing, please update it.

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*300, time.Millisecond*10).Should(BeTrue())
See above

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		Expect(cm.Annotations).To(HaveKeyWithValue("foo", "newbar"))
Shouldn't this be a separate test case?

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		baseCM := cm.DeepCopyObject().(client.Object)
Why not simply `DeepCopy()`?

2021-10-15 06:39 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		Expect(cm.Annotations).To(HaveKeyWithValue("foo", "newbar"))
How is checking the annotations relevant? Shouldn't you check the `Data`?

2021-10-19 07:16 UTC, vanjiii commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*300, time.Millisecond*10).Should(Succeed())
It is not twice - first we check whether we successfully delete the config map; and the we check after the deletion if it is successfully created (again). Focus on the last part (`.Should(BeNotFoundError())`  and `.Should(Succeed())`).

2021-10-19 07:29 UTC, vanjiii commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +			}
If I am not mistaken we wanted:
- the request to run without an error
- to have actual data inside the map.

Will thing about how to improve it!

2021-10-19 07:37 UTC, vanjiii commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*500, time.Millisecond*10).Should(Succeed())
Minor optimization from my side. @BeckerMax give me a hint that I can tweak a bit those times, to improve the test length. If you think they are redundant, I can remove them?

2021-10-19 07:41 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*300, time.Millisecond*10).Should(Succeed())
Thanks, I missed this :)

2021-10-19 07:42 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +			}
Couldn't you still achieve both your goals with something like

```golang
		Eventually(func() map[string]string {
			Expect(testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)).To(Succeed())
			return configMap.Data
		}).Should(Not(BeNil()))
```

2021-10-19 07:43 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*500, time.Millisecond*10).Should(Succeed())
I'm not entirely sure, but I would hope that the defaults are good enough for our purposes here. @BeckerMax can you clarify why you suggested this?

2021-10-19 11:49 UTC, vanjiii commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +			}
I did it like this.

2021-10-19 13:33 UTC, rfranzke requested changes

2021-10-19 13:33 UTC, rfranzke commented on charts/gardener/gardener-resource-manager/values.yaml
> +    maxConcurrentWorkers: 1
```suggestion
    maxConcurrentWorkers: 0
```

Let's disable it by default here

2021-10-19 13:33 UTC, rfranzke commented on charts/gardener/gardener-resource-manager/values.yaml
> +    rootCAPath: "path/to/file"
```suggestion
    rootCAPath: "" # path to a file containing the root CA bundle
```

2021-10-19 13:33 UTC, rfranzke commented on charts/gardener/gardener-resource-manager/templates/deployment.yaml
> +        - --root-ca-publisher-max-concurrent-workers={{ .Values.controllers.rootCAController.maxConcurrentWorkers }}
```suggestion
        {{- if .Values.controllers.rootCAController.maxConcurrentWorkers }}
        - --root-ca-publisher-max-concurrent-workers={{ .Values.controllers.rootCAController.maxConcurrentWorkers }}
        {{- end }}
```

2021-10-19 13:33 UTC, rfranzke commented on charts/gardener/gardener-resource-manager/templates/deployment.yaml
> +        - --root-ca-file="{{ .Values.controllers.rootCAController.rootCAPath }}"
```suggestion
        {{- if .Values.controllers.rootCAController.rootCAPath }}
        - --root-ca-file={{ .Values.controllers.rootCAController.rootCAPath }}
        {{- end }}
```

2021-10-19 13:33 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +	TargetClientConfig   resourcemanagercmd.TargetClientConfig
FYI: After https://github.com/gardener/gardener/pull/4817 is merged, this will be `cluster.Cluster` (see https://github.com/gardener/gardener/pull/4817/commits/7a29f98bf08bfcb9ec5907847920827d335cf3ea).

2021-10-19 13:33 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +		&source.Kind{Type: &corev1.Namespace{}},
We should watch the namespaces in the target cluster, not in the source cluster. You could adapt it like here: https://github.com/gardener/gardener/pull/4817/commits/748c3245b52d5535a3f697ca13b76dc40c0e4bed#diff-3e701f5f461eee9b9554760b87984a9a45bae9b41cabcecc993b79fb8615364fR90

2021-10-19 13:33 UTC, rfranzke commented on pkg/resourcemanager/controller/rootcapublisher/add.go
> +		&source.Kind{Type: configMap},
Same here. Please adapt it like https://github.com/gardener/gardener/pull/4817/commits/748c3245b52d5535a3f697ca13b76dc40c0e4bed#diff-3e701f5f461eee9b9554760b87984a9a45bae9b41cabcecc993b79fb8615364fR77

2021-10-19 13:33 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*300, time.Millisecond*10).Should(Not(BeNil()))
Should this be a separate test case (`It()`)?

2021-10-19 13:33 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		}, time.Millisecond*300, time.Millisecond*10).Should(BeNil())
Same here - separate test case?

2021-10-19 13:33 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		Expect(cm.Data).To(HaveKeyWithValue("foo", "newbar"))
Same here - separate test case?

2021-10-19 13:33 UTC, rfranzke commented on test/integration/envtest/rootcapublisher/publisher_test.go
> +		Expect(cm.Data).To(HaveLen(1))
Use `Consistently` for these two assertions here?

2021-10-22 07:29 UTC, rfranzke commented
@vanjiii #4817 is merged now, you can rebase on top of `master` and finalize this one :)

2021-10-25 08:21 UTC, rfranzke reviewed
Thanks, looks great! A few nits in the envtest.
Apart from the suggestions, you could also check that the `ConfigMap`'s `data` contains the right certificate (the one you have added to `test/integration/envtest/resourcemanager/rootcapublisher/testdata/dummy.crt`)?! :)

2021-10-25 08:21 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +			}
```suggestion
			Expect(testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)).To(Succeed())
```

2021-10-25 08:21 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +	It("should keep the config map in the desired state after delete of the config map", func() {
```suggestion
	It("should recreate the config map if it gets deleted", func() {
```

2021-10-25 08:21 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +		Expect(testClient.Delete(ctx, configMap)).To(Succeed())
```suggestion
		Expect(testClient.Delete(ctx, configMap)).To(Succeed())

```

2021-10-25 08:21 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +
```suggestion
```

2021-10-25 08:21 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +			}
```suggestion
			Expect(testClient.Patch(ctx, cm, client.MergeFrom(baseCM))).To(Succeed())
```

2021-10-25 08:21 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +			}
```suggestion
			Expect(testClient.Get(ctx, client.ObjectKeyFromObject(configMap), configMap)).To(Succeed())
```

2021-10-25 09:54 UTC, vanjiii commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +		Expect(testClient.Delete(ctx, configMap)).To(Succeed())
I am sorry I do not quite get what should the change be? Empty Row..?

2021-10-25 10:27 UTC, rfranzke reviewed
@vanjiii Thanks! Now some of the tests are failing, please check.

2021-10-25 10:27 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/testdata/dummy.crt
> +    -----END CERTIFICATE-----
Just noticed now: Is there a reason for this indentation? If not, let's remove it.

2021-10-25 10:27 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +		}).Should(SatisfyAll(Not(BeNil()), HaveKeyWithValue("ca.crt", "    -----BEGIN CERTIFICATE-----\n    ...\n    -----END CERTIFICATE-----\n")))
You could move this in an `AfterEach` section and put the first three `It`s in a `Context`. This way, you don't duplicate the same code.

2021-10-25 10:27 UTC, rfranzke commented on test/integration/envtest/resourcemanager/rootcapublisher/publisher_test.go
> +		}).Should(SatisfyAll(Not(BeNil()), HaveKeyWithValue("ca.crt", "    -----BEGIN CERTIFICATE-----\n    ...\n    -----END CERTIFICATE-----\n")))
Instead of copying the content of the `dummy.crt` file, can you read it in the `BeforeSuite`, store it in a variable (similar to `testClient`) and use it from there?

2021-10-25 11:20 UTC, rfranzke approved these changes
/lgtm

2021-10-25 11:37 UTC, merged