Protect etcd resource from deletion
gardener/gardener pull request #4861
Opened 2021-10-15 12:19 UTC by vanjiii

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
Simply make the etcd resource deletion protected by including it in the extension crd webhook

**Which issue(s) this PR fixes**:
Fixes #4833

```feature operator
`druid.gardener.cloud/v1alpha1.Etcd` resources are now protected from unintentional deletion, i.e. they must be annotated with `confirmation.gardener.cloud/deletion=true` before any `DELETE` call can succeed.
```

2021-10-15 12:20 UTC, vanjiii commented
/cc @timuthy

2021-10-15 12:20 UTC, rfranzke reviewed
Please extend the integration test (https://github.com/gardener/gardener/tree/master/test/integration/envtest/seedadmissioncontroller)

2021-10-18 13:42 UTC, rfranzke commented
@vanjiii @timuthy Without having checked the details, does this PR interfere with https://github.com/gardener/gardener/pull/4869 (which is probably merged first)?

2021-10-18 14:05 UTC, timuthy commented
> @vanjiii @timuthy Without having checked the details, does this PR interfere with #4869 (which is probably merged first)?

Yes, there will be a conflict. I was not sure how long this PR will remain in a draft state, so I moved on and filed #4869. @vanjiii do you mind rebasing this PR as soon as #4869 is merged?

2021-10-18 14:13 UTC, vanjiii commented
> > @vanjiii @timuthy Without having checked the details, does this PR interfere with #4869 (which is probably merged first)?
> 
> Yes, there will be a conflict. I was not sure how long this PR will remain in a draft state, so I moved on and filed #4869. @vanjiii do you mind rebasing this PR as soon as #4869 is merged?

No, not at all! Of course I will rebase ;)

2021-10-20 05:48 UTC, timuthy requested changes

2021-10-20 05:48 UTC, timuthy commented on pkg/operation/botanist/component/extensions/crds/crds.go
> +		etcdCRD,
We already deploy this CRD as part of the etcd bootstrap component [here](https://github.com/gardener/gardener/blob/550565ea939a7b3e0298740bea7345a27ed65551/pkg/operation/botanist/component/etcd/bootstrap.go#L293). Switching it to this place does not work automatically because today it is part of a `ManagedResource` and when you try to remove it from there it'll be deleted (we certainly don't want that). Is there a particular reason why you added the CRD here as well?

2021-10-20 11:36 UTC, rfranzke commented on pkg/operation/botanist/component/extensions/crds/crds.go
> +		etcdCRD,
+1, it was probably added to make the the `Etcd` CRD available for the envtest. Instead, the envtest should install https://github.com/gardener/gardener/blob/550565ea939a7b3e0298740bea7345a27ed65551/pkg/operation/botanist/component/etcd/bootstrap.go#L293 explictly.

2021-10-21 12:41 UTC, vanjiii commented on pkg/operation/botanist/component/extensions/crds/templates/crd-etcd.tpl.yaml
> +apiVersion: apiextensions.k8s.io/v1
Should be delete

2021-10-21 13:24 UTC, timuthy requested changes
Thanks for the PR which looks pretty good right now. There is one thing missing, though. The `etcd` resource is now protected and thus the `etcd` component has to confirm the deletion in the [Destroy](https://github.com/gardener/gardener/blob/a71be722d3346a87ea58e15d3f2ef1b17a7e0b91/pkg/operation/botanist/component/etcd/etcd.go#L525) function. Please have a look at how the `ControlPlane` component deletes the extension resource [here](https://github.com/gardener/gardener/blob/a71be722d3346a87ea58e15d3f2ef1b17a7e0b91/pkg/operation/botanist/component/extensions/controlplane/controlplane.go#L177).

2021-10-25 07:30 UTC, rfranzke commented on pkg/operation/botanist/component/etcd/etcd.go
> +		}
```suggestion
	if err := gutil.ConfirmDeletion(ctx, e.client, e.etcd); client.IgnoreNotFound(err) != nil {
```

2021-10-25 07:30 UTC, rfranzke commented
@vanjiii Could you check why the `verify` step fails?

2021-10-25 08:46 UTC, rfranzke reviewed
@vanjiii I'm not sure if `gomock.Any()` really is a good choice just to please the test. I would suggest to be more concrete so that the test is more valuable.

2021-10-25 08:49 UTC, vanjiii commented on pkg/operation/botanist/component/etcd/etcd.go
> +		}
I do not think that is as accurate as we intend to:
- `client.IgnoreNotFound(err)` returns bool thus cannot be nil
- if another error happens it will be ignored and the execution will continue (i guess we do not want this)

2021-10-25 09:00 UTC, rfranzke commented on pkg/operation/botanist/component/etcd/etcd.go
> +		}
> client.IgnoreNotFound(err) returns bool thus cannot be nil 

It returns an `error`, see https://github.com/kubernetes-sigs/controller-runtime/blob/1e4d87c9f9e15e4a58bb81909dd787f30ede7693/pkg/client/interfaces.go#L140-L145.

> if another error happens it will be ignored and the execution will continue (i guess we do not want this)
Write

If a `not found` error happens then it will be ignored and we will continue with deleting the other objects (HVPA, etc.). This is what we want, I think. Why not?
If we returned `nil` if the `Etcd` resource was already deleted then I can imagine the following error situation:
1. Deletion of `Etcd` succeeds
2. gardenlet panics/aborts
3. gardenlet restarts
4. Now the HVPA etc. resources are orphaned in the system (because we always exit early here since `Etcd` is already gone).

2021-10-25 10:46 UTC, rfranzke submitted a review, later dismissed
/lgtm

@timuthy, any final feedback? :)

2021-10-25 12:42 UTC, timuthy approved these changes
/lgtm
Thank you very much :)

2021-10-25 14:15 UTC, rfranzke approved these changes

2021-10-25 14:15 UTC, merged