Add the Shoot Maintenance test to envtest
gardener/gardener pull request #4882
Opened 2021-10-20 12:41 UTC by acumino

**How to categorize this PR?**

/area testing
/kind task

**What this PR does / why we need it**:
Refactor Shoot maintenance integration test to envtest
**Which issue(s) this PR fixes**:
Part of #4655
@ialidzhikov 

**Release note**:

```other operator
NONE
```

2021-10-25 13:46 UTC, ialidzhikov requested changes
Thanks for the PR! I left few suggestions inline.

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	//added by me
```suggestion
```

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	initializationTimeout      = 600 * time.Second
```suggestion
	waitForCreateDeleteTimeout = 2 * time.Hour
	initializationTimeout      = 10 * time.Minute
```

(I know that this is inherited from the old version of the test)

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	err                      error
Do we need this `err` to be a package level var? I guess we can now adapt the code to do not rely on this global err var, right?

```suggestion
```

(I know that this is inherited from the old version of the test)

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +
```suggestion
```

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	By("create shoot")
Actually this `By` is a little bit misleading. You don't create the Shoot obj here, you only assign the var. The actual creation is in the `BeforeEach`. So let's move this `By` statement to the place where the actual Shoot creation happens.

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	recorder = utils.CreateRecorder(k8sGardenClient.Kubernetes(), "shoot-maintenance-controller")
I see that your are creating a clientMap to be able to create a recorder afterwards. As this test is based on controller-runtime (while the GCM is still not) can we instead use the controller-runtime Managed to obtain a `record.EventRecorder`?

```
recorder = mgr.GetEventRecorderFor("shoot-maintenance-controller")
```

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +
```suggestion
```

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +
```suggestion
```

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +}, initializationTimeout.Seconds())
I guess this high timeout for the BeforeSuite is leftover from the old integration test. If I am not wrong, the old version of the integration test was creating a real Shoot in its BeforeSuite and that's probably why we have such high timeout (2h). With the envtest refactoring, can we remove (or lower) this timeout?

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +}, initializationTimeout.Seconds())
Same as the comment for the `BeforeSuite` - with the envtest refactoring can we remove (or lower) this timeout as we no longer create or delete a real Shoot.

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +		if !shootCleanupNeeded {
Do we need this `shootCleanupNeeded` with the envtest refactoring?
I guess we can simply ignore NotFound errors in the `AfterEach` for the case when Shoot is not successfully created for some reason.

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +			framework.ExpectNoError(testClient.Patch(ctx, shoot, patch))
For consistency with the rest of the file

```suggestion
			err = testClient.Patch(ctx, shoot, patch)
			Expect(err).To(BeNil())
```

(I know that this is inherited from the old version of the test)

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +		}, waitForCreateDeleteTimeout.Seconds())
With the envtest refactoring we don't need such high timeout (2h) because no real Shoot is being created.

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	Logger    *logrus.Logger
Why this var is exported?

```suggestion
	logger    *logrus.Logger
```

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +		- If running in TestMachinery mode: scale down the Gardener-Scheduler
This step does no longer exist, right?

```suggestion
```

2021-10-25 13:46 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/utills.go
> +}
I think here you simply copied this func from `test/framework/gardener_utils.go`. Instead you can use the `kutil.SetAnnotationAndUpdate` helper func.

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/utills.go
>  // See the License for the specific language governing permissions and
Typo in the file name - `utills.go` -> `utils.go`

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	recorder = mgr.GetEventRecorderFor("shoot-maintenance-controller")
Can we move this part that obtains the recorder to the `addShootMaintenanceControllerToManager` func? In this way we will no longer need the recorder to be a package level var.

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/utills.go
> +	return gardenClient.Patch(ctx, shoot, patch)
```suggestion
	return kutil.SetAnnotationAndUpdate(ctx, gardenClient, shoot, v1beta1constants.GardenerOperation, v1beta1constants.ShootOperationMaintain)
```

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	prepareCloudProfile(ctx, cloudProfile, shoot)
If I understand correctly we first create a CloudProfile, then we updated it with additional images that are also used by the Shoot (which are also known to us because we configure them). Would it be possible to simply create the CloudProfile that we want (to eliminate the UPDATE request)?

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	namespace *corev1.Namespace
It seems that the namespace is not used out of the BeforeSuite. We could make it a local var in the BeforeSuite func.

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	expirationDateInThePast  = metav1.Time{Time: time.Now().UTC().AddDate(0, 0, -1)}
It seems that this var is used only in the tests. Can we move it inside `Describe("Shoot Maintenance controller tests"`.

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +			}()
It seems that right now we have 3 similar `defer`s that aim to rollback the changes to the cloudprofile after the test execution. Would it be possible to remove these defer funcs if we move the CloudProfile creation to BeforeEach (and respectively we delete the CloudProfile in AfterEach) - in this way we would no longer care about reverting changes to the CloudProfile as each test will get a newly created CloudProfile. WDYT?

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/utills.go
> +// DeleteShoot deletes the test shoot
```suggestion
// DeleteShoot deletes the given Shoot.
```

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/utills.go
> +// StartShootMaintenance adds the maintenance annotation on the Shoot to start the Shoot Maintenance
```suggestion
// StartShootMaintenance adds the maintenance operation annotation to the given Shoot.
```

2021-10-26 07:31 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +		},
Is it possible to move the Shoot initialization to the BeforeEach and try to remove the `baseShoot` var?

2021-10-27 08:15 UTC, ialidzhikov reviewed
Few minor nits inline, otherwise lgtm.

2021-10-27 08:15 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +		cloudProfile gardencorev1beta1.CloudProfile
Do we have any concrete reason to not make the cloudProfile a pointer?

2021-10-27 08:15 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +	Describe("Kubernetes version maintenance tests", func() {
You could leave 1 empty line between the `Describe`s.

2021-10-27 08:52 UTC, ialidzhikov submitted a review, later dismissed
/lgtm

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +// Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```suggestion
// Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> + **/
Do we really need these comments?

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +
```suggestion
```

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +			Expect(err).To(BeNil())
```suggestion
			Expect(kutil.SetAnnotationAndUpdate(ctx, testClient, shoot, v1beta1constants.GardenerOperation, v1beta1constants.ShootOperationMaintain)).To(Succeed())
```

You could apply the same for other occurrences.

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> +	return nil
```suggestion
	return c.Watch(&source.Kind{Type: &gardencorev1beta1.Shoot{}}, &handler.EnqueueRequestForObject{})
```

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +// Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```suggestion
// Copyright (c) 2021 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
```

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +
```suggestion
```

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +	Expect(err).ToNot(HaveOccurred())
```suggestion
	Expect(addShootMaintenanceControllerToManager(mgr)).To(Succeed())
```

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_suite_test.go
> +		Expect(err).ToNot(HaveOccurred())
```suggestion
		Expect(mgr.Start(mgrContext)).To(Succeed())
```

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/utils.go
> +		}
Use https://github.com/gardener/gardener/blob/6806495376b1de8b760b10cf5bc5cf9445f30b06/pkg/utils/gardener/deletion_confirmation.go#L58 instead

2021-10-27 14:35 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/utils.go
>  func WaitForExpectedMachineImageMaintenance(ctx context.Context, logger *logrus.Logger, gardenClient client.Client, s *gardencorev1beta1.Shoot, targetMachineImage gardencorev1beta1.ShootMachineImage,
Can we make these utility functions private?

2021-10-27 18:41 UTC, acumino commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> + **/
I think this helps the new reader to understand what the test is trying to achieve in a brief manner.

2021-10-27 18:42 UTC, acumino commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> + **/
Should I remove it or keep it?

2021-10-28 06:09 UTC, rfranzke commented on test/integration/envtest/shootmaintenance/maintenance_control_test.go
> + **/
I don't have a strong opinion, I'm not too familiar with these tests. If you think it's still valueable even after the rewrite/refactoring then let's keep it.

2021-10-29 07:20 UTC, ialidzhikov reviewed
Minor styling suggestions, otherwise lgtm.

2021-10-29 07:20 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/utils.go
> +	// kutil "github.com/gardener/gardener/pkg/utils/kubernetes"
```suggestion
```

2021-10-29 07:20 UTC, ialidzhikov commented on test/integration/envtest/shootmaintenance/utils.go
> +
```suggestion
```

2021-10-29 07:49 UTC, ialidzhikov approved these changes
/lgtm
/squash

2021-10-29 07:59 UTC, rfranzke approved these changes

2021-10-29 09:07 UTC, merged