Add technical-id/cluster-id of the shoot cluster to the worker labels
gardener/gardener pull request #4897
Opened 2021-10-22 16:12 UTC by poelzi

Worker now get the label:
* `worker.gardener.cloud/technical-id`
*  `worker.gardener.cloud/cluster-id`
containing the technical-id and uid of the Shoot Cluster the node belongs to.

**How to categorize this PR?**

/area control-plane
/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
This allows a easier identification of the cluster and tagging of outgoing data like
log files.

**Special notes for your reviewer**:

**Release note**:

```feature operator
Nodes now have a labels for technical id and uid of the shoot cluster they belong to.
```

2021-10-22 16:12 UTC, ghost commented
Thank you @poelzi for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

2021-10-22 17:38 UTC, ialidzhikov requested changes
Isn't possible for your use case to configure worker labels as part of the Shoot spec?https://github.com/gardener/gardener/blob/3686eb34a2b4cc69923f9ed599162dd133671e4f/example/90-shoot.yaml#L60-L61

I am not super convinced that in general we want to maintain any kind of such metadata as a Node label.

2021-10-25 10:55 UTC, poelzi commented
@ialidzhikov we are exporting worker group label as well. We also export the project name and other information as a hostname. The problem is, they are not really machine readable and heavily depends on may factors like the machine controller used.

This change helps operations and automation to easily lookup and verify certain aspects. This information is otherwise only query able from the gardener instance itself and requires a lot of permissions, etc.
There is nothing lost by providing this information in general and not only as part of a specific spec.

2021-10-25 11:46 UTC, ialidzhikov commented
> This change helps operations and automation to easily lookup and verify certain aspects. This information is otherwise only query able from the gardener instance itself and requires a lot of permissions, etc.

There is actually a ConfigMap for each Shoot that contains a basic metadata for the Shoot itself - `kube-system/shoot-info`. If the PR is motived by your logging solution, then I guess it would be possible for you to lookup for the metadata in the `kube-system/shoot-info` ConfigMap and pass it as config option to your logging solution.

> There is nothing lost by providing this information in general and not only as part of a specific spec.

I am not saying that something is being lost. Today you need the shoot technicalID and clusterID, tomorrow you may need 5 more metadata fields. It would be hard to draw the line what is useful information and whether this information is useful for everyone or only for you.

2021-10-26 18:02 UTC, poelzi commented
@ialidzhikov thanks for this hidden feature. I documented this in  #4918

2021-10-26 18:02 UTC, closed without merging