Added priority class for authorization server of reversed vpn.
gardener/gardener pull request #4922
Opened 2021-10-27 14:34 UTC by ScheererJ

Co-authored-by: Sebastian Stauch <sebastian.stauch@sap.com>

**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
Added priority class for authorization server of reversed vpn.
In some environments, most notably GKE, priority class `system-cluster-critical` is handled in a special way requiring a `ResourceQuota` for usage. Our options were to either create a specific `ResourceQuota` for the `garden` namespace or use a different priority class. This pull request uses the latter approach to resolve the issue.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:

**Release note**:

```other operator
None
```

2021-10-27 15:21 UTC, rfranzke commented on pkg/operation/botanist/component/extauthzserver/external_authz_server.go
> +					PriorityClassName:            DeploymentName,
```suggestion
					PriorityClassName:            pc.Name,
```

2021-10-27 15:28 UTC, ialidzhikov requested changes
Can you add a proper explanation in the PR description why exactly we need this custom PriorityClass and why it was not possible to use `system-cluster-critical` in some environments?

2021-10-28 07:14 UTC, DockToFuture commented on pkg/operation/botanist/component/extauthzserver/external_authz_server.go
> +					PriorityClassName:            DeploymentName,
Updated it.

2021-10-28 07:17 UTC, rfranzke approved these changes
/lgtm

2021-10-28 07:54 UTC, ScheererJ commented
> Can you add a proper explanation in the PR description why exactly we need this custom PriorityClass and why it was not possible to use `system-cluster-critical` in some environments?

@ialidzhikov I added a description to the pull request. Does it fulfil your requirements?

2021-10-28 07:56 UTC, ialidzhikov commented
> @ialidzhikov I added a description to the pull request. Does it fulfil your requirements?

Thank you!

2021-10-28 07:56 UTC, ialidzhikov approved these changes
/lgtm

2021-10-28 08:24 UTC, merged