Disable parallel execution of update-codegen
gardener/gardener pull request #5020
Opened 2021-11-16 11:36 UTC by BeckerMax

**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
We sporadically saw errors when running check-generate
locally or in pipelines. Appearance of those errors correlate
with the time we introduced parallelisation for `make generate`.

When looking at the logs of a failing run we can see that the first
error appears when running update-codegen.sh. Consequently, this
removes the parallel execution in this script.

We were not able to consistently reproduce this issue to find the exact
root cause.

**Which issue(s) this PR fixes**:
Fixes #4570 

**Question to the reviewer:**
Should we add an additional option like `generate-parallel` so that one can locally opt-in to get the full parallel experience with the chance of a flake?

**Release note**:

```bugfix developer
Parts of `make-generate` are no longer executed in parallel.
```

/invite @stoyanr

2021-11-16 11:37 UTC, BeckerMax commented on Makefile
> +	@hack/update-codegen.sh
Question to the reviewer:
Should we add an additional option like generate-parallel so that one can locally opt-in to get the full parallel experience with the chance of a flake?

2021-11-16 13:27 UTC, timebertt requested changes
/assign

I have some remarks to this PR
- it is a workaround for https://github.com/gardener/gardener/issues/4570 but not a fix, we should not close the issue with this PR
- we also saw a lot of failures during `mockgen` (one example is in https://github.com/gardener/gardener/issues/4570), this is not addressed by this PR
- if we want to workaround it in the pipeline, I would rather vote for adapting `check-generate.sh` to call `make generate-sequential` if present or `make generate` otherwise, but not adapt the `Makefile`

2021-11-16 13:27 UTC, timebertt commented on Makefile
> +	@hack/update-codegen.sh
See my comment below

2021-11-17 06:28 UTC, BeckerMax commented
Thanks for your feedback!

I decided to keep mockgen parallel as there could be a dependency between failing
`update-codegen.sh` and `generate-parallel.sh` in [make generate](https://github.com/gardener/gardener/blob/e153276478cca254693231868d974ef07e184d9d/Makefile#L192-L193).
Generate-groups is creating conversions, clients and is failing in doing that. Afterwards generate shows errors like: 
```
Generate github.com/gardener/gardener/pkg/operation/botanist/component/extensions/containerruntime/mock
(...)
github.com/gardener/gardener/pkg/client/operations/clientset/versioned: no Go files in /go/src/github.com/gardener/gardener/pkg/client/operations/clientset/versioned
```
[ref](https://concourse.ci-2.gardener.cloud/teams/gardener/pipelines/gardener-master/jobs/master-head-update-job/builds/512#L61089570:1311).

Therefore, I wanted to first try to take the parallelisation away from only `update-codegen.sh` and let it run for a while in the pipelines. If we see no more errors appearing it would mean we could at least run the `generate.sh` in parallel. WDYT?

2021-11-17 13:54 UTC, timebertt commented
Hmm, interesting. `make generate` should actually fail before executing `generate.sh` if `update-codegen.sh` failed...
This probably means, `update-codegen.sh --parallel` is not returning the correct exit code if one generation failed.

2021-11-17 14:07 UTC, timebertt commented on Makefile
> +	@hack/update-codegen.sh
Let's keep it for now, should be fine. If not, we can still change it

2021-11-17 14:09 UTC, timebertt approved these changes
Let's continue with this for now. When testing the parallel generation, I also hit some weird codegen issue locally again, that seems to stem from parallel generation.
If one wants the parallel generation, they can still run `./hack/update-codegen.sh --parallel`
/lgtm

2021-11-17 16:40 UTC, merged