Clean up `VolumeSnapshots` and `VolumeSnapshotContents`
gardener/gardener pull request #5104
Opened 2021-12-01 15:26 UTC by timuthy

**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR enhances Gardener's clean-up logic to also include `VolumeSnapshots` and `VolumeSnapshotContents`. As opposed to other resources, those are only forcefully cleaned up after `1h` because deleting snapshots can take a while depending on the number of snapshots which were taken before.

**Release note**:

```feature operator
Gardener now cleans up `VolumeSnapshots` and `VolumeSnapshotContents` during cluster deletion. These resources are forcefully deleted after a `1h` grace period which eventually lead to leaked snapshots on the cloud provider side. Hence, if the CSI-Snapshotter cannot delete affected snapshots successfully for `1h` (e.g. due to inconsistent data), operators/shoot-owners have to purge them manually.
```

2021-12-03 05:28 UTC, rfranzke commented
/assign
/squash

2021-12-03 07:27 UTC, rfranzke requested changes
Generally lgtm, thanks!
Still,
/needs second-opinion

2021-12-03 07:27 UTC, rfranzke commented on pkg/operation/botanist/cleanup.go
> +		cleanResourceFn(ops, c, &volumesnapshotv1beta1.VolumeSnapshotContentList{}, VolumeSnapshotContentCleanOption, FinalizeAfterOneHour),
Can we still respect the `cleanOptions` here, i.e., if somebody overwrote the default grace period with the `shoot.gardener.cloud/cleanup-kubernetes-resources-finalize-grace-period-seconds` annotation?

2021-12-07 16:32 UTC, timuthy commented
I added d14534c which implements the proposal mentioned in the PR description. It works perfectly for different scenarios, e.g.:
- Snapshot + Content are valid
- Snapshot is gone, Content is stuck in deletion

It's of course slightly implementation specific but still helps to eventually also delete the snapshots on the cloud provider side. Please let me know what you think about it.

PS: I'll add the missing unit tests for `volumeSnapshotContentCleaner` later if we decided to make use of it.

2021-12-08 07:48 UTC, MartinWeindel commented on pkg/utils/kubernetes/client/client.go
> +func (v volumeSnapshotContentCleaner) addDeleteAnnotation(ctx context.Context, c client.Client, obj client.Object, _ *CleanOptions) error {
You may also want to remove the annotation `snapshot.storage.kubernetes.io/volumesnapshot-being-created` if it is set. See [comment in issue 1505](https://github.tools.sap/kubernetes-canary/issues-canary/issues/1505#issuecomment-471097) where setting the `volumesnapshot-being-deleted` was not sufficient.

2021-12-14 07:23 UTC, rfranzke commented
I like the approach @timuthy, feel free to proceed as you planned :)

2021-12-14 07:24 UTC, rfranzke commented
/author-action

2021-12-16 11:44 UTC, timuthy commented
Thanks for the feedback @rfranzke and @MartinWeindel. I adapted the PR so that you can have another look.
/remove author-action

2021-12-20 05:54 UTC, rfranzke submitted a review, later dismissed
/lgtm

2021-12-20 05:54 UTC, rfranzke commented on pkg/utils/kubernetes/client/client.go
> +	// annVolumeSnapshotBeingDeleted triggers the CSI side-care to delete the snapshot on the infrastructure.
Do you mean sidecar?

2021-12-20 09:03 UTC, timuthy commented on pkg/utils/kubernetes/client/client.go
> +	// annVolumeSnapshotBeingDeleted triggers the CSI side-care to delete the snapshot on the infrastructure.
Yes 😄

2021-12-20 09:25 UTC, rfranzke approved these changes
/lgtm

2021-12-20 10:23 UTC, merged