Extract and collect error codes from ManagedResources
gardener/gardener pull request #5111
Opened 2021-12-02 21:10 UTC by timuthy

**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR makes the `WaitUntilManagedResourcesDeleted` to detect and extract error codes from the `ManagedResources` that is stuck in deletion.

**Release note**:

```feature operator
The error code detection has been enhanced for `ManagedResource` objects that are stuck when a shoot is deleted. This enables Gardener to assign the corresponding error code(s) to the shoot object.
```

2021-12-06 08:45 UTC, rfranzke requested changes

2021-12-06 08:45 UTC, rfranzke commented on pkg/apis/core/v1beta1/helper/errors.go
> +// MultiErrorWithCodes is a struct that contains multiple errors and `ErrorCodes`s.
```suggestion
// MultiErrorWithCodes is a struct that contains multiple errors and ErrorCodes.
```

2021-12-06 08:45 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot_control_delete.go
> +			Fn:           flow.TaskFn(botanist. CleanShootNamespaces).Timeout(10 * time.Minute).DoIf(cleanupShootResources),
Revert this

2021-12-07 09:45 UTC, timuthy commented
Thanks for your review @rfranzke. PTAL.

2021-12-07 09:50 UTC, rfranzke commented on pkg/apis/core/v1beta1/helper/errors.go
> +// MultiErrorWithCodes is a struct that contains multiple errors and ErrorCodess.
```suggestion
// MultiErrorWithCodes is a struct that contains multiple errors and ErrorCodes.
```

2021-12-07 14:52 UTC, rfranzke approved these changes
/lgtm

2021-12-09 08:34 UTC, merged