Eliminate client certificate for `cloud-config-downloader`
gardener/gardener pull request #5121
Opened 2021-12-06 14:15 UTC by rfranzke

**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
Similar to #4931, this PR eliminates the client certificate for the `cloud-config-downloader` in favor of a token managed by the `TokenRequestor` controller in `gardener-resource-manager`.

The basic idea is that `cloud-config-downloader` regularly downloads its own token from a `Secret` in the shoot cluster. This secret is used to communicate with the API server for further read requests (e.g., downloading the actual `cloud-config` `Secret` containing the user data for bootstrapping the node) and stored on a file on the disk (similar to how the legacy client certificate was stored).
If the node is newly created then the bootstrap token of the kubelet will be used for the initial reading of this `Secret`.

**Which issue(s) this PR fixes**:
Part of #4661
Part of #4878

**Special notes for your reviewer**:
/invite @BeckerMax
- For safety purposes, we enforce that upgrades must happen from Gardener v1.37 due to #5110.
- :x: Based on #5084 which needs to be merged (hence, PR is in "draft" state)

**Release note**:

```action operator
Before upgrading to this Gardener version make sure that your existing Gardener runs on at least `v1.37`.
```
```noteworthy operator
`cloud-config-downloader` does no longer use a client certificate but an auto-rotated `ServiceAccount` token which is only valid for `90d`.
```

2021-12-09 07:11 UTC, rfranzke commented
/ready

2021-12-09 07:21 UTC, timuthy commented
/assign

2021-12-15 15:14 UTC, danielfoehrKn requested changes
Worked just fine for me.
 - client cert got deleted from the node and replaced by the JWT token
 - no errors in the journal related to authentication errors
 - cloud-config-downloader secret, RBAC and roles created/updated

Might be a good chance to introduce client credentials per worker node. 
Currently (like before with x509 certs), each downloader-service has access to the cloud-config execution script for every node. 

```
   resourceNames:
  - cloud-config-cpu-worker-e06a3
  - cloud-config-large-e06a3
  resources:
  - secrets
  verbs:
  - get
```
By creating a service account + binding + role per worker pool we can ensure that after the bootstrap process each downloader has only a token authorized to access its own `cloud-config-*` secret.

2021-12-15 15:14 UTC, danielfoehrKn commented on pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader_test.go
> +echo "$TOKEN" > "$PATH_CLOUDCONFIG_DOWNLOADER_TOKEN"
Maybe add an additional check for an empty token before throwing away the client certificate.
There might be a temporary problem with the token requestor controller in the GRM .

Plus I would delete the client certs, only after successfully using the Token in the next statement.

2021-12-15 15:14 UTC, danielfoehrKn commented on pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader_test.go
> +echo "$TOKEN" > "$PATH_CLOUDCONFIG_DOWNLOADER_TOKEN"
This comment applies not only to the test code :)

2021-12-15 15:20 UTC, rfranzke commented on pkg/operation/botanist/component/extensions/operatingsystemconfig/downloader/downloader_test.go
> +echo "$TOKEN" > "$PATH_CLOUDCONFIG_DOWNLOADER_TOKEN"
Again, very great ideas! Thanks! Addressed in 927fbfc.

2021-12-15 15:21 UTC, rfranzke commented
> Might be a good chance to introduce client credentials per worker node.

Hm, not sure, probably we could talk about this separately (this PR only aims to eliminate the static credentials). Generally, I have some doubts whether this effort really paid out, but as said, let's potentially talk about it separately if needed. :)

2021-12-15 15:47 UTC, danielfoehrKn commented
Once a worker pool is reconciled with this code, it seems not to be possible to switch back (client cert gone & the existing token cannot get the updated cloud-config execution script).
I know that we generally do not support "downgrades" of gardenlets.
However, might be good to point out that irreversibility in the release notes.
It is of course up to you - I just realized this after switching back my local setup.

> Hm, not sure, probably we could talk about this separately (this PR only aims to eliminate the static credentials). Generally, I have some doubts whether this effort really paid out, but as said, let's potentially talk about it separately if needed. :)

ok, sure.

2021-12-15 15:47 UTC, danielfoehrKn approved these changes
Thanks for addressing the feedback.

2021-12-17 10:50 UTC, merged