Switch seed components to projected `ServiceAccount` tokens
gardener/gardener pull request #5128
Opened 2021-12-07 13:39 UTC by rfranzke

**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
Similar to #5099, this PR adapts all components deployed by Gardener into the shoot cluster to use projected `ServiceAccount` tokens (instead of the static tokens).

**Which issue(s) this PR fixes**:
Part of #4659
Part of #4878

**Special notes for your reviewer**:
- We have to trigger a rollout of the pods, hence, there is a change in the `.metadata.annotations` section of the respective pod templates.
- This PR depends on #5098 (released with `v1.37`), i.e., upgrading to a version containing this PR can only be done from at least Gardener v1.37.

**Release note**:

```action operator
Before upgrading to this Gardener version make sure that your existing Gardener runs on at least `v1.37`.
```
```noteworthy operator
All seed system components deployed by Gardener have been switched to projected `ServiceAccount` tokens (instead of continued usage of static tokens).
```

2021-12-14 10:16 UTC, danielfoehrKn commented
/assign

2021-12-15 11:43 UTC, danielfoehrKn requested changes
I had a problem with the statefulset `fluent-bit`. The rest of the pods mounted the projected tokens without a problem.

Events on the daemon-set
 > Warning  FailedCreate      33s (x16 over 7m13s)  daemonset-controller  (combined from similar events): Error creating: Pod "fluent-bit-9cph9" is invalid: spec.containers[0].volumeMounts[6].mountPath: Invalid value: "/var/run/secrets/kubernetes.io/serviceaccount": must be unique
 
Somehow for this staefulset, it seems like a service account volume is auto-added for the `fluent-bit` service account even though the service account specifies  `automountServiceAccountToken: false`.
 
I am not sure why that happens, but it might make sense to add an additional check in the projected token mount webhook to skip if the mount path already exists.

2021-12-15 12:06 UTC, rfranzke commented
Thanks for taking the time and checking it out, @danielfoehrKn! This was very valuable since it helped me realize that
1) the `fluent-bit` `Pod` still set `.spec.automountServiceAccountToken=true` which made the default SA mount admission plugin interfere with GRM's SA mount webhook
2) the `grafana` `Pod` was not setting `.spec.automountServiceAccountToken=false` which made it having the `default` SA mount.

I've added 4f49340 which addresses the two facts. Please take another look!

2021-12-15 13:04 UTC, danielfoehrKn commented
What is the difference between  setting
> .spec.automountServiceAccountToken=false

and removing it entirely? 
I am asking because I see that for fluent-bit you removed the field, while on Grafanam you set it to `false`

2021-12-15 13:12 UTC, rfranzke commented
When `.spec.automountServiceAccountToken` is set to `false` then there will be no auto-mount from the Kubernetes SA mount plugin. For the behaviour of the projected token mount you might want to look into https://github.com/gardener/gardener/pull/5002/commits/b7738d253f5f3efe28ceb8464a64b79787bd675d:

> The desired behaviour is: If the `Pod`'s `.spec.serviceAccountName` is set and `ServiceAccount`s '.automountServiceAccounToken=false` and ...
> - ... `Pod`s `.spec.automountServiceAccountToken=nil` -> inject
> - ... `Pod`s `.spec.automountServiceAccountToken=true` -> inject
> - ... `Pod`s `.spec.automountServiceAccountToken=false` -> do not inject

> EDIT: got it, you do not want a projected services account for grafana

Yes, Grafana doesn't communicate with KAPI at all, so no need to mount a `ServiceAccount` in the first place.

2021-12-15 13:13 UTC, danielfoehrKn approved these changes
/lgtm works

2021-12-15 13:16 UTC, merged