Revert hvpa-controller to use static `ServiceAccount` token
gardener/gardener pull request #5228
Opened 2022-01-06 09:49 UTC by ialidzhikov

/area control-plane
/kind bug
/kind regression

As explained in https://github.com/gardener/gardener/issues/5222 `hvpa-controller@v0.3.1` is not ready for usage of projected `ServiceAccount` tokens. This PR reverts the component to use static `ServiceAccount` token. Migration to projected `ServiceAccount` tokens can happen when hvpa-controller vendor client-go >= v0.15.7.

Fixes #5222

**Release note**:

```bugfix operator
hvpa-controller component is reverted back to use static `ServiceAccount` tokens as currently the component cannot properly handle project `ServiceAccount` tokens.
```

2022-01-06 09:49 UTC, ialidzhikov commented
/invite @rfranzke

2022-01-06 12:35 UTC, BeckerMax commented
/assign

2022-01-07 03:00 UTC, BeckerMax requested changes

2022-01-07 03:00 UTC, BeckerMax commented on charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
> -automountServiceAccountToken: false
I would propose to also place the if condition: `{{- if .Values.global.readyForProjectedServiceAccountTokens }}`  around here.
With this the projectedVolume will not be injected and the old static SA-token is used until we switch it with this flag. Probably was intended like this in the first place.

2022-01-07 08:34 UTC, rfranzke approved these changes
/lgtm

2022-01-07 12:37 UTC, BeckerMax approved these changes
/lgtm

2022-01-07 13:07 UTC, merged