WIP: Execute Terraform, Kube2IAM only in maintenance
gardener/gardener pull request #528
Opened 2018-11-15 14:16 UTC by timuthy

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2018-11-15 14:25 UTC, rfranzke requested changes

2018-11-15 14:25 UTC, rfranzke commented on pkg/controller/shoot/shoot_control_reconcile.go
> +		requireInfrastructureDeployment = creationPhase || controllerutils.HasTask(o.Shoot.Info.Annotations, common.ShootTaskDeployInfrastructur)
typo

2018-11-15 14:25 UTC, rfranzke commented on pkg/controller/shoot/shoot_control_reconcile.go
> +	// Remove task list from Shoot annotations since reconciliation was successful.
I would first update the shoot annotations (before updating the status).

2018-11-15 14:25 UTC, rfranzke commented on pkg/controller/shoot/shoot_maintenance_control.go
> +		controllerutils.AddTasks(s.Annotations, common.ShootTaskDeployInfrastructur, common.ShootTaskDeployKube2IAMResource)
typo

2018-11-15 14:25 UTC, rfranzke commented on pkg/controller/utils/miscelleneous.go
> +			return
Should be `continue`

2018-11-15 14:25 UTC, rfranzke commented on pkg/controller/utils/miscelleneous.go
> +		if len(existingTasks) > 0 {
Why not adding the needed tasks to a `[]string` and then use `strings.Join(val, separator)`?

2018-11-15 14:46 UTC, Adracus commented on pkg/controller/utils/miscelleneous.go
> +		if len(existingTasks) > 0 {
+1

2018-11-16 09:16 UTC, rfranzke approved these changes
/lgtm

2018-11-16 09:18 UTC, merged