Increase number of max connections to 8192
gardener/gardener pull request #5379
Opened 2022-02-02 10:35 UTC by DockToFuture

**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
This PR increases the number of max connections for envoy-proxy sidecar in vpn-seed-server to `8192`.
We saw on some shoot clusters that the default value of a maximum of 1024 connection was not sufficient for the envoy-proxy and led to a lot of 408 errors because the buffer of the envoy-proxy was overflowing.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Increase number of max connections to `8192` for envoy-proxy sidecar in vpn-seed-server.
```

2022-02-02 11:20 UTC, ialidzhikov commented on pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
> +        - maxConnections: 8192
Shouldn't this be indented as

```suggestion
    circuitBreakers:
      thresholds:
      - maxConnections: 8192
```

?

2022-02-02 11:28 UTC, ScheererJ commented on pkg/operation/botanist/component/vpnseedserver/vpn_seed_server.go
> +        - maxConnections: 8192
Agreed.

2022-02-02 11:28 UTC, ScheererJ requested changes
Please fix the indentation.

2022-02-02 11:32 UTC, ScheererJ approved these changes

2022-02-03 14:44 UTC, ialidzhikov approved these changes
/lgtm

2022-02-04 07:20 UTC, ialidzhikov commented
/milestone v1.40

2022-02-04 07:22 UTC, merged