Introduce validation for max worker node count
gardener/gardener pull request #5389
Opened 2022-02-03 07:49 UTC by shafeeqes

**How to categorize this PR?**

/area networking ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR introduces a validation for the total number of worker nodes in a shoot cluster.
The configured worker pools max Nodes count does not exceed max Nodes count allowed by the Pods CIDR (`spec.networking.pods`). The Pod network calculations that has to be considered are described in https://github.com/gardener/gardener/blob/v1.38.3/docs/usage/shoot_networking.md.
Also, the `nodeCIDRMaskSize` can be customized with the field `spec.kubernetes.kubeControllerManager.nodeCIDRMaskSize`.

**Which issue(s) this PR fixes**:
Fixes #5298 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-02-03 07:49 UTC, shafeeqes commented
/test all

2022-02-03 16:23 UTC, shafeeqes commented
/test all

2022-02-03 16:44 UTC, shafeeqes commented
This PR is /ready for review.
/invite @ialidzhikov

2022-02-03 16:57 UTC, ialidzhikov commented
/assign @ScheererJ @DockToFuture

2022-02-07 07:32 UTC, rfranzke requested changes

2022-02-07 07:32 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +func ValidateShootSpec(meta metav1.ObjectMeta, spec *core.ShootSpec, fldPath *field.Path, inTemplate, isUpdate bool) field.ErrorList {
Why do you introduce an `isUpdate` parameter here when there is already a `ValidateShootSpecUpdate` function? This confusing. Can't you run your function in https://github.com/gardener/gardener/pull/5389/files#diff-a04dba2257c8893abf53b88a89b74aad4031f17b636f5d1e975e5b1dc8daa835R123?

2022-02-07 07:32 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +	CIDR, _ := strconv.Atoi(podNetworkCIDR[len(podNetworkCIDR)-2:])
Why is the error ignored? Also, use lower case

2022-02-07 07:32 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +		allErrs = append(allErrs, field.Invalid(field.NewPath("spec").Child("provider").Child("workers"), totalNodes, fmt.Sprintf("worker configuration incorrect. The spec.networking.pod only supports %d I
```suggestion
		allErrs = append(allErrs, field.Invalid(field.NewPath("spec").Child("provider").Child("workers"), totalNodes, fmt.Sprintf("worker configuration incorrect. The value in `.spec.networking.pods` only supports %d IP addresses. The total of all the nodes specified by the worker pool should be less than %d ", maxNodeCount, maxNodeCount)))
```

2022-02-07 15:53 UTC, ScheererJ requested changes

2022-02-07 15:53 UTC, ScheererJ commented on pkg/apis/core/validation/shoot.go
> +	CIDR, _ := strconv.Atoi(podNetworkCIDR[len(podNetworkCIDR)-2:])
Please use `net.ParseCIDR(...)` instead. The code is not valid for big ranges, e.g. /8. Reusing existing libraries is certainly the better approach.

2022-02-07 15:53 UTC, ScheererJ commented on pkg/apis/core/validation/shoot.go
> +		allErrs = append(allErrs, field.Invalid(field.NewPath("spec").Child("provider").Child("workers"), totalNodes, fmt.Sprintf("worker configuration incorrect. The spec.networking.pod only supports %d I
`maxNodeCount` is not the number of IP addresses. I do not understand the error message. Please adapt the second sentence so that it makes sense.

2022-02-11 08:26 UTC, ScheererJ approved these changes, later dismissed
/lgtm

2022-02-11 08:26 UTC, ScheererJ commented on pkg/apis/core/validation/shoot.go
> +	cidrMask, _ := podNetwork.Mask.Size()
Nit: `Mask.Size()` may return `(0,0)` if the mask is incorrect. Therefore, you could potentially check for this error condition. However, it is fair to assume that `net.ParseCIDR()` provides a proper mask.

2022-02-11 10:41 UTC, ScheererJ approved these changes
/lgtm

2022-02-14 08:23 UTC, rfranzke approved these changes
/lgtm

2022-02-14 08:23 UTC, merged