Use secretref to provide bootstrap kubeconfig
gardener/gardener pull request #5425
Opened 2022-02-09 09:11 UTC by fynluk

**How to categorize this PR?**

/area usability
/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR improved the HelmChart handling.

I created a new HelmChart value to avoid inline bootstrapkubeconfig. 
With this approach, you can now reference a kubeconfig for the bootstrap process instead of inline provisioning.

Use this new values to reference a secret: `values.yaml`
```yaml
global:
  gardenlet:
    gardenClientConnection:
      bootstrapKubeconfig:
        secretRef:
          name: <name of the secret>
          namespace: <namespace of the secret>
```

The install process of the gardenlet needs a bootstrap kubeconfig with a token. This token should be in general auto-generated, so I needed a HelmChart process to include this. I build a setup (outside of the gardenlet helm chart) to generate the token and also the bootstrap kubeconfig. Without this change, I have to provide this kubeconfig inline which is impossible with helm functions.
So that's the motivation of this PR

**Release note**:

```other operator
NONE
```

2022-02-10 07:36 UTC, timebertt commented
/ok-to-test

2022-02-14 08:26 UTC, rfranzke requested changes

2022-02-14 08:26 UTC, rfranzke commented on charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
> +        namespace: {{ required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.namespace is required" .Values.global.gardenlet.config.gardenClientConnection.boot
`secretRef` is missing here?

2022-02-14 08:26 UTC, rfranzke commented on charts/gardener/gardenlet/values.yaml
> +      #     namespace: namespace of your bootstrapKubeconfig
Can you maybe add some comments here? I think it's confusing now that there is `name/namespace` and then `secretRef.name/secretRef.namespace`. A short sentence explaining the difference would shed some light :)

2022-02-17 10:21 UTC, rfranzke commented
/author-action

2022-02-21 08:17 UTC, fynluk commented
Sorry for my absence, I was on holiday. 

I added some documentation as you mentioned, but I didn't understand your first review. secretRef is given in lines 35 and 36. 
```yaml
        {{- if .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef }}
        name: {{ required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.name is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.name }}
        namespace: {{ required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.namespace is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.namespace }}
```
In the first line, I am checking if a secretRef is given. If so, the secret name and ns is stored in the configmap. If not, the bootstrapKubeconfig.name/ns fields are used

2022-02-22 07:05 UTC, rfranzke requested changes

2022-02-22 07:05 UTC, rfranzke commented on charts/gardener/gardenlet/charts/runtime/templates/configmap-componentconfig.yaml
> +        namespace: {{ required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.namespace is required" .Values.global.gardenlet.config.gardenClientConnection.boot
Maybe I'm missing something, but shouldn't it look like this:

```yaml
      bootstrapKubeconfig:
        {{- if .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef }}
        secretRef:
          name: {{ required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.name is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.name }}
          namespace: {{ required ".Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.namespace is required" .Values.global.gardenlet.config.gardenClientConnection.bootstrapKubeconfig.secretRef.namespace }}
        {{- else }}
```

2022-02-23 07:27 UTC, fynluk commented
My understanding the componentconfig is bound as config for the gardenlet. And the bootstrapKubeconfig.secret/ns tells the gardenlet which secret he can use for the bootstrap process, isn't it?
So manipulating the componentconfig would trigger a code change.

2022-02-23 07:30 UTC, rfranzke commented
You're right, of course... :) I missed this. Thanks!

2022-02-23 07:30 UTC, rfranzke approved these changes
/lgtm

2022-02-25 13:25 UTC, merged