Mutually exclusive optional `HibernationSchedule.Start/End`
gardener/gardener pull request #543
Opened 2018-11-21 14:53 UTC by Adracus

**What this PR does / why we need it**:
Make `HibernationSchedule.Start/End` mutually exclusive. This allows to define HibernationSchedules that only wake up or only hibernate a Shoot (@petersutter thx for the idea).

**Special notes for your reviewer**:

**Release note**:

```improvement user
In a `HibernationSchedule`, `start` or `end` can now be omitted (although always one of both needs to be specified). This allows to have schedules that only hibernate or only wake up a Shoot.
```

2018-11-21 14:56 UTC, rfranzke requested changes

2018-11-21 14:56 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +	Start *string `json:"start"`
omitempty

2018-11-21 14:56 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
>  	// Start is a Cron spec at which time a Shoot will be hibernated.
//+optional missing

2018-11-21 14:56 UTC, rfranzke commented on pkg/apis/garden/types.go
>  	// Start is a Cron spec at which time a Shoot will be hibernated.
//+optional missing

2018-11-21 14:56 UTC, rfranzke commented on pkg/apis/garden/types.go
>  	// End is a Cron spec at which time a Shoot will be woken up.
//+optional missing

2018-11-21 14:56 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
>  	// End is a Cron spec at which time a Shoot will be woken up.
//+optional missing

2018-11-21 14:56 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
> +	End *string `json:"end"`
omitempty

2018-11-21 15:07 UTC, adracus commented
Sorry, forgot the `omitempty` / `optional` - was already fixing it.

2018-11-22 06:47 UTC, rfranzke requested changes

2018-11-22 06:47 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
>  	// Start is a Cron spec at which time a Shoot will be hibernated.
// +optional is still missing

2018-11-22 06:47 UTC, rfranzke commented on pkg/apis/garden/v1beta1/types.go
>  	// End is a Cron spec at which time a Shoot will be woken up.
// +optional is still missing

2018-11-22 13:19 UTC, rfranzke approved these changes
/lgtm

2018-11-23 08:09 UTC, merged