[GEP-18] Adapt `monitoring-ingress-credentials{-users}` to new secrets manager
gardener/gardener pull request #5608
Opened 2022-03-18 07:50 UTC by rfranzke

**How to categorize this PR?**

/area security
/kind enhancement
/merge squash

**What this PR does / why we need it**:
This PR adapts the `monitoring-ingress-credentials{-users}` secrets to new secrets manager. Those secrets are used to secure the two exposed Grafana instances deployed for each shoot control plane.;

Additionally, the seed controller also deploys a Grafana and secures it with a similar secret. This one is generated by `gardener-controller-manager` on start-up (`garden.BootstrapCluster` function) and then replicated in each seed namespace in the garden. From there, the gardenlet's seed controller picks it up and uses it.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3292#issuecomment-1036058890

/invite @timebertt @BeckerMax 
/invite @wyb1 @istvanballok

**Release note**:

```noteworthy user
NONE
```

2022-03-30 06:49 UTC, BeckerMax commented
/assign

2022-03-30 07:35 UTC, ary1992 reviewed
Nit

2022-03-30 07:35 UTC, ary1992 commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	// credentials for observability components
```suggestion
	// credentials for observability components.
```

2022-03-30 08:36 UTC, rfranzke commented
/cla

2022-03-31 12:44 UTC, BeckerMax requested changes
See all my feedback here as suggestions. Resolve/Apply as you find appropriate.
Tested it and functionality-wise works as expected.

2022-03-31 12:44 UTC, BeckerMax commented on pkg/utils/encoding.go
>  // CreateSHA1Secret takes a username and a password and returns a sha1-schemed credentials pair as string.
comment outdated

2022-03-31 12:44 UTC, BeckerMax commented on pkg/operation/garden/garden.go
> +	if err := secretsManager.Cleanup(ctx); err != nil {
I would move this Cleanup function either at the end of BootstrapCluster function or maybe in the [Run func](https://github.com/gardener/gardener/blob/176d4179148aa3dca13e5ede1ba1236d622cb488/pkg/controllermanager/controller/factory.go#L87) to give it more visibility. Reason is it has effects on potentially new secrets created with this identity and it is kind of hidden in this func deep down.

2022-03-31 12:44 UTC, BeckerMax commented on pkg/operation/garden/garden.go
> +	if numberOfGlobalMonitoringSecrets > 1 {
Is this like a safety check if something went wrong with the secret creation? Or why do we need this here?

2022-03-31 12:44 UTC, BeckerMax commented on pkg/utils/secrets/manager/generate.go
> +		if configName != "kube-apiserver-basic-auth" {
I would be explicit here:
```suggestion
		if configName == "observability-ingress" ||  configName ==  "observability-ingress-users" {
```
a bit more straight-forward to read and guards against future bugs in case you add other old secrets which should be kept (which might not want BasicAuthFormatNormal).

2022-03-31 13:15 UTC, rfranzke commented on pkg/operation/garden/garden.go
> +	if numberOfGlobalMonitoringSecrets > 1 {
Well, it doesn't make sense to have more than one of these secrets. This check was simply missing, so I added it.

2022-03-31 13:43 UTC, BeckerMax approved these changes
/lgtm

2022-03-31 13:45 UTC, merged