Improve the hibernation doc
gardener/gardener pull request #5621
Opened 2022-03-21 13:48 UTC by ialidzhikov

/area documentation

Fixes https://github.com/gardener/gardener/issues/5606

**Release note**:

```other operator
NONE
```

2022-03-21 13:49 UTC, ialidzhikov commented
/invite @n-boshnakov

2022-03-22 10:08 UTC, n-boshnakov requested changes

2022-03-22 10:08 UTC, n-boshnakov commented on docs/usage/shoot_hibernate.md
> +The `.spec.hibernation.enabled` field specifies whether the cluster needs to be hibernated or not. If the field is set to `true`, the cluster's desired state is to be hibernated. If it is set to `fal
```suggestion
The `.spec.hibernation.enabled` field specifies whether the cluster needs to be hibernated or not. If the field is set to `true`, the cluster's desired state is to be hibernated. If it is set to `false` or not specified at all, the cluster's desired state is to be awakened.
```

2022-03-22 11:12 UTC, n-boshnakov approved these changes
lgtm

2022-03-22 16:47 UTC, rfranzke approved these changes
/lgtm
/milestone v1.43

2022-03-22 17:38 UTC, merged