Add validation for locked feature gate
gardener/gardener pull request #5667
Opened 2022-03-28 06:35 UTC by acumino

**How to categorize this PR?**

/area ops-productivity
/kind bug

**What this PR does / why we need it**:
This PR adds validation for the locked feature gates. Now Gardener forbids upgrading clusters if the feature gate is locked to default and the user wants to set a value that does not default.

**Which issue(s) this PR fixes**:
Fixes #5362

**Special notes for your reviewer**:
This PR adds doesn't add validation for the feature gate which has been removed in any of the Kubernetes versions supported by the Gardener.

**Release note**:

```other operator
NONE
```

2022-03-28 06:40 UTC, rfranzke commented
/assign

2022-03-28 06:43 UTC, rfranzke requested changes
Thanks!

Can you please adapt the script to fetch this information (https://github.com/gardener/gardener/blob/master/hack/compare-k8s-feature-gates.sh), the explanation doc string (https://github.com/gardener/gardener/blob/96dd4b835cdd80803560060d49847249ddcc68f7/pkg/utils/validation/features/featuregates.go#L27-L31) and the docs for supporting a new Kubernetes version (https://github.com/gardener/gardener/blob/master/docs/development/new-kubernetes-version.md#adapting-gardener)?

2022-03-28 06:43 UTC, rfranzke commented on pkg/utils/validation/features/featuregates_test.go
> +			Entry("setting non-default value for lockedfeaturegate", map[string]bool{"EndpointSlice": false}, "1.21.5", ConsistOf(PointTo(MatchFields(IgnoreExtras, Fields{
```suggestion
			Entry("setting non-default value for locked feature gate", map[string]bool{"EndpointSlice": false}, "1.21.5", ConsistOf(PointTo(MatchFields(IgnoreExtras, Fields{
```

2022-03-28 08:03 UTC, rfranzke commented
The explanation doc string is not yet adapted.

2022-03-28 08:05 UTC, acumino commented
> The explanation doc string is not yet adapted.

The function I have added is not exported do we still need Doc string?

2022-03-28 08:06 UTC, rfranzke commented
I am talking about:

> the explanation doc string (https://github.com/gardener/gardener/blob/96dd4b835cdd80803560060d49847249ddcc68f7/pkg/utils/validation/features/featuregates.go#L27-L31)

2022-03-29 06:01 UTC, rfranzke reviewed
Nit

2022-03-29 06:01 UTC, rfranzke commented on docs/development/new-kubernetes-version.md
> +  - For feature gates locked to default, add `<new-version>` as LockedToDefaultInVersion to the already existing feature gate in the map.
```suggestion
  - For feature gates locked to default, add `<new-version>` as `LockedToDefaultInVersion` to the already existing feature gate in the map.
```

2022-03-29 08:40 UTC, rfranzke approved these changes
/lgtm

2022-03-29 09:13 UTC, merged