Fix cloud config updates & docker issue
gardener/gardener pull request #568
Opened 2018-11-29 16:29 UTC by Adracus

**What this PR does / why we need it**:
Fix orphan containers being created during regular cloud config sync.
Enable rollout of cloud config fixes via secret content update.

**Which issue(s) this PR fixes**:
Fixes #560

**Special notes for your reviewer**:

**Release note**:

```noteworthy user
⚠️ An issue with orphaned containers being created during the node's cloud config syncs has been fixed. Deploying this change requires a rolling update of all worker nodes of all shoot clusters.
```

2018-11-30 04:47 UTC, vlerenc commented
Very good, another critical issue resolved. I am wondering how we could protect us from this in the future. I hope we can write integration tests and make sanity checks afterwards like scanning the logs for warnings and errors or check certain things like how many outbound calls (to the infrastructure where made), were there any left overs, e.g. IaaS resources like volumes, and things like to the pods/containers match the actual containers on the file system (there are a ton of more things to check of course). I know that fixing the issue was of highest priority, but maybe we can hve a chat after the patch release, how it can become easy/easier to write/add such checks in the future. The easier it is, the more often we will do it, which is in the end the only thing that can protect us, would you agree?

2018-11-30 07:32 UTC, rfranzke requested changes

2018-11-30 07:32 UTC, rfranzke commented on charts/shoot-cloud-config/charts/downloader/templates/cloud-config/_download-cloud-config.sh
>      kubectl "$@"
Can we remove the volumes mounts

```bash
     -v "$DIR_CLOUDCONFIG"/:"$DIR_CLOUDCONFIG" \
     -v "$DIR_CLOUDCONFIG_DOWNLOADER"/:"$DIR_CLOUDCONFIG_DOWNLOADER" \
```

in the `kubectl` function now?

2018-11-30 07:32 UTC, rfranzke commented on charts/shoot-cloud-config/charts/downloader/templates/cloud-config/_download-cloud-config.sh
>      kubectl "$@"
Let's bump hyperkube to `v1.12.3` if we now need to touch the script anways.

2018-11-30 07:32 UTC, rfranzke commented on charts/shoot-cloud-config/charts/downloader/templates/cloud-config/_download-cloud-config.sh
>  mkdir -p "$DIR_CLOUDCONFIG" "$DIR_KUBELET"
The downloaded script can do it on its own, right?
Can we remove this (same applies for the used variables)?

2018-11-30 07:32 UTC, rfranzke commented on charts/shoot-cloud-config/charts/original/templates/_cloud-config-script.tpl
> +    k8s.gcr.io/hyperkube:v1.9.3 \
Let's bump hyperkube to `v1.12.3` if we now need to touch the script anways.

2018-11-30 07:32 UTC, rfranzke commented on pkg/operation/hybridbotanist/cloud_config.go
> +		"kubeconfig": b.Secrets["cloud-config-downloader"].Data["kubeconfig"],
Why is this here? Seems not to be used anywhere, nor is it part of the `values.yaml`.

2018-11-30 09:20 UTC, timuthy requested changes

2018-11-30 09:20 UTC, timuthy commented on pkg/operation/hybridbotanist/cloud_config.go
> +	config, err = b.InjectImages(config, b.ShootVersion(), b.ShootVersion(), common.RubyImageName, common.HyperkubeImageName)
Just for sake of integrity, can you add the RubyImage to https://github.com/gardener/gardener/blob/90c0d6aa6150f3a265dcb5b77b2426a2f9947817/charts/shoot-cloud-config/charts/original/values.yaml?

2018-11-30 10:28 UTC, timuthy approved these changes

2018-11-30 11:54 UTC, Adracus commented
@vlerenc agree regarding your idea, in general we need more well-typed and well-tested code where we know about the side effects. However, in particular for bash scripts I don't immediately see a handful of measures other than replacing them by proper binaries (which lead to other required builds / other problems?). As said, let's have a chat afterwards.

2018-11-30 12:32 UTC, rfranzke approved these changes
/lgtm

2018-11-30 12:33 UTC, merged

2018-12-01 10:47 UTC, vlerenc commented
Yes, unit tests for bash scripts suck and writing both in Go makes things certainly better/easier. But I am thinking about something different here: I am concerned about side effects and finding a way to properly test for those. This is unrelated to the flow, whether there were bash scripts or binaries at work. It's about finding a way to plug in tests that take a look at the system, while it is running or towards the end, and raise test failures. E.g. we may decide not to want warnings and errors in our Gardener API/Ctr logs after running the test or we may decide to inspect the pods and their state (all running, no restarts) or we may decide to inspect the Docker daemon before we destroy the machine and make sure there are no surprising Docker containers (especially, if we ran into that problem once, so that we never again run into the problem). Only when we reach this level of testing, beyond unit tests, we will get better/reach higher quality.