[GEP-18] Adapt extensions library to new secrets manager
gardener/gardener pull request #5803
Opened 2022-04-13 14:48 UTC by timebertt

**How to categorize this PR?**

/area security
/kind enhancement

**What this PR does / why we need it**:

This PR adapts the extensions library to the new secrets manager. This is a prerequisite for making extensions ready for full support of the CA rotation feature.
It includes the following parts

- document what needs to be done in extensions to support the shoot CA rotation
- cleanup `useTokenRequestor` flags, as it is required now (we can't generate client certificates any more in extensions) and enough time for migration has passed
- add SecretsManager utilities for extensions
- adapt generic `ControlPlane` actuator to new secrets manager (more or less the only part in the extension library that needs to be adapted)
- ❌ implement dummy `ControlPlane` / `ValuesProvider` in provider-local as a test case, verify in e2e test
- ❌ test things manually with another provider extension

**Which issue(s) this PR fixes**:
Part of #3292

**Special notes for your reviewer**:

Opened as draft for early feedback, in draft until the above points are completed as well.

**Release note**:

```other operator
TODO
```

2022-04-13 14:52 UTC, timebertt commented
/test all

2022-04-14 07:53 UTC, timebertt commented
/test all

2022-04-14 10:55 UTC, timebertt commented
I managed to find the cause for a flaky test behavior while running it locally. Now, the CA rotation e2e test should be more stable.
/test pull-gardener-e2e-kind

2022-04-14 12:23 UTC, timebertt commented
Alright, g/g part of this PR is finished. However, I will keep it in draft state until I have verified it in provider-aws e2e. (will do next week)
/test all

2022-04-19 13:43 UTC, timebertt commented
Rebased onto current master (without changes in commits)

2022-04-19 13:46 UTC, timebertt commented
/test all

2022-04-19 13:49 UTC, rfranzke requested changes

2022-04-19 13:49 UTC, rfranzke commented on docs/development/secrets_management.md
> +- On initialization of a `SecretsManager`, pass an `identity` specific to the component, controller and purpose. For example, gardenlet's shoot controller uses `gardenlet` as the `SecretsManager`'s i
Nit:

```suggestion
- On initialization of a `SecretsManager`, pass an `identity` specific to the component, controller and purpose. For example, gardenlet's shoot controller uses `gardenlet` as the `SecretsManager`'s identity, the `Worker` controller in `provider-foo` should use `provider-foo-worker` and the `ControlPlane` controller should use `provider-foo-controlplane-exposure` for `ControlPlane` objects of purpose `exposure`.  
```

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/ca-rotation.md
> +# CA Rotation in Extensions
Please add this doc to the index (`docs/README.md`)

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/ca-rotation.md
> +[GEP-18](../proposals/18-shoot-CA-rotation.md) adds support for automated rotation of Shoot cluster certificate authorities (CAs).
```suggestion
[GEP-18](../proposals/18-shoot-CA-rotation.md) proposes adding support for automated rotation of Shoot cluster certificate authorities (CAs).
```

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/ca-rotation.md
> +This document outlines all requirements, that Gardener extensions need to fulfill in order to support the CA rotation feature.
```suggestion
This document outlines all requirements that Gardener extensions need to fulfill in order to support the CA rotation feature.
```

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/ca-rotation.md
> +In order to fulfill the requirements listed above, extension controllers can reuse the [`SecretsManager`](../development/secrets_management.md), that gardenlet uses to manage all shoot cluster CAs, c
```suggestion
In order to fulfill the requirements listed above, extension controllers can reuse the [`SecretsManager`](../development/secrets_management.md) that gardenlet uses to manage all shoot cluster CAs, certificates, and other secrets as well.
```

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/ca-rotation.md
> +          Name:       "ca-provider-foo-controlplane",
Nit: Extract the name in a variable that can be re-used in the `SignedByCA` option to prevent duplication

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/ca-rotation.md
> +  E.g., there should be different identities for `infrastructrue`, `worker` controller etc. and the `controlplane` controller should use dedicated `SecretsManager` identities per purpose (e.g. `provi
```suggestion
  E.g., there should be different identities for `Infrastructure`, `Worker` controller etc. and the `ControlPlane` controller should use dedicated `SecretsManager` identities per purpose (e.g. `provider-foo-controlplane` and `provider-foo-controlplane-exposure`).
```

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/conventions.md
> +With [gardener/gardener#4661](https://github.com/gardener/gardener/issues/4661) we moved away from using client certificates in favor of short-lived auto-rotated `ServiceAccount` tokens. These tokens
```suggestion
With [gardener/gardener#4661](https://github.com/gardener/gardener/issues/4661) we moved away from using client certificates in favor of short-lived, auto-rotated `ServiceAccount` tokens. These tokens are managed by gardener-resource-manager's [`TokenRequestor`](../concepts/resource-manager.md#tokenrequestor).
```

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/conventions.md
> +With [GEP-18](../proposals/18-shoot-CA-rotation.md) (Shoot cluster CA rotation), a dedicated CA will be used for signing client certificates ([gardener/gardener#5779](https://github.com/gardener/gard
```suggestion
With [GEP-18](../proposals/18-shoot-CA-rotation.md) (Shoot cluster CA rotation), a dedicated CA will be used for signing client certificates ([gardener/gardener#5779](https://github.com/gardener/gardener/pull/5779)) which will be rotated when triggered by the shoot owner.
```

2022-04-19 13:49 UTC, rfranzke commented on docs/extensions/conventions.md
> +The `generic-token-kubeconfig` secret contains the CA bundle for establishing trust to shoot API servers. However, as the secret is immutable its name changes with the rotation of the Cluster CA.
```suggestion
The `generic-token-kubeconfig` secret contains the CA bundle for establishing trust to shoot API servers. However, as the secret is immutable, its name changes with the rotation of the cluster CA.
```

2022-04-19 13:49 UTC, rfranzke commented on extensions/pkg/util/secret/manager/manager.go
> +	}
```suggestion
	if shootStatus := cluster.Shoot.Status; shootStatus.Credentials != nil && shootStatus.Credentials.Rotation != nil &&
	shootStatus.Credentials.Rotation.CertificateAuthorities != nil && 
	shootStatus.Credentials.Rotation.CertificateAuthorities.LastInitiationTime != nil {
		timeCopy := shootStatus.Credentials.Rotation.CertificateAuthorities.LastInitiationTime.Time
		caLastInitiationTime = &timeCopy
	}
```

2022-04-19 13:49 UTC, rfranzke commented on extensions/pkg/util/secret/manager/manager.go
> +func LastSecretRotationStartTimesFromCluster(cluster *extensionscontroller.Cluster, secretConfigs []SecretConfigWithOptions) map[string]time.Time {
Can this function become unexported?

2022-04-19 13:49 UTC, rfranzke commented on extensions/pkg/util/secret/manager/manager.go
> +func FilterCAConfigs(secretConfigs []SecretConfigWithOptions) []SecretConfigWithOptions {
Can this function become unexported?

2022-04-19 13:49 UTC, rfranzke commented on extensions/pkg/util/secret/manager/manager_suite_test.go
> +	RunSpecs(t, "SecretsManager Utils Suite")
```suggestion
	RunSpecs(t, "Extensions Utils SecretsManager Suite")
```

2022-04-19 13:49 UTC, rfranzke commented on extensions/pkg/controller/controlplane/genericactuator/actuator.go
> +	secretsFunc func(namespace string) []extensionssecretsmanager.SecretConfigWithOptions, shootAccessSecrets func(namespace string) []*gutil.ShootAccessSecret,
Nit: Align this variable name with the shoot access secrets, i.e., either call it `secretConfigs`, or rename it to `secretConfigsFunc` and rename `shootAccessSecrets` to `shootAccessSecretsFunc`.

Same for exposure secrets.

2022-04-19 13:49 UTC, rfranzke commented on test/e2e/shoot/create_rotate-ca_delete.go
> +		HaveKeyWithValue(providerLocalDummyServer, HaveLen(1)),
Do you also want to add a client cert here and check that it already got renewed?

2022-04-19 15:14 UTC, timebertt commented
Thank you @rfranzke for your review. I addressed all your suggestions :)
/test all

2022-04-20 07:36 UTC, rfranzke commented on docs/development/secrets_management.md
> +
Nit: Why there is this empty line? :)

2022-04-20 07:40 UTC, timebertt commented on docs/development/secrets_management.md
> +
Ooops 🙈

2022-04-20 13:03 UTC, timebertt commented
/test all

2022-04-20 16:02 UTC, timebertt commented
I manually tested this PR e2e with https://github.com/gardener/gardener-extension-provider-aws/pull/538.
I successfully created a shoot and the new dedicated CA was created along with server certs for ccm and csi snapshot validator.
On shoot CA rotation they were rotated as desired, the secrets were successfully transported to components and webhook config and the old secrets got cleaned up afterwards.

With this, I consider this PR ready to be merged.
As discussed, let's get it in before the release. 
/milestone v1.45
cc @acumino

2022-04-21 06:29 UTC, rfranzke reviewed
/lgtm
/approve

2022-04-21 06:34 UTC, timebertt commented
Because of https://github.com/gardener/gardener-extension-provider-aws/pull/538#issuecomment-1104045687, I dropped the commit that cleaned up the `useProjectedTokenMount` flag in the terraformer library.
Instead, it is now defaulted to true, but can be disabled for testing purposes.
@rfranzke PTAL :)

2022-04-21 06:53 UTC, rfranzke reviewed
/lgtm

2022-04-21 07:56 UTC, timebertt commented
/retest

2022-04-21 10:14 UTC, acumino commented
/retest

2022-04-21 10:17 UTC, timebertt commented
/retest

2022-04-21 11:04 UTC, merged