Fix disabling of seed VPA
gardener/gardener pull request #5811
Opened 2022-04-15 12:46 UTC by stoyanr

**How to categorize this PR?**

/area auto-scaling
/kind bug

**What this PR does / why we need it**:
Ensures that the seed VPA is properly destroyed when the corresponding seed setting is false, fixing the previous issue introduced with #5745.

**Which issue(s) this PR fixes**:
Fixes #5810 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Seed VPA is now properly destroyed if the corresponding seed setting is false.
```

2022-04-15 12:47 UTC, stoyanr commented
/invite @andrerun @ialidzhikov

2022-04-15 13:28 UTC, andrerun approved these changes
/lgtm

2022-04-15 15:01 UTC, ialidzhikov requested changes

2022-04-15 15:01 UTC, ialidzhikov commented on pkg/operation/seed/seed.go
> +			}),
I don't think that this will be enough. Written like this, each Seed reconciliation will destroy the vpa-exporter Deployment. To my knowledge vpa-exporter is a kind of separate seed component and should be always deployed to the Seed (having in mind the prerequisite that Seed has to have VPA installed). I can rather image that vpa-exporter is extracted to a separate component that is always deployed on Seed reconcile and never destroyed when Seed does not enable VPA.

2022-04-15 15:16 UTC, rfranzke commented
Let's please not extract vpa-exporter into a separate component. Instead, we can enable/disable the three others by setting proper Values (I think this is how it was done with the Helm charts before).

2022-04-15 15:41 UTC, ialidzhikov commented
> Let's please not extract vpa-exporter into a separate component. Instead, we can enable/disable the three others by setting proper Values (I think this is how it was done with the Helm charts before).

AFAIS it was a separate chart - https://github.com/gardener/gardener/tree/v1.44.3/charts/seed-bootstrap/templates/vpa-exporter. The problem is rather in the Destroy - on seed reconcile it should not destroy the vpa-exporter, but on deletion - it should.

2022-04-15 22:05 UTC, rfranzke commented
Would it maybe be possible to only call Destroy on seed deletion, and call Reconcile in all other cases with proper "Enabled" settings in the values? Since VPA is now managed via GRM, it will take care of cleaning up no longer required resources.

2022-04-18 07:22 UTC, stoyanr commented
> Let's please not extract vpa-exporter into a separate component. Instead, we can enable/disable the three others by setting proper Values (I think this is how it was done with the Helm charts before).

From my perspective it doesn't matter much how it was done before. I agree with @ialidzhikov that having vpa-exporter as a separate component would be cleaner, even though perhaps a bit more verbose. Nevertheless I will fix it as suggested above.

2022-04-18 08:52 UTC, stoyanr commented on pkg/operation/seed/seed.go
> +			}),
Fixed as suggested by @rfranzke below.

2022-04-18 11:59 UTC, ialidzhikov approved these changes
/lgtm
/approve

2022-04-18 12:00 UTC, merged