Streamline defaulted value of ETCDConfig
gardener/gardener pull request #5820
Opened 2022-04-19 16:37 UTC by acumino

**How to categorize this PR?**

/area control-plane
/kind technical-debt

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #5157

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-04-20 09:07 UTC, acumino commented
/cc @abdasgupta

2022-04-21 06:17 UTC, kris94 requested changes

2022-04-21 06:17 UTC, kris94 commented on pkg/gardenlet/apis/config/v1alpha1/defaults.go
> +func SetDefaults_ETCDConfig(obj *ETCDConfig) {
Could you add unit test [here](https://github.com/gardener/gardener/blob/master/pkg/gardenlet/apis/config/v1alpha1/defaults_test.go) for this function?

2022-04-22 15:04 UTC, rfranzke commented
Can you please add a proper PR description?

2022-04-25 14:55 UTC, acumino commented
/cc @rfranzke

2022-04-26 18:57 UTC, abdasgupta approved these changes
Looks fine to me

2022-04-27 08:27 UTC, rfranzke reviewed
/lgtm
/approve

2022-04-27 09:00 UTC, merged