Update OWA GEP to better reflect current state
gardener/gardener pull request #5837
Opened 2022-04-21 10:38 UTC by dimityrmirchev

**How to categorize this PR?**

/area documentation
/kind cleanup

**What this PR does / why we need it**:
This PR updates the OWA GEP to better reflect the current state of the project.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-04-21 10:39 UTC, dimityrmirchev commented
/invite @vpnachev

2022-04-21 10:41 UTC, dimityrmirchev commented
/cc @vpnachev

2022-04-21 12:19 UTC, rfranzke commented
Typically, we don't maintain the GEPs after implementation but rather add dedicated documents for the respective features. I'm fine with merging this, though.

2022-04-21 12:29 UTC, dimityrmirchev commented
Ok, thanks! I just wanted to clarify/remove some things from the GEP that were never implemented so that no one reading it gets confused.

2022-04-21 13:28 UTC, plkokanov requested changes
Just one very very very small nit.

2022-04-21 13:28 UTC, plkokanov commented on docs/proposals/12-oidc-webhook-authenticator.md
> +1. OWA watches for changes on this resource and does [OIDC discovery](https://openid.net/specs/openid-connect-discovery-1_0.html). The [OIDC provider's  configuration](https://openid.net/specs/openid
```suggestion
1. OWA watches for changes on this resource and does [OIDC discovery](https://openid.net/specs/openid-connect-discovery-1_0.html). The [OIDC provider's configuration](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse) has to be accessible under the `spec.issuerURL` with a [well-known path (.well-known/openid-configuration)](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig).
```

2022-04-21 14:30 UTC, vpnachev commented
/approve

2022-04-21 15:18 UTC, rfranzke reviewed
/approve

2022-04-22 15:03 UTC, rfranzke reviewed
As this is only documentation, let's get it in
/milestone v1.45
/lgtm

2022-04-22 15:31 UTC, merged