Add documentation for shoot access
gardener/gardener pull request #5849
Opened 2022-04-22 11:40 UTC by ary1992

**How to categorize this PR?**

/area documentation

**What this PR does / why we need it**:
This PR adds documentation for accessing shoot with static token kubeconfig and dynamically created kubeconfig using shoot/adminKubeconfig subresource.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2022-04-22 13:52 UTC, rfranzke requested changes
- We can now drop https://github.com/gardener/gardener/tree/master/example/shoot-kubeconfig, I think
- Can you add a link to this document here (https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#rotate-kubeconfig-credentials)
- Can you add a third section talking about OIDC as option? https://github.com/gardener/gardener/blob/5023d12c26ddd05fb7f4ddbf40e3425f8176f462/example/90-shoot.yaml#L140

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +# Shoot_access.md
```suggestion
# Accessing Shoot Clusters
```

Please also add this document to the index (`docs/README.md`).

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +There are several scenarios where end-user would like to access shoot cluster. There are several options available to user to access the shoot cluster.
```suggestion
After creation of a shoot clusters, end-users require a `kubeconfig` to access it. There are several options available to get to such `kubeconfig`.
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +## Static token kubeconfig :
```suggestion
## Static Token Kubeconfig
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +  - To access the shoot cluster with the static token kubeconfig, shoot should have `.spec.kubernetes.enableStaticTokenKubeconfig` option set to `true`. enableStaticTokenKubeconfig will allow the cre
```suggestion
This `kubeconfig` contains a [static token](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-token-file) and provides `cluster-admin` privileges.
It is created by default and persisted in the `<shoot-name>.kubeconfig` secret in the project namespace in the garden cluster.
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +   - Static token doesn't have user identity associated with it. User in that token will always be system:cluster-admin irrespective of the person accessing the cluster. Hence it is impossible to aud
```suggestion
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
...
spec:
  kubernetes:
    enableStaticTokenKubeconfig: true
...
\```

It is **not** the recommended method to access the shoot cluster as the static token `kubeconfig` has some security flaws associated with it:

- The static token in the `kubeconfig` doesn't have any expiration date. To revoke the static token, the user needs to rotate the kuebcconfig credentials (see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#rotate-kubeconfig-credentials).
- The static token doesn't have any user identity associated with it. The user in that token will always be `system:cluster-admin` irrespective of the person accessing the cluster. Hence, it is impossible to audit the events in cluster.
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +  ```
```suggestion
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +## Dynamic kubeconfig
```suggestion
## `shoots/adminkubeconfig` subresource
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +  Shoot subresource called `adminKubeconfig` allows user to dynamically generate short lived `kubeconfig` that can be used to access shoot cluster with `cluster-admin` priviledge. `shoots/adminkubeco
```suggestion
The `shoots/adminkubeconfig` subresource allows users to dynamically generate short-lived `kubeconfig`s that can be used to access shoot cluster with `cluster-admin` privileges. The credentials associated with this `kubeconfig` are client certificates which have a very short validity and must be renewed before they expire.
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +
```suggestion
> The [`gardenctl-v2`](https://github.com/gardener/gardenctl-v2/) tool makes it easy to target shoot clusters and automatically renews such `kubeconfig`s when required.
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +  User identity of kubeconfig will be the user authenticating to gardener API server. Following command can be used to request a kubeconfig using the `AdminKubeconfigRequest`.
```suggestion
The username associated with such `kubeconfig` will be the same which is used for authenticating to the Gardener API. Apart from this advantage, the created `kubeconfig`s will not be persisted anywhere.

The following command can be used to request a `kubeconfig` using the `AdminKubeconfigRequest` resource.
```

2022-04-22 13:52 UTC, rfranzke commented on docs/usage/shoot_access.md
> +
```suggestion
```bash
export NAMESPACE=my-namespace
export SHOOT_NAME=my-shoot
kubectl create \
    -f example/shoot-kubeconfig/kubeconfig-request.json \
    --raw /apis/core.gardener.cloud/v1beta1/namespaces/${NAMESPACE}/shoots/${SHOOT_NAME}/adminkubeconfig | jq -r ".status.kubeconfig" | base64 -d
\```

Here, the `kubeconfig-request.json` has the following content:

```json
{
    "apiVersion": "authentication.gardener.cloud/v1alpha1",
    "kind": "AdminKubeconfigRequest",
    "spec": {
        "expirationSeconds": 1000
    }
}
\```
```

2022-04-27 08:14 UTC, rfranzke commented
/kind enhancement

2022-04-27 08:26 UTC, rfranzke requested changes
Apart from the inline suggestions, can you add a link to your document to this section at the end: https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#rotate-kubeconfig-credentials

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +## Static Token Kubeconfig :
```suggestion
## Static Token Kubeconfig
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +After creation of a shoot clusters, end-users requires a `kubeconfig` to access it. There are several options available to get to such `kubeconfig`.
```suggestion
After creation of a shoot clusters, end-users require a `kubeconfig` to access it. There are several options available to get to such `kubeconfig`.
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +kubernetes:
```suggestion
  kubernetes:
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +It is **not** the recommended method to access the shoot cluster as the static token `kubeconfig` has some security flaws associated with it:
```suggestion

It is **not** the recommended method for accessing the shoot cluster as the static token `kubeconfig` has some security flaws associated with it:
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +- The static token in the `kubeconfig` doesn't have any expiration date. To revoke the static token, the user needs to rotate the kuebcconfig credentials (see https://github.com/gardener/gardener/blo
```suggestion
- The static token in the `kubeconfig` doesn't have any expiration date. To revoke the static token, the user needs to rotate the kubeconfig credentials (see https://github.com/gardener/gardener/blob/master/docs/usage/shoot_operations.md#rotate-kubeconfig-credentials).
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +The [`shoots/adminkubeconfig`](https://github.com/gardener/gardener/blob/master/docs/proposals/16-adminkubeconfig-subresource.md) subresource allows users to dynamically generate short-lived `kubecon
```suggestion
The [`shoots/adminkubeconfig`](https://github.com/gardener/gardener/blob/master/docs/proposals/16-adminkubeconfig-subresource.md) subresource allows users to dynamically generate temporary `kubeconfig`s that can be used to access shoot cluster with `cluster-admin` privileges. The credentials associated with this `kubeconfig` are client certificates which have a very short validity and must be renewed before they expire (by calling the subresource  endpoint again).
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +
```suggestion

In order to request such a `kubeconfig`, you can run the following commands:

```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +> The [`gardenctl-v2`](https://github.com/gardener/gardenctl-v2/) tool makes it easy to target shoot clusters and automatically renews such `kubeconfig` when required.
```suggestion

> The [`gardenctl-v2`](https://github.com/gardener/gardenctl-v2/) tool makes it easy to target shoot clusters and automatically renews such `kubeconfig` when required.
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +## `oidcConfig`
```suggestion
## OpenID Connect
```

2022-04-27 08:26 UTC, rfranzke commented on docs/usage/shoot_access.md
> +For further information on (Cluster)OpenIDConnectPreset, refer to [doc](https://github.com/gardener/gardener/blob/master/docs/usage/openidconnect-presets.md).
```suggestion
The `kube-apiserver` of shoot clusters can be provided with [OpenID Connect configuration](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens) via the `ShootSpec`:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
...
spec:
  kubernetes:
    oidcConfig:
      ...
\```

It is the end-user's responsibility to incorporate the OpenID Connect configurations in `kubeconfig` for accessing the cluster (i.e., Gardener will not automatically generate `kubeconfig` based on these OIDC settings).
The recommended way is using the `kubectl` plugin called [`kubectl oidc-login`](https://github.com/int128/kubelogin) for OIDC authentication.

If you want to use the same OIDC configuration for all your shoots by default then you can use the `ClusterOpenIDConnectPreset` and `OpenIDConnectPreset` API resources. They allowing defaulting the `.spec.kubernetes.kubeAPIServer.oidcConfig` fields for newly created `Shoot`s such that you don't have to repeat yourself every time (similar to `PodPreset` resources in Kubernetes).
`ClusterOpenIDConnectPreset` specified OIDC configuration applies to `Projects` and `Shoots` cluster-wide (hence, only available to Gardener operators) while `OpenIDConnectPreset` is `Project`-scoped.
Shoots have to "opt-in" for such defaulting by using the `oidc=enable` label.

For further information on `(Cluster)OpenIDConnectPreset`, refer to [this document](https://github.com/gardener/gardener/blob/master/docs/usage/openidconnect-presets.md).
```

2022-04-27 08:26 UTC, rfranzke commented
Can you also please provide a proper release note for users so that they get aware of this document?

2022-04-27 10:13 UTC, acumino reviewed
Minor Nits

2022-04-27 10:13 UTC, acumino commented on docs/usage/shoot_access.md
> +After creation of a shoot clusters, end-users require a `kubeconfig` to access it. There are several options available to get to such `kubeconfig`.
```suggestion
After creation of a shoot cluster, end-users require a `kubeconfig` to access it. There are several options available to get to such `kubeconfig`.
```

2022-04-27 10:13 UTC, acumino commented on docs/usage/shoot_access.md
> +The [`shoots/adminkubeconfig`](https://github.com/gardener/gardener/blob/master/docs/proposals/16-adminkubeconfig-subresource.md) subresource allows users to dynamically generate temporary `kubeconfi
```suggestion
The [`shoots/adminkubeconfig`](https://github.com/gardener/gardener/blob/master/docs/proposals/16-adminkubeconfig-subresource.md) subresource allows users to dynamically generate temporary `kubeconfig`s that can be used to access shoot cluster with `cluster-admin` privileges. The credentials associated with this `kubeconfig` are client certificates which have a very short validity and must be renewed before they expire (by calling the subresource endpoint again).
```

2022-04-27 10:13 UTC, acumino commented on docs/usage/shoot_access.md
> +For further information on `(Cluster)OpenIDConnectPreset`, refer to [this document](https://github.com/gardener/gardener/blob/master/docs/usage/openidconnect-presets.md).
I guess the relative link is the preferred way. Similar changes in other places.
```suggestion
For further information on `(Cluster)OpenIDConnectPreset`, refer to [this document](openidconnect-presets.md).
```

2022-04-27 10:13 UTC, acumino commented on docs/usage/shoot_access.md
> +For further information on `(Cluster)OpenIDConnectPreset`, refer to [this document](https://github.com/gardener/gardener/blob/master/docs/usage/openidconnect-presets.md).
/cc @rfranzke

2022-04-28 08:29 UTC, rfranzke reviewed
Thanks!

/approve

2022-04-28 08:36 UTC, acumino commented
/lgtm

2022-04-28 08:51 UTC, rfranzke commented
/retest

2022-04-28 09:19 UTC, merged