Make ingresses resolvable/reachable in provider-local
gardener/gardener pull request #5924
Opened 2022-05-04 16:53 UTC by timebertt

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:

Removes the limitation of provider-local that `Ingress` objects in the seed cluster are not reachable/resolvable.
With this, the shoot node logging feature gate can also be enabled and used with provider-local.

**Which issue(s) this PR fixes**:
Fixes one of the current [limitations of provider-local](https://github.com/gardener/gardener/blob/476a39f2b59ff5b93832bdb9cd046a6c96190b2e/docs/extensions/provider-local.md#current-limitations).

**Special notes for your reviewer**:

Thanks @rfranzke for the pairing on this topic!

**Release note**:

```feature developer
provider-local now supports `Ingress` objects in the Seed cluster and now enables using the [shoot node logging feature](https://github.com/gardener/gardener/blob/476a39f2b59ff5b93832bdb9cd046a6c96190b2e/docs/deployment/configuring_logging.md#enable-logs-from-the-shoots-node-systemd-services).
```

2022-05-05 10:50 UTC, plkokanov requested changes
Just some minor nits that I saw, otherwise pretty easy to review :)
I'm about to do a quick test locally.

2022-05-05 10:50 UTC, plkokanov commented on example/gardener-local/kind/cluster-local.yaml
> +  # istio-ingressgateway
Nice! These comments are really useful. Previously I had to dig into the code base to see where the ports are used.

2022-05-05 10:50 UTC, plkokanov commented on docs/extensions/provider-local.md
> +This controller reconciles `Services` of type `LoadBalancer` in the local `Seed` cluster
nit: 
```suggestion
This controller reconciles `Services` of type `LoadBalancer` in the local `Seed` cluster.
```

2022-05-05 10:50 UTC, plkokanov commented on docs/extensions/provider-local.md
> +It makes important LoadBalancer Services (e.g. `istio-ingress/istio-ingressgateway` and `garden/nginx-ingress-controller`) available to the host by setting `spec.ports[].nodePort` well-known ports th
nit:
```suggestion
It makes important LoadBalancer Services (e.g. `istio-ingress/istio-ingressgateway` and `garden/nginx-ingress-controller`) available to the host by setting `spec.ports[].nodePort` to well-known ports that are mapped to `hostPorts` in the kind cluster configuration.
```

2022-05-05 15:29 UTC, rfranzke commented
/assign

Can you check why the e2e tests are failing, please?

2022-05-06 08:45 UTC, rfranzke commented
FYI @vlvasilev, this might be of interested for you 😉

2022-05-06 09:37 UTC, rfranzke commented on pkg/provider-local/controller/ingress/add.go
> +// Copyright (c) 2022 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
Please add this controller with to https://github.com/gardener/gardener/blob/2a5dacb7f89414d7ed28a98fd9688283fb3977cc/charts/gardener/provider-local/extension/values.yaml#L20

2022-05-11 11:30 UTC, timebertt commented
/test pull-gardener-integration

2022-05-11 11:58 UTC, timebertt commented
@plkokanov @rfranzke I addressed your review comments.

I've also found the reason for the test failures by execing into a running test job pod (couldn't reproduce locally).
Shoots got unhealthy with something like
```
$ k -n garden-local get shoot default-7nr6k -oyaml
...
  - lastTransitionTime: "2022-05-11T11:39:49Z"
    lastUpdateTime: "2022-05-11T11:38:45Z"
    message: 'Stateful set "prometheus" is unhealthy: not enough ready replicas (0/1)'
    reason: StatefulSetUnhealthy
    status: "False"
    type: ControlPlaneHealthy
...

$ k -n shoot--local--default-7nr6k describe po prometheus-0
...
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m39s  default-scheduler  0/1 nodes are available: 1 Too many pods.
  Warning  FailedScheduling  2m37s  default-scheduler  0/1 nodes are available: 1 Too many pods.

$ k get po -A --no-headers | grep -v Pending | wc -l
110

$ k get no gardener-local-control-plane -oyaml
...
  allocatable:
    cpu: "100"
    ephemeral-storage: 102033388Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 100Gi
    pods: "110"
  capacity:
    cpu: "100"
    ephemeral-storage: 102033388Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 100Gi
    pods: "110"
```

These scheduler events would have been helpful for debugging, if they would have get dumped into the test logs.
I think, this was skipped because the context deadline was already exceeded:
```
    {"level":"error","msg":"Cannot dump shoot state default-6vm7d: retry failed with context deadline exceeded, last error: shoot \"default-6vm7d\" was not successfully reconciled","ts":"2022-05-04T17:20:54.149Z"}
```

This is addressed as well in a new commit.
I will check again later, what's our best way to deal with the max pods limitation.

2022-05-11 12:01 UTC, rfranzke commented
Nice finding @timebertt. We can probably use https://kind.sigs.k8s.io/docs/user/configuration/#kubeadm-config-patches to set the kubelet config in the kind cluster accordingly, right?

2022-05-11 12:34 UTC, timebertt commented
> These scheduler events would have been helpful for debugging, if they would have get dumped into the test logs. I think, this was skipped because the context deadline was already exceeded: [...]
> This is addressed as well in a new commit. I will check again later, what's our best way to deal with the max pods limitation.

Ok nice, this worked at least. The build logs now include the full event dump for better debugging including:

```
{"level":"info","msg":"At 0001-01-01 00:00:00 +0000 UTC - event for gardener-resource-manager-79ffd6d47d-7rdzj: { } FailedScheduling: 0/1 nodes are available: 1 Too many pods.","ts":"2022-05-11T12:22:22.626Z"}
```

2022-05-11 13:48 UTC, timebertt commented
Ok, I pushed another commit increasing `maxPods` to 500 in our kind config.

I tested this out locally and increasing `maxPods` seems to be the only thing we need to do.
We are using the default `calico-ipam` in kind, which ignores `node.spec.podCIDR` and instead manages IP blocks on its own via the `ipamblocks.crd.projectcalico.org` CR. It uses `/26` blocks by default, but creates new pools as needed.

```
$ k get no gardener-local-control-plane -oyaml | grep -e podCIDR: -e pods:
  podCIDR: 10.1.0.0/24
    pods: "500"
    pods: "500"

$ k get deploy nginx # we have 10 system pods
NAME    READY     UP-TO-DATE   AVAILABLE   AGE
nginx   490/500   500          490         16m

$ k get ipamblocks.crd.projectcalico.org
NAME              AGE
10-1-130-192-26   16m
10-1-131-0-26     15m
10-1-131-128-26   14m
10-1-131-192-26   14m
10-1-131-64-26    14m
10-1-132-0-26     14m
10-1-132-128-26   13m
10-1-132-64-26    13m
```

Let's see how this works out in CI 🚀

2022-05-12 08:14 UTC, rfranzke commented
/assign @oliver-goetz

2022-05-12 08:46 UTC, rfranzke commented
After a joint review with @oliver-goetz:

/lgtm
/approve

2022-05-12 09:18 UTC, merged