Add MaxAllowed for VPA objects
gardener/gardener pull request #5976
Opened 2022-05-16 07:44 UTC by dimitar-kostadinov

**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Limits the range of maximum allowed resource requests to ensure that pods are schedulable
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
- category: other
- target_group: operator
```

2022-05-18 07:37 UTC, dimitar-kostadinov commented
/invite @voelzmo

2022-05-19 06:00 UTC, rfranzke commented
/assign

2022-05-19 06:03 UTC, rfranzke reviewed
/approve

2022-05-20 17:45 UTC, voelzmo requested changes
Not finished reviewing, just submitting to not lose comments.

2022-05-20 17:45 UTC, voelzmo commented on pkg/operation/botanist/component/kubeproxy/resources.go
> +							corev1.ResourceMemory: resource.MustParse("50Mi"),
Why are we adding `minAllowed` here? In my dev Shoot, `kube-proxy` isn't using many resources and therefore has requests like this
```
    - resources:
        requests:
          cpu: 11m
          memory: 11500k
```

We run a kube-proxy for every node – do we have good reasons for making it ask for more?

2022-05-20 17:45 UTC, voelzmo commented on pkg/operation/botanist/component/coredns/coredns.go
> +							MaxAllowed: corev1.ResourceList{
This is the VPA for the [cluster-proportional-autoscaler that coredns uses](https://github.com/gardener/gardener/blob/master/docs/usage/dns-autoscaling.md), not the VPA for coredns itself. If we want to set a value similar to `maxAllowed`, we need to do it [as commandline parameter](https://github.com/gardener/gardener/blob/be54f2c1b8909bcf664aa108b6632f360c746815/pkg/operation/botanist/component/coredns/coredns.go#L682) – I think it is called [`max`](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler#linear-mode).

2022-05-23 11:43 UTC, voelzmo commented
Finishing up my review: I think we're missing GRM if we want to go with [this list](https://github.tools.sap/kubernetes/autoscaling/issues/27#issuecomment-956809) and insert a `maxAllowed` value for all `critical` components in g/g with this PR.

2022-06-08 09:26 UTC, timebertt commented
@dimitar-kostadinov @voelzmo @danielfoehrKn what's the status of this PR?

2022-06-09 07:20 UTC, voelzmo approved these changes
/approve

2022-06-09 12:42 UTC, timebertt commented
/retest

2022-06-09 14:11 UTC, rfranzke commented
/test pull-gardener-e2e-kind

2022-06-09 15:21 UTC, merged