Annotate the shoot-namespace in the seed with Shoot's annotations
gardener/gardener pull request #600
Opened 2018-12-10 17:02 UTC by vpnachev

**What this PR does / why we need it**:
This PR provides a mechanism for transporting metadata(annotations) from the Garden cluster to the Seed cluster. In this way, controllers working in the seed cluster could get additional information. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
The shoot namespace in the seed cluster will be annotated with all annotations of the shoot resource prefixed with `seed-namespace-annotation.shoot.garden.sapcloud.io/`. The namespace is annotated with the value of `shoot.status.uid` as well.
```

2018-12-10 23:40 UTC, rfranzke requested changes
Just a naming suggestions, otherwise LGTM

2018-12-10 23:40 UTC, rfranzke commented on pkg/operation/common/types.go
> +	AnnotateSeedNamespacePrefix = "seed-namespace-annotation.shoot.garden.sapcloud.io/"
Please rename to `custom.shoot.sapcloud.io/`

2018-12-11 10:26 UTC, vpnachev commented on pkg/operation/common/types.go
> +	AnnotateSeedNamespacePrefix = "seed-namespace-annotation.shoot.garden.sapcloud.io/"
Done

2018-12-11 10:27 UTC, vpnachev commented
Thanks @rfranzke !
I have implemented the proposed change.

2018-12-11 13:40 UTC, rfranzke approved these changes
/lgtm

2018-12-11 14:05 UTC, merged