Update/remove memory limits. Disable limit autoscaling.
gardener/gardener pull request #6020
Opened 2022-05-23 16:52 UTC by andrerun

**How to categorize this PR?**
/area auto-scaling
/area robustness
/kind enhancement

**What this PR does / why we need it**:
Improves stability by updating and removing various components' memory limits and disabling limit autoscaling.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Includes only mid-and-higher priority improvements. Lower priority limit scaling improvements will be addressed by a separate change set.

**Release note**:

```bugfix operator
Memory limits of various components were updated, based on measured usage, to prevent OOMKills due to reaching the limits. Limit scaling was disabled to prevent limit downscaling during periods of load system load.
```

2022-05-25 10:05 UTC, voelzmo requested changes
submitting initial review comments

2022-05-25 10:05 UTC, voelzmo commented on charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
> +      controlledValues: RequestsOnly
Technically, we don't need to add `controlledValues: RequestsOnly` when we're removing the limits. I think we only do this for the components which still have limits that we picked and don't want to be modified by VPA.

2022-05-25 10:05 UTC, voelzmo commented on charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
> -          limits:
We shouldn't remove fluent-bit's memory limit according to @vlvasilev

2022-05-25 10:05 UTC, voelzmo commented on charts/seed-bootstrap/charts/monitoring/values.yaml
> -      limits:
I'm not sure if we should be dropping prometheus memory limits entirely, I think we rather set it to different values for the other prometheus instances? See also the comment above about specifying `controlledValues: RequestsOnly`

2022-05-25 10:05 UTC, voelzmo commented on charts/seed-bootstrap/values.yaml
> -        memory: 2000Mi
See comment above: I think we had different memory limits for prometheus in mind and didn't want to remove them entirely?

2022-05-25 10:05 UTC, voelzmo commented on charts/istio/istio-istiod/templates/deployment.yaml
> -          limits:
Did we see any concrete issues with the memory limit for istio? I think initially we didn't put it on our list of "remove memory limits entirely" workload?

2022-05-25 10:05 UTC, voelzmo commented on pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
> -								Limits: corev1.ResourceList{
Did we see any concrete issues with the memory limit for dependency-watchdog? I think initially we didn't put it on our list of "remove memory limits entirely" workload?

2022-05-25 14:21 UTC, andrerun commented on charts/istio/istio-istiod/templates/deployment.yaml
> -          limits:
Much of the limits removal is due to misinterpretation of the empty values in the desired limits table as "no limit". Desired limits for these components have not been established.

I did the research on istio though, and it is indeed critical, so I marked it accordingly in the table.

2022-05-26 07:52 UTC, andrerun commented on charts/seed-bootstrap/charts/hvpa/templates/controller-deployment.yaml
> +      controlledValues: RequestsOnly
Thanks! It makes perfect sense to avoid verbose configuration which has no effect. Applied.

2022-05-26 07:55 UTC, andrerun commented on charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
> -          limits:
Was due to aforementioned misinterpretation of "desired value = empty" as "desired = no limit". Now fixed.

2022-05-26 07:55 UTC, andrerun commented on charts/seed-bootstrap/charts/monitoring/values.yaml
> -      limits:
Was due to aforementioned misinterpretation of "desired value = empty" as "desired = no limit". Now fixed.

2022-05-26 07:55 UTC, andrerun commented on charts/seed-bootstrap/values.yaml
> -        memory: 2000Mi
Was due to aforementioned misinterpretation of "desired value = empty" as "desired = no limit". Now fixed.

2022-05-26 07:56 UTC, andrerun commented on pkg/operation/botanist/component/dependencywatchdog/bootstrap.go
> -								Limits: corev1.ResourceList{
Was due to aforementioned misinterpretation of "desired value = empty" as "desired = no limit". Now fixed.

2022-05-30 14:17 UTC, voelzmo approved these changes
/approve

2022-05-30 16:57 UTC, rfranzke reviewed
/approve

2022-05-30 17:27 UTC, merged