Upgrade `k8s.io/*` to `v0.24.1`, `sigs.k8s.io/controller-runtime` to `v0.12.1`
gardener/gardener pull request #6101
Opened 2022-06-13 14:07 UTC by kris94

**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
This PR upgrades to the latest versions of our go upstream dependencies:

- sigs.k8s.io/controller-runtime@v0.12.1: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.12.1
- k8s.io/*@v0.24.0

**Which issue(s) this PR fixes**:
Fixes #5990

**Special notes for your reviewer**:

**Release note**:

```other dependency
`k8s.io/*`  is now upgraded to `v0.24.1` and `sigs.k8s.io/controller-runtime` is now upgraded to `v0.12.1`.
```

2022-06-13 14:12 UTC, kris94 commented
/test all

2022-06-14 09:09 UTC, kris94 commented
/test pull-gardener-e2e-kind

2022-06-14 09:19 UTC, rfranzke commented on go.mod
> +	k8s.io/api v0.24.0
There is already v0.24.1  :)

2022-06-14 09:19 UTC, rfranzke commented on pkg/admissioncontroller/webhooks/admission/auditpolicy/admission.go
> -		auditv1beta1.AddToScheme,
This means that we don't accept audit configurations in `v1alpha1` or `v1beta1` anymore. Probably we should add this explicitly as a release note.

2022-06-14 09:19 UTC, rfranzke commented on pkg/operation/botanist/component/kubecontrollermanager/waiter.go
> +		lock := resourcelock.EndpointsLeasesResourceLock
Instead of using `EndpointsLeasesResourceLock` just don't use any constant (since there is none anymore) and write "endpoints" explicitly here.

2022-06-14 09:19 UTC, rfranzke commented on pkg/utils/kubernetes/leaderelection.go
> +	case resourcelock.EndpointsLeasesResourceLock:
Instead of using `EndpointsLeasesResourceLock` just don't use any constant (since there is none anymore) and write "endpoints" explicitly here.

2022-06-14 09:19 UTC, rfranzke commented on pkg/utils/kubernetes/leaderelection.go
> +	case resourcelock.ConfigMapsLeasesResourceLock:
Instead of using `ConfigMapsLeasesResourceLock` just don't use any constant (since there is none anymore) and write "configmaps" explicitly here.

2022-06-14 09:19 UTC, rfranzke commented on pkg/utils/kubernetes/leaderelection_test.go
> +				lock = resourcelock.EndpointsLeasesResourceLock
Instead of using `EndpointsLeasesResourceLock` just don't use any constant (since there is none anymore) and write "endpoints" explicitly here.

2022-06-14 09:19 UTC, rfranzke commented on pkg/utils/kubernetes/leaderelection_test.go
> +				lock = resourcelock.ConfigMapsLeasesResourceLock
Instead of using `ConfigMapsLeasesResourceLock` just don't use any constant (since there is none anymore) and write "configmaps" explicitly here.

2022-06-14 11:24 UTC, kris94 commented
/test all

2022-06-14 11:32 UTC, rfranzke commented
/assign

2022-06-15 05:05 UTC, acumino reviewed
Apart from the comments above. controller-tools need to be updated to newer version.

2022-06-15 05:05 UTC, acumino commented on go.mod
>  	github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.11.1 // keep this value in sync with sigs.k8s.io/controller-runtime
```suggestion
	github.com/prometheus/client_golang => github.com/prometheus/client_golang v1.12.1 // keep this value in sync with sigs.k8s.io/controller-runtime
```

2022-06-15 05:05 UTC, acumino commented on go.mod
>  	sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20220513175748-3f265c36d7bf // v0.11.0
This also needs to be updated.

2022-06-15 05:05 UTC, acumino commented on pkg/utils/kubernetes/leaderelection.go
> +	case "endpoints":
Should we declare constant for it and then use it?

2022-06-15 05:05 UTC, acumino commented on pkg/utils/kubernetes/leaderelection.go
> +	case "configmaps":
Same here.

2022-06-15 05:07 UTC, rfranzke commented on pkg/utils/kubernetes/leaderelection.go
> +	case "endpoints":
Not needed I think given that this is only used for old Kubernetes versions whose support we likely will drop in the next time.

2022-06-15 05:07 UTC, rfranzke commented on pkg/utils/kubernetes/leaderelection.go
> +	case "configmaps":
Not needed I think given that this is only used for old Kubernetes versions whose support we likely will drop in the next time.

2022-06-15 10:38 UTC, acumino commented
> Apart from the comments above. controller-tools need to be updated to newer version.

`controller-tools` also need to be updated. Is there any specific reason for not updating it?

2022-06-15 10:40 UTC, acumino requested changes

2022-06-15 10:40 UTC, acumino commented on go.mod
>  	sigs.k8s.io/controller-tools v0.8.0
We usually update this also in the same PR in which controller runtime and k8s dependencies are updated.

2022-06-15 14:21 UTC, rfranzke commented
The changes look good to me. 
Maybe we can make use of this point from #5990:

> - Add base context to `manager.Options` for `Runnable`s (ref https://github.com/kubernetes-sigs/controller-runtime/pull/1846) (previously, a new `context.Background()` was created so the `Runnable`s aren't canceled when a top-level context is)

We add a `Runnable` to the `manager` in `provider-local` ([here](https://github.com/gardener/gardener/blob/6af87c88f796d53d23776a8839b63145cf108808/cmd/gardener-extension-provider-local/app/app.go#L262-L264)).

Also, we generally add `Runnable`s to the `manager` when registering webhooks to extensions, so this is relevant/interesting for all extensions with webhooks. However, this is not a concern of this PR but rather only when the extensions themselves get revendored.

2022-06-17 17:16 UTC, rfranzke commented on pkg/admissioncontroller/webhooks/admission/auditpolicy/admission.go
> +	"golang.org/x/mod/semver"
use `github.com/Masterminds/semver` instead (and move to import group below)

2022-06-20 07:00 UTC, rfranzke commented
/needs rebase

2022-06-21 09:16 UTC, rfranzke commented on go.mod
> +	k8s.io/api v0.24.1
Meanwhile there is 0.24.2

2022-06-21 09:16 UTC, rfranzke commented on third_party/apiserver/pkg/apis/audit/v1alpha1/conversion_test.go
> +/*
Probably we can drop the test files here in the copied code.

2022-06-21 09:16 UTC, rfranzke commented on third_party/apiserver/pkg/apis/audit/v1beta1/conversion_test.go
> +/*
Probably we can drop the test files here in the copied code.

2022-06-21 11:04 UTC, rfranzke commented
/lgtm
/approve

2022-06-21 11:23 UTC, rfranzke commented
/cla

2022-06-21 12:54 UTC, rfranzke commented
/test pull-gardener-e2e-kind

2022-06-21 13:45 UTC, rfranzke commented
/test pull-gardener-e2e-kind

2022-06-21 14:18 UTC, merged