Adapt provider-local to use priority class gardener-system-900
gardener/gardener pull request #6236
Opened 2022-06-29 08:53 UTC by kris94

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR removes the custom priority class from the provider-local charts and adapts it to use priorityClass `gardener-system-900` as part of https://github.com/gardener/gardener/issues/5634
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Provider-local now uses priorityClass gardener-system-900
```

2022-06-30 05:35 UTC, acumino reviewed
`provider-local` mcm should also be adapted to use priority class `gardener-system-300`.

2022-06-30 07:24 UTC, rfranzke commented
Also, the local path provisioner (https://github.com/gardener/gardener/tree/master/charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates) should get the right priority class

2022-06-30 12:02 UTC, kris94 commented
@rfranzke, @timebertt 
> Also, the local path provisioner (https://github.com/gardener/gardener/tree/master/charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates) should get the right priority class

Local path provisioner is not described [in the priority classes table](https://github.com/gardener/gardener/blob/master/docs/development/priority-classes.md) What value should we assign to it?

2022-06-30 12:03 UTC, rfranzke commented
It is comparable to the CSI driver/controllers

2022-07-04 07:13 UTC, acumino reviewed
/lgtm

2022-07-04 11:36 UTC, rfranzke requested changes

2022-07-04 11:36 UTC, rfranzke commented on charts/gardener/provider-local/internal/shoot-system-components/charts/local-path-provisioner/templates/deployment.yaml
> +      priorityClassName: gardener-system-200
How does this work? This component is running in the shoot and here we should only see `gardener-shoot-system-*` priority classes. 
In this light, `system-cluster-critical` is more appropriate (CSI drivers are using `system-node-critical` but those are `DaemonSet`s)

2022-07-04 14:09 UTC, rfranzke reviewed
/lgtm
/approve

2022-07-04 14:47 UTC, merged