Promote the `SecretBindingProviderValidation` feature gate to beta
gardener/gardener pull request #6240
Opened 2022-06-29 11:46 UTC by ialidzhikov

/kind enhancement

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/4888

**Release note**:

```breaking user
The `SecretBindingProviderValidation` feature gate of `gardener-apiserver` is now promoted to beta and enabled by default. This enables the following validations:
- requires the provider type of a `SecretBinding` to be set (on `SecretBinding` creation)
- requires the `SecretBinding` provider type to match the `Shoot` provider type (on `Shoot` creation)
- enforces immutability on the provider type of a `SecretBinding`
```

2022-06-29 11:50 UTC, rfranzke reviewed
/lgtm
/approve

2022-06-29 11:52 UTC, ialidzhikov commented
/hold
looks like the integration tests need adaptation

2022-06-29 12:46 UTC, ialidzhikov commented
/hold cancel

2022-06-30 05:52 UTC, acumino requested changes

2022-06-30 05:52 UTC, acumino commented on pkg/features/features.go
> +	// alpha: v1.51.0
```suggestion
	// beta: v1.51.0
```

2022-06-30 05:54 UTC, ialidzhikov commented on pkg/features/features.go
> +	// alpha: v1.51.0
Thanks!

2022-06-30 05:56 UTC, acumino reviewed
Thanks!
/lgtm

2022-06-30 06:58 UTC, timebertt commented
/skip

2022-06-30 08:14 UTC, merged