Enforce that Shoot nginx-ingress addon and Seed VPA are not enabled for ManagedSeeds
gardener/gardener pull request #6388
Opened 2022-07-22 15:24 UTC by ialidzhikov

**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
This PR enforces the following validations for ManagedSeeds:
- The Shoot nginx-ingress addon to be not enabled for ManagedSeeds. The addon is deprecated and supported only for Shoot clusters with evaluation purpose. Instead the Gardener managed Seed ingress controller or the self-managed ingress controller should be used.
- The Seed VPA to be not enabled for ManagedSeeds. https://github.com/gardener/gardener/issues/6305 outlines the motivation for it. Instead the Shoot VPA should be used.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6305

**Release note**:

```other operator
TBD
```

2022-07-27 06:41 UTC, ialidzhikov commented
/test pull-gardener-e2e-kind

2022-07-29 15:32 UTC, plkokanov requested changes
A few nits.
And one question - does it make sense to also document in the release note the proper order in which to edit `Shoots` and `ManagedSeeds` that do not conform to the new requirements (if this order matters)? E.g. first the Shoot should be edited to disable nginx and enable Shoot VPA, then the `ManagedSeed` should be adapted to disable the Seed VPA.

2022-07-29 15:32 UTC, plkokanov commented on docs/usage/managed_seed.md
> +   An Ingress controller is also a prerequisite for a Seed cluster. For a Seed cluster it is possible to enable Gardener managed Ingress controller or to deploy self-managed Ingress controller. There
small nit:
```suggestion
   An Ingress controller is also a prerequisite for a Seed cluster. For a Seed cluster it is possible to enable Gardener managed Ingress controller or to deploy self-managed Ingress controller. There is also the nginx-ingress addon that can be enabled for a Shoot (using the Shoot spec). However, the Shoot nginx-ingress addon is in deprecated mode and it is not recommended for production clusters. Due to these reasons, the Gardener API server does not allow the Shoot nginx-ingress addon to be enabled for ManagedSeeds.
```

2022-07-29 15:32 UTC, plkokanov commented on plugin/pkg/shoot/managedseed/admission.go
> +	} else if a.GetOperation() == admission.Delete {
You don't need the else here right? I guess it would be a bit cleaner without it.

2022-07-29 15:32 UTC, plkokanov commented on plugin/pkg/managedseed/validator/admission.go
> +		return apierrors.NewInvalid(gk, managedSeed.Name, append(allErrs, field.Invalid(shootNamePath, managedSeed.Spec.Shoot.Name, "shoot ingress addon is not supported for managed seeds - use managed see
```suggestion
		return apierrors.NewInvalid(gk, managedSeed.Name, append(allErrs, field.Invalid(shootNamePath, managedSeed.Spec.Shoot.Name, "shoot ingress addon is not supported for managed seeds - use the managed seed ingress controller")))
```

2022-08-01 03:04 UTC, shafeeqes commented
/retest

2022-08-01 14:22 UTC, ialidzhikov commented on plugin/pkg/shoot/managedseed/admission.go
> +	} else if a.GetOperation() == admission.Delete {
Yes, it can be adapted to:
```golang
	if a.GetOperation() == admission.Update {
		return v.validateUpdate(ctx, a)
	}

	switch {
	case a.GetName() == "":
		return v.validateDeleteCollection(ctx, a)
	default:
		return v.validateDelete(ctx, a)
	}
```

But if the admission plugin is adapted to handle a new operation (`CREATE`), then the code has to be adapted. There is a small benefit being explicit as in this way we clearly show what is being performed on which operation (without requiring the reader to go up and check which operations the admission plugin handles). I would rather vote to keep it as it is. But if you insist can also adapt to your suggestion.

2022-08-01 14:26 UTC, ialidzhikov commented
> And one question - does it make sense to also document in the release note the proper order in which to edit `Shoots` and `ManagedSeeds` that do not conform to the new requirements (if this order matters)? E.g. first the Shoot should be edited to disable nginx and enable Shoot VPA, then the `ManagedSeed` should be adapted to disable the Seed VPA.

I think the order should not matter. But good point, I will a sentence to the release note of type "Before upgrading to this version of Gardener make sure that all ManagedSeeds and the Shoots they refer to conform the newly enforced configuration options ."

2022-08-01 15:45 UTC, plkokanov commented on plugin/pkg/shoot/managedseed/admission.go
> +	} else if a.GetOperation() == admission.Delete {
Makes sense, we can leave it as it is.

2022-08-02 06:19 UTC, plkokanov commented
/lgtm

2022-08-02 06:21 UTC, plkokanov approved these changes

2022-08-02 06:23 UTC, merged