metrics: etcd_object_counts->apiserver_storage_object_counts
gardener/gardener pull request #6390
Opened 2022-07-25 03:27 UTC by Sallyan

**How to categorize this PR?**
/area monitoring
/kind enhancement

**What this PR does / why we need it**:
Metric `etcd_object_counts` in etcd3 storage metrics, which is to show number of stored objects. 
And this metric is deprecated in version `1.22.0`, and will be replaced by `apiserver_storage_object_counts`
```
	etcdObjectCounts = compbasemetrics.NewGaugeVec(
		&compbasemetrics.GaugeOpts{
			Name:              "etcd_object_counts",
			DeprecatedVersion: "1.22.0",
			Help:              "Number of stored objects at the time of last check split by kind. This metric is replaced by apiserver_storage_object_counts.",
			StabilityLevel:    compbasemetrics.ALPHA,
		},
		[]string{"resource"},
	)
```
**But in the metrics.go it is defined as name ``**

And the metric `etcd_object_counts` is used in three dashboards, if the Kubernetes version is 1.22.0+, this panel will show no data as the metric is deprecated. This PR also updates the dashboards to use two query of the two metrics. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

2022-07-25 05:51 UTC, Sallyan commented
Will check the test failure.

2022-07-25 08:35 UTC, istvanballok requested changes
with @rickardsjp

2022-07-25 08:35 UTC, istvanballok commented on vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
> +			Name:           "apiserver_storage_object_counts",
Note that this file is a vendored (hence for us it is a conceptually read-only) copy of the upstream k8s source code, and it is not meaningful to change it.

Generally, if you'd like to change some files in the vendor folder, I think it should be changed upstream, after a discussion with the upstream community.

https://github.com/kubernetes/kubernetes/blob/5f6b60bb1323a60f59119e315ac52b8a453a3939/staging/src/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go#L52

Note also that after the initial implementation was announced in the release notes and in the help text you mentioned, the metric name was adjusted in this PR: https://github.com/kubernetes/kubernetes/pull/100082

So please adjust this PR to use the new metric name: `apiserver_storage_objects`.

You can verify it with the following command:

```
k proxy
curl -s http://localhost:8001/metrics | grep apiserver_storage_objects
```

2022-07-25 08:35 UTC, istvanballok commented on pkg/operation/botanist/component/kubeapiserver/monitoring.go
> +    monitoringMetricApiserverStorageObjectCounts,
inconsistent indentation

2022-07-25 08:48 UTC, Sallyan commented on vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
> +			Name:           "apiserver_storage_object_counts",
Okay, thanks a lot for the information. Will update this PR.

2022-07-25 09:10 UTC, Sallyan commented on pkg/operation/botanist/component/kubeapiserver/monitoring.go
> +    monitoringMetricApiserverStorageObjectCounts,
Updated `go fmt`:)

2022-07-25 09:12 UTC, istvanballok commented on vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
> +			Name:           "apiserver_storage_object_counts",
Please make sure to review (and adjust) the PR description as well and revert the change in the vendor folder. For simplicity, you could also squash the commits.

2022-07-26 07:22 UTC, rfranzke reviewed
/approve

@wyb1 @istvanballok @rickardsjp please have a look and provide feedback

2022-07-26 07:46 UTC, istvanballok approved these changes
/lgtm

2022-07-26 11:47 UTC, rfranzke commented
@acumino Can we add this to the v1.52 milestone?

2022-07-26 11:48 UTC, acumino commented
> @acumino Can we add this to the v1.52 milestone?

Yes, but tests are still failing that's why I have not added it to 1.52

2022-07-26 11:53 UTC, rfranzke commented
This looks unrelated 👀 

/retest-required

2022-07-26 12:03 UTC, acumino commented
/milestone v1.52

2022-07-26 13:55 UTC, oliver-goetz commented
/override check-release-milestone
The status of the last commit does not change anymore, if the milestone was added afterwards.

2022-07-26 13:56 UTC, oliver-goetz commented
/override Check Release Milestone

2022-07-26 13:58 UTC, oliver-goetz commented
What a shame, the PR status is still not updated 😓

2022-07-26 14:01 UTC, oliver-goetz commented
Awesome 😃

2022-07-26 15:07 UTC, merged

2022-08-25 14:18 UTC, vpnachev commented
Was the https://github.com/gardener/gardener/blob/a92a54f2792f7952498fb9473acf5e4d4494dcf8/pkg/operation/botanist/component/etcd/monitoring.go#L154-L155 

skipped by incident or it does not need to be adapted to the new metric name?
cc @istvanballok @wyb1

2022-08-26 01:34 UTC, Sallyan commented
> Was the
> 
> https://github.com/gardener/gardener/blob/a92a54f2792f7952498fb9473acf5e4d4494dcf8/pkg/operation/botanist/component/etcd/monitoring.go#L154-L155
> 
> skipped by incident or it does not need to be adapted to the new metric name? cc @istvanballok @wyb1

I think it's better to keep this one and  add new record: 
```
   - record: shoot: apiserver_storage_objects:sum_by_resource 
     expr: max(apiserver_storage_objects) by (resource) 
```