[GRM] Label managed resources
gardener/gardener pull request #6393
Opened 2022-07-25 10:27 UTC by dimityrmirchev

**How to categorize this PR?**

/area dev-productivity robustness
/kind enhancement

**What this PR does / why we need it**:
This PR labels all resources managed by GRM with a `resources.gardener.cloud/origin` label so that they can be easily described with selectors. It uses a similar to the `resources.gardener.cloud/origin` annotation convention.

**Which issue(s) this PR fixes**:
Fixes #6385 

**Special notes for your reviewer**:

**Release note**:

```developer feature
Gardener resource manager now labels all managed objects with `resources.gardener.cloud/origin` label. This is an improvement which will allow these objects to be easily described with a label selector.
```

2022-07-25 11:46 UTC, dimityrmirchev commented
/retest-required

Not sure why `apidiff` is failing. All changes seem compatible to me. Logs show:
```log
FAIL: contains incompatible changes:
github.com/gardener/gardener/pkg/apis/resources/v1alpha1
  Compatible changes:
  - OriginLabel: added
github.com/gardener/gardener/pkg/apis/resources/v1alpha1/helper
  Compatible changes:
  - OriginLabelForManagedResource: added
  - SplitOriginLabel: added
make: *** [Makefile:238: check-apidiff] Error 1 
```

2022-07-25 12:59 UTC, dimityrmirchev commented
/test pull-gardener-e2e-kind

2022-07-25 13:35 UTC, shafeeqes commented
> /retest-required
> 
> Not sure why `apidiff` is failing. All changes seem compatible to me. Logs show:
> 
> ```
> FAIL: contains incompatible changes:
> github.com/gardener/gardener/pkg/apis/resources/v1alpha1
>   Compatible changes:
>   - OriginLabel: added
> github.com/gardener/gardener/pkg/apis/resources/v1alpha1/helper
>   Compatible changes:
>   - OriginLabelForManagedResource: added
>   - SplitOriginLabel: added
> make: *** [Makefile:238: check-apidiff] Error 1 
> ```

This is expected. api-diff is not a "required" test to merge.

2022-07-26 04:46 UTC, shafeeqes reviewed
The changes looks good to me. But do we need the origin annotation now? Can we not replace its usage with the label instead? We can even make use of label selectors (like [here](https://github.com/gardener/gardener/blob/a58e1877da2763f6237a0304ed052be6e02ffadb/pkg/resourcemanager/controller/managedresource/reconciler.go#L823-L836)).

2022-07-26 04:47 UTC, shafeeqes commented
/retest-required

2022-07-26 06:09 UTC, dimityrmirchev commented
There is some issue with this PR. I will try to reproduce it locally and see what is going on.
> But do we need the origin annotation now? Can we not replace its usage with the label instead?

I think that the annotation may not be necessary any more. This can be addressed at a later stage.

2022-07-26 11:42 UTC, dimityrmirchev commented
Label values were exceeding 63 symbols which is a limitation on the label itself ([ref](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set)). I changed to constant labeling across all objects managed by the GRM.

2022-07-26 11:43 UTC, rfranzke requested changes
Can you explain again the rationale of this PR/the underlying issue? In #6385 you write:

> Resources created by GRM to be labeled so that they can be easily described with object selectors used by different webhooks. 

However, this PR adds origin labels with a "random" name (containing cluster ID, namespace and annotation). How does this help now if I have to know these details?

We already add `origin=gardener` labels to some of the resources. Isn't something like this what we need here? You were already proposing in the issue:

> Some suggestions about the labeling convention:
> 1. `resources.gardener.cloud/origin=resourcemanager`
> 2. `resources.gardener.cloud/origin=namespace/mr-name`
> 3. `gardener.cloud/origin=resourcemanager`
> 4. others?

I vote for `resources.gardener.cloud/origin`. The value of the origin should probably be configurable (defaulting to `gardener`).

2022-07-26 11:45 UTC, rfranzke commented on docs/concepts/resource-manager.md
> +In addition all objects managed by the resource manager get a dedicated label `resources.gardener.cloud/managed-by: resource-manager`. This label can be used in order to easily describe these objects
```suggestion
In addition, all objects managed by the resource manager get a dedicated label `resources.gardener.cloud/managed-by: resource-manager`. This label can be used in order to easily describe these objects with a [selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).
```

2022-07-26 11:52 UTC, dimityrmirchev commented
@rfranzke The rationale behind the "random" name was that it can serve in two scenarios:
 - I want to select all objects where the label exists
 - I want to select all objects where the label exists and has a particular value (not sure if there is such use cases)
 
Anyway this approach was in the end not feasible due to label length constraints. I am not set on the current label value `resources.gardener.cloud/managed-by: resource-manager` so I can change it to `resources.gardener.cloud/origin: gardener` (or something else) if this is the consensus.

2022-07-26 12:01 UTC, rfranzke commented
OK, thanks. I'm also fine with `.../managed-by`, this sounds better and given that we already have this `origin` annotation is probably less confusing. However, as said, I think the value should be configurable

2022-07-26 12:26 UTC, dimityrmirchev commented
Do you mean configurable like part of the [ControllerConfig](https://github.com/gardener/gardener/blob/5ac7715129d564ee7a22092e249c0c0178496312/pkg/resourcemanager/controller/managedresource/add.go#L60) and probably passed as a flag on GRM start? If this is done all workloads that want to use this label in a selector should also know about its value (unless they use the "exists" label operator). Do we have any use case or immediate benefit to doing this?

2022-07-26 12:29 UTC, rfranzke commented
> Do you mean configurable like part of the [ControllerConfig](https://github.com/gardener/gardener/blob/5ac7715129d564ee7a22092e249c0c0178496312/pkg/resourcemanager/controller/managedresource/add.go#L60) and probably passed as a flag on GRM start?

Yes

> Do we have any use case or immediate benefit to doing this?

I'm thinking about scenarios where multiple GRMs are active in the same cluster, e.g. in managed seeds. There might be the need to differentiate.

2022-07-26 12:38 UTC, dimityrmirchev commented
Thanks. Then I can add this addition and leave a default value. One last thing. Do you prefer this value to be "gardener" or "resource-manager"?

2022-07-26 12:44 UTC, rfranzke commented
I think GRM is just the mechanism to deploy the resources, but the actually originator of the source is `gardener`, so I would use `gardener` as default.

2022-07-26 13:44 UTC, rfranzke reviewed
Thanks, this looks good.
Can you please adjust the integration test to make sure the label is present and lost under update (https://github.com/gardener/gardener/blob/master/test/integration/resourcemanager/managedresource/resource_test.go)?

2022-07-28 14:40 UTC, rfranzke reviewed
/lgtm
/approve

2022-07-28 14:40 UTC, rfranzke commented
/unassign @rfranzke

2022-07-29 07:00 UTC, timebertt commented
Thanks for this PR, well done!

2022-08-01 03:00 UTC, shafeeqes commented
/retest

2022-08-01 04:21 UTC, merged