Upgrade gardener/autoscaler
gardener/gardener pull request #6428
Opened 2022-08-01 11:19 UTC by rishabh-11

**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
Updates the CA image in the charts for v1.23.0
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following image is updated:
- eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler: v1.22.2 (For Kubernetes `1.22`)
The following image is added:
- eu.gcr.io/gardener-project/gardener/autoscaler/cluster-autoscaler: v1.23.0 (For Kubernetes >= `1.23`)

```

2022-08-01 11:24 UTC, himanshu-kun approved these changes
/lgtm

2022-08-01 11:35 UTC, ialidzhikov commented
/ok-to-test

2022-08-02 06:48 UTC, ialidzhikov requested changes
The v1.23 image fails with:

```
$ k -n shoot--foo--bar get po cluster-autoscaler-9f8858789-tlcz7
NAME                                 READY   STATUS             RESTARTS   AGE
cluster-autoscaler-9f8858789-tlcz7   0/1     CrashLoopBackOff   6          7m42s

$ k -n shoot--foo--bar logs cluster-autoscaler-9f8858789-tlcz7
standard_init_linux.go:228: exec user process caused: no such file or directory
```

2022-08-02 06:56 UTC, himanshu-kun commented
> The v1.23 image fails with:
> 
> ```
> $ k -n shoot--foo--bar get po cluster-autoscaler-9f8858789-tlcz7
> NAME                                 READY   STATUS             RESTARTS   AGE
> cluster-autoscaler-9f8858789-tlcz7   0/1     CrashLoopBackOff   6          7m42s
> 
> $ k -n shoot--foo--bar logs cluster-autoscaler-9f8858789-tlcz7
> standard_init_linux.go:228: exec user process caused: no such file or directory
> ```

taking a look 🤔

2022-08-02 12:16 UTC, ialidzhikov requested changes

2022-08-02 12:16 UTC, ialidzhikov commented on charts/images.yaml
> +  tag: "v1.23.0"
```suggestion
  tag: "v1.23.1"
```

2022-08-02 13:07 UTC, himanshu-kun approved these changes

2022-08-02 14:20 UTC, ialidzhikov approved these changes
/lgtm
/approve

2022-08-02 14:21 UTC, merged