Enhance etcd readiness check
gardener/gardener pull request #6434
Opened 2022-08-01 15:35 UTC by timuthy

**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR enhances the readiness check for `etcd` resources. It is performed when Gardenlet waits for Etcd-Druid to successfully finish its reconciliation. As written in https://github.com/gardener/gardener/issues/6419#issuecomment-1201281436, the definition for `etcd.status.ready` has become ambiguous since multi-node etcd.

Unexpectedly, `etcd.status.ready` can be `true` while an update is still being rolled out and thus makes Gardenlet to proceed with the shoot reconcile/delete flow in some occasions. 

**Which issue(s) this PR fixes**:
Fixes #6419

**Special notes for your reviewer**:
The bug was found in the scope of #6419 which explains the situation in more detail. **Please note, that the bug itself is only relevant in combination with HA shoot clusters, i.e. those which have a multi-node etcd in their control plane**.

**Release note**:

```bugfix operator
A bug has been fixed for HA shoots and their underlying etcd clusters. In some occasions, Gardenlet didn't wait for changes to be completely rolled out to etcd. Especially in combination with the CA-rotation feature this could cause the cluster being stuck in an unrecoverable state.
```

2022-08-02 06:38 UTC, plkokanov requested changes
Just one nit.

2022-08-02 06:38 UTC, plkokanov commented on pkg/operation/botanist/component/etcd/waiter.go
> +		return fmt.Errorf("update is being rolled out, only %d/%d replicas are up-to-date", etcd.Status.Replicas, etcd.Status.UpdatedReplicas)
```suggestion
		return fmt.Errorf("update is being rolled out, only %d/%d replicas are up-to-date", etcd.Status.UpdatedReplicas,  etcd.Status.Replicas)
```

2022-08-02 18:01 UTC, timuthy commented on pkg/operation/botanist/component/etcd/waiter.go
> +		return fmt.Errorf("update is being rolled out, only %d/%d replicas are up-to-date", etcd.Status.Replicas, etcd.Status.UpdatedReplicas)
Makes sense, thank you 😄

2022-08-03 09:44 UTC, ialidzhikov reviewed
/lgtm

2022-08-03 09:45 UTC, plkokanov approved these changes
/lgtm

2022-08-03 10:20 UTC, merged