Add Kibana dashboard
gardener/gardener pull request #644
Opened 2019-01-09 09:15 UTC by KristianZH

**What this PR does / why we need it**:
Creating Kibana dashboard automatically when Kibana is deployed.

<img width="1773" alt="screen shot 2019-01-09 at 9 42 33" src="https://user-images.githubusercontent.com/16671526/50889069-ba9dc200-13ff-11e9-87f8-39b90e82b135.png">

/cc @ialidzhikov @vlvasilev @vpnachev @dguendisch 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2019-01-09 09:29 UTC, rfranzke requested changes

2019-01-09 09:29 UTC, rfranzke commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-deployment.yaml
>        annotations:
checksum annotation for new configmap is missing

2019-01-09 09:29 UTC, rfranzke commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-saved-objects-config.yaml
> +  namespace: shoot--i355448p--i355448-l
what's this?

2019-01-09 10:56 UTC, rfranzke submitted a review, later dismissed
/lgtm

2019-01-09 10:58 UTC, rfranzke commented
Merge is on hold until @ialidzhikov and @dguendisch reviewed.

2019-01-09 11:23 UTC, dguendisch commented
/lgtm

2019-01-09 11:30 UTC, dguendisch submitted a review, later dismissed
/lgtm

2019-01-09 14:22 UTC, ialidzhikov requested changes
You could also rebase.

2019-01-09 14:22 UTC, ialidzhikov commented on pkg/operation/common/utils.go
> +		configmaps   = []string{"kibana-object-registration", "curator-hourly-config", "curator-daily-config", "fluent-bit-config", "fluentd-es-config"}
You could add also the new `kibana-saved-objects` cm in the array.

2019-01-09 14:22 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-saved-objects-config.yaml
> +{
error converting YAML to JSON: yaml: line 10: could not find expected ':'. You could fix the yaml.

2019-01-09 15:40 UTC, ialidzhikov requested changes

2019-01-09 15:40 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-saved-objects-config.yaml
> +    {"attributes": {"title": "logstash-*", "timeFieldName": "@timestamp"}}
You could also expand this json in order to be consistent in the formatting.

2019-01-09 15:40 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-saved-objects-config.yaml
> +        "title": "Dashboard Pod Logs",
We already know that it is a dashboard. Maybe `Pod Logs` is a better name?

2019-01-09 15:40 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-deployment.yaml
> +        name: auto-register-objects
Maybe `auto-create-objects` is a better name because register was a specific term only for index pattern.

2019-01-09 15:40 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
> +      HTTP_RESPONSE = "$1"
This will result in `line 11: HTTP_RESPONSE: command not found`. It should be `HTTP_RESPONSE="$1"`.

2019-01-09 15:40 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
> +    function get_http_status {
Maybe something like:
```bash
function get_http_status {
  local HTTP_RESPONSE="$1"
  echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://'
}
```
and:
```bash
HTTP_STATUS=$(get_http_status "$HTTP_RESPONSE")
```

2019-01-09 15:40 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
> +    create_saved_objects
Maybe `create_dashboard` is a better name?

2019-01-09 15:40 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-saved-objects-config.yaml
> +            "title": "Dashboard Pod Logs",
Maybe `Pod Logs` is a better name, we already know that it is a dashbaord.

2019-01-09 16:15 UTC, ialidzhikov requested changes

2019-01-09 16:15 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
> +         -X POST $KIBANA_HOST/api/kibana/dashboards/import?exclude=index-pattern \
As far as I see, we don't have an index-pattern in dashboard.json. Maybe it is a left-over and we can remove the exclude query param?

2019-01-09 16:15 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-saved-objects-config.yaml
> +            "title": "log_histogramm",
Typo - histogram. You could fix it everywhere.

2019-01-10 08:04 UTC, ialidzhikov requested changes

2019-01-10 08:04 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
> +          get_http_status "$HTTP_RESPONSE"
You could remove this.

2019-01-10 08:04 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
> +        get_http_status "$HTTP_RESPONSE"
You could remove this.

2019-01-10 08:04 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-objects-registration-config.yaml
> +         get_http_status "$HTTP_RESPONSE"
You could remove this.

2019-01-10 12:28 UTC, KristianZH commented
@vpnachev Can you review the last changes

2019-01-10 12:37 UTC, ialidzhikov submitted a review, later dismissed
/lgtm

2019-01-10 12:41 UTC, vpnachev requested changes
Fix the comment.

2019-01-10 12:41 UTC, vpnachev commented on pkg/operation/common/utils.go
> +		configmaps   = []string{"kibana-object-registration", "kibana-saved-objects-config", "curator-hourly-config", "curator-daily-config", "fluent-bit-config", "fluentd-es-config"}
The ConfigMap is not called `kibana-saved-objects-config` but `kibana-saved-objects`

2019-01-10 21:27 UTC, merged