[WIP] Document how to create new cloud provider API and validate requests
gardener/gardener pull request #652
Opened 2019-01-14 16:38 UTC by deitch

**What this PR does / why we need it**:
Document the steps to add a new cloud provider to the Gardener API and validate the requests

**Special notes for your reviewer**:
As discussed with @rfranzke on Slack. Continuation of #647 

**Release note**:

```improvement developer
Document adding new cloud provider to gardener component
```

2019-01-15 11:06 UTC, deitch commented
It feels like there is a lot of repetition here, @rfranzke . Does some of the code need to be created twice? Once at high-level and once in `v1beta1`?

2019-01-15 11:07 UTC, rfranzke commented
What do you mean? I didn't get it

2019-01-15 11:11 UTC, deitch commented
> I didn't get it

I based the doc on #360 and #366. If I look at #360, I see a lot of what goes into https://github.com/gardener/gardener/blob/master/pkg/apis/garden/types.go is similar to or duplicative of what goes into https://github.com/gardener/gardener/blob/master/pkg/apis/garden/v1beta1/types.go . Same for `helpers.go`.

2019-01-15 11:13 UTC, rfranzke commented
Can you give an example?

2019-01-15 11:19 UTC, deitch commented
Sure. Using #360, look at [here](https://github.com/gardener/gardener/pull/360/files#diff-9c42317eee788d58380acadcfab41545R47) and [here](https://github.com/gardener/gardener/pull/360/files#diff-a3d3f75ad34298fb9696284b0ef772c2R55). There were a few more.

2019-01-15 11:22 UTC, rfranzke commented
Ah OK, yes, the types are "duplicate" (not in general, but in our case). The internal API version is the same like the external API version (v1beta1).
See also https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go and https://github.com/kubernetes/api/blob/master/apps/v1/types.go, that's the same.

The API server acts on the internal version while the controller-manager acts on the v1beta1 version.

2019-01-15 11:23 UTC, deitch commented
Yeah, makes sense.

I will await your review (i.e. finding my errors) on the rest of the doc.

2019-01-15 11:26 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +  * `Secret` [40-secret-seed.yaml.tpl](../../hack/templates/resources/40-secret-seed.yaml.tpl) This contains the secrets necessary to invoke the cloud provider's API to deploy the Seed cluster, and t
Regarding the review, I thought you are still working on it. About this part we already talked in Slack: The seed cluster is not deployed by Gardener, it's just connected to it by providing the proper kubeconfig.

2019-01-15 11:27 UTC, deitch commented on docs/development/new-cloud-provider-api-extension.md
> +  * `Secret` [40-secret-seed.yaml.tpl](../../hack/templates/resources/40-secret-seed.yaml.tpl) This contains the secrets necessary to invoke the cloud provider's API to deploy the Seed cluster, and t
Oh yes, I missed updating this. Coming now.

2019-01-15 11:28 UTC, deitch commented on docs/development/new-cloud-provider-api-extension.md
> +  * `Secret` [40-secret-seed.yaml.tpl](../../hack/templates/resources/40-secret-seed.yaml.tpl) This contains the secrets necessary to invoke the cloud provider's API to deploy the Seed cluster, and t
Updated.

2019-01-15 11:29 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +  * `Secret` [40-secret-seed.yaml.tpl](../../hack/templates/resources/40-secret-seed.yaml.tpl) This contains the secrets necessary to invoke the cloud provider's API to deploy the Seed cluster, and t
Thx! Will check soon 👍

2019-01-15 17:43 UTC, rfranzke requested changes
Very detailed, thank you for your efforts. Once we move out the cloud providers we will need to adapt the document, but the degree of detail shows that the move-out is very much needed. We must depend on clean APIs instead of munching everything together as of today. Thanks again!

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +1. Add the cloud provider to the template files in [hack/templates/resources](../../hack/templates/resources/) :
s/the cloud provider/the cloud provider specific configuration

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +  * `Secret` [40-secret-seed.yaml.tpl](../../hack/templates/resources/40-secret-seed.yaml.tpl) This contains the secrets necessary to invoke the cloud provider's API to manage Shoot ectd backups, and
s/to manage .../to create blob storage buckets for managing the etcd backups of shoot clusters

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +  * `Seed`: [50-seed.yaml.tpl](../../hack/templates/resources/50-seed.yaml.tpl) This contains the configuration for the Seed cluster..
s/cluster../cluster.

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +  * `Secret`: [70-secret-cloudprovider.yaml.tpl](../../hack/templates/70-secret-cloudprovider.yaml.tpl) This contains the secrets necessary for to invoke the cloud provider's API to deploy the Shoot
s/secrets/credentials

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +  * `SecretBinding`: [80-secretbinding-cloudprovider.yaml.tpl](../../hack/templates/resources/80-secretbinding-cloudprovider.yaml.tpl) This binds the secret defined in the previous step with quotas f
I would leave the quota part out to reduce surface for confusion - we will provide separate documentation on how exactly the `SecretBinding` resource is used. Let's focus here on the cloud provider extension part.

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +    * Add logic in `getShootWorkerResources()` to populate the return `[]quoteworker` slice with the workers for the cloud provider.
s/quoteworker/quotaworker

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +    * Add logic in `quotaVerificationNeeded()` to return if quote verification is required. Note: What is "quote verification"?
s/quote/quota

It is possible to define Quotas for Shoot clusters, e.g., project "A" may use shoots with max. 8 CPUs.
The "quota verification" function checks whether a shoot that was put under quota has changes in relevant sections of the shoot specification that might be related to CPU (in this example), e.g. the worker pools. The admission controller checks whether this change is allowed or not (constrained by the defined Quota).

2019-01-15 17:43 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +
Remove unneeded empty lines at the end of the document

2019-01-16 08:54 UTC, deitch commented on docs/development/new-cloud-provider-api-extension.md
> +  * `SecretBinding`: [80-secretbinding-cloudprovider.yaml.tpl](../../hack/templates/resources/80-secretbinding-cloudprovider.yaml.tpl) This binds the secret defined in the previous step with quotas f
Hmm... ok. But we do need to update that `tpl` file, so some description would be useful. I guess as long as it binds to the right `secretRef` we are good.

2019-01-16 08:55 UTC, deitch commented on docs/development/new-cloud-provider-api-extension.md
> +    * Add logic in `getShootWorkerResources()` to populate the return `[]quoteworker` slice with the workers for the cloud provider.
Do you want to quote that? :-)

2019-01-16 08:58 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +    * Add logic in `getShootWorkerResources()` to populate the return `[]quoteworker` slice with the workers for the cloud provider.
[?](https://github.com/gardener/gardener/blob/master/plugin/pkg/shoot/quotavalidator/admission.go#L430)

2019-01-16 09:00 UTC, deitch commented
> the degree of detail shows that the move-out is very much needed

Yes, indeed. It took quite some time to back out all of the areas. Even having written this, I am a little nervous about doing the implementation, but we shall see.

> We must depend on clean APIs instead of munching everything together as of today.

You have my vote! :-)

Addressed all of your comments and rebased, of course. Back to you.

2019-01-16 09:01 UTC, deitch commented on docs/development/new-cloud-provider-api-extension.md
> +    * Add logic in `getShootWorkerResources()` to populate the return `[]quoteworker` slice with the workers for the cloud provider.
I was making a pun on my type of "quota" to "quote". The pun failed...

2019-01-16 09:10 UTC, rfranzke commented on docs/development/new-cloud-provider-api-extension.md
> +    * Add logic in `getShootWorkerResources()` to populate the return `[]quoteworker` slice with the workers for the cloud provider.
Haha 👍

2019-01-16 09:13 UTC, deitch commented on docs/development/new-cloud-provider-api-extension.md
> +    * Add logic in `getShootWorkerResources()` to populate the return `[]quoteworker` slice with the workers for the cloud provider.
It was a pretty bad joke anyways...

2019-01-16 11:33 UTC, rfranzke commented
Thank's, looks good so far. PR is still labelled as "WIP" - should we wait with merge?

2019-01-16 11:37 UTC, deitch commented
Not at all. I put `WIP` more as an indication of, “I’m not sure what I’m doing here, and it probably will take a few reviews by @rfranzke and others before it makes any sense!” :-)

I’ll remove that now.

2019-01-16 11:41 UTC, deitch commented
Is there anything else to add? Did I miss any?

2019-01-16 11:43 UTC, rfranzke commented
Don't think so. Let's merge it. :) Thank you again!

2019-01-16 11:43 UTC, rfranzke approved these changes
/lgtm

2019-01-16 17:43 UTC, merged