Skip problematic webhook check for Gardener-managed webhooks
gardener/gardener pull request #6573
Opened 2022-08-24 14:31 UTC by rfranzke

**How to categorize this PR?**

/area ops-productivity dev-productivity
/kind enhancement

**What this PR does / why we need it**:
- Gardener-managed webhooks are no longer considered by the shoot care controller when it comes to find problematic webhooks.
- The `node-shoot` webhook was using `Fail` failure policy, but `Ignore` is good enough and is more relaxed which is fine for the local setup.

**Which issue(s) this PR fixes**:
Fixes #6562 

**Release note**:

```other operator
Gardener-managed webhooks are no longer considered by the shoot care controller when it comes to find problematic webhooks.
```

2022-08-25 06:12 UTC, acumino commented on pkg/operation/care/constraints.go
> +		if strings.Contains(webhookConfig.Annotations[resourcesv1alpha1.OriginAnnotation], c.shoot.SeedNamespace) {
Should we use the label selector here to select based on `resources.gardener.cloud/managed-by` label which was introduced with https://github.com/gardener/gardener/pull/6393?

2022-08-25 07:14 UTC, oliver-goetz commented
Apart from @acumino comment to `resources.gardener.cloud/managed-by` label, lgtm

2022-08-25 14:43 UTC, rfranzke commented
/test pull-gardener-integration

2022-08-26 10:48 UTC, acumino requested changes

2022-08-26 10:48 UTC, acumino commented on pkg/operation/care/constraints.go
> +		}
This is not required as we will get only that webhook here that doesn't have `resources.gardener.cloud/managed-by` label.

2022-08-26 10:48 UTC, acumino commented on pkg/operation/care/constraints.go
> +		}
Same here.

2022-08-29 05:48 UTC, acumino reviewed
/lgtm

2022-08-29 07:01 UTC, oliver-goetz commented
/approve

2022-08-29 07:58 UTC, merged