Drop gardenlet dependency towards openvpn binary
gardener/gardener pull request #6641
Opened 2022-09-07 09:40 UTC by acumino

**How to categorize this PR?**

/area security
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6561

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-09-07 09:41 UTC, acumino commented
/test all

2022-09-07 09:43 UTC, acumino commented
/test all

2022-09-07 11:04 UTC, rfranzke commented
@ScheererJ @marwinski Can you please check if this is a valid approach?

2022-09-07 13:00 UTC, ScheererJ requested changes
Please adapt the minor issue.

In general, I have no problem with replacing `openvpn`/`openssl` for key generation with go's `crypto/rand` library.

2022-09-07 13:00 UTC, ScheererJ commented on pkg/utils/secrets/vpn_tlsauth.go
> +	key := startString + keyString + endString
Even though `openvpn` can likely work with the key as far as I can tell from [its parsing logic](https://github.com/OpenVPN/openvpn/blob/d2e6605fec0d8641deef0ec7807811d0222bb71e/src/openvpn/crypto.c#L1168) it would probably be better if the key is formatted as it was before, i.e. adding a line break `\n` character after every 32 characters.
(This may make the line break at the beginning of `endString` redundant.)

2022-09-07 13:00 UTC, ScheererJ commented on pkg/utils/secrets/vpn_tlsauth.go
>  func generateVPNKey() ([]byte, error) {
It may be worthwhile to add a comment what kind of content this function generates and how this can be done with `openvpn`.

2022-09-07 16:34 UTC, acumino commented
/test pull-gardener-integration

2022-09-08 03:28 UTC, rfranzke commented
@acumino Please add a release note.
/approve

2022-09-08 07:25 UTC, ScheererJ approved these changes
/lgtm
/approve

2022-09-08 08:22 UTC, merged