landscape issue 66, add api server failure rate high to control plan
gardener/gardener pull request #6736
Opened 2022-09-26 02:07 UTC by cathyzhang05

**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Add api server failure rate high alert to control plan

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2022-09-26 02:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=6736) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=6736) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=6736) it.</sub>

2022-09-26 02:10 UTC, cathyzhang05 commented
/assign @istvanballok

2022-09-26 02:14 UTC, cathyzhang05 commented
/unassign @istvanballok 
/invite @istvanballok

2022-09-26 03:34 UTC, shafeeqes commented
/ok-to-test

2022-09-26 05:04 UTC, shafeeqes commented
Please adapt the unit tests.

2022-09-26 05:06 UTC, shafeeqes commented
/cc @istvanballok

2022-09-28 02:56 UTC, cathyzhang05 commented
/retest

2022-09-28 08:16 UTC, istvanballok requested changes
Please fix the typo in the title and the description: `plan` -> `plane` and make sure to add a release note.

Also note that the title prefix "landscape issue 66, " contains a prominent reference to an SAP internal repository which is not so meaningful in this public g/g repository. Please check some other PRs in this repository and follow their example by removing the mentioned prefix from the title.

2022-09-28 08:16 UTC, istvanballok commented on pkg/operation/botanist/component/kubeapiserver/monitoring.go
> +      summary: Kubernetes API server failure rate is high
There are several issues here, please review / double check.

- please make sure the fields and texts are consistent (30m vs 10mins)
- is 0.3% high? maybe you meant 30%? Anyways, the comparison with this value is missing in the promql expression. Without such a comparison (`>0.3`) the alert would always fire
- please watch out for typo-s (exceed, exceeds)

please consider using the local setup to test your changes: https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md

2022-10-21 11:33 UTC, rfranzke commented
@cathyzhang05 What is the status of this PR? Do you still plan to continue working on it?

2022-10-25 08:41 UTC, cathyzhang05 commented
> @cathyzhang05 What is the status of this PR? Do you still plan to continue working on it?

Hi @rfranzke , previously I have some trouble to setup local environment, right now it has been resolved. I am testing locally. And adjusting the threshold values.

2022-10-28 07:25 UTC, istvanballok approved these changes
/lgtm

Please fix the typo (plan vs. plane) in the PR description and add a sentence as a release note.

2022-10-28 08:47 UTC, cathyzhang05 commented
/assign @oliver-goetz

2022-10-28 12:05 UTC, oliver-goetz commented
/retitle Add new Prometheus alert `ApiserverRequestsFailureRate` for API Server failure rate
/approve

2022-10-28 12:44 UTC, merged