Speed up local image builds by defining Skaffold dependencies
gardener/gardener pull request #6781
Opened 2022-10-06 14:55 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
#6735 already started with it, however it actually introduced more problems than it solved since it didn't specify the full list of dependencies. Consequently, the images were only re-built when there were changes in the provided packages. If there were changes in other packages (actually used but not provided in `skaffold.yaml`) then they were not re-built.

With this PR, we define all transitive `gardener/gardener` package dependencies for each binary which (a) fixes the mentioned problem and (b) speeds up image builds in general.

The information was retrieved via

```shell
go list -f '{{ .Deps }}' ./cmd/gardener-apiserver
```

etc.

**Which issue(s) this PR fixes**:
Part of #6016

**Special notes for your reviewer**:
As you can see, there are quite some weird dependencies that shouldn't exist ideally (e.g., `gardener-apiserver` should not depend on `pkg/resourcesmanager/*`, etc.). Improving this is out of scope of this PR, however I'll add a respective task to #6016.

**Release note**:

```other operator
NONE
```

2022-10-07 08:17 UTC, plkokanov commented
This means that any new package that we add will also have to be added to the appropriate dependency list, right? Is there anyway we can add a check whether that was done, or document it?

2022-10-07 11:29 UTC, rfranzke commented
Fair point @plkokanov, I have reworked the PR and added a script that checks for the correctly defined dependencies in the `skaffold.yaml` as part of `make check`. As a result, it's much more verbose now, but definitely much easier and less error-prone to maintain. Thanks for the suggestion, PTAL.

2022-10-07 12:47 UTC, plkokanov requested changes
Thanks for adding the check!
Just one very small nit/suggestion, otherwise lgtm.

2022-10-07 12:47 UTC, plkokanov commented on hack/check-skaffold-deps.sh
> +    tr " " "\n" |\
You can skip the `tr` call by using 
```
  go list -f '{{join .Deps "\n"}}' "./cmd/$binary_name" |\
```

2022-10-10 07:41 UTC, plkokanov commented
/lgtm
/approve

2022-10-10 08:25 UTC, merged