Streamline `gardener-resource-manager` entrypoint and introduce component configuration
gardener/gardener pull request #6865
Opened 2022-10-21 08:25 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity
/kind cleanup technical-debt

**What this PR does / why we need it**:
This PR streamlines the `gardener-resource-manager` entrypoint as well as all controllers and webhooks so that it is aligned with other components like `garden{er-controller-manager,er-scheduler,let}`.

It also introduces a component config API for GRM (previously it was using CLI flags only).

**Which issue(s) this PR fixes**:
Part of #4251

**Release note**:

```breaking developer
The `gardener-resource-manager` component has been reworked entirely. It now uses a component config instead of CLI flags. Also, its Helm chart has been dropped entirely since there was no usage.
```

2022-10-24 07:25 UTC, oliver-goetz commented
/assign

2022-10-24 20:24 UTC, oliver-goetz reviewed
I'm currently in the middle of commit `Rework main entrypoint`. Some nits I discovered so far.

2022-10-24 20:24 UTC, oliver-goetz commented on docs/concepts/resource-manager.md
> +kind: `ManagedResource`
keeping the previous version looks better.
```suggestion
kind: ManagedResource
```

2022-10-24 20:24 UTC, oliver-goetz commented on docs/concepts/resource-manager.md
> +kind: `ManagedResource`
same here

2022-10-24 20:24 UTC, oliver-goetz commented on docs/concepts/resource-manager.md
> +The `gardener-resource-manager` can manage a resource in different modes. The supported modes are:
This sentence says **different modes**, but there is only one (`Ignore`) listed below. It sounds as if other modes have been forgotten to be mentioned.

2022-10-24 20:24 UTC, oliver-goetz commented on docs/concepts/resource-manager.md
> +In order to enable the _TokenInvalidator_ you have to set `.controllers.tokenValidator.enabled=.webhooks.tokenValidator.enabled=true` in the component configuration.
```suggestion
In order to enable the _TokenInvalidator_ you have to set `.controllers.tokenInvalidator.enabled=true` and `.webhooks.tokenInvalidator.enabled=true` in the component configuration.
```

2022-10-24 20:24 UTC, oliver-goetz commented on pkg/resourcemanager/apis/config/register.go
> +// GroupName is the group name use in this package.
```suggestion
// GroupName is the group name used in this package.
```

2022-10-24 20:24 UTC, oliver-goetz commented on pkg/resourcemanager/apis/config/validation/validation.go
> +	if conf.LogLevel != "" && !sets.NewString(logger.AllLogLevels...).Has(conf.LogLevel) {
An empty LogLevel should not be allowed
```suggestion
	if !sets.NewString(logger.AllLogLevels...).Has(conf.LogLevel) {
```

2022-10-24 20:24 UTC, oliver-goetz commented on pkg/resourcemanager/apis/config/validation/validation.go
> +	if conf.LogFormat != "" && !sets.NewString(logger.AllLogFormats...).Has(conf.LogFormat) {
Same for LogFormat
```suggestion
	if !sets.NewString(logger.AllLogLevels...).Has(conf.LogLevel) {
```

2022-10-24 20:24 UTC, oliver-goetz commented on cmd/gardener-controller-manager/app/app.go
>  		GracefulShutdownTimeout: pointer.Duration(5 * time.Second),
```suggestion
		Logger: log,
		Scheme: kubernetes.GardenScheme,
		GracefulShutdownTimeout: pointer.Duration(5 * time.Second),

		HealthProbeBindAddress:  fmt.Sprintf("%s:%d", cfg.Server.HealthProbes.BindAddress, cfg.Server.HealthProbes.Port),
		MetricsBindAddress:      fmt.Sprintf("%s:%d", cfg.Server.Metrics.BindAddress, cfg.Server.Metrics.Port),
```
There is a tiny difference compare to the others 😅

2022-10-25 17:01 UTC, oliver-goetz requested changes
some bits and pieces in the helm chart. 
Otherwise 🚀

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
Deployment via botanist adds this namespace selector
```yaml
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
      - kubernetes-dashboard
```

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
Deployment via botanist adds this namespace selector
```yaml
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
      - kubernetes-dashboard
```

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
Deployment via botanist adds this namespace selector
```yaml
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
      - kubernetes-dashboard
```

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
Deployment via botanist adds this namespace selector
```yaml
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
      - kubernetes-dashboard
```

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/runtime/templates/deployment.yaml
> +spec:
When deployed by botanist the labels look slightly different.
```yaml
  labels:
    app: gardener-resource-manager
```

However, the labels seem to be consistent in both scenarios.

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +      - resource-manager
Please see my comment at `gardener-resource-manager` deployment. 
The labels and selectors seem look consistently in the helm chart, but Botanist uses different labels.
```yaml
  labels:
    app: gardener-resource-manager
```

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +    - key: app
Same here with the labels.

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +      operator: NotIn
Same here with the labels.

2022-10-25 17:01 UTC, oliver-goetz commented on charts/gardener/resource-manager/charts/runtime/templates/configmap.yaml
> +    logFormat: {{ .Values.global.config.leaderElection.logFormat }}
`logLevel` and `logFormat` under `leaderElection` looks strange. Maybe something like this.
```suggestion
    logLevel: {{ .Values.global.config.logLevel | default "info" }}
    logFormat: {{ .Values.global.config.logFormat | default "json" }}
```

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
Yes, but botanist is specific to seeds/shoots while this Helm chart is for general-purpose and does not make such assumptions.

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
ref https://github.com/gardener/gardener/pull/6865#discussion_r1005235810

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
ref https://github.com/gardener/gardener/pull/6865#discussion_r1005235810

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +  reinvocationPolicy: Never
ref https://github.com/gardener/gardener/pull/6865#discussion_r1005235810

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/runtime/templates/deployment.yaml
> +spec:
ref https://github.com/gardener/gardener/pull/6865#discussion_r1005235810

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +      - resource-manager
ref https://github.com/gardener/gardener/pull/6865#discussion_r1005235810

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +    - key: app
ref https://github.com/gardener/gardener/pull/6865#discussion_r1005235810

2022-10-26 05:24 UTC, rfranzke commented on charts/gardener/resource-manager/charts/application/templates/mutatingwebhookconfiguration.yaml
> +      operator: NotIn
ref https://github.com/gardener/gardener/pull/6865#discussion_r1005235810

2022-10-26 08:02 UTC, oliver-goetz commented
/lgtm

2022-10-26 09:23 UTC, oliver-goetz approved these changes

2022-10-26 10:55 UTC, rfranzke commented
/test pull-gardener-e2e-kind

2022-10-26 11:33 UTC, merged