Multi client configuration
gardener/gardener pull request #69
Opened 2018-01-28 18:53 UTC by mvladev

It allows you to have multiple client configurations:

```yaml
apiVersion: componentconfig.sapcloud.io/v1alpha1
kind: ControllerManagerConfiguration
clientConnection:
  acceptContentTypes: application/vnd.kubernetes.protobuf
  contentType: application/vnd.kubernetes.protobuf
  qps: 100
  burst: 130
  kubeconfig: /Users/my-user/.kube/config
gardenerClientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
  kubeconfig: /Users/muy-user/git/go/src/github.com/gardener/gardener/dev/kubeconfig
controller:
  healthCheckPeriod: 30s
  reconciliation:
    concurrentSyncs: 20
    resyncPeriod: 10m
    retryDuration: 1440m
gardenNamespace: garden
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: configmaps
logLevel: info
metrics:
  interval: 30s
server:
  bindAddress: 0.0.0.0
  port: 2718

```

2018-01-29 07:09 UTC, rfranzke requested changes
Thank you, just a few suggestions.
Please either squash both commits or separate changes in the API from other changes.

2018-01-29 07:09 UTC, rfranzke commented on Makefile
> +	@go run -ldflags $(LD_FLAGS_RUN) cmd/garden-controller-manager/main.go --config=dev/componentconfig-garden-controller-manager.yaml
If we remove this we need to document somewhere that the `clientConnection.kubeconfig` field in the Garden controller manager's Componentconfig must be set properly.

2018-01-29 07:09 UTC, rfranzke commented on cmd/garden-controller-manager/app/garden_controller_manager.go
> +		gardnerKubeConfig = config.GardenerClientConnection.KubeConfigFile
Typo

2018-01-29 07:09 UTC, rfranzke commented on cmd/garden-controller-manager/app/garden_controller_manager.go
> +		&clientcmd.ClientConfigLoadingRules{ExplicitPath: gardnerKubeConfig},
Typo

2018-01-29 07:09 UTC, rfranzke commented on pkg/apis/componentconfig/v1alpha1/types.go
> +	// GarClientConnection specifies the kubeconfig file and client connection
Typo

2018-01-29 07:09 UTC, rfranzke commented on pkg/apis/componentconfig/v1alpha1/types.go
> +	// settings for the gardener-apiserver.
garden-apiserver

2018-01-29 07:33 UTC, mvladev commented
fixed all comments.

Squashed and `Makefile` changes will come in separate PR

2018-01-29 10:42 UTC, rfranzke commented
It seems that providing a GardenerClientConfiguration is mandatory:

```
$ make dev-all
time="2018-01-29T11:39:54+01:00" level=info msg="Starting Garden controller manager..."
panic: invalid configuration: no configuration has been provided

goroutine 1 [running]:
github.com/gardener/gardener/cmd/garden-controller-manager/app.NewCommandStartGardenControllerManager.func1(0xc42035a240, 0xc4203daf10, 0x0, 0x1)
	/Users/d065849/go/src/github.com/gardener/gardener/cmd/garden-controller-manager/app/garden_controller_manager.go:192 +0x10f
github.com/gardener/gardener/vendor/github.com/spf13/cobra.(*Command).execute(0xc42035a240, 0xc42000c070, 0x1, 0x1, 0xc42035a240, 0xc42000c070)
	/Users/d065849/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/gardener/gardener/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42035a240, 0xc42035a240, 0x0, 0x8)
	/Users/d065849/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/gardener/gardener/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42035a240, 0x8, 0x0)
	/Users/d065849/go/src/github.com/gardener/gardener/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/d065849/go/src/github.com/gardener/gardener/cmd/garden-controller-manager/main.go:30 +0x4a
exit status 2
make: *** [dev-all] Error 1
```

In case it has not been provided, we should fall-back to the normal Kubernetes Config: `k8sGardenClient.GetConfig()`

2018-01-31 14:16 UTC, mvladev commented
@rfranzke all previous issues are fixed

2018-01-31 14:46 UTC, rfranzke commented on Makefile
> +	@KUBECONFIG=~/.kube/config GARDENER_KUBECONFIG=~/.kube/config WATCH_NAMESPACE=$(USER) go run -ldflags $(LD_FLAGS_RUN) cmd/gardener-controller-manager/main.go --config=example/componentconfig-gardene
Let's keep `--config=dev/componentconfig-gardener-controller-manager.yaml`

2018-01-31 14:46 UTC, rfranzke commented on Makefile
> +	@KUBECONFIG=~/.kube/config GARDENER_KUBECONFIG=~/.kube/config go run -ldflags $(LD_FLAGS_RUN) cmd/gardener-controller-manager/main.go --config=example/componentconfig-gardener-controller-manager.yam
Let's keep `--config=dev/componentconfig-gardener-controller-manager.yaml`

2018-01-31 14:48 UTC, rfranzke reviewed
Thank you @mvladev , some suggestions due to recent renaming.

2018-01-31 14:48 UTC, rfranzke commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +	gardenClient := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
Can we call this `gardenerClient`? Sorry, we just recently renamed everything to `gardener-*`, so `gardener-apiserver` and `gardener-controller-manager`.

2018-01-31 14:48 UTC, rfranzke commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +	gardenClientConfig, err := gardenClient.ClientConfig()
Can we call this `gardenerClientConfig`? Sorry, we just recently renamed everything to `gardener-*`, so `gardener-apiserver` and `gardener-controller-manager`.

2018-01-31 14:48 UTC, rfranzke commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +	gardenClientSet, err := gardenclientset.NewForConfig(gardenClientConfig)
See above

2018-01-31 14:48 UTC, rfranzke commented on cmd/gardener-controller-manager/app/gardener_controller_manager.go
> +	k8sGardenClient.SetGardenClientset(gardenClientSet)
See above

2018-01-31 15:14 UTC, mvladev commented
@rfranzke renamed garden -> gardener

2018-02-01 09:27 UTC, rfranzke approved these changes
LGTM

2018-02-01 09:27 UTC, merged