Change curator's cronjob schedule
gardener/gardener pull request #692
Opened 2019-01-28 15:11 UTC by KristianZH

**What this PR does / why we need it**:
Until now all the curators have been triggering jobs at the same time. This could be dangerous because we can exceed the pod limit in this way.
  
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@ialidzhikov @vlvasilev @mvladev @vlerenc 
**Release note**:
```improvement operator
NONE
```

2019-01-28 16:12 UTC, ialidzhikov submitted a review, later dismissed
/lgtm

2019-01-29 00:29 UTC, mvladev requested changes

2019-01-29 00:29 UTC, mvladev commented on pkg/operation/botanist/controlplane.go
> +				"schedule": fmt.Sprintf("%d 0,6,12,18 * * *", ct.Minute()%54+5),
better have it 
```suggestion
				"schedule": fmt.Sprintf("%d %d,%d,%d,%d * * *", ct.Minute(), ct.Add(ct.Hour(), time.Hour * 6).Hour(), ct.Add(time.Hour * 12).Hour(), ct.Add(time.Hour * 18).Hour()),
```

2019-01-29 09:13 UTC, KristianZH commented on pkg/operation/botanist/controlplane.go
> +				"schedule": fmt.Sprintf("%d 0,6,12,18 * * *", ct.Minute()%54+5),
The daily curator serves for optimization of newly created indices. With your suggestion, this optimization will delay up to 5 hours and 59 mins in the worst case (The Shoot is created in 23:54)

2019-01-30 07:35 UTC, rfranzke approved these changes
/lgtm

2019-01-31 16:05 UTC, merged