Fix test to use TokenRequest API for garden clusters >=1.24
gardener/gardener pull request #6977
Opened 2022-11-09 14:16 UTC by vpnachev

**How to categorize this PR?**

/area testing
/kind bug

**What this PR does / why we need it**:
Fix test to use TokenRequest API for garden clusters >=1.24

**Which issue(s) this PR fixes**:
Fixes #6975 

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2022-11-09 14:18 UTC, vpnachev commented
/cc @rfranzke

2022-11-09 14:28 UTC, vpnachev commented
/cc @dguendisch

2022-11-09 14:42 UTC, dguendisch commented
/lgtm
thank you!

2022-11-10 06:46 UTC, rfranzke reviewed
/approve

2022-11-10 06:56 UTC, timebertt requested changes

2022-11-10 06:56 UTC, timebertt commented on test/testmachinery/gardener/security/rbac.go
> +
Can you simplify this to always use the token request API?
The minimum supported garden version is 1.20 which should offer the token request API by default.

2022-11-10 08:12 UTC, vpnachev commented
/lgtm cancel 

The test is leaking ServiceAccounts, I will try to fix this, too.

2022-11-10 09:55 UTC, timebertt commented
There is also https://github.com/gardener/gardener/blob/b7c070b02657b224d55ed73a54207d21ae3d976f/test/utils/shoots/access/serviceaccount.go including helpers for cleanup. You might want to reuse/share some code.

2022-11-10 12:35 UTC, vpnachev commented
/title Fix testmachinery test to always use TokenRequest API and to properly clean up created service account

2022-11-10 14:59 UTC, vpnachev commented on test/testmachinery/gardener/security/rbac.go
> +
Done.

2022-11-10 15:00 UTC, vpnachev commented
I am curious, can I lgtm this myself?
/lgtm

2022-11-11 06:41 UTC, timebertt approved these changes
/lgtm

2022-11-11 07:21 UTC, merged

2022-11-11 07:57 UTC, vpnachev commented
/cherry-pick release-v1.59

2022-11-11 07:57 UTC, vpnachev commented
/cherry-pick release-v1.58

2022-11-11 07:57 UTC, vpnachev commented
/cherry-pick release-v1.57