Drop support for Shoots with K8s < 1.20
gardener/gardener pull request #6987
Opened 2022-11-10 09:06 UTC by dimitar-kostadinov

**How to categorize this PR?**

/area open-source dev-productivity
/kind cleanup

**What this PR does / why we need it**:
Drop support for Shoots with K8s < 1.20 

**Which issue(s) this PR fixes**:
Fixes #6911

**Special notes for your reviewer**:

**Release note**:

```breaking operator
⚠️ Gardener does no longer support shoot clusters with Kubernetes versions < 1.20. Make sure to upgrade all existing clusters before upgrading to this Gardener version.
```
```breaking operator
⚠️ The minimum Kubernetes version for garden clusters has been raised from `v1.17` to `v1.20`. Make sure that your garden cluster meets this requirement before upgrading to this Gardener version.
```

2022-11-14 15:45 UTC, dimityrmirchev requested changes
There are multiple occurrences of version 1.19 checks in this repository. Should we also drop them with this PR?

Here is an [example](https://github.com/gardener/gardener/blob/6c60ccc4f4c27ae767af1742e9581291473d5039/pkg/operation/botanist/component/kubecontrollermanager/kube_controller_manager.go#L584)

2022-11-15 04:13 UTC, shafeeqes commented
/assign

2022-11-15 04:54 UTC, shafeeqes commented
In line with https://github.com/gardener/gardener/pull/6987#pullrequestreview-1179367074, Can you please check the usages of these constraints https://github.com/gardener/gardener/blob/d98cf02c88c84316544894e6ce2a3992f3768730/pkg/utils/version/version.go#L26-L39 and remove them as we will only support Shoots >= 1.20 now.

2022-11-18 08:38 UTC, shafeeqes commented
I found some more places, which needs cleanup:
1. https://github.com/gardener/gardener/blob/0745524969ed3da045820a360213f648e84440c7/docs/usage/shoot_scheduling_profiles.md#L29
2. https://github.com/gardener/gardener/blob/14031504179bfaae0ad5cb3cba1e5b5d132a91f5/pkg/operation/botanist/component/shootsystem/shootsystem_test.go#L233-L244
3. https://github.com/gardener/gardener/blob/14031504179bfaae0ad5cb3cba1e5b5d132a91f5/pkg/apis/core/validation/shoot_test.go#L1984-L1995
4. https://github.com/gardener/gardener/blob/788e94264a9c5d59711d1f7d863cd68fba53dfde/docs/usage/reversed-vpn-tunnel.md#L52

2022-11-18 09:05 UTC, shafeeqes commented on hack/api-reference/core-config.json
> +            "docsURLTemplate": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#{{lower .TypeIdentifier}}-{{arrIndex .PackageSegments -1}}-{{arrIndex .PackageSegments -2}}"
```suggestion
            "docsURLTemplate": "https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#{{lower .TypeIdentifier}}-{{arrIndex .PackageSegments -1}}-{{arrIndex .PackageSegments -2}}"
```
for all other api groups as well.

2022-11-18 10:01 UTC, dimitar-kostadinov commented
/retest

2022-11-21 03:16 UTC, shafeeqes commented on docs/usage/reversed-vpn-tunnel.md
> -
We can still keep this part, I think.

2022-11-22 06:46 UTC, ialidzhikov commented
/assign

2022-11-22 11:05 UTC, ialidzhikov commented on README.md
> -| Provider/K8s | v1.25 | v1.24 | v1.23 | v1.22 | v1.21 | v1.20 | v1.19 | v1.18 | v1.17 |
There is the following code snippet:https://github.com/gardener/gardener/blob/9fae12b4cc29928cefd5f0cade44290e33378844/pkg/operation/botanist/component/resourcemanager/resource_manager.go#L656-L659

According to the comment my understanding is that we can clean it up. It is anyways for GRM and since longtime we don't support Seeds with K8s < 1.20. @dimityrmirchev can you also confirm that it is now safe to remove the fsGroup setting?

2022-11-22 11:05 UTC, ialidzhikov commented on README.md
> -| Provider/K8s | v1.25 | v1.24 | v1.23 | v1.22 | v1.21 | v1.20 | v1.19 | v1.18 | v1.17 |
You could update the version in https://github.com/gardener/gardener/blob/30ce9c0f4d3fcbbfb496236b868eccc09a97defa/docs/development/local_setup.md#L468 to a more recent one.

For example 
```
kubectl get seed
NAME       STATUS    PROVIDER    REGION      AGE    VERSION       K8S VERSION
seed-aws   Ready     aws         eu-west-1   4m     v1.61.0-dev   v1.24.8
```

2022-11-22 11:05 UTC, ialidzhikov commented on README.md
> -| Provider/K8s | v1.25 | v1.24 | v1.23 | v1.22 | v1.21 | v1.20 | v1.19 | v1.18 | v1.17 |
As we discussed with you on the phone https://github.com/gardener/gardener/blob/4823157cccf0782e02a9ffbeb4a79fde2a85849c/pkg/operation/botanist/component/kubeapiserver/secrets.go#L188-L199 has to be adapted in the way we agreed and https://github.com/gardener/gardener/blob/e4e5c9f947c2e941fb9a6b93adf387f573e405af/pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go#L134-L135 has to be cleaned up from the kubeapiserver component.

2022-11-22 12:19 UTC, ialidzhikov commented on docs/usage/reversed-vpn-tunnel.md
> -
Yes, it is now preserved with the only change that the feature gate is Beta.

2022-11-22 12:20 UTC, ialidzhikov commented on README.md
> -| Provider/K8s | v1.25 | v1.24 | v1.23 | v1.22 | v1.21 | v1.20 | v1.19 | v1.18 | v1.17 |
It should be now addressed with the latest force push. Thanks!

2022-11-22 14:06 UTC, ialidzhikov reviewed
In general looks good to me. Minor suggestions inline.

2022-11-22 14:06 UTC, ialidzhikov commented on example/30-cloudprofile.yaml
> -    - version: 18.04.201906170
Nit: Can we revert this change? (I mean the version to be `18.04.201906170` as before)

2022-11-22 14:06 UTC, ialidzhikov commented on pkg/apis/core/v1alpha1/defaults_test.go
> +			obj.Spec.Kubernetes.Version = "1.22"
```suggestion
			obj.Spec.Kubernetes.Version = "1.21"
```

We could leave the K8s version < 1.22 to make sure that the worker K8s versions gets respected and that's why the worker CRI is updated to containerd. And let's keep the worker K8s version to be 1.22 as before.

2022-11-22 14:06 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/defaults_test.go
> +			obj.Spec.Kubernetes.Version = "1.22"
Same as the comment in `pkg/apis/core/v1alpha1/defaults_test.go`.

2022-11-22 14:06 UTC, ialidzhikov commented on pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
> -					Expect(secretList.Items[0].Data).To(HaveKey("token"))
@rfranzke , with `ControlPlaneSecretConfig` in the generated Secret data for the user-kubeconfig Secrets there was also `token` field containing the token. With `KubeconfigSecretConfig` in the generated Secret data there is only the `kubeconfig` field. I hope this is also fine? WDYT?

2022-11-22 14:18 UTC, rfranzke commented on pkg/operation/botanist/component/kubeapiserver/kube_apiserver_test.go
> -					Expect(secretList.Items[0].Data).To(HaveKey("token"))
I hope so. This was always somewhat "duplicative" and just made extracting the token easier, but it's still possible with the `kubeconfig` field only.

2022-11-24 03:44 UTC, shafeeqes reviewed
/lgtm

2022-11-24 06:28 UTC, dimityrmirchev commented on README.md
> -| Provider/K8s | v1.25 | v1.24 | v1.23 | v1.22 | v1.21 | v1.20 | v1.19 | v1.18 | v1.17 |
Yes, this is the same occurrence of https://github.com/gardener/gardener/blob/555bb9874d0507d2bd382e8a2657569f6a80e530/pkg/resourcemanager/webhook/projectedtokenmount/handler.go#L102 which I see is also removed with this PR

2022-11-28 06:54 UTC, ialidzhikov commented on README.md
> -| Provider/K8s | v1.25 | v1.24 | v1.23 | v1.22 | v1.21 | v1.20 | v1.19 | v1.18 | v1.17 |
Thank you @dimityrmirchev for confirming!

2022-11-28 07:20 UTC, ialidzhikov reviewed
Final suggestions, otherwise lgtm

2022-11-28 07:20 UTC, ialidzhikov commented on pkg/operation/botanist/component/kubeapiserver/secrets.go
> -			Name:           SecretBasicAuthName,
We can now clean up the `SecretBasicAuthName` cons, right?

2022-11-28 07:20 UTC, ialidzhikov commented on pkg/operation/botanist/component/kubeapiserver/secrets.go
> -		basicAuth, err = secretutils.LoadBasicAuthFromCSV(SecretBasicAuthName, secretBasicAuth.Data[secretutils.DataKeyCSV])
The `LoadBasicAuthFromCSV` func seems no longer used. We can clean it up.

2022-11-28 11:59 UTC, ialidzhikov reviewed
/lgtm
/approve

2022-11-28 12:00 UTC, ialidzhikov commented
/test pull-gardener-integration
/test pull-gardener-e2e-kind-ha-single-zone

2022-11-28 12:04 UTC, merged