Add documentation for supported architectures in shoot
gardener/gardener pull request #7003
Opened 2022-11-11 14:32 UTC by acumino

**How to categorize this PR?**

/area documentation
/kind task

**What this PR does / why we need it**:
This PR adds documentation for supported architecture in shoot worker pool.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/backlog/issues/19

/cc @rfranzke 

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-11-11 14:34 UTC, shafeeqes commented
Please add this to `docs/README.md` as well.

2022-11-14 05:27 UTC, shafeeqes commented on docs/usage/shoot_supported_architectures.md
> +Users can create shoot with worker groups having virtual machines of different architectures. CPU architecture of each worker pool can be specified in shoot yaml as follows:-
```suggestion
Users can create a Shoot with worker groups having virtual machines of different architectures. CPU architecture of each worker pool can be specified in the Shoot yaml as follows:-
```
Not very sure about the capitalization though.

2022-11-14 11:59 UTC, rfranzke requested changes

2022-11-14 11:59 UTC, rfranzke commented on docs/usage/shoot_supported_architectures.md
> +# Shoot Supported Architectures
```suggestion
# Supported CPU Architectures for Shoot Worker Nodes
```

2022-11-14 11:59 UTC, rfranzke commented on docs/usage/shoot_supported_architectures.md
> +If there is no value specified for architecture it defaults to `amd64`.
You could mention that the architectures must be present in the `CloudProfile`.

2022-11-15 05:43 UTC, shafeeqes commented on docs/usage/shoot_supported_architectures.md
> +If no value is specified for the architecture field it defaults to `amd64`. For a valid shoot object, a machine should be present in the respective CloudProfile with the same CPU architecture as spec
```suggestion
If no value is specified for the architecture field, it defaults to `amd64`. For a valid shoot object, a machine should be present in the respective CloudProfile with the same CPU architecture as specified in the `Shoot` yaml.
```

2022-11-15 10:12 UTC, shafeeqes commented
/lgtm

2022-11-15 10:17 UTC, rfranzke requested changes

2022-11-15 10:17 UTC, rfranzke commented on docs/usage/shoot_supported_architectures.md
> +If no value is specified for the architecture field, it defaults to `amd64`. For a valid shoot object, a machine should be present in the respective CloudProfile with the same CPU architecture as spe
```suggestion
If no value is specified for the architecture field, it defaults to `amd64`. For a valid shoot object, a machine type should be present in the respective `CloudProfile` with the same CPU architecture as specified in the `Shoot` yaml.
```

Don't we need a machine image with the right architecture as well?
Can you maybe also show some short YAML example of such `CloudProfile`?

2022-11-15 10:17 UTC, rfranzke commented on docs/usage/shoot_supported_architectures.md
> +Currently, Gardener supports two most widely used CPU architectures:-
```suggestion
Currently, Gardener supports two most widely used CPU architectures:
```

2022-11-15 14:26 UTC, rfranzke reviewed
/lgtm
/approve

2022-11-15 18:24 UTC, acumino commented
/milestone v1.60

2022-11-15 19:04 UTC, merged