Fix calculation of overlapping CIDR ranges.
gardener/gardener pull request #7112
Opened 2022-11-30 09:37 UTC by axel7born

**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
Due to the wrong overlap test, NetworkPolicy `allow-private-networks` doesn't contain a `except` clauses for networks that are includes in the subnet but have the same start address. 

**Which issue(s) this PR fixes**:
Fixes #7110

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fixed a bug where service, pod or node CIDRs that are private network (RFC1918) or carrier-grade NAT (RFC6598) IPv4 blocks would not be added as except clause to `allow-to-private-networks` networkpolicy.
```

2022-11-30 09:37 UTC, axel7born commented
/test all

2022-11-30 11:46 UTC, axel7born commented
/test pull-gardener-integration

2022-12-01 15:45 UTC, axel7born commented
/cc @DockToFuture @ScheererJ

2022-12-01 15:55 UTC, ScheererJ commented on pkg/operation/botanist/component/networkpolicies/peers.go
> +		if parentBlock.Contains(ip) && (parentBlockMaskLength < ipNetMaskLength) {
```suggestion
		if parentBlock.Contains(ip) && parentBlockMaskLength < ipNetMaskLength {
```

2022-12-01 15:55 UTC, ScheererJ commented on pkg/operation/botanist/component/networkpolicies/peers.go
> +		if parentBlock.Contains(ip) && (parentBlockMaskLength < ipNetMaskLength) {
With this change we will exclude all blocks if they are in the parent block AND smaller.
What about equal size blocks? Should they be excluded?
If the parent block is indeed smaller what should happen then?

2022-12-01 16:17 UTC, axel7born commented on pkg/operation/botanist/component/networkpolicies/peers.go
> +		if parentBlock.Contains(ip) && (parentBlockMaskLength < ipNetMaskLength) {
Equal size blocks can't be excluded. This would result in an invalid NetworkPolicy.
If the parent block is smaller, the creation would also fail.
The current logic is, that we don't add the `except` clause in that case.
Actually, it would be correct not to allow the parent block in such a case. 
But I fear, that could break existing clusters with such configuration.

2022-12-01 16:23 UTC, ScheererJ requested changes
Could you please remove the unnecessary parentheses? Apart from that, the change looks fine.

2022-12-01 16:27 UTC, ScheererJ approved these changes
/lgtm

2022-12-02 08:17 UTC, rfranzke commented
/approve

2022-12-02 09:00 UTC, merged