Refactor handling of shoot controller special cases
gardener/gardener pull request #7189
Opened 2022-12-12 15:00 UTC by timebertt

**How to categorize this PR?**

/area dev-productivity quality
/kind technical-debt

**What this PR does / why we need it**:

Previously, special cases for confined and jittered shoot reconciliations (see [docs](https://github.com/gardener/gardener/blob/master/docs/concepts/gardenlet.md#shoot-controller)) were handled by a few lines of boolean variable combinations, and the reconciliation due tracker.
We faced some bugs and regressions in this logic because it was not covered by tests at all, was not readable, and was not documented at all.
However, this logic is quite important for the stability of large-scale gardener installations.

This PR refactors this logic to make it more readable and well-documented and adds full unit test coverage.
Additionally, we can now use the helpers in both the shoot main reconciler and its event handler.
This allows us to use `AddAfter` in the event handler, instead of performing a reconciliation that will exit early with `RequeueAfter` (and allows us to get rid of the reconciliation due tracker).

Co-Authored-By @rfranzke 

**Which issue(s) this PR fixes**:
Follow-up on https://github.com/gardener/gardener/pull/7082
Part of https://github.com/gardener/gardener/issues/4251

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-12-12 16:40 UTC, rfranzke commented
/assign

2022-12-12 19:43 UTC, timuthy commented
/assign

2022-12-12 20:21 UTC, timebertt commented
This PR should go into the v1.62.0 release. Otherwise, the `reconcileInMaintenanceOnly=false` case is partially broken.
cc @oliver-goetz 
/milestone v1.62

2022-12-13 09:11 UTC, rfranzke commented
/assign @ary1992

2022-12-13 10:17 UTC, rfranzke reviewed
Thanks, we did a joint review with @ary1992

2022-12-13 10:17 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot/helper/infos.go
> +	// we allow immediate reconciliations.
```suggestion
	// we requeue according to the sync period configured in gardenlet configuration (which might have been overwritten on the shoot via annotation).
```

2022-12-13 10:26 UTC, rfranzke reviewed
Thank you @timebertt for the joint work on this, enjoyed it.

/lgtm
/approve

2022-12-13 10:26 UTC, timebertt commented
Thanks for the fast review, PTAL :)

2022-12-13 11:16 UTC, timebertt commented
/retest-required

2022-12-13 12:32 UTC, timuthy commented
/unassign
for now since there are enough reviewers and I won't make it in time.

2022-12-13 13:27 UTC, acumino requested changes

2022-12-13 13:27 UTC, acumino commented on pkg/controllermanager/controller/shoot/maintenance/add.go
> +	"k8s.io/utils/clock"
```suggestion
```

2022-12-13 14:26 UTC, timebertt commented
Sorry folks, something went wrong during the rebase. It should be fixed now.

2022-12-13 14:27 UTC, acumino reviewed
/lgtm

2022-12-13 14:56 UTC, rfranzke reviewed
/lgtm

2022-12-13 15:13 UTC, merged

2022-12-14 15:57 UTC, timuthy commented
Kudos @timebertt and @rfranzke for touching this spaceship 👨‍🚀 Nice PR!