Fix bug where `kubelet-monitor` kills processes other than `kubelet`
gardener/gardener pull request #7278
Opened 2023-01-03 18:43 UTC by eric-garber

**How to categorize this PR?**

/area robustness
/kind bug

**What this PR does / why we need it**:

Fixes a bug where `kubelet-monitor` incorrectly kills processes other than kubelet when trying to restart kubelet.
 
The existing `kubelet-monitor` executes `pkill -f "kubelet"` to restart kubelet.
The `-f` flag causes it to match any process which has "kubelet" anywhere in its arguments.
That causes it to incorrectly kill processes which pass "/var/lib/kubelet/..." as arguments  (eg. CSI drivers).
Fix this by removing the `-f` flag from `pkill` so that it only matches the process name.

**Which issue(s) this PR fixes**:
Fixes #7252

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-01-03 18:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener?pullRequest=7278) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener?pullRequest=7278) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener?pullRequest=7278) it.</sub>

2023-01-04 05:10 UTC, acumino requested changes

2023-01-04 05:10 UTC, acumino commented on pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/templates/scripts/health-monitor.tpl.sh
> +    pkill "kubelet"
By default `pkill` will kill any process which has `kubelet` as a substring in its name. If I understand the issue correctly we want to kill process with exact match to name `kubelet` for that you can use following suggestion.
```suggestion
    pkill -x "kubelet"
```
From `pkill` manual
```
-x                Require an exact match of the process name, or argument list if -f is given.  The default is to match any substring.
```

2023-01-09 06:06 UTC, acumino commented
/ping @eric-garber

2023-01-10 13:28 UTC, acumino commented
/cc @ialidzhikov @rfranzke

2023-01-10 18:22 UTC, eric-garber commented on pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/templates/scripts/health-monitor.tpl.sh
> +    pkill "kubelet"
Thanks for catching this.
I'd incorrectly assumed that `pkill -x` would need to exactly match the full path to the executable (ie. `argv[0]` of the command line that it was executed with), which is why I'd avoided it.
I've double-checked on one of our gardener nodes and using ` pkill -x "kubelet"` here is correct.
It matches against `/proc/$PID/comm` rather than `/proc/$PID/cmdline`:
```
$ k exec -it privileged-pod -- nsenter --all -t 1
# pgrep -x kubelet
20177
# cat /proc/20177/comm
kubelet
# cat /proc/20177/cmdline
/opt/bin/kubelet --bootstrap-kubeconfig=/var/lib/kubelet/kubeconfig-bootstrap ...
```

2023-01-10 18:23 UTC, eric-garber reviewed
Thanks for catching the issue and fixing the tests. Super appreciated!

2023-01-11 06:11 UTC, rfranzke reviewed
Nice, thanks colleagues!

/lgtm
/approve

2023-01-11 06:11 UTC, merged

2023-01-17 08:55 UTC, shafeeqes commented
/cherry-pick release-v1.62

2023-02-01 08:12 UTC, rfranzke commented
cc @AleksandarSavchev 
This is the PR that was mentioned in today's review meeting