Replace Grafana with Plutono, Loki with Vali
gardener/gardener pull request #7318
Opened 2023-01-13 12:31 UTC by istvanballok

**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:

Replace Grafana with [Plutono](https://github.com/credativ/plutono), Loki with [Vali](https://github.com/credativ/vali).

> Plutono is a fork of [Grafana](https://github.com/grafana/grafana) 7.5 under the Apache 2.0 License. It is currently limited to maintenance and security updates.
> Vali is a fork of [Loki](https://github.com/grafana/loki/) 2.2.1 under the Apache 2.0 License. It is currently limited to maintenance and security updates.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

/cc @rickardsjp @nickytd @Kristian-ZH @vlvasilev 

**Next steps**:

- [x] Write a script to execute string replacements in file and folder names and in file contents: Grafana->Plutono, Loki->Vali. A script is needed to recreate these commits when rebasing this PR.
- [x] Adjust the container image references
- [x] Ensure that the monitoring functionality works as expected for new shoots
- [ ] Ensure that the migration of the monitoring artifacts works as expected for existing seeds and shoots (e.g. the old grafana artifacts should be removed)
- [ ] Adjust the vendored fluentbit-operator dependency
- [ ] Adjust the [gardener/logging](https://github.com/gardener/logging/blob/cd5effc2259b184d23a1f1c2aca381e04bf1b9b4/.ci/pipeline_definitions#L15-L24) artifacts (fluent-bit-to-loki, loki-curator) 
- [ ] Ensure that the logging functionality works as expected for new shoots
- [ ] Ensure that the migration of the logging artifacts works as expected for existing seeds and shoots (e.g. the old loki artifacts should be removed)
- [ ] Prepare PRs for the extensions

**Release note**:

```other operator
TODO. Grafana and Loki are replaced with the fork of their last Apache 2.0 licensed releases: Plutono and Vali.
TODO. share what happens to logs in Loki
```

2023-03-01 10:57 UTC, istvanballok commented
Closing in favor of a future PR because we (@rickardsjp) could not find a solution that we can take full responsibility for, for the specific subtopic of the loki to vali migration. The current approach would mean that both loki and vali would be kept around for some time (2 weeks), and at least for a few minutes the resource requests of both loki and vali could cause a significant increase in the footprint of the shoot control planes in the seed, which could lead to noticeable cost increases or capacity shortages with machine types when this update is rolled out in large scale Gardener installations. The alternatives are deleting the loki installation at the beginning, but that means the logs are lost and e.g. root cause analysis of serious outage might be impacted. We did not want to take this decision. Another alternative is to keep the loki pvc with the vali sts indefinitely does not feel clean either. Unfortunately the obvious approach of "renaming" the loki pvc is not supported by K8s and migrating the loki files is not really feasible either, because loki has up to 500k tiny files and copying those very time consuming. Maybe in a future PR we might follow the log deletion approach. Note that the rename commits can be reused for any future PR.

2023-03-01 11:46 UTC, rfranzke commented
> Another alternative is to keep the loki pvc with the vali sts indefinitely does not feel clean either.

I can't follow, why don't we simply keep the loki PVCs and just rename the rest? It's not a "clean renaming", yes, but why does it matter/who cares?

2023-03-01 12:16 UTC, istvanballok commented
We had an observability area internal discussion and the conclusion was that a new PR will be opened that will probably implement one of the alternatives from above.

2023-03-01 12:27 UTC, nickytd commented
A better/cleaner strategy is to create Vali PV(C), keep the current Lokis for the standard retention period  and clean up/free the resources after that period. That would mean to increase the memory consumptions of the shoots for that period but you gain: 1. clean and consistent deployment model and 2. Ability to consult historic logs available in lokis during that period, if there is a need to do so. Kubernetes shall allow the seeds to "breathe" in that period in terms of the resource consumption.

2023-03-08 12:27 UTC, istvanballok commented
> Unfortunately the obvious approach of "renaming" the loki pvc is not supported by K8s

Unfortunately we made a mistake during our investigations and came to the incorrect conclusion that it is not possible to rename persistent volume claims. This led to exploring more exotic approaches and eventually to the feeling of being stuck on this effort because all the alternatives had smaller or bigger disadvantages and (financial) risks that we did not want to take.

We could / should have done it earlier, but now that @rickardsjp and I double checked the question of "renaming" existing pvc-s it turns out that this is possible by changing the `persistentVolumeReclaimPolicy` of the persistent volume to `Retain` temporarily, deleting the old pvc, removing the pvc reference from the pv and attaching a new pvc with the new name to the existing pv: 

> PersistentVolumes can have various reclaim policies, including "Retain", "Recycle", and "Delete". For dynamically provisioned PersistentVolumes, the default reclaim policy is "Delete". This means that a dynamically provisioned volume is automatically deleted when a user deletes the corresponding PersistentVolumeClaim. This automatic behavior might be inappropriate if the volume contains precious data. In that case, it is more appropriate to use the "Retain" policy. With the "Retain" policy, if a user deletes a PersistentVolumeClaim, the corresponding PersistentVolume will not be deleted. Instead, it is moved to the Released phase, where all of its data can be manually recovered. ([link](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume))

<details>

<summary>We scripted this approach, including the "rename" of the loki statefulset to vali, and tested it on all the infrastructures (including the local setup). It worked as expected.</summary>

```bash
#!/bin/bash -exv

# Mark the volume of loki
kubectl exec loki-0 -c loki -- sh -c "echo loki > /data/hello"

kubectl get sts loki -o yaml        | kubectl neat > sts.yml
kubectl get pvc loki-loki-0 -o yaml | kubectl neat > pvc.yml

kubectl delete sts loki

pv_id=$(kubectl get pvc loki-loki-0 -o jsonpath='{.spec.volumeName}')
kubectl patch pv "$pv_id" -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'

kubectl delete pvc loki-loki-0
kubectl patch pv "$pv_id" -p '{"spec":{"claimRef": null }}'

sed 's/loki-loki-0/vali-vali-0/g' pvc.yml | kubectl apply -f -
sed 's/name: loki$/name: vali/g'  sts.yml | kubectl apply -f -

kubectl patch pv "$pv_id" -p '{"spec":{"persistentVolumeReclaimPolicy":"Delete"}}'

# Wait for the vali StatefulSet to be ready
kubectl rollout status sts/vali

# Verify that the volume of vali is the former loki volume
kubectl exec vali-0 -c vali -- cat /data/hello
```

</details>

The only downside of this approach is that for the dynamically provisioned persistent volumes there is a naming convention that the `metadata.uid` field of the pvc is used as a suffix in the name of the dynamically provisioned pv. After "renaming" the pvc, the name of the pv will still contain the previous pvc's uid, but as it is a non human readable uid, it is probably OK. Note that the references between the pvc and the pv (the pvc's `spec.volumeName` and the pv's `spec.claimRef` fields) are correct.

So we'll pick up this PR again and try to implement the following steps in Gardener:
- as a first step of deploying the monitoring stack, check if there is a loki in the control plane. If there is one:
  - delete the grafana deployment and the loki statefulset, the related other artifacts (configmaps, ingresses, ...) but keep the loki pvc
  - execute the steps above to "rename" the loki pvc to vali
- deploy the plutono and vali artifacts. The vali statefulset will create a vali-0 pod that will use the former loki-0 pvc that is now renamed to vali-0. Loki and Vali are compatible on the disk layout so with this approach the older logs will be accessible and there is no increased resource usage due to keeping the grafana + loki artifacts around for a few weeks.

/reopen

2023-03-31 08:40 UTC, nickytd commented
We need to keep the `networking.resources.gardener.cloud/to-all-shoots-loki-tcp-metrics: allowed` label in the pod templates of the fluent-bit daemon set to allow the migrated fluent-bits to target both reconciled shoots with vali logging stack and not-reconciled shoots with loki logging stack.

Hence the labels in the fluent-bit template shall include both network policy related labels
```yaml
...
        networking.resources.gardener.cloud/to-all-shoots-vali-tcp-metrics: allowed
        # we need this annotation for during the migration phase to be able to target both loki and vali instances
        networking.resources.gardener.cloud/to-all-shoots-loki-tcp-metrics: allowed
```

2023-05-08 12:24 UTC, istvanballok commented
/retest-required

2023-05-08 14:16 UTC, istvanballok commented
/retest-required

2023-05-09 13:18 UTC, istvanballok commented
/test pull-gardener-e2e-kind

2023-05-10 07:06 UTC, istvanballok commented
/hold

We identified an issue with the change introduced in the commit "Allow the fluentbits to talk to loki during the transition phase": in the current state, the fluentbit operator (https://github.com/gardener/gardener/pull/7568) does not support adding labels. Reviews are still welcome.

2023-05-11 10:10 UTC, istvanballok commented
/unhold

The issue we noticed in https://github.com/gardener/gardener/pull/7318#issuecomment-1541461532 is resolved by the commit "Add the hash of the labels as a suffix to the fluentbit custom resource".

There are no known issues any more. 🎉 

lgtm FMPOV 😊

/cc @rickardsjp @nickytd @Kristian-ZH @vlvasilev for review and lgtm 🤞 
/cc @rfranzke @ialidzhikov for further insights and approval 🤞

2023-05-11 11:38 UTC, nickytd commented
/lgtm

2023-05-11 12:29 UTC, rickardsjp reviewed
lgtm (no slash, contributed to this)

2023-05-11 12:38 UTC, vlvasilev approved these changes
/lgtm

2023-05-11 13:57 UTC, rickardsjp commented
/lgtm

re-adding, just a rebase due to a conflict with https://github.com/gardener/gardener/pull/7923

2023-05-11 14:32 UTC, istvanballok commented
/test pull-gardener-e2e-kind-ha-single-zone-upgrade

2023-05-12 06:34 UTC, Kristian-ZH approved these changes
/lgtm

2023-05-12 06:34 UTC, Kristian-ZH approved these changes
/lgtm

2023-05-12 08:03 UTC, istvanballok commented
> Once this PR has been reviewed and has the lgtm label, please assign timuthy for approval.

/assign timuthy

2023-05-15 05:38 UTC, timuthy commented
/approve

2023-05-15 08:24 UTC, rfranzke commented
@shafeeqes Milestone?

2023-05-15 08:49 UTC, shafeeqes commented
/milestone v1.71

2023-05-15 09:03 UTC, shafeeqes commented
/test pull-gardener-integration

2023-05-15 09:20 UTC, rfranzke requested changes
/hold

2023-05-15 09:20 UTC, rfranzke commented on charts/gardener/gardenlet/templates/clusterrole-gardenlet.yaml
> +- apiGroups: # TODO (istvanballok,rickardsjp): remove in a future release. Patching persistent volumes is needed for the Loki -> Vali migration.
Please specify in which release version this can be removed.

2023-05-15 09:20 UTC, rfranzke commented on docs/proposals/13-automated-seed-management.md
> +The second approach decouples the seed autoscaler controller from the actual metrics evaluation, and therefore allows plugging in new metrics more easily. It also has the advantage that the exported
We don't maintain GEPs, so revert changes in `docs/proposals`

2023-05-15 09:20 UTC, rfranzke commented on pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
> +	//TODO(rickardsjp, istvanballok): Remove in the next release once the Loki to Vali migration is complete.
specify version

2023-05-15 09:20 UTC, rfranzke commented on pkg/operation/botanist/monitoring.go
> +	//TODO(rickardsjp, istvanballok): Remove in the next release once the Grafana to Plutono migration is complete.
version

2023-05-15 09:20 UTC, rfranzke commented on pkg/operation/care/checker.go
> +// TODO(rickardsjp, istvanballok): remove in a future release
version

2023-05-15 09:20 UTC, rfranzke commented on pkg/operation/care/checker.go
> +	// TODO(rickardsjp, istvanballok): remove in a future release
version

2023-05-15 09:20 UTC, rfranzke commented on pkg/operation/care/checker.go
> +		// TODO(rickardsjp, istvanballok): remove in a future release
version

2023-05-15 09:20 UTC, rfranzke commented on pkg/operation/care/health_check_test.go
> +		// TODO(rickardsjp, istvanballok): Remove in a future release
version

2023-05-15 11:25 UTC, rfranzke requested changes
What if a `Shoot` is stuck in reconciliation (maybe because of invalid infrastructure credentials) for a long time? Then the migrations will not be performed, and eventually we drop the migration code, and then what?
Perhaps it makes sense to perform the migrations for shoots right away on gardenlet startup to make sure that we can delete the migration coding in the next release?

2023-05-16 08:23 UTC, istvanballok commented
> What if a `Shoot` is stuck in reconciliation (maybe because of invalid infrastructure credentials) for a long time? Then the migrations will not be performed, and eventually we drop the migration code, and then what?
Perhaps it makes sense to perform the migrations for shoots right away on gardenlet startup to make sure that we can delete the migration coding in the next release?

If a shoot is not reconciled and we drop the migration code, we would leak resources when it is eventually reconciled because the loki sts and the grafana deployment would not be deleted. Furthermore, the vali disk would be a brand new one, so the logs of loki would not be migrated. Maybe we could mitigate this by checking for shoots that could not reconcile "manually" but this is not really a good solution because we might not have access to all the Gardener landscapes.

On the other hand, the migration runs in the seed so we don't need infrastructure credentials for the shoot, but we haven't tested this case actually: when the reconciliation fails for some reason. Maybe the reconciliation would be stopped before the migration task is executed and then we have a problem.

We thought that the migration needs to run in the maintenance time window of the shoots. Note that the operating system config of the shoot nodes is updated, so that the shoot's kube-system namespace logs are sent to vali and not to loki. That should be done probably only in the maintenance time window.

@rfranzke: Would it be an option to add a TODO in the release notes for landscape operators to check that all the shoots have successfully reconciled to v1.71?

2023-05-16 10:43 UTC, rfranzke commented
>  Would it be an option to add a TODO in the release notes for landscape operators to check that all the shoots have successfully reconciled to v1.71?

How do you envision operators would ensure this? In most cases, those landscape operators are not in control of all shoots, i.e. they cannot take care of potential third-party dependencies (e.g., invalid infrastructure credentials).

2023-05-16 11:21 UTC, vpnachev commented
While the concerns for missed migration for failed shoots are valid, I doubt this the first and the only migration scenario in Gardener that is affected by inability to completely reconcile the shoot, hence I would consider the concerns as out of scope of this change. A more general solution eventually should be implemented, e.g. reconciliation flow to be split and the tasks in one of them to be ensured is always executable no matter the shoot state - then such migration tasks must be part of the guaranteed flow.   

There is also no prevention mechanism to skip gardener versions, it just well documented policy - right?  So, no matter what is done in code, a Gardener operator can consciously skip the versions with the migration code and loki resources will leak again.

2023-05-16 11:26 UTC, rfranzke commented
> While the concerns for missed migration for failed shoots are valid, I doubt this the first and the only migration scenario in Gardener that is affected by inability to completely reconcile the shoot, hence I would consider the concerns as out of scope of this change.

In the past we "worked around" this by simply waiting for "long enough", but in more recent migrations (e.g., `NetworkPolicy`s) we executed the relevant code right after start-up of gardenlet to make sure each `Shoot` gets the changes independent of the reconciliation flow.

> There is also no prevention mechanism to skip gardener versions, it just well documented policy - right? So, no matter what is done in code, a Gardener operator can consciously skip the versions with the migration code and loki resources will leak again.

Right, we cannot prevent this. If people don't adhere to the upgrade policy guide, they must help themselves. However, we should at least cover the recommended scenario (i.e., operators upgrading Gardener versions one by one).

2023-05-16 11:31 UTC, vpnachev commented
> we executed the relevant code right after start-up of gardenlet to make sure each `Shoot` gets the changes independent of the reconciliation flow.

This might work in some cases, but in this case it will cause all kubelets of all shoots in a Gardener landscape to be restarted nearly at the same time and for sure outside of the maintenance window, therefore it is not applicable.

2023-05-16 11:36 UTC, rfranzke commented
Yes, maybe. Another approach could be to run the migration earlier in the reconciliation flows. Perhaps there are even more options. In the end, I just wanted to know whether the colleagues thought about this scenario. If you want to proceed without covering it, let's go ahead. We all know that there will be shoots which will be affected, and we also know that no landscape operator can make sure that all shoots were reconciled successfully before the next version is rolled out. Hence, there will be leaked resources and all other consequences as explained by @istvanballok above.

2023-05-16 11:52 UTC, nickytd commented
> Yes, maybe. Another approach could be to run the migration earlier in the reconciliation flows. Perhaps there are even more options. In the end, I just wanted to know whether the colleagues thought about this scenario. If you want to proceed without covering it, let's go ahead. We all know that there will be shoots which will be affected, and we also know that no landscape operator can make sure that all shoots were reconciled successfully before the next version is rolled out. Hence, there will be leaked resources and all other consequences as explained by @istvanballok above.

Which basically means that we need an ability to plug in `maintenance jobs` in the gardenlet workflow to facilitate such operations. At the bare minimum a job reporting resources without an owner or with non-existing owner might be of value.

2023-05-16 12:49 UTC, istvanballok commented
> RF: In the end, I just wanted to know whether the colleagues thought about this scenario.

I think this discussion is valid because we (cc @rickardsjp) did not think about or test these aspects.

>> Would it be an option to add a TODO in the release notes for landscape operators to check that all the shoots have successfully reconciled to v1.71?
>
> RF: How do you envision operators would ensure this?
> RF: we also know that no landscape operator can make sure that all shoots were reconciled successfully before the next version is rolled out

Just for my understanding: would it be feasible for landscape operators to filter for shoots that have not reconciled successfully and reach out to the shoot owners if the root cause is e.g. related to aspects that they do not control, like the invalid shoot infrastructure credentials?

Such snippets could help to achieve that:

```
k get shoots -A -o json > shoots.json
< shoots.json jq '.items[].status| select(.lastOperation.type == "Reconcile" and .lastOperation.state != "Succeeded") | {type: .lastOperation.state, version: .gardener.version}' -r -c | sort | uniq -c
     1 {"type":"Error","version":"v1.70.2"}
     2 {"type":"Failed","version":"v1.70.2"}
     3 {"type":"Processing","version":"v1.70.2"}
```

and to find the affected shoots:

```
< shoots.json jq '.items[]| select(.status.lastOperation.type == "Reconcile" and .status.lastOperation.state == "Error") | .metadata | {namespace, name} | "https://dashboard..../namespace/\(.namespace)/shoots/\(.name)"' -r
https://dashboard..../namespace/garden-foo/shoots/bar
```

Then open the Gardener Dashboard link and reach out to the shoot owners.

> RF: In the past we "worked around" this by simply waiting for "long enough"

We adjusted the TODO comments so that the migration logic is reverted only in the n+2 release, i.e. v1.73.

> VN: This might work in some cases, but in this case it will cause all kubelets of all shoots in a Gardener landscape to be restarted nearly at the same time and for sure outside of the maintenance window, therefore it is not applicable.

We agree.

> RF: Yes, maybe. Another approach could be to run the migration earlier in the reconciliation flows. Perhaps there are even more options.

Just for my understanding, this is the relevant snippet that defines the order of the tasks in the shoot reconciliation flow.

https://github.com/gardener/gardener/blob/master/pkg/gardenlet/controller/shoot/shoot/reconciler_reconcile.go#L334-L338

So we could / should check which tasks come before this task in the topological sort order, and if this task could be moved before them, and what kind of errors can we have due to the tasks that come earlier in the flow.

If the shoot infrastructure credentials are invalid, the shoot reconciliation flow will fail. That would mean that the "DeploySeedLogging" step should be executed prior to it. We are not quite sure if doing it that early could have negative side effects e.g. during the initial creation phase.

So maybe a pragmatic approach would be to wait a bit longer (e.g. v1.73) with the cleanup and let the landscape operators assess which shoots have not been migrated yet. What do you think?

2023-05-16 13:49 UTC, istvanballok commented
After checking with @vpnachev we suggest to remove the migration logic in the n+6. release, so in about 3 months from now. That should give sufficient time so that even the shoots that are broken now due to e.g. invalid shoot infrastructure credentials are going to be fixed by the shoot owners and the Loki->Vali migration can be executed for them as well.

2023-05-16 13:50 UTC, rickardsjp commented
/lgtm

2023-05-16 15:05 UTC, rfranzke commented
> After checking with @vpnachev we suggest to remove the migration logic in the n+6. release, so in about 3 months from now. That should give sufficient time so that even the shoots that are broken now due to e.g. invalid shoot infrastructure credentials are going to be fixed by the shoot owners and the Loki->Vali migration can be executed for them as well.

Then that's the decision. Just to document this here as well, the following was mentioned in a private Slack chat:

> We also discussed that later a script cleaning Loki related resource in a seed can be made available via https://github.com/gardener/documentation/tree/master/website. It can be referred from the release node of the `n+6` release when the migration code is finally dropped.

/unhold

2023-05-16 15:33 UTC, shafeeqes commented
/retest-required

2023-05-16 16:14 UTC, merged