Creating new K8SNodeNotReady alert
gardener/gardener pull request #7335
Opened 2023-01-16 15:02 UTC by jguipi

**How to categorize this PR?**
/area monitoring
/area TODO
/kind TODO

**What this PR does / why we need it**:
First PR to add monitoring for how often nodes get killed
https://github.tools.sap/kubernetes/landscape-stability/issues/89 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```other operator
- Add an alert to see how many node are not ready for more than 10 minutes
```

2023-01-16 15:51 UTC, jguipi commented
cc.: @istvanballok @rickardsjp

2023-01-17 06:35 UTC, rfranzke commented
/cc @istvanballok @rickardsjp 
@jguipi please fix the unit tests

2023-01-17 09:33 UTC, istvanballok requested changes
Thank you @jguipi for the PR! :)

I shared some minor improvements regarding the PR description off-line. Regarding the unit test failure:

```
>> make generate
make generate needs to be run:
M docs/monitoring/user_alerts.md 
```

the generated file that lists the alerts has to be regenerated by executing the `make generate` command or rather preferably executing the `hack/generate-monitoring-docs.sh` script directly to specifically regenerate only the monitoring docs to save some time.

2023-01-17 09:33 UTC, istvanballok commented on charts/seed-monitoring/charts/core/charts/prometheus/rules/node-exporter.rules.yaml
> +      description: One or many node have not been ready for more than 10 minutes
Please improve the wording. :) (in, nodes)

2023-01-17 09:33 UTC, istvanballok commented on charts/seed-bootstrap/aggregate-prometheus-rules/nodes.rules.yaml
> +
Please improve the wording. :) (in, nodes) and the line break.

2023-01-17 09:33 UTC, istvanballok commented on charts/seed-bootstrap/aggregate-prometheus-rules/nodes.rules.yaml
> +    expr: ALERTS{alertname="K8SNodeNotReady", alertstate="firing"} > 0
I'm not sure if we need this on the aggregate Prometheus level. We could discuss this together off-line.

2023-01-20 08:21 UTC, istvanballok requested changes
some minor comments:
- please adjust the wording of the title as well (use the imperative mood, https://cbea.ms/git-commit/#imperative)
- please check the singular/plural form of node(s) in the PR and fix the wording appropriately
- the test fails because the generated file is not up to date, please regenerate it when the alert changes. Please consider adding a unit test as well. See comment of https://github.com/gardener/gardener/pull/7290#discussion_r1073197550
- I'm not sure if the alert is needed/meaningful on the aggregate Prometheus level.
- `sum(kube_node_status_condition{condition=“Ready”,status!=“true”})` aggregates the metrics of all the nodes, so if nodes take turn and become not ready in an overlapping manner, the alert would fire - I’m not sure if that matches the intention of the PR. We should check if this causes false positive alerts when (scenario 1) the cluster autoscaler shuts down nodes or (scenario 2) when the nodes are rolled due to OS/K8s version changes. I think the goal of this alert is to catch cases (scenario 3) when nodes break (and the cluster self heals after the mcm replaced the broken nodes) without a "legitimate" reason, e.g. due to a regression in the OS image.
- I suggest to try to trigger these (or similar) scenarios above in a controlled manner in a dev shoot cluster and then check the promql expression in the control plane Prometheus interactively (without an alert definition, just by executing the expression). It would be good to gain confidence this way that the alert catches the relevant scenario and hopefully will not yield false positives. Note that you could try to trigger scenario 3 by manually breaking the node e.g. by tweaking the kubelet systemd service. Please share the insights of these experiments in the PR or off-line - it will help to eventually check the promQL expression during the PR review to make sure that the expression is not only syntactically correct but also fulfills the intent of the PR.

2023-01-23 15:07 UTC, jguipi commented
Closing PR do to more testing

2023-01-23 15:07 UTC, closed without merging