Simplify debugging integration tests
gardener/gardener pull request #7431
Opened 2023-02-02 08:12 UTC by timebertt

**How to categorize this PR?**

/area testing
/kind enhancement

**What this PR does / why we need it**:

Adds `make start-envtest` to run a test environment (only kube or including gardener) separately from a test suite.
This allows developers to keep it running for as long as they want and inspect integration tests using kubectl.
This is closer to what is happening in CI and simpler to use for deflaking than a full-blown kind cluster or gardener setup.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6016

**Special notes for your reviewer**:

**Release note**:

```feature developer
`make start-envtest` brings up a test environment that can simplify debugging of integration tests. See the [docs](https://github.com/gardener/gardener/blob/master/docs/development/testing.md#integration-tests-envtests) for more information.
```

2023-02-02 10:02 UTC, plkokanov commented
/assign

2023-02-03 08:07 UTC, rfranzke commented on docs/development/testing.md
> +This allows you to keep the test environment running for as long as you want and debug integration tests by executing multiple test runs in parallel or inspecting test runs using `kubectl`.
```suggestion
This allows you to keep the test environment running for as long as you want, and to debug integration tests by executing multiple test runs in parallel or inspecting test runs using `kubectl`.

2023-02-03 08:07 UTC, rfranzke commented on docs/development/testing.md
> +When you are finished, just hit `^C` for tearing down the test environment.
Just to make it more clear 😉 

```suggestion
When you are finished, just hit `CTRL-C` for tearing down the test environment.
```

2023-02-03 08:26 UTC, plkokanov requested changes
Tried it out and it simplifies testing a lot :)

I did get one error because my docker daemon was not working. Although, it did not seem to cause any further problems:
```
$ make start-envtest 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
``` 
Is that expected?

2023-02-03 08:26 UTC, plkokanov commented on docs/development/testing.md
> +If your test suite requires a different control plane configuration (e.g., disabled admission plugins or enabled feature gates), feel free to locally modify the configuration in [`test/start-envtest`
Is it possible to supply additional configurations via an option or env variable? 
We can sometimes forget to revert the modifications that have been made to the `test/start-envtest` script.

2023-02-03 08:38 UTC, timebertt commented
> I did get one error because my docker daemon was not working. Although, it did not seem to cause any further problems:
> 
> ```
> $ make start-envtest 
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> ```
> 
> Is that expected?

This error is not related to my PR. It is caused by this line if your docker daemon is not running: https://github.com/gardener/gardener/blob/1a25ce2375da8984db9234403708cb759d78a719/Makefile#L313

2023-02-03 08:53 UTC, timebertt commented on docs/development/testing.md
> +If your test suite requires a different control plane configuration (e.g., disabled admission plugins or enabled feature gates), feel free to locally modify the configuration in [`test/start-envtest`
We could build something for sure. However, supporting overwrites for all envtest options seems like a high effort given that you can simply go ahead and edit the go file.
TBH, I don't see the necessity for it. This is no different than modifications to `start-apiserver` scripts or similar things.
Also, I don't see a risk of "forgetting" not to commit stuff there.

2023-02-03 08:55 UTC, timebertt commented
@rfranzke @plkokanov PTAL :)

2023-02-03 09:17 UTC, plkokanov commented
/lgtm

2023-02-03 09:56 UTC, timebertt commented
/retest-required

2023-02-03 09:57 UTC, rfranzke commented
/approve

2023-02-03 10:56 UTC, merged