Allow vpn-client in kube-apiserver to talk to seed apiserver in case of HA VPN.
gardener/gardener pull request #7440
Opened 2023-02-03 10:27 UTC by ScheererJ

**How to categorize this PR?**

/area networking
/kind bug

**What this PR does / why we need it**:
Allow vpn-client in kube-apiserver to talk to seed apiserver in case of HA VPN.

In the HA VPN, the ip address management of the vpn clients on the seed is done via annotations. Therefore, vpn-client container of the kube-apiserver needs to be able to communicate with the seed's apiserver. In case the seed is a gardener shoot this most likely causes vpn-client to use the external address of the seed's apiserver. This is due to the apiserver-proxy pod mutator injecting the KUBERNETES_SERVICE_HOST environment variable with the external name. However, in other seed scenarios vpn-client might also connect to the seed's apiserver via other means, e.g. through in-cluster communication. For this general case, the existing network policies were not sufficient. This change adds allowance to the seed's apiserver via the corresponding network policy.

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Release note**:

```other operator
Fixed bug that cause HA VPN to fail in case the seed's apiserver was not targeted by kube-apiserver's vpn-client via a public address
```

2023-02-03 10:33 UTC, MartinWeindel approved these changes
lgtm

2023-02-03 11:23 UTC, rfranzke requested changes

2023-02-03 11:23 UTC, rfranzke commented on pkg/operation/botanist/component/kubeapiserver/deployment.go
> +	deployment.Spec.Template.Labels[v1beta1constants.LabelNetworkPolicyToSeedAPIServer] = v1beta1constants.LabelNetworkPolicyAllowed
```suggestion
	deployment.Spec.Template.Labels[v1beta1constants.LabelNetworkPolicyToRuntimeAPIServer] = v1beta1constants.LabelNetworkPolicyAllowed
```

2023-02-06 15:37 UTC, ScheererJ commented on pkg/operation/botanist/component/kubeapiserver/deployment.go
> +	deployment.Spec.Template.Labels[v1beta1constants.LabelNetworkPolicyToSeedAPIServer] = v1beta1constants.LabelNetworkPolicyAllowed
Resolved with latest commit.

2023-02-07 07:23 UTC, rfranzke reviewed
/lgtm
/approve

2023-02-07 07:23 UTC, rfranzke commented
/milestone v1.64

2023-02-07 07:24 UTC, rfranzke commented
/cherry-pick release-v1.62

2023-02-07 07:24 UTC, rfranzke commented
/cherry-pick release-v1.63

2023-02-07 07:33 UTC, rfranzke commented
/test pull-gardener-e2e-kind-operator

2023-02-07 07:44 UTC, rfranzke commented
/test pull-gardener-e2e-kind-operator

2023-02-07 08:37 UTC, merged

2023-02-07 12:48 UTC, rfranzke commented
@ScheererJ or @MartinWeindel, can you make sure of opening respective cherry-pick PRs for the release branches? Automatic PRs don't work in this case, unfortunately.