Consider all MR in `shoot` namespace in `seed` for health check except one having class seed
gardener/gardener pull request #7462
Opened 2023-02-07 11:47 UTC by acumino

**How to categorize this PR?**

/area control-plane quality
/kind enhancement

**What this PR does / why we need it**:
This PR considers all MRs present in `shoot` namespace in `seed` for health check except one having class `seed`. Now all MR which follow the above condition is considered for shoot `ShootSystemComponentsHealthy` condition.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/6775

**Special notes for your reviewer**:
If any MR gets stuck in `Progressing` for more than `managedResourceProgressingThreshold`, It will set `SystemComponentsHealthy` to false as follow.
```
 - lastTransitionTime: "2023-02-07T11:19:26Z"
      lastUpdateTime: "2023-02-07T11:19:26Z"
      message: ManagedResource extension-networking-calico-config is progressing for
        more than 5m0s
      reason: ProgressingRolloutStuck
      status: Progressing
      type: SystemComponentsHealthy
```
After this PR all extension can drop MR healthcheck.

**Release note**:

```other operator
NONE
```

2023-02-07 11:49 UTC, acumino commented
/cc @rfranzke @ialidzhikov

2023-02-07 12:35 UTC, acumino commented
/retest

2023-02-08 11:46 UTC, rfranzke requested changes
Can we have a unit test for it?
Also, please adapt https://github.com/gardener/gardener/blob/master/docs/extensions/shoot-health-status-conditions.md.

2023-02-09 04:04 UTC, acumino commented
/hold until https://github.com/gardener/gardener/pull/7475 is merged.

2023-02-13 13:57 UTC, acumino commented
> Can we have a unit test for it? Also, please adapt https://github.com/gardener/gardener/blob/master/docs/extensions/shoot-health-status-conditions.md.

Can you suggest, where to add the unit test?

2023-02-13 13:59 UTC, acumino commented
/unhold

2023-02-14 05:44 UTC, acumino commented
/retest

2023-02-14 07:23 UTC, rfranzke reviewed
For the test, it seems that the [integration test](https://github.com/gardener/gardener/blob/master/test/integration/gardenlet/shoot/care/care_test.go) is the easiest option to get this tested. Can you find a way to get this working?

2023-02-14 07:23 UTC, rfranzke commented on docs/extensions/healthcheck-library.md
> +By default, Gardener performs health check for all the managed resources created in the shoot control plane.
```suggestion
By default, Gardener performs health check for all the `ManagedResource`s with `.spec.class=nil` created in the shoot namespaces.
```

2023-02-14 07:23 UTC, rfranzke commented on docs/extensions/healthcheck-library.md
> +By default, Gardener performs health check for all the managed resources created in the shoot control plane.
Add a release note for dependencies to make extension developers aware of this.

2023-02-14 09:33 UTC, acumino commented
/test pull-gardener-e2e-kind

2023-02-14 10:17 UTC, acumino commented
/test pull-gardener-e2e-kind

2023-02-14 11:32 UTC, acumino commented
> For the test, it seems that the [integration test](https://github.com/gardener/gardener/blob/master/test/integration/gardenlet/shoot/care/care_test.go) is the easiest option to get this tested. Can you find a way to get this working?

Integration test will require a lot of modification for checking the functionality of this PR. One easy way will be to add the unit test [here](https://github.com/gardener/gardener/blob/master/pkg/operation/care/health_check_test.go) but in this file we only test exported function. WDYT?

2023-02-14 11:55 UTC, rfranzke commented
Sure, if you see an easier way with a unit test, also fine for me.

2023-02-15 10:02 UTC, rfranzke requested changes

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +		Expect(testClient.Create(ctx, deployment)).To(Succeed(), "for deployment "+name)
WithOffset

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +		Eventually(func() error {
WithOffset

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +			Expect(testClient.Delete(ctx, deployment)).To(Succeed(), "for deployment "+name)
WithOffset

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +			Eventually(func() error {
WithOffset

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +			Eventually(func() error {
WithOffset

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +					ContainCondition(OfType(gardencorev1beta1.ShootEveryNodeReady), WithStatus(gardencorev1beta1.ConditionProgressing), WithReason("MissingNodes")),
Drop this, or? We only care about the `SystemComponentsHealthy` condition in this test case.

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +			It("SystemComponentsHealthy condition should not fail beacause of Managed Resource", func() {
```suggestion
			It("SystemComponentsHealthy condition should not fail because all relevant Managed Resources are healthy", func() {
```

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +					ContainCondition(OfType(gardencorev1beta1.ShootSystemComponentsHealthy), WithStatus(gardencorev1beta1.ConditionProgressing), WithReason("NoTunnelDeployed"), WithMessageSubstrings("no tunnels are
This expectation doesn't fit to the test case description. You talk about the condition to not fail, but here you expect that it fails. Can you instead fake the tunnel so that we can expect `True` status here? Otherwise, add a comment here about it.

2023-02-15 10:02 UTC, rfranzke commented on test/integration/gardenlet/shoot/care/care_test.go
> +			It("SystemComponentsHealthy condition should fail because of Managed Resource healthiness", func() {
```suggestion
			It("SystemComponentsHealthy condition should fail because of ManagedResource is not healthy", func() {
```

2023-02-15 10:04 UTC, acumino commented on test/integration/gardenlet/shoot/care/care_test.go
> +					ContainCondition(OfType(gardencorev1beta1.ShootSystemComponentsHealthy), WithStatus(gardencorev1beta1.ConditionProgressing), WithReason("NoTunnelDeployed"), WithMessageSubstrings("no tunnels are
I tried faking tunnel, but it seems it is not possible.

2023-02-15 13:32 UTC, acumino commented
/test pull-gardener-e2e-kind-ha-multi-zone-upgrade

2023-02-16 08:38 UTC, rfranzke commented
/lgtm
/approve

2023-02-16 09:28 UTC, merged