Deflake `E2E Operator` test
gardener/gardener pull request #7482
Opened 2023-02-13 11:30 UTC by acumino

**How to categorize this PR?**

/area testing
/kind flake

**What this PR does / why we need it**:
The test was failing at [this](https://github.com/gardener/gardener/blob/ebca5ce49bd5ac6c3edd0bbbda76be44a963798a/test/e2e/operator/garden/internal/rotation/certificate_authorities.go#L109) step because there can be the case where both `lastCompletionTriggeredTime` and `lastInitiationFinishedTime` are exactly same up to the seconds precision, one such example while executing the test locally
```
status:
  conditions:
  - lastTransitionTime: "2023-02-13T08:22:57Z"
    lastUpdateTime: "2023-02-13T08:22:57Z"
    message: Garden operation is currently being processed.
    reason: ReconciliationProgressing
    status: Progressing
    type: Reconciled
  credentials:
    rotation:
      certificateAuthorities:
        lastCompletionTriggeredTime: "2023-02-13T08:22:57Z"
        lastInitiationFinishedTime: "2023-02-13T08:22:57Z"
        lastInitiationTime: "2023-02-13T08:20:46Z"
        phase: Completing
  gardener:
    id: 6GqyhkihlzCu4Bx7CnMMUHkM0C2zGZzvHZ1abfCLB15UvOcdIt49gQ7LK9ysJBJ2
    name: gardener-operator-b4888759d-fbcck
    version: v1.65.0-dev
  observedGeneration: 1
```

This PR now considers the scenario where both `lastCompletionTriggeredTime` and `lastInitiationFinishedTime` are same.
Also it adds the cleanup part of `Garden` in `DeferCleanup` so it gets executed even though test fails in between at some step.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7334

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-02-13 13:50 UTC, rfranzke commented
/assign

2023-02-14 07:15 UTC, rfranzke reviewed
Nice, thanks!

2023-02-14 07:15 UTC, rfranzke commented on test/e2e/operator/garden/internal/rotation/certificate_authorities.go
> +	Expect(v.Garden.Status.Credentials.Rotation.CertificateAuthorities.LastCompletionTriggeredTime.Time.Equal(v.Garden.Status.Credentials.Rotation.CertificateAuthorities.LastInitiationFinishedTime.Time)
Can you adapt similar occurrences in https://github.com/gardener/gardener/blob/ebca5ce49bd5ac6c3edd0bbbda76be44a963798a/test/e2e/gardener/shoot/internal/rotation as well, please? I think there are at least 3 of them (CA, ETCD, SA)

2023-02-14 07:30 UTC, rfranzke requested changes

2023-02-14 07:30 UTC, rfranzke commented on test/e2e/gardener/shoot/internal/rotation/etcd_encryption_key.go
> +	Expect(v.Shoot.Status.Credentials.Rotation.CertificateAuthorities.LastCompletionTriggeredTime.Time.Equal(v.Shoot.Status.Credentials.Rotation.CertificateAuthorities.LastInitiationFinishedTime.Time) |
ETCDEncryptionKey?

2023-02-14 07:30 UTC, rfranzke commented on test/e2e/gardener/shoot/internal/rotation/service_account_key.go
> +	Expect(v.Shoot.Status.Credentials.Rotation.CertificateAuthorities.LastCompletionTriggeredTime.Time.Equal(v.Shoot.Status.Credentials.Rotation.CertificateAuthorities.LastInitiationFinishedTime.Time) |
ServiceAccountKey?

2023-02-14 08:10 UTC, acumino commented on test/e2e/gardener/shoot/internal/rotation/etcd_encryption_key.go
> +	Expect(v.Shoot.Status.Credentials.Rotation.CertificateAuthorities.LastCompletionTriggeredTime.Time.Equal(v.Shoot.Status.Credentials.Rotation.CertificateAuthorities.LastInitiationFinishedTime.Time) |
Copy-Paste error 🤦 .

2023-02-14 08:13 UTC, rfranzke reviewed
/lgtm
/approve

2023-02-14 08:56 UTC, merged

2023-02-17 06:48 UTC, rfranzke commented
/cherry-pick release-v1.64

2023-02-17 06:48 UTC, rfranzke commented
/cherry-pick release-v1.63

2023-02-17 06:48 UTC, rfranzke commented
/cherry-pick release-v1.62