Website Cleanup Part 6 - Proposals (Part 2)
gardener/gardener pull request #7488
Opened 2023-02-15 08:02 UTC by n-boshnakov

**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR proofreads the Proposals section of the documentation. This is Part 2 of 2.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

2023-02-15 08:18 UTC, ialidzhikov requested changes

2023-02-15 08:18 UTC, ialidzhikov commented on docs/proposals/20-ha-control-planes.md
> +For each cluster, Гardener provides a capability to create one or more `Worker Pool/Group`. Each worker pool can span across one or more availability zones. For a combination of each worker pool and
```suggestion
For each cluster, Gardener provides a capability to create one or more `Worker Pool/Group`. Each worker pool can span across one or more availability zones. For a combination of each worker pool and zone there will be a corresponding `MachineDeployment` which will also map 1:1 to a `Node Group`, which is understood by cluster-autoscaler.
```

2023-02-15 10:06 UTC, ialidzhikov reviewed
Why we keep updating the GEPs? Because when you navigate to https://gardener.cloud/docs/, they are part of the Gardener docs? Why they have to be part of the user facing docs? When I navigate to https://docs.k8s.io I don't see any KEPs. I would rather suggest excluding them from the gardener.cloud/docs and stop updating them with wording improvements or typo fixes.

2023-02-15 10:07 UTC, rfranzke commented
I agree with @ialidzhikov. We can merge this PR now since work was invested already, though.

2023-02-15 10:09 UTC, ialidzhikov commented
I would like to first see change that excludes the GEPs from https://gardener.cloud/docs.

2023-02-15 10:11 UTC, rfranzke commented
> I would like to first see change that excludes the GEPs from https://gardener.cloud/docs.

Is this related to this PR in any way?

2023-02-15 10:18 UTC, n-boshnakov commented
I have created a PR that removes the Proposals section from the public website, as per @ialidzhikov's request.

2023-02-15 11:23 UTC, ialidzhikov commented on docs/proposals/20-ha-control-planes.md
> +- Setting up a high availability Gardener service.
```suggestion
- Setting up a highly available Gardener service.
```

2023-02-15 12:46 UTC, ialidzhikov reviewed
/lgtm

2023-02-16 06:08 UTC, acumino commented on docs/proposals/03-networking-extensibility.md
> +The goal of the Gardener Network Extensions is to support different network plugin, therefore the specification for the network resource won't be fixed and will be customized based on the underlying
```suggestion
The goal of the Gardener Network Extensions is to support different network plugins, therefore the specification for the network resource won't be fixed and will be customized based on the underlying network plugin. To do so, a `NetworkConfig` field in the spec will be provided where each plugin will be defined. Below is an example of deploying Calico as the cluster network plugin.
```

2023-02-16 06:08 UTC, acumino commented on docs/proposals/10-shoot-additional-container-runtimes.md
> +        1. A label for each container runtime support will be added to every node that belongs to the worker pool. This should be done similarly to the way labels created today for each node, through
```suggestion
        1. A label for each container runtime support will be added to every node that belongs to the worker pool. This should be done similarly to the way labels are created today for each node, through kubelet execution parameters (`_kubelet.flags: --node-labels`). When creating the OperatingSystemConfig (original) for the worker, each container runtime support should be mapped to a label on the node.
```

2023-02-16 06:08 UTC, acumino commented on docs/proposals/14-reversed-cluster-vpn.md
> +This solution reuses multiple instances of the envoy component used for the kube-apiserver endpoints. We assume that the availability for kube-apiservers is good enough for the cluster VPN as well.
```suggestion
This solution reuses multiple instances of the envoy component used for the kube-apiserver endpoints. We assume that the availability of kube-apiservers is good enough for the cluster VPN as well.
```

2023-02-16 06:08 UTC, acumino commented on docs/proposals/14-reversed-cluster-vpn.md
> +This is roughly depcited in this diagram. Note that the `vpn-seed` and `vpn-shoot` containers only require very little changes and are fully backwards compatible.
```suggestion
This is roughly depicted in this diagram. Note that the `vpn-seed` and `vpn-shoot` containers only require very little changes and are fully backwards compatible.
```

2023-02-16 06:08 UTC, acumino commented on docs/proposals/14-reversed-cluster-vpn.md
> +While it is possible to configure a WireGuard device using DNS names, only IP addresses can be stored in Linux Kernel data structures. A change of a load balancer IP address can therefore not be miti
```suggestion
While it is possible to configure a WireGuard device using DNS names, only IP addresses can be stored in Linux Kernel data structures. A change of a load balancer IP address can therefore not be mitigated on that level. As WireGuard dynamically adapts endpoint IP addresses, a change in load balancer IPs is mitigated in most but not all cases. This is why a re-advertiser is required for public cloud providers such as AWS.
```

2023-02-16 06:08 UTC, acumino commented on docs/proposals/18-shoot-CA-rotation.md
> +  - Shoot reconciliation needs to be idemptotent to CA rotation phase, i.e., if a usual reconciliation or maintenance operation is triggered in between, no new CAs are generated or similar things tha
```suggestion
  - Shoot reconciliation needs to be idempotent to CA rotation phase, i.e., if a usual reconciliation or maintenance operation is triggered in between, no new CAs are generated or similar things that would interfere with the CA rotation sequence.
```

2023-02-16 06:08 UTC, acumino commented on docs/proposals/18-shoot-CA-rotation.md
> +  - `gardener-apiserver` performs the needful validation: a user can't trigger another rotation if one is already in progress, a user can't trigger `complete-ca-rotation` if first phase has not been
```suggestion
  - `gardener-apiserver` performs the needful validation: a user can't trigger another rotation if one is already in progress, a user can't trigger `complete-ca-rotation` if first phase has not been completed, etc.
```

2023-02-16 08:23 UTC, acumino reviewed
/lgtm

2023-02-16 08:44 UTC, ialidzhikov reviewed
/approve

2023-02-16 11:24 UTC, merged