Removes `BackupEntry` and `Shoot` migration reconcilers and the `ForceRestore` feature gate
gardener/gardener pull request #7543
Opened 2023-02-22 13:58 UTC by plkokanov

**How to categorize this PR?**

/area control-plane-migration
/kind cleanup

**What this PR does / why we need it**:
This PR removes the `BackupEntry` Migration reconciler and the `Shoot` migration reconciler since they will not be needed anymore. This is done as part of the removal of the control plane migration "bad case" scenario. Additionally they were causing some problems when the `ForceRestore` feature gate was enabled where if control plane migration was triggered and the source `Seed` was too slow to start the `migration` phase, the `restore` phase was triggered without there being anything wrong with the source `Seed`. This unnecessarily performed a "bad case" control plane migration that leaves an orphaned namespace for the control plane of the `Shoot` in the source `Seed`.

Additionally, this PR also removes the `ForceRestore` feature gate as it is not used anymore after the removal of the reconcilers mentioned above. There is no deprecation period as the `ForceRestore` feature gate was still alpha, and simply deprecating it while removing the reconcilers does not make much sense.

**Which issue(s) this PR fixes**:
Part of #6302 
Fixes #7286 

**Special notes for your reviewer**:

**Release note**:

```other operator
The `BackupEntry` and `Shoot` "Migration" reconcilers were removed, as part of the removal of the "
```
```breaking operator
The `ForceRestore` feature gate has been removed.
```

2023-02-23 07:03 UTC, rfranzke commented
/assign

2023-02-23 07:08 UTC, rfranzke requested changes

2023-02-23 07:08 UTC, rfranzke commented on docs/deployment/feature_gates.md
> +| ForceRestore                                 | `false` | `Removed`    | `1.65` |        |
This will not make it into v1.65
```suggestion
| ForceRestore                                 | `false` | `Removed`    | `1.66` |        |
```

2023-02-23 07:08 UTC, rfranzke commented on example/20-componentconfig-gardenlet.yaml
> +
drop this empty line

2023-02-23 10:06 UTC, shafeeqes commented
/assign

2023-02-24 06:19 UTC, shafeeqes reviewed
Thanks for the PR, no comments from my side apart from the open ones.
lgtm

2023-02-24 14:29 UTC, rfranzke reviewed
/lgtm
/approve

2023-02-27 10:33 UTC, merged