Enable `FullNetworkPoliciesInRuntimeCluster` feature gate locally
gardener/gardener pull request #7630
Opened 2023-03-13 10:28 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR enables the `FullNetworkPoliciesInRuntimeCluster` feature gate (introduced with https://github.com/gardener/gardener/pull/7589) for the local setup. Since `gardener-extension-networking-calico` is not yet released (though, we require https://github.com/gardener/gardener-extension-networking-calico/pull/247), a DEV tag is used for now.

/cc @ScheererJ 

**Release note**:

```other operator
NONE
```

2023-03-13 11:29 UTC, ScheererJ requested changes
The calico extension release was earlier than expected. Hence, we can directly switch to it.

2023-03-13 11:29 UTC, ScheererJ commented on example/provider-local/garden/base/kustomization.yaml
> +- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/565ba75d31bfbb5a66f0916873e055fce4c3875e/example/controller-registration.yaml
```suggestion
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.31.0/example/controller-registration.yaml
```

2023-03-13 11:29 UTC, ScheererJ commented on example/provider-local/garden/base/patch-controller-deployment.yaml
> +      tag: v1.31.0-dev-565ba75d31bfbb5a66f0916873e055fce4c3875e
```suggestion
      tag: v1.31.0
```

2023-03-13 11:32 UTC, rfranzke commented
After https://github.com/gardener/gardener-extension-networking-calico/pull/229 the `networking-calico` extension enforces a non-nil `.spec.networking.nodes`. We have to wait for a new release.
/hold

2023-03-15 16:57 UTC, ScheererJ requested changes

2023-03-15 16:57 UTC, ScheererJ commented on example/provider-local/garden/base/kustomization.yaml
> +- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.31.0/example/controller-registration.yaml
`.spec.networking.nodes` is optional again with v1.31.1.

```suggestion
- https://raw.githubusercontent.com/gardener/gardener-extension-networking-calico/v1.31.1/example/controller-registration.yaml
```

2023-03-15 16:57 UTC, ScheererJ commented
/unhold

2023-03-16 08:36 UTC, ScheererJ approved these changes
Thanks a lot.
/lgtm

2023-03-16 08:38 UTC, rfranzke commented
/test pull-gardener-e2e-kind

2023-03-16 10:03 UTC, merged