Update scrape-config for istio-ingress.
gardener/gardener pull request #7658
Opened 2023-03-17 08:52 UTC by axel7born

* Update scrape config to get metrics from istio-ingress pods in other namespaces.
* Adapt istio-ingress dashboard to show metrics summarized per namespace.

**How to categorize this PR?**

/area networking monitoring
/kind bug

**What this PR does / why we need it**:
In the Grafana dashboard `Istio Ingress Gateway` only metrics from pod in the default namespace `istio-ingress` were visible. However, with the `ExposureClasses` and the introduction of Highly Available Shoot Control Planes, ingress-gateway pod are also deployed in other namespaces. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```fix operator
Fix missing metrics from istio ingress-gateways.
```

2023-03-17 09:03 UTC, ScheererJ requested changes

2023-03-17 09:03 UTC, ScheererJ commented on pkg/operation/botanist/component/istio/monitoring.go
> +   label: istio=ingressgateway
Shouldn't it be two space indentation?

```suggestion
    label: istio=ingressgateway
```

2023-03-17 09:03 UTC, ScheererJ commented on pkg/operation/botanist/component/istio/monitoring.go
> +  regex: ` + v1beta1constants.DefaultSNIIngressServiceName + `;tls-tunnel;` + v1beta1constants.DefaultSNIIngressNamespace + `.*
What if https://github.com/gardener/gardener/blob/b2d32fe231cb47926480eb30a1d8f2ca6b9be4dc/example/20-componentconfig-gardenlet.yaml#L153 is changed?
What if https://github.com/gardener/gardener/blob/b2d32fe231cb47926480eb30a1d8f2ca6b9be4dc/example/20-componentconfig-gardenlet.yaml#L168 is changed?

2023-03-17 09:58 UTC, axel7born commented on pkg/operation/botanist/component/istio/monitoring.go
> +  regex: ` + v1beta1constants.DefaultSNIIngressServiceName + `;tls-tunnel;` + v1beta1constants.DefaultSNIIngressNamespace + `.*
I removed the namespace from the regex.

2023-03-17 09:58 UTC, axel7born commented on pkg/operation/botanist/component/istio/monitoring.go
> +   label: istio=ingressgateway
fixed

2023-03-17 10:01 UTC, axel7born commented
/cc @istvanballok @rickardsjp 
Could you take a look, if the changes in the scrape config make sense?

2023-03-20 06:46 UTC, axel7born commented
/test all

2023-03-22 08:50 UTC, ScheererJ approved these changes
/lgtm

2023-03-22 09:02 UTC, ScheererJ commented
/hold
waiting for feedback from @istvanballok / @rickardsjp

2023-03-27 12:00 UTC, istvanballok approved these changes
/lgtm with a minor comment

2023-03-27 12:00 UTC, istvanballok commented on charts/seed-bootstrap/dashboards/istio/istio-ingress-gateway-dashboard.json
> +          "legendFormat": "{{ pod }}",
```suggestion
          "legendFormat": "{{ namespace }}",
```

I think there is a similar typo in the panel above but I could not annotate it in the review as the respective line did not change.

Note that Grafana seems to do the "right" thing if the result of the query has a single label, and even if it does not match the label expression in the legend configuration, the label values are shown. Nevertheless, we could still adjust the Legend expression for consistency.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/23032437/227934350-20c1e742-aa86-48eb-a060-0aed6598a0fd.png">

2023-03-27 13:20 UTC, axel7born commented on charts/seed-bootstrap/dashboards/istio/istio-ingress-gateway-dashboard.json
> +          "legendFormat": "{{ pod }}",
Fixed.

2023-03-27 14:39 UTC, ScheererJ commented
/unhold

2023-03-27 14:40 UTC, ScheererJ approved these changes
/lgtm

2023-03-27 15:21 UTC, merged