Remove Loki metrics named port
gardener/gardener pull request #7766
Opened 2023-04-07 11:10 UTC by Kristian-ZH

**How to categorize this PR?**

/area logging
/kind bug

**What this PR does / why we need it**:
Currently there is an issue in Cilium with the named ports: Ref: https://github.com/cilium/cilium/issues/24779
This issue is causing troubles with the network policies and the connection FluentBit-Loki-Grafana is broken

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@vlvasilev 
@dimityrmirchev 
@axel7born 
@DockToFuture 

**Release note**:

```other operator
None
```

2023-04-10 07:45 UTC, ialidzhikov requested changes, later dismissed

2023-04-10 07:45 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
> +        networking.resources.gardener.cloud/to-logging-tcp-3100: allowed
Why you don't name to something like "ingest"? We already discussed that the current name is wrong - port named "metrics" that is actually used for pushing logs to loki.

2023-04-10 07:45 UTC, ialidzhikov commented on charts/seed-bootstrap/charts/fluent-bit/templates/fluent-bit-daemonset.yaml
> +        networking.resources.gardener.cloud/to-logging-tcp-3100: allowed
About https://github.com/cilium/cilium/issues/24779? Duplicate port with another Pod's port in the same namespace? If that's the case don't we have almost every component with such a metrics port?

2023-04-13 11:41 UTC, ialidzhikov reviewed
/lgtm

2023-04-14 12:13 UTC, rfranzke reviewed
/approve

2023-04-14 14:07 UTC, merged