Require provider extension for seed type
gardener/gardener pull request #7928
Opened 2023-05-11 14:44 UTC by timuthy

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR contributes make the seed reconcile flow checking if there is a provider extensions being ready that is of the seed provider type. Provider extensions can come with components, e.g. webhooks, that need to adjust resources not only belonging to shoot control planes.

One example is the [Azure Provider Extension](https://github.com/gardener/gardener-extension-provider-azure) which amends zonal node affinities for `Pod`s (see https://github.com/gardener/gardener-extension-provider-azure/pull/602). This webhook is not only relevant for shoot contorl-plane `Pod`s and thus must be present before any seed system components are deployed to the cluster.

**Special notes for your reviewer**:
/cc @kon-angelo @dguendisch

**Release note**:

```breaking operator
It is required to have `ControllerRegistrations`s for Kinds `ControlPlane`, `Infrastructure` and `Worker` with the same types used for seeds (`seed.spec.provider.type`). This is already the case if seeds and shoots share the same cloud provider. The seed reconciliation flow waits for the associated `ControllerInstallation` to be ready before continuing rolling out seed system components. It allows Gardener provider extensions to ship components that not only act on shoot control-plane but also on seed system components.
```

2023-05-11 15:04 UTC, rfranzke commented
/assign

2023-05-15 11:46 UTC, rfranzke requested changes

2023-05-15 11:46 UTC, rfranzke commented on pkg/utils/gardener/seed.go
> +func ComputeRequiredExtensionsForSeed(seed *gardencorev1beta1.Seed) sets.Set[string] {
Can you also add a unit test for this exported function?

2023-05-15 11:46 UTC, rfranzke commented on pkg/utils/gardener/seed.go
> +	var wantedKindTypeCombinations = sets.New[string]()
```suggestion
	wantedKindTypeCombinations := sets.New[string]()
```

2023-05-15 11:46 UTC, rfranzke commented on pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
> +}
This looks too similar to https://github.com/gardener/gardener/blob/13d5158c55cc6b21ff1a24bb068c00dd223e8563/pkg/operation/botanist/botanist.go#L240-L282. Can you find a way to make the code reusable?

2023-05-15 11:46 UTC, rfranzke commented on pkg/controllermanager/controller/seed/extensionscheck/reconciler.go
> -		}
Can you maybe extend the commit message and explain why this could be removed now?

2023-05-19 11:47 UTC, rfranzke reviewed
Sweet, well done, let's go! :)
/lgtm
/approve

2023-05-22 12:23 UTC, kon-angelo reviewed
/lgtm

2023-05-22 15:45 UTC, merged