Refactor `blackbox exporter` Helm chart into Golang component
gardener/gardener pull request #7978
Opened 2023-05-24 15:04 UTC by acumino

**How to categorize this PR?**

/area dev-productivity quality robustness
/kind technical-debt test
/platform all

**What this PR does / why we need it**:
This PR refactors the `blackbox exporter` and adopts the Golang component concept.

**Which issue(s) this PR fixes**:
Part of #2754

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-05-26 04:36 UTC, ary1992 commented on charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/deployment.yaml
> +# TODO (acumino): drop this chart in release v1.75
```suggestion
# TODO(acumino): drop this chart in release v1.75
```

Same at other places too.

2023-05-26 04:47 UTC, shafeeqes requested changes
Thanks for the PR.
Only few minor comments.

2023-05-26 04:47 UTC, shafeeqes commented on pkg/operation/botanist/blackboxexporter_test.go
> +			kubernetesClient *kubernetesmock.MockInterface
```suggestion
```

2023-05-26 04:47 UTC, shafeeqes commented on charts/shoot-core/components/charts/monitoring/charts/blackbox-exporter/templates/serviceaccount.yaml
> +# TODO (acumino): drop this chart in release v1.75
```suggestion
# TODO(acumino): Drop this chart in release v1.75
```

2023-05-26 04:47 UTC, shafeeqes commented on pkg/component/blackboxexporter/blackboxexporter.go
> +					"origin":                    "gardener",
```suggestion
					managedresources.LabelKeyOrigin: managedresources.LabelValueGardener,
```

2023-05-26 06:04 UTC, shafeeqes reviewed
/lgtm

2023-05-26 07:23 UTC, acumino commented
/test pull-gardener-e2e-kind-ha-multi-zone-upgrade

2023-05-29 04:01 UTC, ary1992 commented
/lgtm
/approve

2023-05-29 04:38 UTC, shafeeqes commented
/test pull-gardener-unit

2023-05-29 04:53 UTC, merged