Improve accuracy of local control plane migration e2e tests
gardener/gardener pull request #7981
Opened 2023-05-24 19:33 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
When performing control plane migration with `provider-local`, the full migration and restoration logic implemented in the extensions library (generic `Worker` actuator) is now executed (previously, it was skipped). This improves the accuracy of the e2e tests for control plane migration.

**Which issue(s) this PR fixes**:
Introduced with https://github.com/gardener/gardener/pull/6059

**Special notes for your reviewer**:
/cc @plkokanov 

**Release note**:

```feature developer
When performing control plane migration with `provider-local`, the full migration and restoration logic implemented in the extensions library (generic `Worker` actuator) is now executed (previously, it was skipped). This improves the accuracy of the e2e tests for control plane migration.
```

2023-05-24 19:34 UTC, rfranzke commented
FYI @jensac @mreiger

2023-05-25 09:14 UTC, plkokanov commented
/assign

2023-05-25 11:08 UTC, plkokanov requested changes
Just one nit, otherwise I think it looks good.

2023-05-25 11:08 UTC, plkokanov commented on pkg/provider-local/controller/worker/actuator.go
> +func (a *actuator) deleteNoLongerMachines(ctx context.Context, log logr.Logger, namespace string) error {
```suggestion
func (a *actuator) deleteNoLongerNeededMachines(ctx context.Context, log logr.Logger, namespace string) error {
```

2023-05-26 09:48 UTC, plkokanov commented
/lgtm
/approve

2023-05-26 11:01 UTC, acumino commented
/test pull-gardener-integration

2023-05-26 11:09 UTC, merged