Deploy `Etcd` CRDs independent of Etcd bootstrap
gardener/gardener pull request #8002
Opened 2023-05-31 09:01 UTC by acumino

**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR separates the Etcd CRD deployment from Etcd Bootstrap step. Check the motivation for this PR in https://github.com/gardener/gardener/issues/7997

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7997

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-05-31 09:02 UTC, acumino commented
/test all

2023-05-31 09:20 UTC, acumino commented
/milestone v1.72

2023-05-31 09:24 UTC, ary1992 commented
/assign

2023-05-31 09:27 UTC, rfranzke commented
/assign

2023-05-31 10:14 UTC, acumino commented
/retest

2023-05-31 11:08 UTC, rfranzke requested changes

2023-05-31 11:08 UTC, rfranzke commented on pkg/component/etcd/crd.go
> +	CRD string
```suggestion
	etcdCRD string
```

2023-05-31 11:08 UTC, rfranzke commented on pkg/operator/controller/garden/reconciler_delete.go
> +			Name:         "Destroying custom resource definition for ETCD/EtcdCopyBackupsTask",
```suggestion
			Name:         "Destroying ETCD-related custom resource definitions",
```

2023-05-31 11:08 UTC, rfranzke commented on pkg/operator/controller/garden/reconciler_reconcile.go
> +			Name: "Deploying custom resource definition for ETCD/EtcdCopyBackupsTask",
```suggestion
			Name: "Deploying ETCD-related custom resource definitions",
```

2023-05-31 11:08 UTC, rfranzke commented on pkg/gardenlet/controller/seed/seed/reconciler_reconcile.go
> +	if !seedIsGarden {
Please adapt https://github.com/gardener/gardener/blob/master/test/integration/gardenlet/seed/seed/seed_test.go to cover this case

2023-05-31 11:08 UTC, rfranzke commented on pkg/gardenlet/controller/seed/seed/reconciler_delete.go
> +				Name:         "Destroy custom resource definition for ETCD/EtcdCopyBackupsTask",
```suggestion
				Name:         "Destroy ETCD-related custom resource definitions",
```

2023-05-31 11:08 UTC, rfranzke commented on pkg/component/etcd/crd.go
> +type etcdCRD struct {
```suggestion
type crd struct {
```

2023-05-31 11:08 UTC, rfranzke commented on pkg/component/etcd/bootstrap.go
> -	resources["crdEtcdCopyBackupsTask.yaml"] = []byte(etcdCopyBackupsTaskCRD)
This will make GRM try to delete the CRDs, right?
I guess we have to keep them with the ignore annotation for at least one release.

2023-05-31 16:03 UTC, acumino commented on pkg/component/etcd/crd.go
> +	CRD string
This is exported for testing.

2023-05-31 16:04 UTC, acumino commented on pkg/component/etcd/bootstrap.go
> -	resources["crdEtcdCopyBackupsTask.yaml"] = []byte(etcdCopyBackupsTaskCRD)
Adapted in a668c17cf65f1e98fc2ea0e23e938d2ff33c3261

2023-06-01 05:48 UTC, rfranzke commented on pkg/component/etcd/bootstrap.go
> +	resources["crd.yaml"] = []byte(etcdCRD)
Add a TODO statement to clean this up after v1.72 got released.

2023-06-01 06:24 UTC, rfranzke reviewed
/lgtm
/approve

Thanks!

2023-06-01 07:09 UTC, merged