Allow deletion for `Shoot`s with invalid spec
gardener/gardener pull request #8122
Opened 2023-06-20 15:04 UTC by timuthy

**How to categorize this PR?**

/area usability
/area ops-productivity
/kind regression

**What this PR does / why we need it**:
This PR reverts the behavior added with https://github.com/gardener/gardener/pull/2118 but reverted again in the scope of the controller-runtime refactoring in https://github.com/gardener/gardener/pull/7082/commits/3c88461ba4702125dd712574d41938f1e1fb4597.

The `shoot.status.uid` was intentionally only set when the operation could be initialized once. It serves as a marker in order to determine if Gardenlet has ever created resources that must be cleaned up during deletion. Thus, we can immediately finalize shoot clusters that were created with a wrong configuration at the outset (see #1926) and don't initialize an `operation`.

**Which issue(s) this PR fixes**:
Fixes #1926

**Special notes for your reviewer**:
/cc @rfranzke

**Release note**:

```bugfix user
A regression was fixed that prevented deletions for shoot clusters which were created with a wrong configuration (e.g. with an unavailable domain name).
```

2023-06-20 15:18 UTC, rfranzke commented
/assign

2023-06-20 15:22 UTC, rfranzke requested changes
Nice, thanks for adding a new e2e test <3

2023-06-20 15:22 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +	// Gardenlet can directly finalize the shoot deletion since not resources need to be cleaned up.
```suggestion
	// Gardenlet can directly finalize the shoot deletion since no resources need to be cleaned up.
```

2023-06-20 15:22 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot/reconciler.go
> +	// This shortcut also allows users to delete shoot clusters that were wrongly configured in the first place, e.g. https://github.com/gardener/gardener/issues/1926.
```suggestion
	// This shortcut also allows users to delete shoot clusters that were wrongly configured in the first place, e.g. see https://github.com/gardener/gardener/issues/1926.
```

2023-06-20 15:22 UTC, rfranzke commented on test/e2e/gardener/shoot/create_and_delete_failed.go
> +				f.GetShoot(ctx, shoot)
```suggestion
				g.Expect(f.GetShoot(ctx, shoot)).To(Succeed())
```

2023-06-20 15:22 UTC, rfranzke commented on test/e2e/gardener/shoot/create_and_delete_failed.go
> +			By("Wait until Shoot is set to Failed")
```suggestion
			By("Wait until last operation in Shoot is set to Failed")
```

2023-06-20 15:22 UTC, rfranzke commented on test/e2e/gardener/shoot/create_and_delete_failed.go
> +			ctx, cancel := context.WithTimeout(parentCtx, 15*time.Minute)
We can lower the time here, right? The expectation would be that this test runs rather fast?

2023-06-22 06:33 UTC, rfranzke reviewed
/lgtm
/approve

2023-06-22 06:33 UTC, rfranzke commented
@timuthy I guess we should cherry-pick this, right?

2023-06-22 07:14 UTC, timuthy commented
As discussed, we can cherry-pick this change when we see an urgent need. For the moment we think it's good to have this change on the main branch only to go through the "extended release validation".

2023-06-22 09:36 UTC, acumino commented
/test pull-gardener-e2e-kind-operator

2023-06-22 11:33 UTC, timuthy commented
/test pull-gardener-e2e-kind-operator

2023-06-22 12:14 UTC, merged