Adds 'docker for desktop' support to local seed setup
gardener/gardener pull request #817
Opened 2019-03-13 14:37 UTC by plkokanov

**What this PR does / why we need it**:
Adds support for docker for desktop to the dev-setup-local script.
 
**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
The kubernetes apiserver is additionally exposed with a service of type NodePort to keep the local seed setup logic simpler and similar to the setup for minikube.

**Release note**:
None

2019-03-13 22:16 UTC, ialidzhikov requested changes
Thank you for this PR!

- In local_setup.md we have:

This setup is based on [minikube](https://github.com/kubernetes/minikube), a Kubernetes cluster running on a single node. 

Could you please change to:
This setup is based on [minikube](https://github.com/kubernetes/minikube), a Kubernetes cluster running on a single node. [kind](https://github.com/kubernetes-sigs/kind) and [Docker Desktop](https://www.docker.com/products/docker-desktop) are also supported.

- From the local_setup.md instructions:

```bash
$ sed -e 's/Logging: true/Logging: false/g' -i dev/20-componentconfig-gardener-controller-manager.yaml
sed: -i may not be used with stdin
```

Could you please also change to:
```
$ sed -i -e 's/Logging: true/Logging: false/g' dev/20-componentconfig-gardener-controller-manager.yaml
```

- I am not sure why I don't have this service. Shouldn't we fail when it is missing?

```
$ make dev-setup-local
Found Docker Kubernetes ...
Error from server (NotFound): services "kube-apiserver-docker-desktop" not found
namespace/garden-dev unchanged
project.garden.sapcloud.io/dev created
[...]
```

- With Docker for Mac Stable for seed local I receive condition:

```
message: 'Get https://192.168.1.3/api?timeout=32s: dial tcp 192.168.1.3:443: connect:
  operation timed out'
reason: K8SVersionTooOld
status: "False"
type: Available
```

Do I need to install Docker for Mac Edge to make it work?

2019-03-14 06:42 UTC, timuthy commented on example/50-seed-local.yaml
> +  ingressDomain: <local-kubernetes-ip>.nip.io
Please change this in `hack/templates/resources/50-seed.yaml.tpl` because these examples are rendered by running `hack/generate-examples`.

2019-03-14 06:42 UTC, timuthy commented on example/90-shoot-local.yaml
> +    domain: <local-kubernetes-ip>.nip.io
Please change this in `hack/templates/resources/90-shoot.yaml.tpl` because these examples are rendered by running `hack/generate-examples`.

2019-03-14 08:23 UTC, vpnachev requested changes
Thanks!

2019-03-14 08:23 UTC, vpnachev commented on hack/dev-setup-local
> +      kubectl -n kube-system expose pod ${_docker_kube_apiserver_service} --type=NodePort --name=kube-apiserver-docker-desktop --port=${_docker_api_server_secure_port} &>/dev/null
```suggestion
      kubectl -n kube-system expose pod ${_docker_kube_apiserver_service} --type=NodePort --name=${_docker_kube_apiserver_service} --port=${_docker_api_server_secure_port} &>/dev/null
```

2019-03-14 08:23 UTC, vpnachev commented on hack/dev-setup-local
> +  kubectl config view --raw -o jsonpath="{.users[?(.name == \"${_docker_user}\")].user.client-certificate-data}" | base64 -d > ${_cert}
Maybe `--flatten` flag should be used as well. This is useful when the certificates and keys are stored in separate files. `--flatten` will put the content of these files in the config output.
To be clear, I propose
`kubectl config view --raw -o ...`  to be 
`kubectl config view --raw --flatten -o ...`

2019-03-14 08:23 UTC, vpnachev commented on hack/dev-setup-local
> +env="$(k8s_env)"
`env` is a command name.
change it to something other.

2019-03-14 08:23 UTC, vpnachev commented on hack/dev-setup-local
> +case "$env" in
do not forget to rename `env` here

2019-03-14 08:23 UTC, vpnachev commented on hack/dev-setup-local
> +        echo "Unsupported k8s environment for local seed: ${env}"
do not forget to rename `env` here

2019-03-14 08:23 UTC, plkokanov commented
Hello @ialidzhikov and thanks for the review.

- I will add Docker for Desktop/Mac Edge support to the documentation
- As for the `sed` command in the [local_setup.md] instructions - it works for me. Do you have gnu-sed installed and configured to be used instead of the MacOS sed? 
- I am using Docker for Mac Edge where the kubernetes version is 1.13. The kubernetes version in Docker for Mac is 1.10 (I think).

2019-03-14 10:47 UTC, ialidzhikov requested changes
- `sed -i [...]` works for both sed and gsed, so I would prefer to have:
```
$ sed -i -e 's/Logging: true/Logging: false/g' dev/20-componentconfig-gardener-controller-manager.yaml
```

- It worked quite well with edge version. Nice!

2019-03-14 10:47 UTC, ialidzhikov commented on hack/dev-setup-local
> +  local _key=${2}
You could unify the indentation - 2 vs 4 spaces.

2019-03-14 15:00 UTC, ialidzhikov submitted a review, later dismissed
/lgtm, could you please squash to single commit?

2019-03-14 16:43 UTC, vpnachev submitted a review, later dismissed
/lgtm

2019-03-15 09:11 UTC, vpnachev requested changes
I have found something today that should be investigated a bit further.
The kubeconfig for the  `local` seed  does not embed the `certificate-authority`, hence if you deploy GCM inside k8s cluster, then this controller manager cannot read the file `/home/user/.minikube/ca.crt` for example.

2019-03-15 09:24 UTC, vpnachev requested changes

2019-03-15 09:24 UTC, vpnachev commented on hack/dev-setup-local
> +  --embed-certs=false
This should be `--embed-certs=true` for `minikube` and `--embed-certs=false` for `docker for desktop`

2019-03-18 07:30 UTC, rfranzke approved these changes
/lgtm

2019-03-18 07:41 UTC, vpnachev approved these changes
lgtm

2019-03-18 07:42 UTC, merged