Release responsible schedule for v1.79 until v1.87
gardener/gardener pull request #8226
Opened 2023-07-12 11:00 UTC by rfranzke

**How to categorize this PR?**

/area delivery
/kind enhancement

**What this PR does / why we need it**:
Extends the docs with a proposal for the release responsible schedule for v1.79 until v1.87

**Release note**:

```other operator
NONE
```

2023-07-12 11:07 UTC, ary1992 commented
/lgtm

2023-07-12 12:07 UTC, ScheererJ requested changes

2023-07-12 12:07 UTC, ScheererJ commented on docs/development/process.md
> +v1.80   | Week 37-38  | September 11, 2023     | September 24, 2023 | [@shafeeqes](https://github.com/shafeeqes)       |
```suggestion
v1.79   | Week 35-36  | August 28, 2023        | September 10, 2023 | [@shafeeqes](https://github.com/shafeeqes)       |
v1.80   | Week 37-38  | September 11, 2023     | September 24, 2023 | [@ScheererJ](https://github.com/ScheererJ)       |
```

2023-07-12 12:09 UTC, ScheererJ reviewed
/lgtm

2023-07-12 13:27 UTC, oliver-goetz commented
/lgtm

/retest

2023-07-12 14:17 UTC, timuthy reviewed
/lgtm

2023-07-12 14:34 UTC, rfranzke commented
Feedback missing from
/cc @plkokanov @ialidzhikov

2023-07-12 14:42 UTC, plkokanov commented
/lgtm

2023-07-12 16:42 UTC, shafeeqes reviewed
/lgtm

2023-07-13 05:50 UTC, acumino reviewed
/lgtm

2023-07-25 07:34 UTC, ialidzhikov approved these changes

2023-07-25 08:51 UTC, shafeeqes commented
/test pull-gardener-integration

2023-07-25 10:12 UTC, merged