Split `make generate` targets
gardener/gardener pull request #8289
Opened 2023-08-02 10:50 UTC by shafeeqes

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR splits the `generate` target based on the targets, ie; WHAT to run, and the MODE ie; "parallel" or "sequential", and WHICH folder to run the targets for.

For detailed steps, you can run `make generate PRINT_HELP=y`, This info is also printed with every generate command.
```
$ make generate WHAT="manifests protobuf" WHICH="extensions charts" MODE="sequential"

For more info on the generate command, Run 'make generate PRINT_HELP=y'
> Generate
```

```
$ make generate PRINT_HELP=y

# Usage: make generate [WHAT="<targets>"] [MODE="<mode>"] [WHICH="<folders>"]
#
# Options:
#   WHAT   - Specify the targets to run (e.g., "protobuf codegen manifests logcheck gomegacheck monitoring-docs")
#   WHICH  - Specify which folders to run the "manifests" target in, not applicable for other targets (e.g., "charts cmd example extensions pkg plugin test")
#   MODE   - Specify the mode for the 'manifests' target (e.g., "sequential" or "parallel")
#
# Examples:
#   make generate
#   make generate WHAT="codegen protobuf"
#   make generate WHAT="codegen protobuf" MODE="sequential"
#   make generate WHAT="manifests" WHICH="pkg plugin" MODE="sequential"
#
```

**Which issue(s) this PR fixes**:
Fixes part of #6016

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-08-02 10:51 UTC, seshachalam-yv commented
/assign

2023-08-02 12:24 UTC, rfranzke commented on hack/generate-sequential.sh
> +# Copyright 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
2023

2023-08-03 15:23 UTC, seshachalam-yv requested changes

2023-08-03 15:23 UTC, seshachalam-yv commented on hack/generate.sh
> +MODE="paralell"
```suggestion
MODE="parallel"
```

2023-08-03 15:23 UTC, seshachalam-yv commented on hack/generate.sh
> +        fi
```suggestion
        WHAT="${1:-$WHAT}"
```

2023-08-03 15:23 UTC, seshachalam-yv commented on hack/generate.sh
> +        fi
```suggestion
        WHICH="${1:-$WHICH}"
```

2023-08-03 15:23 UTC, seshachalam-yv commented on hack/generate.sh
> +  done
```suggestion
  local which="$1"
  IFS=' ' read -ra entries <<< "$which"
  for entry in "${entries[@]}"; do
    which=${which//$entry/./$entry/...}
  done
  echo "$which"
```

2023-08-03 15:23 UTC, seshachalam-yv commented on hack/generate.sh
> +}
```suggestion
run_target() {
  local target=$1
  local which=$2
  case "$target" in
    protobuf)
      $REPO_ROOT/hack/update-protobuf.sh
      ;;
    codegen)
      $REPO_ROOT/hack/update-codegen.sh
      ;;
    manifests)
      if [[ "$MODE" == "sequential" ]]; then
        # In sequential mode, paths need to be converted to go package notation (e.g., ./charts/...)
        which=$(overwrite_paths "$which")
        $REPO_ROOT/hack/generate-sequential.sh $which
      else
        $REPO_ROOT/hack/generate-parallel.sh $which
      fi
      ;;
    logcheck)
      cd "$REPO_ROOT/$LOGCHECK_DIR" && go generate ./...
      ;;
    gomegacheck)
      cd "$REPO_ROOT/$GOMEGACHECK_DIR" && go generate ./...
      ;;
    monitoring-docs)
      $REPO_ROOT/hack/generate-monitoring-docs.sh
      ;;
    *)
      echo "Unknown target: $target. Available targets are 'protobuf', 'codegen', 'manifests', 'logcheck', 'gomegacheck', 'monitoring-docs'."
      exit 1
      ;;
  esac
}
```

2023-08-03 15:23 UTC, seshachalam-yv commented on hack/generate.sh
> +  run_target "$target"
```suggestion
IFS=' ' read -ra TARGETS <<< "$WHAT"
for target in "${TARGETS[@]}"; do
  run_target "$target" "$WHICH"
```

2023-08-04 08:17 UTC, shafeeqes commented
/retest

2023-08-04 08:58 UTC, seshachalam-yv approved these changes
Thanks @shafeeqes for addressing my review comments.
/lgtm

2023-08-04 09:27 UTC, seshachalam-yv commented
/approve

2023-08-08 07:19 UTC, oliver-goetz commented
thanks 😄 

/approve

2023-08-08 08:07 UTC, merged