Drop deprecated `node-local-dns` annotations
gardener/gardener pull request #8364
Opened 2023-08-17 09:44 UTC by acumino

**How to categorize this PR?**

/area networking
/kind cleanup

**What this PR does / why we need it**:
This PR drops the deprecated `node-local-dns` annotation.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/7581

**Special notes for your reviewer**:

**Release note**:

```breaking user
Deprecated annotation `alpha.featuregates.shoot.gardener.cloud/node-local-dns` is removed. Use field `.spec.systemComponents.nodeLocalDNS.enabled` in `Shoot` instead. Switching on node-local-dns via shoot specification will roll the nodes even if node-local-dns was enabled beforehand via annotation.
```
```breaking user
Deprecated annotation `alpha.featuregates.shoot.gardener.cloud/node-local-dns-force-tcp-to-{cluster-dns, upstream-dns}` is removed. Use field `.spec.systemComponents.nodeLocalDNS.{forceTCPToClusterDNS, forceTCPToUpstreamDNS}` in `Shoot` instead.
```

2023-08-17 12:15 UTC, ScheererJ requested changes
Thanks for the change. I think that we should not change the default behaviour if the option is not specified.

2023-08-17 12:15 UTC, ScheererJ commented on pkg/apis/core/v1beta1/helper/helper_test.go
> +		Entry("with system components and node-local-dns is disabled", &gardencorev1beta1.SystemComponents{NodeLocalDNS: &gardencorev1beta1.NodeLocalDNS{Enabled: true}}, true),
```suggestion
		Entry("with system components and node-local-dns is enabled", &gardencorev1beta1.SystemComponents{NodeLocalDNS: &gardencorev1beta1.NodeLocalDNS{Enabled: true}}, true),
```

2023-08-17 12:15 UTC, ScheererJ commented on pkg/apis/core/v1beta1/helper/helper_test.go
> +		Entry("with system components is enabled", &gardencorev1beta1.SystemComponents{NodeLocalDNS: &gardencorev1beta1.NodeLocalDNS{Enabled: false}}, false),
```suggestion
		Entry("with system components and node-local-dns is disabled", &gardencorev1beta1.SystemComponents{NodeLocalDNS: &gardencorev1beta1.NodeLocalDNS{Enabled: false}}, false),
```

2023-08-17 12:15 UTC, ScheererJ commented on pkg/component/nodelocaldns/nodelocaldns.go
> +	if c.values.Config != nil && c.values.Config.ForceTCPToClusterDNS != nil && *c.values.Config.ForceTCPToClusterDNS {
Please revert the logic here. We should not change the default, i.e. without specifying the option it should force tcp.

2023-08-17 12:15 UTC, ScheererJ commented on pkg/component/nodelocaldns/nodelocaldns.go
> +	if c.values.Config != nil && c.values.Config.ForceTCPToUpstreamDNS != nil && *c.values.Config.ForceTCPToUpstreamDNS {
Same as above.

2023-08-18 13:15 UTC, ialidzhikov commented on extensions/pkg/controller/worker/machines.go
>  	// Do not consider the shoot annotations here to prevent unintended node roll-outs.
This comment can be now removed - no Shoot annotation, nothing to be considered.
```suggestion
```

2023-08-18 13:15 UTC, ialidzhikov commented on pkg/apis/core/v1beta1/helper/helper.go
>  }
Can be simplified such as:

```suggestion
func IsNodeLocalDNSEnabled(systemComponents *gardencorev1beta1.SystemComponents) bool {
	return systemComponents != nil && systemComponents.NodeLocalDNS != nil && systemComponents.NodeLocalDNS.Enabled
}
```

2023-08-21 06:16 UTC, ialidzhikov reviewed
/lgtm

2023-08-21 07:01 UTC, ScheererJ approved these changes
/lgtm
/approve

2023-08-21 08:10 UTC, merged