Remove usage of initializers and adapt PV-labelling logic to prepare for K8s 1.14
gardener/gardener pull request #838
Opened 2019-03-19 14:00 UTC by rfranzke

**What this PR does / why we need it**:
Due to kubernetes/kubernetes#72972 the alpha `Initializers` feature will be entirely removed with Kubernetes 1.14. We are currently relying on it as the cloud-controller-manager uses it to label persistent volumes before they become visible in the API.
This functionality is also removed (see kubernetes/kubernetes#73102) with 1.14.
As a consequence, in order to use PV labelling until the community has migrated all CCMs to use `MutatingWebhookConfiguration`s for that, the only way is to enable the (already deprecated) `PersistentVolumeLabel` admission controller in the kube-apiserver.
That means that the kube-apiserver needs to talk to the cloud provider to figure out the region/zone of the PV (and later add them as label).
--> We have to provide the cloud credentials + config to the API server in this case.

Shoot clusters with Kubernetes version < 1.14 still have an enabled initializer feature.

**Special notes for your reviewer**:
The kube-apiserver does now talk to the cloud provider to figure out information about created PVs. However, it **does not** use the cloud's metadata service but its public API. We don't have to change our network policy preventing the kube-apiserver's from accessing the metadata service.

/cc @marwinski @ThormaehlenFred 

**Release note**:

```noteworthy operator
Due to the fact that the `Initializer` feature is entirely dropped with Kubernetes 1.14 Gardener does now no longer rely on it. It was used to enable the cloud-controller-manager for labelling created PVs. This is now done by the `PersistentVolumeLabel` admission controller inside the kube-apiserver. Consequently, the kube-apiserver does now have information about the cloud (credentials/config).
```

2019-03-19 14:40 UTC, mvladev commented
What removes existing deployed resources - controller, mutatingwebhooks and so?

I would suggest to keep the templates and use them to do clean up. After 1 or more release we can remove them as well.

2019-03-19 14:42 UTC, rfranzke commented
Which concrete existing deployed resources are you referring to?

2019-03-19 14:45 UTC, mvladev commented
Those 2:
https://github.com/gardener/gardener/blob/0949217791253338d1a908840b85c3656c6135e9/charts/shoot-core/charts/cloud-controller-manager/templates/rbac-pvl-controller.yaml
https://github.com/gardener/gardener/blob/0949217791253338d1a908840b85c3656c6135e9/charts/shoot-core/charts/cloud-controller-manager/templates/webhook-gardener-add-initializer.yaml

2019-03-19 14:47 UTC, rfranzke commented
Not needed. kube-addon-manager will take care removing them.

2019-03-19 14:50 UTC, mvladev commented
Oh yes - they are deployed in the Shoot. What about:
https://github.com/gardener/gardener/blob/0949217791253338d1a908840b85c3656c6135e9/charts/seed-bootstrap/templates/gardener-external-admission-controller.yaml

2019-03-19 14:55 UTC, rfranzke commented
https://github.com/gardener/gardener/pull/838/files#diff-5ca37df1e48dc263572bf7822db58a8aR339

2019-03-20 09:58 UTC, timuthy requested changes

2019-03-20 09:58 UTC, timuthy commented on pkg/client/kubernetes/admissionplugins_test.go
> +			plugins := GetAdmissionPluginsForVersion("1.11.23")
```suggestion
			plugins := GetAdmissionPluginsForVersion("1.14.0")
```

2019-03-20 10:11 UTC, timuthy submitted a review, later dismissed
/lgtm

2019-03-22 14:22 UTC, adracus commented
/lgtm

2019-03-22 14:22 UTC, adracus approved these changes

2019-03-25 08:24 UTC, merged