bug() #844 Changed PLEG log counting
gardener/gardener pull request #845
Opened 2019-03-20 17:36 UTC by fsniper

**What this PR does / why we need it**:
This is fixing where health-monitor is using a duplicate hyperkube log for restarts.

**Which issue(s) this PR fixes**:
Fixes #844 

**Release note**:
```category operator
This fixes bug #844 which can cause shoot node reboot loops.
```

2019-03-21 09:05 UTC, timuthy requested changes
Thank you very much.

I just have a small comment.

2019-03-21 09:05 UTC, timuthy commented on charts/seed-operatingsystemconfig/original/templates/scripts/_health-monitor.sh
> +            if count_pleg_not_healthy="$(journalctl --since="$(date --date '-10min' "+%Y-%m-%d %T")" -u kubelet | grep "PLEG is not healthy" | cut -f3 -d' '| cut -f2 -d':' | sort | uniq | wc -l)"; th
Please add a comment with an example output of the Kubelet log and that this command only counts the an occurrence per minute.

2019-03-21 09:29 UTC, timuthy commented
As a consequence, it'll take longer to restart the node (10 mins) in case `PLEG` is permanently unhealthy. So maybe we should also decrease the event count [threshold](https://github.com/gardener/gardener/blob/6722ff4ef98a66fa88e07b81a59412eeee4535fa/charts/seed-operatingsystemconfig/original/templates/scripts/_health-monitor.sh#L133).

WDYT @rfranzke, @fsniper?

2019-03-21 10:42 UTC, fsniper commented
Oh @timuthy , you are absolutely right. 

In fact, this is looking for last 10 minutes and if we are counting different minutes, this means we need to have a log for every minute. hyperkube is supposed to log 3 minutes apart. Even though it's logging duplicates - probably -  meaning, we will never hit this. I am thinking to change this to 5. This will likely come down to 3 real logs in the last 10 minutes.

2019-03-22 07:26 UTC, timuthy commented
As far as I see it, the [3 minutes](https://github.com/kubernetes/kubernetes/blob/release-1.13/pkg/kubelet/pleg/generic.go#L142) are only considered in the beginning as a threshold (i.e. `relistTime` is not reset).
After this threshold has been exceeded the `PLEG is not healthy` log it printed in a maximum of [5 seconds interval](https://github.com/kubernetes/kubernetes/blob/release-1.13/pkg/kubelet/kubelet.go#L1828) to the log.

Eventually, we will reach the limit of 10 entires but it'll also take 10 mins to make the affected worker restart.

2019-03-25 14:04 UTC, fsniper commented
This part of the check will be removed. This is decided on #844 . Closing this PR

2019-03-25 14:04 UTC, closed without merging