Support for Kubernetes v1.28
gardener/gardener pull request #8479
Opened 2023-09-13 20:23 UTC by oliver-goetz

**How to categorize this PR?**

/area open-source
/kind enhancement

**What this PR does / why we need it**:
Support for Kubernetes v1.28.

**Which issue(s) this PR fixes**:
Part of #8291

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2023-09-15 04:09 UTC, shafeeqes commented on pkg/utils/version/version.go
> +	ConstraintK8sLess128 *semver.Constraints
This is not used anywhere; do we need this? We can always add when we need it.

2023-09-15 07:44 UTC, shafeeqes reviewed
/lgtm

2023-09-18 11:34 UTC, ScheererJ requested changes
Thanks for the change. It looks good overall.

Are the empty commits "just" markers so that the next developer working on Kubernetes v1.29 support knows what to do?

2023-09-18 11:34 UTC, ScheererJ commented on pkg/component/shootsystem/shootsystem.go
> +	if versionutils.ConstraintK8sGreaterEqual128.Check(s.values.Shoot.KubernetesVersion) {
Should we not add a test for this similar to what we did in https://github.com/gardener/gardener/pull/7275/commits/ff962d055de9c84b767fa347d32f094e43f84b92?

2023-09-18 12:30 UTC, rfranzke commented on pkg/component/shootsystem/shootsystem.go
> +			"validatingadmissionpolicy-status-controller")
Did you check whether they really appear in the `kube-system` namespace as `ServiceAccount`s?

2023-09-18 12:30 UTC, rfranzke commented on pkg/component/shootsystem/shootsystem.go
> +			"validatingadmissionpolicy-status-controller")
```suggestion
			"validatingadmissionpolicy-status-controller",
		)
```

2023-09-18 13:59 UTC, oliver-goetz commented on pkg/component/shootsystem/shootsystem.go
> +			"validatingadmissionpolicy-status-controller")
Yes, when `LegacyServiceAccountTokenCleanUp` feature gate is activated for `kube-controller-manager` `legacy-service-account-token-cleaner` appears.
When `ValidatingAdmissionPolicy` feature gates is activated for `kube-controller-manager` and `admissionregistration.k8s.io/v1beta1` runtime config in `kube-apiserver` is activated `validatingadmissionpolicy-status-controller` appears.

2023-09-18 14:00 UTC, rfranzke commented on pkg/component/shootsystem/shootsystem.go
> +			"validatingadmissionpolicy-status-controller")
Great, thank you :)

2023-09-18 14:07 UTC, oliver-goetz commented on pkg/component/shootsystem/shootsystem.go
> +			"validatingadmissionpolicy-status-controller")
Why not `legacy-service-account-token-cleaner`?

2023-09-18 17:28 UTC, oliver-goetz commented on pkg/component/shootsystem/shootsystem.go
> +			"validatingadmissionpolicy-status-controller")
Ah, you just want me to create a line break right? 😄

2023-09-19 04:36 UTC, acumino commented
/assign

2023-09-19 07:18 UTC, ScheererJ reviewed
/lgtm

2023-09-19 08:49 UTC, acumino reviewed
Had a look together with @dimitar-kostadinov, PR looks good, we also tested the creation and deletion of the shoot with workers in the provider-local setup. 

Probably [this](https://github.com/gardener/gardener/blob/ad64150e76a4b1c7dd2e474332db73e4bc391d7b/test/framework/resources/templates/vpntunnel-copy.yaml.tpl#L31-L32) TODO can be addressed now.

From the 1.28 release notes - 
- Support for cgroup v1 is removed. (Do we need some changes for it?)
- Replaced `apiserver_storage_db_total_size_in_bytes` with `apiserver_storage_size_bytes` metric. (Can you adapt to this change?)

2023-09-19 11:10 UTC, oliver-goetz commented
> Had a look together with @dimitar-kostadinov, PR looks good, we also tested the creation and deletion of the shoot with workers in the provider-local setup.
> 
> Probably [this](https://github.com/gardener/gardener/blob/ad64150e76a4b1c7dd2e474332db73e4bc391d7b/test/framework/resources/templates/vpntunnel-copy.yaml.tpl#L31-L32) TODO can be addressed now.

I don't know what to do here tbh 😄  
The container to which the downloaded kubectl binary is mounted [sleeps](https://github.com/gardener/gardener/blob/ad64150e76a4b1c7dd2e474332db73e4bc391d7b/test/framework/resources/templates/vpntunnel-copy.yaml.tpl#L47-L49) and `registry.k8s.io/kubectl:v1.28.2` contains the kubectl binary only.

> 
> From the 1.28 release notes -
> 
> * Support for cgroup v1 is removed. (Do we need some changes for it?)

Afaik operators have to ensure in the cloud-profiles to combine Kubernetes v1.28 with cgroupv2 host OS only.
However, when I was checking for cgroup I found `KubeletCgroupDriverFromCRI` feature gate ([ref](https://github.com/kubernetes/kubernetes/pull/118770)) which I added to the operating system config

> * Replaced `apiserver_storage_db_total_size_in_bytes` with `apiserver_storage_size_bytes` metric. (Can you adapt to this change?)

done 👍

2023-09-19 16:06 UTC, acumino commented on pkg/component/kubeapiserver/monitoring.go
> +// TODO: The apiserver_storage_db_total_size_in_bytes metric is replaced by apiserver_storage_size_bytes in K8s 1.28 (https://github.com/kubernetes/kubernetes/pull/118812). Remove this metric when we
```suggestion
// TODO: The apiserver_storage_db_total_size_in_bytes metric is replaced by apiserver_storage_size_bytes in K8s 1.28 (https://github.com/kubernetes/kubernetes/pull/118812). Remove this metric when we remove support for K8s 1.27.
```

2023-09-19 17:59 UTC, oliver-goetz commented on pkg/component/kubeapiserver/monitoring.go
> +// TODO: The apiserver_storage_db_total_size_in_bytes metric is replaced by apiserver_storage_size_bytes in K8s 1.28 (https://github.com/kubernetes/kubernetes/pull/118812). Remove this metric when we
I kept this in sync with the upstream deprecation strategy on this field ([ref](https://github.com/kubernetes/kubernetes/pull/118812#discussion_r1252607835)).

2023-09-20 07:14 UTC, rfranzke commented on pkg/component/shootsystem/shootsystem.go
> +			"validatingadmissionpolicy-status-controller")
Actually yes :D

2023-09-20 07:48 UTC, acumino reviewed
/lgtm

2023-09-20 08:20 UTC, rfranzke commented
/approve

2023-09-20 11:12 UTC, acumino commented
/retest-required

2023-09-20 12:33 UTC, merged