Update `MCM` related crds
gardener/gardener pull request #8491
Opened 2023-09-15 14:21 UTC by rishabh-11

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR updates the MCM related crds (machine, machinedeployment and machineset) to the latest ones. 

**Which issue(s) this PR fixes* 
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Update `machine`, `machinedeployment` and `machineset` crd, which introduces the `errorCode` field in the `lasOperation` struct as a part of the machine status.
```

2023-09-15 14:21 UTC, rishabh-11 commented
cc @himanshu-kun

2023-09-15 14:26 UTC, ialidzhikov requested changes

2023-09-15 14:26 UTC, ialidzhikov commented on pkg/component/machinecontrollermanager/templates/crd-machinedeployments.tpl.yaml
> -    gardener.cloud/deletion-protected: "true"
Revert this and similar removals of the `gardener.cloud/deletion-protected` label.

2023-09-15 14:48 UTC, rishabh-11 commented on pkg/component/machinecontrollermanager/templates/crd-machinedeployments.tpl.yaml
> -    gardener.cloud/deletion-protected: "true"
addressed in [41b62fc](https://github.com/gardener/gardener/pull/8491/commits/41b62fcdfc837b1b50815a56137615854350396b)

2023-09-15 16:18 UTC, rishabh-11 commented
make retest-required

2023-09-15 16:20 UTC, rishabh-11 commented
/retest-required

2023-09-15 16:31 UTC, himanshu-kun approved these changes
/lgtm , minor suggestions made

2023-09-15 16:31 UTC, himanshu-kun commented on pkg/component/machinecontrollermanager/templates/crd-machinesets.tpl.yaml
> +  creationTimestamp: null
```suggestion
```

2023-09-15 16:31 UTC, himanshu-kun commented on pkg/component/machinecontrollermanager/templates/crd-machinedeployments.tpl.yaml
> +  creationTimestamp: null
```suggestion
```

2023-09-15 16:31 UTC, himanshu-kun commented on pkg/component/machinecontrollermanager/templates/crd-machines.tpl.yaml
> +  creationTimestamp: null
```suggestion
```

2023-09-18 04:50 UTC, himanshu-kun reviewed
/lgtm from my side

2023-09-18 05:23 UTC, rishabh-11 commented
/retest-required

2023-09-18 11:25 UTC, ialidzhikov commented
@rishabh-11 @himanshu-kun I pushed d0c25f427f8ff7a4ca1effb30eff55e7add77d19 to add a source information from where the MCM CRDs are actually maintained. This is similar to the etcd-druid CRDs (ref https://github.com/gardener/gardener/blob/ebda2b53e4b4e8893bfbbbb6510a4654c93ffdb7/pkg/component/etcd/crds/templates/crd-druid.gardener.cloud_etcds.yaml#L1) and VPA CRDs (https://github.com/gardener/gardener/blob/498403ac7be3f528d51e3647882155414f22289e/pkg/component/vpa/templates/crd-verticalpodautoscalers.tpl.yaml#L2).

2023-09-18 11:25 UTC, ialidzhikov commented
/approve

2023-09-19 06:49 UTC, ialidzhikov commented
That's the reason for the test failures - see https://github.com/gardener/gardener/pull/7599#issuecomment-1458311520. 
I think we have to first update out machine-controller-manager-provider-local to vendor newer MCM and to no longer rely on the `.status.node` field.

2023-09-20 08:09 UTC, rfranzke commented
Please adapt https://github.com/gardener/gardener/blob/32c069f46a072f492e4e14c335d63337cb419da8/pkg/provider-local/imagevector/images.yaml#L2-L9 now that https://github.com/gardener/machine-controller-manager-provider-local/pull/18 got merged (new image is `ghcr.io/gardener/machine-controller-manager-provider-local:sha-8e34e10`).

2023-09-20 08:24 UTC, rfranzke commented
/lgtm

2023-09-20 10:04 UTC, merged