[node-agent] Introduce token `Secret` controller
gardener/gardener pull request #8629
Opened 2023-10-09 12:36 UTC by rfranzke

**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:
This PR introduces the token controller in `gardener-node-agent` whose main purpose is watching the access token `Secret` in the (shoot) cluster's `kube-system` namespace. Whenever it changes, it writes the new token to the disk. The kubeconfig points to the same file ([ref](https://github.com/gardener/gardener/pull/8627/files#diff-55fb15b9da09f83f4983b2003c189b5e2ad4d71afb010bbf61f97dfe1a0b8fcfR210)).

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/8023

**Special notes for your reviewer**:
- [ ] This PR depends on #8627 which needs to be merged, hence it remains in draft state until then. Relevant commits start after the "empty separator commit".

**Release note**:

```other operator
NONE
```

2023-10-09 19:11 UTC, rfranzke commented
/cc @oliver-goetz

2023-10-10 09:19 UTC, plkokanov requested changes
Overall looks good. I just saw a couple nits.

2023-10-10 09:19 UTC, plkokanov commented on pkg/nodeagent/controller/token/reconciler.go
> +		return reconcile.Result{}, fmt.Errorf("secret key %q does not exist or empty", resourcesv1alpha1.DataKeyToken)
Nit:
```suggestion
		return reconcile.Result{}, fmt.Errorf("secret key %q does not exist or is empty", resourcesv1alpha1.DataKeyToken)
```

2023-10-10 09:19 UTC, plkokanov commented on test/integration/nodeagent/token/token_test.go
> +		Expect(err).To(MatchError(ContainSubstring("file does not exist")))
Isn't there a chance that the reconciliation runs really quickly before this check i executed?

2023-10-10 09:19 UTC, plkokanov commented on docs/concepts/node-agent.md
> +Since the underlying client is based on `k8s.io/client-go` and the kubeconfig points to this token file, it is dynamically reloaded without further doing.
```suggestion
Since the underlying client is based on `k8s.io/client-go` and the kubeconfig points to this token file, it is dynamically reloaded without further processing.
```
Although I'm not exactly sure what you meant with 'doing' here :sweat_smile:

2023-10-10 10:20 UTC, rfranzke commented on test/integration/nodeagent/token/token_test.go
> +		Expect(err).To(MatchError(ContainSubstring("file does not exist")))
You're right, I guess it could happen. I removed this since there is not much benefit in asserting this anyways. Thanks.

2023-10-10 16:41 UTC, plkokanov commented
/lgtm

2023-10-12 12:28 UTC, rfranzke commented
ping @oliver-goetz

2023-10-12 15:17 UTC, oliver-goetz commented
/assign

2023-10-12 16:01 UTC, oliver-goetz commented
awesome 😄 
/lgtm
/approve

2023-10-12 17:25 UTC, oliver-goetz commented
/retest

2023-10-12 19:55 UTC, merged