Set Default Delta Snapshot Retention Period to 15 Days
gardener/gardener pull request #8659
Opened 2023-10-17 10:43 UTC by seshachalam-yv

This commit sets a default retention period of 15 days for delta snapshots in the Gardener ETCD component to aid in debugging efforts. The retention period ensures that delta snapshots are available for a longer period, providing a sufficient window for reviewing changes in case of issues.

**How to categorize this PR?**

/area backup
/kind enhancement

**What this PR does / why we need it**:
This PR sets a default retention period of 15 days for delta snapshots in the Gardener ETCD component. The extended retention period will assist in debugging efforts by ensuring that delta snapshots are available for a longer period, providing a sufficient window for reviewing changes in case of issues.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
Introduced a default retention period of 15 days for delta snapshots in the Gardener ETCD component to aid in debugging efforts.
```

2023-10-17 10:48 UTC, rfranzke reviewed
Shouldn't this value be configurable and not hard-coded?

2023-10-17 13:41 UTC, seshachalam-yv commented
> Shouldn't this value be configurable and not hard-coded?

Not required to be configurable, something like `Spec.Backup.DeltaSnapshotPeriod` . Hardcoded value is okay.

2023-10-18 04:08 UTC, seshachalam-yv commented
/hold

2023-11-03 10:21 UTC, seshachalam-yv commented
> > > Shouldn't this value be configurable and not hard-coded?
> > 
> > 
> > Not required to be configurable, something like `Spec.Backup.DeltaSnapshotPeriod` . Hardcoded value is okay.
> 
> I don't agree. The PR description talks about "The extended retention period will assist in debugging efforts". This doesn't justify a hard-coded value and your comparison is wrong/invalid. I'm fine to not make it configurable per `Etcd` resource, but at least centrally per seed (via the etcd config in the gardenlet's component config).


Thank you @rfranzke for your review and suggestion. I have made the necessary adjustments to address your review comments to make it configurable `DeltaSnapshotRetentionPeriod`.

The PR title and description have been updated to accurately reflect the introduction of the `DeltaSnapshotRetentionPeriod` configuration in the `ETCDConfig` section of the `GardenletConfiguration`.

/unhold

2023-11-03 15:19 UTC, timuthy requested changes

2023-11-03 15:19 UTC, timuthy commented on pkg/operation/botanist/etcd.go
> +		var deltaSnapshotRetentionPeriod *metav1.Duration
```suggestion
		var (
	        	backupLeaderElection *config.ETCDBackupLeaderElection
			deltaSnapshotRetentionPeriod *metav1.Duration
		)
```

2023-11-03 15:19 UTC, timuthy commented on pkg/component/etcd/etcd.go
> +	DeltaSnapshotRetentionPeriod *metav1.Duration
```suggestion
	// DeltaSnapshotRetentionPeriod defines the duration for which delta snapshots will be retained, excluding the latest snapshot set.
	DeltaSnapshotRetentionPeriod *metav1.Duration
```

2023-11-03 15:25 UTC, timuthy requested changes
Can you please enhance `example/20-componentconfig-gardenlet.yaml`?

2023-11-06 07:51 UTC, rfranzke reviewed
/lgtm

2023-11-06 20:03 UTC, timuthy reviewed
/lgtm
/approve

2023-11-06 21:32 UTC, merged