Block new incoming connections to seed cluster from vpn tunnel
gardener/gardener pull request #874
Opened 2019-03-27 15:35 UTC by DockToFuture

**What this PR does / why we need it**:
Set iptable rule to block new incoming connections from shoot cluster.
**Which issue(s) this PR fixes**:
Fixes: https://github.com/gardener/vpn/issues/40

**Special notes for your reviewer**:

**Release note**:

```improvement operator
```

2019-03-27 15:46 UTC, rfranzke commented
Can you elaborate what exactly happens here? What is blocked, etc.?

2019-03-27 17:02 UTC, zanetworker commented
Do we really want to block all traffic to the API server? There are things that needs to talk to the API server still e.g., Kube-proxy, kubelet, ...etc

2019-03-28 07:08 UTC, rfranzke requested changes

2019-03-28 07:08 UTC, rfranzke commented on charts/seed-controlplane/charts/kube-apiserver/templates/kube-apiserver.yaml
> +        image: alpine:3.8
Don't hard-code this, we have it in our [`images.yaml`](https://github.com/gardener/gardener/blob/master/charts/images.yaml#L139-L141).

2019-03-28 07:08 UTC, rfranzke commented on charts/seed-monitoring/charts/prometheus/templates/prometheus.yaml
> +        image: alpine:3.8
Don't hard-code this, we have it in our [`images.yaml`](https://github.com/gardener/gardener/blob/master/charts/images.yaml#L139-L141).

2019-03-28 08:03 UTC, rfranzke requested changes
You have to add `alpine` to list of injected images during deployment, e.g. https://github.com/gardener/gardener/blob/master/pkg/operation/hybridbotanist/controlplane.go#L379 for kube-apiserver (similar for prometheus).

2019-03-28 11:49 UTC, rfranzke approved these changes
/lgtm

2019-03-28 12:42 UTC, zanetworker commented
/lgtm

2019-03-28 12:42 UTC, zanetworker approved these changes
/lgtm

2019-03-28 13:35 UTC, merged