Fix alicloud metadata reachability and adapt integration test
gardener/gardener pull request #875
Opened 2019-03-27 15:39 UTC by schrodit

**What this PR does / why we need it**:
This PR fixes the reachability of the metadata service in alicloud

**Release note**:

```improvement operator
Fix alicloud metadata service reachability
```

2019-03-27 15:45 UTC, zanetworker requested changes

2019-03-27 15:45 UTC, zanetworker commented on test/integration/shoots/applications/shoot_app_test.go
> +		FCIt("should block traffic to the metadataservice", func(ctx context.Context) {
remove the focus here.

2019-03-27 15:45 UTC, zanetworker commented on test/integration/shoots/applications/shoot_app_test.go
> +			fmt.Println(cloudProvider)
can you remove this line?

2019-03-27 15:47 UTC, schrodit commented on test/integration/shoots/applications/shoot_app_test.go
> +		FCIt("should block traffic to the metadataservice", func(ctx context.Context) {
done

2019-03-27 15:47 UTC, schrodit commented on test/integration/shoots/applications/shoot_app_test.go
> +			fmt.Println(cloudProvider)
done

2019-03-27 16:17 UTC, zanetworker commented
/lgtm

2019-03-27 16:17 UTC, zanetworker submitted a review, later dismissed

2019-03-27 16:17 UTC, zanetworker commented
@jia-jerry can you please have a look?

2019-03-28 02:03 UTC, jia-jerry commented
> @jia-jerry can you please have a look?

Thanks for your fix. I need to do verification. There is a CSI plugin running in Shoot cluster. It needs to access meta data.

2019-03-28 07:17 UTC, rfranzke commented on charts/seed-controlplane/charts/kube-apiserver/templates/network-policy.yaml
> +        {{ if eq .Values.cloudProvider "alicloud" }}
```suggestion
        {{- if eq .Values.cloudProvider "alicloud" }}
```

2019-03-28 07:17 UTC, rfranzke commented on charts/seed-controlplane/charts/kube-apiserver/templates/network-policy.yaml
> +        {{ else }}
```suggestion
        {{- else }}
```

2019-03-28 07:17 UTC, rfranzke commented on charts/seed-controlplane/charts/kube-apiserver/templates/network-policy.yaml
> +        {{ end }}
```suggestion
        {{- end }}
```

2019-03-28 07:19 UTC, rfranzke commented
@jia-jerry Why are you writing this? The network policy only applies for pods in the seed, not in the shoot. AFAIK there is no CSI container running in the seed for Alicloud - I only see them in the shoot's `kube-system` namespace.

2019-03-28 07:26 UTC, jia-jerry commented
> @jia-jerry Why are you writing this? The network policy only applies for pods in the seed, not in the shoot. AFAIK there is no CSI container running in the seed for Alicloud - I only see them in the shoot's `kube-system` namespace.

You are right. The code change looks good to me.

2019-03-28 07:34 UTC, rfranzke commented
Thanks! Please squash, then we can merge it.

2019-03-28 07:50 UTC, schrodit commented
Squashed the commits.

2019-03-28 08:01 UTC, rfranzke approved these changes
/lgtm

2019-03-28 08:23 UTC, merged