add kubelet version and OS image version in node/worker pool overview dashboard
gardener/gardener pull request #8757
Opened 2023-11-03 05:42 UTC by tedteng

**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
add two graphs showing kubelet version and OS image version in node/worker pool overview dashboard. It helps users check version upgrades during the rolling update or the version status of nodes.

<img width="1807" alt="image" src="https://github.com/gardener/gardener/assets/42234376/57a69f2d-ca3d-4f0d-b733-bfdc74e4a176">
<img width="1499" alt="image" src="https://github.com/gardener/gardener/assets/42234376/a4e929ed-dbe2-4afd-b8d8-9b505b5d9e6d">

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
showing kubelet version and OS image version in Prometheus Node/Worker Pool overview dashboard
```

2023-11-06 07:45 UTC, rfranzke commented
/cc @istvanballok @rickardsjp

2023-11-07 23:57 UTC, tedteng commented
/retest

2023-11-14 05:24 UTC, tedteng commented
ping @istvanballok @rickardsjp

2023-11-20 23:59 UTC, tedteng commented
/retest-required

2023-11-22 13:57 UTC, istvanballok requested changes
There is a minor typo that the hard coded "All" value is used in the panel titles instead of the variable "worker_group", like for the other panels.

The release notes sentence:
```
showing kubelet version and OS image version in Prometheus Node/Worker Pool overview dashboard
```

could be slightly improved: Prometheus ... dashboard -> Plutono ... dashboard.

Otherwise, it looks good to me.

2023-11-22 13:57 UTC, istvanballok commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +      "title": "OS Image of Nodes in Worker Group(s) All",
```suggestion
      "title": "OS Image of Nodes in Worker Group(s) $worker_group",
```

2023-11-22 13:57 UTC, istvanballok commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +      "title": "Kubelet versions of nodes in Worker Group(s) All",
```suggestion
      "title": "Kubelet versions of nodes in Worker Group(s) $worker_group",
```

2023-11-22 13:57 UTC, istvanballok commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +}
maybe add a new line

2023-11-23 01:26 UTC, tedteng commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +      "title": "OS Image of Nodes in Worker Group(s) All",
7c78ef96a

2023-11-23 01:26 UTC, tedteng commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +      "title": "Kubelet versions of nodes in Worker Group(s) All",
7c78ef96a

2023-11-23 01:26 UTC, tedteng commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +}
7c78ef96a

2023-11-23 15:43 UTC, istvanballok approved these changes
/lgtm

2023-11-24 00:07 UTC, tedteng commented
/assign @timebertt

2023-11-24 07:25 UTC, timebertt commented
/approve

2023-11-24 08:13 UTC, merged