Updated clusterrole for CA
gardener/gardener pull request #8822
Opened 2023-11-16 09:23 UTC by sssash18

**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
This PR adds a addition to cluster role for CA.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-11-16 09:44 UTC, himanshu-kun requested changes
I think we can assign role instead of clusterrole for this. could you check if any role has already been created for CA where we could add this rule.
Also provide more context in the PR regarding the change , the CA issue link and provide a release note for `operator`

2023-11-16 09:44 UTC, himanshu-kun commented on pkg/component/clusterautoscaler/bootstrap.go
> +				},
kindly add a test case if there is for the already existing rules in `bootstrap_test.go`

2023-11-16 11:10 UTC, sssash18 commented
/test pull-gardener-e2e-kind

2023-11-16 14:07 UTC, rfranzke commented
/approve

2023-11-17 06:53 UTC, sssash18 commented
/retest

2023-11-17 12:31 UTC, rfranzke requested changes

2023-11-17 12:31 UTC, rfranzke commented on pkg/component/clusterautoscaler/bootstrap.go
> +		role = &rbacv1.Role{
I don't understand this `Role`. It would allow CA to read deployments in the `garden` namespace, but there is no CA running in this namespace.

2023-11-17 12:31 UTC, rfranzke commented
/approve cancel

2023-11-22 18:57 UTC, rfranzke commented
/cc @himanshu-kun 
Please review/approve. Can we merge this now?

2023-11-23 03:08 UTC, himanshu-kun approved these changes
/lgtm

2023-11-23 08:50 UTC, rfranzke reviewed
/approve

2023-11-23 10:13 UTC, merged