Prepare for removal of `.spec.secretRef` fields in the Seed
gardener/gardener pull request #8833
Opened 2023-11-17 12:58 UTC by acumino

**How to categorize this PR?**

/area control-plane
/kind api-change
/kind cleanup

**What this PR does / why we need it**:
https://github.com/gardener/gardener/pull/8064 deprecated field `seed.spec.secretRef`, as a subsequent step this PR drops the usage of `secretRef` and in the subsequent release, the field will be dropped from the API.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7597

**Special notes for your reviewer**:

**Release note**:

```breaking operator
All the functionality related to the deprecated field `seed.spec.secretRef` has been removed and subsequently `seed.spec.secretRef` will be dropped from the Seed API in a later release of Gardener. Please check your `Seed`s and remove any usage before upgrading to this Gardener version.
```

2023-11-20 04:41 UTC, shafeeqes commented
/assign

2023-11-21 10:12 UTC, plkokanov requested changes
With @dimitar-kostadinov we had a joint look at the PR. We generally have some minor comments.
We also have a question regarding the `seedmanagement.gardener.cloud/seed-secret-name` and `seedmanagement.gardener.cloud/seed-secret-namespace` annotations
We see that the logic behind them has generally been removed, however they are still present here: https://github.com/gardener/gardener/blob/69f2d8b40ddab2e1bf1ce0a887a64023c4866f44/pkg/admissioncontroller/webhook/auth/seed/graph/eventhandler_managedseed.go#L100-L104 
Is this code still necessary? 
If not, can we remove the constants used for the annotations as well: https://github.com/gardener/gardener/blob/69f2d8b40ddab2e1bf1ce0a887a64023c4866f44/pkg/apis/seedmanagement/v1alpha1/constants/types_constants.go#L22-L25

2023-11-21 10:12 UTC, plkokanov commented on plugin/pkg/global/resourcereferencemanager/admission_test.go
> +				Spec: core.SeedSpec{},
Nit: this is just the default `SeedSpec` struct so you could skip the explicit assignment.

2023-11-21 10:12 UTC, plkokanov commented on pkg/gardenlet/controller/managedseed/actuator.go
> +	var backupSecret *corev1.Secret
Nit 
```suggestion
	var (
		backupSecret *corev1.Secret
		err error
	)
```

2023-11-21 10:12 UTC, plkokanov commented on pkg/gardenlet/controller/managedseed/actuator.go
> +func (a *actuator) getSeedSecrets(ctx context.Context, spec *gardencorev1beta1.SeedSpec, managedSeed *seedmanagementv1alpha1.ManagedSeed) (*corev1.Secret, error) {
```suggestion
func (a *actuator) getBackupSecret(ctx context.Context, spec *gardencorev1beta1.SeedSpec, managedSeed *seedmanagementv1alpha1.ManagedSeed) (*corev1.Secret, error) {
```

2023-11-21 10:12 UTC, plkokanov commented on pkg/gardenlet/controller/managedseed/actuator.go
> -	if spec.SecretRef != nil {
Since this is removed the `deleteSeedSecrets` function only deletes the backup secret, could you rename the function to `deleteBackupSecret`?

2023-11-21 10:12 UTC, plkokanov commented on docs/concepts/gardenlet.md
> +    settings:
Quick q: did you add the `settings` field here just to have some additional fields in the example?

2023-11-22 09:40 UTC, acumino commented on docs/concepts/gardenlet.md
> +    settings:
Yes.

2023-11-27 06:54 UTC, shafeeqes commented on test/framework/gardener_utils.go
> +			// here we expect seed kubeconfig secret is created in Garden for testing
```suggestion
			// For tests, we expect the seed kubeconfig secret to be present in the garden namespace
```

2023-11-27 06:54 UTC, shafeeqes commented on test/framework/gardener_utils.go
> +				return seed, nil, fmt.Errorf("seed is not a ManagedSeed also seed kubeconfig secret is not present in Garden, %s: %w", client.ObjectKeyFromObject(seed), err)
```suggestion
				return seed, nil, fmt.Errorf("seed is not a ManagedSeed also no seed kubeconfig secret present in the garden namespace, %s: %w", client.ObjectKeyFromObject(seed), err)
```

2023-11-27 11:31 UTC, rfranzke commented
/assign

2023-11-28 11:40 UTC, shafeeqes reviewed
/lgtm

2023-11-28 16:28 UTC, rfranzke reviewed
/lgtm
/approve

2023-11-28 17:53 UTC, merged