Add dashboard showing problematic nodes
gardener/gardener pull request #8869
Opened 2023-11-27 13:59 UTC by adenitiu

**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
This PR adds a new dashboard where one could see nodes that are unhealthy / unschedulable for more than 5 mins, during a time window of 30 mins, ignoring actions taken by the ClusterAutoscaler or by a possible K8S upgrade activity.

**Which issue(s) this PR fixes**:
This should provide a hint whether there is a problem with nodes which we would normally not spot as node becoming `NotReady` are usually self-healed.

**Special notes for your reviewer**:

**Release note**:

```other operator
Add unhealthy nodes dashboard.
```

2023-11-27 15:11 UTC, adenitiu commented
/retest-required

2023-11-29 10:35 UTC, acumino reviewed
A couple of points - 
- I think you want to add this dashboard for every shoot, in that case, add the dashboard inside the dashboard/shoot folder.
- Why a separate dashboard? Probably, it should be added inside the `Node Details` dashboard.

2023-11-30 09:52 UTC, adenitiu commented
@acumino thanks for the review. 
I added the dashboard under the `seed` folder, because I would like to monitor mostly only our Seeds, not all the problematic nodes on each enduser shoot.  To be honest, am not sure if the location is the correct one, hence am open for suggestions. 
And to answer the 2nd point: it's because I did not find any Node related dashboard in the `seed` folder.

2023-12-04 14:54 UTC, adenitiu commented
/retest-required

2023-12-04 15:17 UTC, adenitiu commented
/retest-required

2023-12-05 10:19 UTC, adenitiu commented
/retest-required

2023-12-05 10:28 UTC, acumino requested changes
It would be nice if you could post updated dashboard picture in the PR description. To have an idea of how the overall dashboard will look.

2023-12-05 10:28 UTC, acumino commented on pkg/component/plutono/plutono_test.go
> +					testDashboardConfigMap(ctx, c, types.NamespacedName{Namespace: namespace, Name: plutonoDashboardsConfigMap.Name}, 23)
This change is not needed any more.
```suggestion
					testDashboardConfigMap(ctx, c, types.NamespacedName{Namespace: namespace, Name: plutonoDashboardsConfigMap.Name}, 22)
```

2023-12-05 10:28 UTC, acumino commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +      "description": "Shows the number of nodes having issues for more than 5 mins in the cluster over a period of 30mins",
```suggestion
      "description": "Shows the number of nodes having issues for more than 5 mins in the cluster over a period of 30 mins.",
```

2023-12-05 10:28 UTC, acumino commented on pkg/component/plutono/dashboards/shoot/owners/worker/node-pool-dashboard.json
> +      "title": "Nodes marked unhealthy, ignoring CA or K8S / GL upgrade activities",
I am guessing, GL refers to Garden Linux, in that case.
```suggestion
      "title": "Nodes marked unhealthy, ignoring CA or K8S / OS upgrade activities.",
```

2023-12-05 10:38 UTC, acumino reviewed
/approve
/cc @istvanballok 
For dashboard query.

2023-12-05 10:42 UTC, adenitiu commented
The dashboard would look like this
<img width="1745" alt="Screenshot 2023-12-05 at 11 41 32" src="https://github.com/gardener/gardener/assets/119592402/5003dbc1-9d5b-4344-bb58-fb246a4ae4bb">

2023-12-05 10:44 UTC, acumino commented
> The dashboard would look like this

Not necessary, but the single dashboard should be aligned to the left. WDYT?

2023-12-05 12:59 UTC, acumino commented
/retest

2023-12-05 13:32 UTC, istvanballok approved these changes
/lgtm
I double checked the promql expression and also tested the dashboard panel itself.

2023-12-05 15:20 UTC, merged