🧹 Cleanup a few `TODO`s
gardener/gardener pull request #8883
Opened 2023-11-30 10:40 UTC by rfranzke

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
- Remove MCM legacy CRD deletion, follow-up of #8559, released with `v1.82.0`
- Remove legacy `shoot-node-logging` MR cleanup, follow-up of #8501, released with `v1.80.0`
- Remove MCM legacy resources cleanup in generic `Worker` actuator, follow-up of #8596, released with `v1.82.0`
- Restrict GRM's token requestor to secrets with `class=shoot`, follow-up of #8152, released with `v1.74.0`
- Remove support for deprecated `NetworkPolicy` annotations, follow-up of #7907, released with `v1.71.0`

**Release note**:

```breaking developer
Support for the deprecated `NetworkPolicy` annotations `networking.resources.gardener.cloud/from-policy-allowed-ports` and `networking.resources.gardener.cloud/from-policy-pod-label-selector` has been removed. Use `networking.resources.gardener.cloud/from-<some-alias>-allowed-ports` instead ([documentation](https://github.com/gardener/gardener/blob/master/docs/concepts/resource-manager.md#networkpolicy-controller)).
```

2023-12-01 10:38 UTC, ary1992 reviewed
/lgtm

2023-12-04 14:02 UTC, acumino requested changes

2023-12-04 14:02 UTC, acumino commented on pkg/gardenlet/controller/shoot/shoot/cleaner.go
>  		if mr.Spec.Class != nil {
We rather need - 
```
		if pointer.StringDeref(mr.Spec.Class, "") != resourcesv1alpha1.ResourceManagerClassShoot {
			continue
		}
```

2023-12-04 14:26 UTC, rfranzke commented on pkg/gardenlet/controller/shoot/shoot/cleaner.go
>  		if mr.Spec.Class != nil {
I don't think so - this is about cleaning up `ManagedResource`s, but the class restriction change is only about token requestor secrets. We don't set `.spec.class` for shoot `ManagedResource`s.

2023-12-05 12:09 UTC, acumino reviewed
/lgtm
/approve

2023-12-05 13:06 UTC, merged