Update apiserver-proxy to v0.15.0 and remove flag `--setup-iptables`
gardener/gardener pull request #8933
Opened 2023-12-08 15:30 UTC by axel7born

**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Remove the optional creation of iptables rules and the flag`--setup-iptables`.
```

2023-12-08 15:34 UTC, ialidzhikov requested changes

2023-12-08 15:34 UTC, ialidzhikov commented on pkg/component/apiserverproxy/apiserver_proxy.go
> -									"--setup-iptables=false",
You need to adapt the tests.

2023-12-11 09:15 UTC, ScheererJ reviewed
Thanks for the simplification.

/lgtm

2023-12-11 11:01 UTC, ialidzhikov approved these changes

2023-12-11 12:49 UTC, merged