[Gardenlet] Clean up technical debt in defaulting code
gardener/gardener pull request #8985
Opened 2023-12-21 05:40 UTC by ary1992

**How to categorize this PR?**

/area dev-productivity
/kind technical-debt

**What this PR does / why we need it**:
This PR cleans up technical debt in our API defaulting code according to https://github.com/gardener/gardener/issues/7312.
This PR tackles the following resources in the core API group:
- gardenlet.config.gardener.cloud

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7312

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-12-21 05:41 UTC, ary1992 commented
/test all

2023-12-21 08:09 UTC, ary1992 commented
/test all

2023-12-28 08:10 UTC, shafeeqes requested changes
Only minor nits

2023-12-28 08:10 UTC, shafeeqes commented on pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
> +			// given APIGroup supports protobuf or not. defaults must not touch these, otherwise the integelligent
```suggestion
			// given APIGroup supports protobuf or not. defaults must not touch these, otherwise the intelligent
```

2023-12-28 08:10 UTC, shafeeqes commented on pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
> +			// given APIGroup supports protobuf or not. defaults must not touch these, otherwise the integelligent
```suggestion
			// given APIGroup supports protobuf or not. defaults must not touch these, otherwise the intelligent
```

2023-12-28 08:10 UTC, shafeeqes commented on pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
> +			// given APIGroup supports protobuf or not. defaults must not touch these, otherwise the integelligent
```suggestion
			// given APIGroup supports protobuf or not. defaults must not touch these, otherwise the intelligent
```

2023-12-28 08:17 UTC, ary1992 commented on pkg/gardenlet/apis/config/v1alpha1/defaults_test.go
> +			// given APIGroup supports protobuf or not. defaults must not touch these, otherwise the integelligent
oops copy pasted the comment.

2023-12-28 09:45 UTC, shafeeqes commented
/lgtm

2023-12-29 04:07 UTC, shafeeqes commented
/approve
/retest

2023-12-29 09:04 UTC, merged