Added ignore-daemonsets-utilization flag to CA
gardener/gardener pull request #8986
Opened 2023-12-21 08:25 UTC by sssash18

**How to categorize this PR?**

/area auto-scaling
/kind enhancement

**What this PR does / why we need it**:
This PR adds a new flag `ignore-daemonsets-utilization` in the shoot spec for autoscaler
**Which issue(s) this PR fixes**:
Fixes # https://github.com/gardener/autoscaler/issues/266

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2023-12-21 08:50 UTC, acumino requested changes

2023-12-21 08:50 UTC, acumino commented on pkg/apis/core/types_shoot.go
> +	// IgnoreDaemonsetsUtilization allow CA to ignore DaemonSet pods when calculating resource utilization for scaling down
Nit
```suggestion
	// IgnoreDaemonsetsUtilization allows CA to ignore DaemonSet pods when calculating resource utilization for scaling down.
```

2023-12-21 08:50 UTC, acumino commented on pkg/apis/core/v1beta1/defaults_shoot.go
> +	if obj.IgnoreDaemonsetsUtilization == nil {
Enhance test for this new case [here](https://github.com/gardener/gardener/blob/ccb71cb5fa98b95be02e6335415905078291bed0/pkg/apis/core/v1beta1/defaults_shoot_test.go#L863).

2023-12-21 08:50 UTC, acumino commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// IgnoreDaemonsetsUtilization allow CA to ignore DaemonSet pods when calculating resource utilization for scaling down
Add this field at the end, we sort the field based on protobuf number.

2023-12-21 09:53 UTC, sssash18 commented
/test pull-gardener-e2e-kind-upgrade

2023-12-28 09:59 UTC, shafeeqes reviewed
Thanks for the PR.

2023-12-28 09:59 UTC, shafeeqes commented on pkg/apis/core/v1beta1/defaults_shoot_test.go
> +			Expect(obj.Spec.Kubernetes.ClusterAutoscaler.IgnoreDaemonsetsUtilization).To(PointTo(Equal(false)))
Add an `Expect` in the below `It` as well?

2023-12-28 09:59 UTC, shafeeqes commented on pkg/apis/core/v1beta1/defaults_shoot_test.go
>  		It("sshould not overwrite the already set values for ClusterAutoscaler field", func() {
```suggestion
		It("should not overwrite the already set values for ClusterAutoscaler field", func() {
```

2023-12-28 09:59 UTC, shafeeqes commented on pkg/component/clusterautoscaler/cluster_autoscaler_test.go
> +		configIgnoreDaemonsetsUtilization   bool  = false
Should this not be added to the `configFull` below?
And set this to true.

2023-12-29 06:18 UTC, shafeeqes reviewed
One minor nit left

2023-12-29 06:18 UTC, shafeeqes commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// Verbosity allows CA to modify it's log level
```suggestion
	// Verbosity allows CA to modify it's log level.
```
And for the internal API as well.

2023-12-29 06:20 UTC, shafeeqes commented
Can you please adapt https://github.com/gardener/gardener/blob/aaa0c60fbc3ff3355addb3a9c3deffea65ec7e84/example/90-shoot.yaml#L283-L297 with the new fields?

2023-12-29 06:21 UTC, shafeeqes commented on pkg/apis/core/types_shoot.go
> +	IgnoreDaemonsetsUtilization *bool
Move this above Verbosity for consistency with the versioned API.

2023-12-29 06:29 UTC, shafeeqes commented on pkg/apis/core/v1beta1/types_shoot.go
> +	Verbosity *int32 `json:"verbosity,omitempty" protobuf:"varint,14,opt,name=verbosity"`
```suggestion
	// Verbosity allows CA to modify it's log level.
	//+optional
	Verbosity *int32 `json:"verbosity,omitempty" protobuf:"varint,14,opt,name=verbosity"`
```

2023-12-29 06:30 UTC, shafeeqes commented on pkg/apis/core/v1beta1/types_shoot.go
> +	Verbosity *int32 `json:"verbosity,omitempty" protobuf:"varint,14,opt,name=verbosity"`
```suggestion
	// IgnoreDaemonsetsUtilization allows CA to ignore DaemonSet pods when calculating resource utilization for scaling down.
	// +optional
	IgnoreDaemonsetsUtilization *bool `json:"ignoreDaemonsetsUtilization,omitempty" protobuf:"varint,13,opt,name=ignoreDaemonsetsUtilization"`
	// Verbosity allows CA to modify it's log level.
	// +optional
	Verbosity *int32 `json:"verbosity,omitempty" protobuf:"varint,14,opt,name=verbosity"`
```

2023-12-29 06:48 UTC, shafeeqes commented
Thanks!
/lgtm

2023-12-29 08:00 UTC, sssash18 commented
/test pull-gardener-e2e-kind-ha-single-zone-upgrade

2024-01-01 06:20 UTC, ary1992 reviewed
Just minor nits.

2024-01-01 06:20 UTC, ary1992 commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// IgnoreDaemonsetsUtilization allows CA to ignore DaemonSet pods when calculating resource utilization for scaling down.
```suggestion
	// IgnoreDaemonsetsUtilization allows CA to ignore DaemonSet pods when calculating resource utilization for scaling down (default: false).
```

2024-01-01 06:20 UTC, ary1992 commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// Verbosity allows CA to modify it's log level.
```suggestion
	// Verbosity allows CA to modify its log level (default: 2).
```

2024-01-01 06:20 UTC, ary1992 commented on pkg/apis/core/types_shoot.go
> +	// Verbosity allows CA to modify it's log level.
```suggestion
	// Verbosity allows CA to modify its log level.
```

2024-01-01 06:27 UTC, ary1992 commented on example/90-shoot.yaml
> +  #   ignoreDaemonsetsUtilization: false
```suggestion
```

2024-01-01 06:27 UTC, ary1992 commented on example/90-shoot.yaml
> +  #   verbosity: 2
Maintain the same ordering as defined in `types_shoot.go` file.

```suggestion
  #   ignoreDaemonsetsUtilization: false
  #   verbosity: 2
```

2024-01-01 08:56 UTC, ary1992 approved these changes

2024-01-01 16:42 UTC, shafeeqes commented
/approve
/retest

2024-01-02 03:27 UTC, shafeeqes commented
/retest

2024-01-02 04:39 UTC, sssash18 commented
/test pull-gardener-e2e-kind-migration-ha-single-zone

2024-01-02 05:28 UTC, sssash18 commented
/test pull-gardener-e2e-kind-migration-ha-single-zone

2024-01-02 06:04 UTC, merged