Adjust default values for `cluster-autoscaler` in shoot example
gardener/gardener pull request #8990
Opened 2023-12-22 10:56 UTC by aaronfern

**How to categorize this PR?**

/area documentation open-source

**What this PR does / why we need it**:
This PR adjusts the values for `cluster-autoscaler` in the shoot example
These new values are taken from default values defined in the `autoscaler` repo

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
None
```

2023-12-22 10:56 UTC, aaronfern commented
/invite @himanshu-kun

2023-12-22 15:12 UTC, aaronfern commented
/retest

2023-12-24 07:05 UTC, aaronfern commented
/retest

2023-12-26 04:43 UTC, himanshu-kun requested changes
I think there is a misunderstanding @aaronfern .. I meant to match this example file with [these](https://github.com/gardener/gardener/blob/8fa09bdc88d4afbffa63573c042de2426d0ac56a/pkg/apis/core/v1beta1/defaults_shoot.go#L303-L332) defaults. 

As you can see the example already matches them ... but I don't see a default declared at `g/g` for `newPodScaleUpDelay` in the code I pointed.. could you update that to `0` and only change that in the example file.

2024-01-01 06:27 UTC, aaronfern commented
Closing this PR as I need to change shoot defaults.
I will open a new PR with the required changes 
/close

2024-01-01 06:27 UTC, closed without merging