Make VPN Network Range Configurable
gardener/gardener pull request #8991
Opened 2023-12-22 14:23 UTC by SimonKienzler

**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:

This PR introduces a new field to the `Seed.spec.networks` section called `vpn`, which allows operators to configure the previously hard-coded VPN Network on a per-seed basis.

**Which issue(s) this PR fixes**:

Part of #8987 

**Special notes for your reviewer**:

Please advise if I missed any parts of the code base where this change needs to be addressed.

**Release note**:

```feature operator
VPN Network can now be configured on a per-seed basis.
```

2024-01-19 18:49 UTC, oliver-goetz commented
/remove-lifecycle stale

/assign

2024-01-23 16:59 UTC, oliver-goetz requested changes
Thanks for the PR 🙂 

This PR does not look complete. You have added a property for the VPN CIDR to the API and to the vpnseedserver and vpnshoot components too. However, these properties are not used anywhere.

/ok-to-test

2024-01-23 16:59 UTC, oliver-goetz commented on pkg/apis/core/validation/seed.go
> +		if core.IsIPv6SingleStack(seedNetworks.IPFamilies) {
Shouldn't the default IP range depend on `primaryIPFamily` instead?
That's at least what's checked a few lines below
`allErrs = append(allErrs, cidrvalidation.ValidateCIDRIPFamily(networks, string(primaryIPFamily))...)`

2024-01-23 16:59 UTC, oliver-goetz commented on pkg/component/vpnseedserver/vpn_seed_server.go
> +	VPNCIDR string
What's the scope of this property? It is not used anywhere.

2024-01-23 16:59 UTC, oliver-goetz commented on pkg/component/vpnshoot/vpnshoot.go
> +	Network string
This property is used neither.

2024-02-08 13:30 UTC, SimonKienzler commented
/remove-lifecycle stale

We'll hopefully find some time to work on this in the upcoming weeks.

2024-03-25 09:38 UTC, timebertt commented
/remove-lifecycle rotten

@SimonKienzler what's the status of this PR? Should we hand this one over to a colleague?

2024-03-25 12:01 UTC, SimonKienzler commented
A handover would be greatly appreciated from my side ❤️

2024-04-05 06:35 UTC, timebertt commented
/assign

2024-04-05 14:59 UTC, timebertt commented
/close
Unfortunately, this PR is quite conflicted with changes in the master branch.
I tried rebasing the commits but the PR is missing some things here and there.
To make things easier to review and follow, I will open a new PR with the missing parts and nicely structured commits.

2024-04-05 14:59 UTC, closed without merging