Fix broken links - 2024.01
gardener/gardener pull request #9014
Opened 2024-01-09 13:09 UTC by n-boshnakov

**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR fixes broken links in the repo.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

2024-01-09 14:17 UTC, ary1992 reviewed
Thanks for the changes.
/lgtm

2024-01-09 14:17 UTC, ary1992 commented
/retest

2024-01-09 14:56 UTC, ialidzhikov requested changes

2024-01-09 14:56 UTC, ialidzhikov commented on docs/extensions/logging-and-monitoring.md
> +* [Exemplary Implementation (ClusterFilter) for the AWS Provider](https://github.com/gardener/gardener-extension-provider-aws/blob/master/charts/gardener-extension-provider-aws/templates/clusterfilte
```suggestion
* [Exemplary Implementation (ClusterFilter) for the AWS Provider](https://github.com/gardener/gardener-extension-provider-aws/blob/master/charts/gardener-extension-provider-aws/templates/clusterfilters-logging.yaml)
* [Exemplary Implementation (ClusterParser) for the Shoot DNS Service](https://github.com/gardener/gardener-extension-shoot-dns-service/blob/master/charts/gardener-extension-shoot-dns-service/templates/clusterparsers-logging.yaml)
```

2024-01-10 12:27 UTC, ialidzhikov approved these changes
/lgtm

2024-01-10 17:46 UTC, merged