[SeedManagement] Clean up technical debt in defaulting code
gardener/gardener pull request #9033
Opened 2024-01-11 12:39 UTC by ary1992

**How to categorize this PR?**

/area dev-productivity
/kind technical-debt

**What this PR does / why we need it**:
This PR cleans up technical debt in our API defaulting code according to https://github.com/gardener/gardener/issues/7312.
This PR tackles the following resources in the core API group:

- seedmanagement.gardener.cloud

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/7312

**Special notes for your reviewer**:

**Release note**:

```other developer
NONE
```

2024-01-17 12:02 UTC, plkokanov requested changes
Thanks for the PR. Some minor doubts inline.

2024-01-17 12:02 UTC, plkokanov commented on pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
> +		SetDefaults_Gardenlet(obj.Spec.Gardenlet, obj.Name, obj.Namespace)
I think it's ok to keep these as `setDefaults` to avoid confusion, since they anyways do not match the signature that the generator expects for `SetDefaults_*` functions and will not be called from the generated code.

2024-01-17 12:02 UTC, plkokanov commented on pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
> +	SetDefaults_GardenletConfiguration(gardenletConfig, name, namespace)
Same as above

2024-01-17 12:02 UTC, plkokanov commented on pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
> +	SetDefaults_Resources(obj.Resources)
This can be kept as `setDefaultsResources` since it will also not be called by the generated code as it actually defaults a filed of the decoded `runtime.RawExtension`.

2024-01-17 12:02 UTC, plkokanov commented on pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
> +	SetDefaults_SeedSpec(&obj.SeedConfig.SeedTemplate.Spec, name, namespace)
Same as above.

2024-01-18 11:02 UTC, ary1992 commented on pkg/apis/seedmanagement/v1alpha1/defaults_managedseed.go
> +		SetDefaults_Gardenlet(obj.Spec.Gardenlet, obj.Name, obj.Namespace)
Yeah I was also confused about this. Thanks for the clarification.

2024-01-22 08:23 UTC, plkokanov commented
/approve

2024-01-30 09:09 UTC, plkokanov commented
/lgtm

2024-01-30 12:53 UTC, acumino commented
/retest

2024-01-30 14:05 UTC, merged