Added descriptions to the concept topics
gardener/gardener pull request #9084
Opened 2024-01-26 15:33 UTC by n-boshnakov

**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR adds short descriptions to the topics in the Concepts section.

**Which issue(s) this PR fixes**:
Fixes [#191](https://github.com/gardener/website-generator/issues/191) in gardener/website-generator

**Special notes for your reviewer**:

**Release note**:

```doc developer
NONE
```

2024-01-29 10:38 UTC, BeckerMax requested changes

2024-01-29 10:38 UTC, BeckerMax commented on docs/concepts/apiserver_admission_plugins.md
> +description: A list of all existing admission plugins together with their responsibilities
```suggestion
description: A list of all Gardener managed admission plugins together with their responsibilities
```

2024-01-29 10:38 UTC, BeckerMax commented on docs/concepts/architecture.md
> +description: The concepts behind the Kubernetes and Gardener architecture
```suggestion
description: The concepts behind the Gardener architecture
```

2024-01-29 10:38 UTC, BeckerMax commented on docs/concepts/backup-restore.md
> +description: Understand the backup and restore configuration of Gardener
```suggestion
description: Understand the etcd backup and restore capabilities of Gardener
```

2024-01-29 10:38 UTC, BeckerMax commented on docs/concepts/gardenlet.md
> +description: Understand how Gardener can manage seed clusters decentrally
```suggestion
description: Similarly to Kubernetes which runs a primary “agent” on every node, the kubelet, gardener runs a gardenlet as а primary “agent” on every seed cluster. Understand how the gardenlet works and learn more about the different Gardener components.
```

2024-01-29 10:38 UTC, BeckerMax commented on docs/concepts/resource-manager.md
> +description: Learn more about the component that creates, updates, and deletes Kubernetes resources in a target cluster
```suggestion
description: Learn more about the central component that exists once per gardener landscape and hosts controllers next to the gardener apiserver.
```

2024-01-29 10:38 UTC, BeckerMax commented on docs/concepts/resource-manager.md
> +---
```suggestion
---
title: Gardener Resource Manager
description: Set of controllers with different responsibilities running once per Seed and once per Shoot.
---
```

2024-01-29 10:38 UTC, BeckerMax commented on docs/concepts/node-agent.md
> +description: Maintance of node-specific components without management by Kubernetes
```suggestion
description: How Gardener bootstraps machines into worker nodes and how it installs and maintains gardener-managed node-specific components.
```

2024-01-29 10:39 UTC, BeckerMax commented
Maybe we should end all descriptions with a `point` at the end like K8s also does it https://kubernetes.io/docs/concepts/

2024-01-29 11:49 UTC, n-boshnakov commented
> Maybe we should end all descriptions with a `point` at the end like K8s also does it https://kubernetes.io/docs/concepts/

The rest of the descriptions in our website do not end with periods, so adding them only to the Concepts section might feel off. I'd suggest we stick to not using them.

2024-01-29 12:38 UTC, n-boshnakov commented
@BeckerMax I updated the `gardenlet` description to make it a bit shorter and took the second description for `Resource Manager`, while keeping the name the same in order to fit better with the rest of the topic titles. 

Regarding the titles, do you think that we should have them be generic or specific - `Resource Manager` vs `Gardener Resource Manager`?

2024-01-30 13:54 UTC, n-boshnakov commented
/retest-required

2024-01-31 10:02 UTC, BeckerMax commented
> Regarding the titles, do you think that we should have them be generic or specific - Resource Manager vs Gardener Resource Manager?

No strong preference. Internally we always include the `Gardener` as `Resource Manager` sounds very generic. Also short as in GRM. If you feel it is visually more appealing to use the shortened form that is fine for me too.

/lgtm

2024-01-31 10:03 UTC, BeckerMax approved these changes

2024-01-31 11:37 UTC, n-boshnakov commented
> > Regarding the titles, do you think that we should have them be generic or specific - Resource Manager vs Gardener Resource Manager?
> 
> No strong preference. Internally we always include the `Gardener` as `Resource Manager` sounds very generic. Also short as in GRM. If you feel it is visually more appealing to use the shortened form that is fine for me too.
> 
> /lgtm

I can update the names for all the relevant topics to include "Gardener", that way it would look alright.

2024-01-31 18:03 UTC, oliver-goetz reviewed
Thanks for the PR 😄

2024-01-31 18:03 UTC, oliver-goetz commented on docs/concepts/admission-controller.md
>  # Gardener Admission Controller
```suggestion
---
title: Gardener Admission Controller
description: Functions and list of handlers for the Gardener Admission Controller
---

## Overview
```
This one is not consistent with the others yet.

2024-02-01 11:15 UTC, acumino commented
/hold

2024-02-01 11:17 UTC, acumino commented
/unhold

2024-02-01 12:23 UTC, merged