Added autoscaler options to worker groups
gardener/gardener pull request #9245
Opened 2024-02-26 06:59 UTC by aaronfern

**How to categorize this PR?**

/area auto-scaling 
/kind api-change

**What this PR does / why we need it**:
This PR adds  some `autoscaler` options to workers.
With this change, users can configure certain worker specific autoscaler options instead of one single value for all worker groups

**Which issue(s) this PR fixes**:
Fixes partially gardener/autoscaler#240

**Special notes for your reviewer**:
`Autoscaler` will read these values from annotations in the `machineDeployment` (ref: https://github.com/gardener/autoscaler/pull/257), so the values from `spec.provider.worker.autoscaler` are added as annotations to the `machineDeployment`

**Release note**:

```noteworthy user
users can not set some autoscaler options per worker groups via `spec.provider.workers.autoscaler`. 
```

2024-02-26 07:40 UTC, rfranzke commented
/assign

2024-02-26 10:00 UTC, rfranzke requested changes

2024-02-26 10:00 UTC, rfranzke commented on example/90-shoot.yaml
> +    # autoscaler:
Maybe 
```suggestion
    # clusterAutoscaler:
```

to align with the fields in `.spec.kubernetes`?

2024-02-26 10:00 UTC, rfranzke commented on example/90-shoot.yaml
> +    # autoscaler:
Please adapt https://github.com/gardener/gardener/blob/master/docs/usage/shoot_autoscaling.md#horizontal-node-auto-scaling

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/core/types_shoot.go
> +// ClusterAutoscalerOptions jdkddskddd
?

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/core/types_shoot.go
> +	// Autoscaler is a map of kernel settings to apply on all machines in this worker pool.
?

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// Autoscaler is a map of kernel settings to apply on all machines in this worker pool.
?

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/core/v1beta1/types_shoot.go
> +// ClusterAutoscalerOptions jdkddskddd
?

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +	}
unit tests

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// ScaleDownUtilizationThreshold defines the threshold in fraction (0.0 - 1.0) under which a node is being removed.
// +optional

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +// ClusterAutoscalerOptions jdkddskddd
?

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// ScaleDownGpuUtilizationThreshold defines the threshold in fraction (0.0 - 1.0) of gpu resources under which a node is being removed.
// +optional

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// ScaleDownUnneededTime defines how long a node should be unneeded before it is eligible for scale down.
// +optional

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// Autoscaler is a map of kernel settings to apply on all machines in this worker pool.
?

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	Autoscaler *ClusterAutoscalerOptions `json:"autoscaler,omitempty"`
same here

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// MaxNodeProvisionTime defines how long CA waits for node to be provisioned.
// +optional

2024-02-26 10:00 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// ScaleDownUnreadyTime defines how long an unready node should be unneeded before it is eligible for scale down.
// +optional

2024-02-26 10:00 UTC, rfranzke commented on pkg/component/extensions/worker/worker.go
> +		if workerPool.Autoscaler != nil {
```suggestion
		var autoscalerOptions *extensionsv1alpha1.ClusterAutoscalerOptions
		if workerPool.Autoscaler != nil {
			autoscalerOptions = &extensionsv1alpha1.ClusterAutoscalerOptions{}
```

2024-02-26 10:00 UTC, rfranzke commented on pkg/component/extensions/worker/worker_test.go
> +		It("should successfully deploy the Worker resource with cluster autoscaker options when present", func() {
```suggestion

		It("should successfully deploy the Worker resource with cluster autoscaler options when present", func() {
```

2024-02-26 10:00 UTC, rfranzke commented on pkg/provider-local/controller/worker/machines.go
> +		}
Extend https://github.com/gardener/gardener/blob/master/docs/extensions/worker.md so that provider extensions know that they must add the annotations

2024-02-26 10:00 UTC, rfranzke commented on extensions/pkg/controller/worker/machines.go
> +	McdAnnotations       map[string]string
Names are confusing. What are `Annotations` and what are `McdAnnotations`? Please find better names to make it more clear.

2024-02-26 10:00 UTC, rfranzke commented on pkg/provider-local/controller/worker/machines.go
> +		}
Can you extract this into a helper function in `https://github.com/gardener/gardener/tree/master/pkg/apis/extensions/v1alpha1/helper` that all provider extensions can call to generate this annotation map?

2024-02-26 17:53 UTC, aaronfern commented on pkg/apis/core/types_shoot.go
> +// ClusterAutoscalerOptions jdkddskddd
Apologies for the comments
Just slipped from me completely 🥴

2024-02-26 17:57 UTC, aaronfern commented on extensions/pkg/controller/worker/machines.go
> +	McdAnnotations       map[string]string
From context, `Annotations` was supposed to be `workerPool.Annotations` which in turn are annotations for the node template spec of the mcd
I have renamed `McdAnnotations` to `ClusterAutoscalerOptions`. Hope that should suffice

2024-02-26 20:18 UTC, aaronfern commented
/retest

2024-02-27 15:27 UTC, rfranzke requested changes

2024-02-27 15:27 UTC, rfranzke commented on docs/extensions/worker.md
> +The `spec.pools[].clusterAutoscaler` field containes `cluster-autoscaler` settings that are to be applied only to specific worker group
```suggestion
The `spec.pools[].clusterAutoscaler` field contains `cluster-autoscaler` settings that are to be applied only to specific worker group
```

2024-02-27 15:27 UTC, rfranzke commented on docs/extensions/worker.md
> +The `spec.pools[].clusterAutoscaler` field containes `cluster-autoscaler` settings that are to be applied only to specific worker group
OK, very nice, but what now? What do I have to do as extension developer?

2024-02-27 15:27 UTC, rfranzke commented on docs/usage/shoot_autoscaling.md
> +The `Shoot` API allows to configure a few flags of the `cluster-autoscaler`
```suggestion
The `Shoot` API allows to configure a few flags of the `cluster-autoscaler`:
```

2024-02-27 15:27 UTC, rfranzke commented on docs/usage/shoot_autoscaling.md
> +The following flags are general options for `cluster-autoscaler`, and these values will be used for all worker groups except for those who have specific values defined:
```suggestion
The following flags are general options for `cluster-autoscaler`, and these values will be used for all worker groups except for those overwriting them:
```

2024-02-27 15:27 UTC, rfranzke commented on docs/usage/shoot_autoscaling.md
> +The following flags allow some `cluster-autoscaler` flags to be set per worker group. They are specified along with the worker and override any general value such as those specified in the flags abov
```suggestion
The following flags allow some `cluster-autoscaler` flags to be set per worker pool. They are specified along with the worker and override any general value such as those specified in the flags above:
```

2024-02-27 15:27 UTC, rfranzke commented on docs/usage/shoot_autoscaling.md
> +* `.spec.provider.workers.clusterAutoscaler.maxNodeProvisionTime` defines how long cluster autoscaler should wait for a node to be provisioned.
```suggestion
* `.spec.provider.workers[].clusterAutoscaler.scaleDownUtilizationThreshold` defines the threshold under which a node is being removed
* `.spec.provider.workers[].clusterAutoscaler.scaleDownGpuUtilizationThreshold` defines the threshold for gpu resources under which a node is being removed
* `.spec.provider.workers[].clusterAutoscaler.scaleDownUnneededTime` defines how long a node should be unneeded before it is eligible for scale down
* `.spec.provider.workers[].clusterAutoscaler.scaleDownUnreadyTime` defines how long an unready node should be unneeded before it is eligible for scale down.
* `.spec.provider.workers[].clusterAutoscaler.maxNodeProvisionTime` defines how long cluster autoscaler should wait for a node to be provisioned.
```

2024-02-27 15:27 UTC, rfranzke commented on docs/usage/shoot_autoscaling.md
> +* `.spec.provider.workers.clusterAutoscaler.maxNodeProvisionTime` defines how long cluster autoscaler should wait for a node to be provisioned.
You could also explain why some of the fields that can be specified globally cannot be specified per worker pool. That might a question that arises when people start using this feature.

2024-02-27 15:27 UTC, rfranzke commented on extensions/pkg/controller/worker/machines.go
> +	ClusterAutoscalerOptions map[string]string
```suggestion
	ClusterAutoscalerAnnotations map[string]string
```

2024-02-27 15:27 UTC, rfranzke commented on extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
> +				Annotations: deployment.ClusterAutoscalerOptions,
I don't think this works in all cases. Instead, you should do something like this in L256:

```golang
for k, v := range deployment.ClusterAutoscalerOptions {
	metav1.SetMetadataAnnotation(&machineDeployment.ObjectMeta, k, v)
}

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	MaxNodeProvisionTimeAnnotation = "autoscaler.gardener.cloud/max-node-provision-time"
No strong opinion, but I guess they better belong here: https://github.com/gardener/gardener/blob/master/pkg/apis/extensions/v1alpha1/types_worker.go

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/core/v1beta1/types_shoot.go
> +// ClusterAutoscalerOptions contains the cluster autoscaler configurations for the worker.
```suggestion
// ClusterAutoscalerOptions contains the cluster autoscaler configurations for a worker pool.
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/core/v1beta1/types_shoot.go
> +	// ClusterAutoscaler contains the cluster autoscaler configurations for the worker.
```suggestion
	// ClusterAutoscaler contains the cluster autoscaler configurations for the worker pool.
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +// ValidateClusterAutoscalerOptions validates the cluster autoscaler options of workers
```suggestion
// ValidateClusterAutoscalerOptions validates the cluster autoscaler options of worker pools.
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/core/validation/shoot.go
> +	allErrs := field.ErrorList{}
```suggestion
	var allErrs field.ErrorList
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/core/validation/shoot_test.go
> +			Describe("clusterAutoscaler options validation", func() {
```suggestion

			Describe("ClusterAutoscalerOptions validation", func() {
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/core/validation/shoot_test.go
> +				DescribeTable("cluster autoscaler values",
```suggestion

				DescribeTable("cluster autoscaler values",
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/helper/helper.go
> +func GetClusterAutoscalerAnnotationMap(caOptions *extensionsv1alpha1.ClusterAutoscalerOptions) map[string]string {
```suggestion
func GetMachineDeploymentClusterAutoscalerAnnotations(caOptions *extensionsv1alpha1.ClusterAutoscalerOptions) map[string]string {
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/helper/helper.go
> +	mcdAnnotationMap := map[string]string{}
```suggestion
	annotations := map[string]string{}
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/helper/helper_test.go
> +		It("should return empty map when an empty map is passed", func() {
```suggestion

		It("should return empty map when an empty map is passed", func() {
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/helper/helper_test.go
> +		It("should return correctly populated map when all options are passed", func() {
```suggestion

		It("should return correctly populated map when all options are passed", func() {
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/helper/helper_test.go
> +		It("should return correctly populated map when partial options are passed", func() {
```suggestion

		It("should return correctly populated map when partial options are passed", func() {
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +// ClusterAutoscalerOptions contains the cluster autoscaler configurations for the worker.
```suggestion
// ClusterAutoscalerOptions contains the cluster autoscaler configurations for the worker pool.
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/types_worker.go
> +	// ClusterAutoscaler contains the cluster autoscaler configurations for the worker.
```suggestion
	// ClusterAutoscaler contains the cluster autoscaler configurations for the worker pool.
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/component/extensions/worker/worker.go
> +				autoscalerOptions.ScaleDownUtilizationThreshold = &ScaleDownUtilThreshold
```suggestion
				autoscalerOptions.ScaleDownUtilizationThreshold = ptr.To(*workerPool.ClusterAutoscaler.ScaleDownUtilizationThreshold)
```

2024-02-27 15:27 UTC, rfranzke commented on pkg/component/extensions/worker/worker.go
> +				autoscalerOptions.ScaleDownGpuUtilizationThreshold = &ScaleDownGpuUtilThreshold
```suggestion
				autoscalerOptions.ScaleDownGpuUtilizationThreshold = ptr.To(*workerPool.ClusterAutoscaler.ScaleDownGpuUtilizationThreshold)
```

2024-02-28 04:06 UTC, aaronfern commented
/test pull-gardener-e2e-kind-ha-multi-zone-upgrade

2024-02-28 09:21 UTC, rfranzke reviewed
Thanks! Just a few more nits before we are ready :)

2024-02-28 09:21 UTC, rfranzke commented on docs/extensions/worker.md
> +The `spec.pools[].clusterAutoscaler` field contains `cluster-autoscaler` settings that are to be applied only to specific worker group. `Cluster-autoscaler` expects to find these settings as annotati
```suggestion
The `spec.pools[].clusterAutoscaler` field contains `cluster-autoscaler` settings that are to be applied only to specific worker group. `cluster-autoscaler` expects to find these settings as annotations on the `MachineDeployment`, and so providers must pass these values to the corresponding `MachineDeployment` via annotations. The keys for these annotations can be found [here](https://github.com/gardener/gardener/blob/master/pkg/apis/extensions/v1alpha1/types_worker.go) and the values for the corresponding annotations should be the same as what is passed into the field.
```

Do you want to refer to your helper function (`extensionsv1alpha1helper.GetMachineDeploymentClusterAutoscalerAnnotations`)?

2024-02-28 09:21 UTC, rfranzke commented on pkg/apis/core/validation/shoot_test.go
> +			Describe("clusterAutoscaler options validation", func() {
```suggestion
			Describe("ClusterAutoscaler options validation", func() {
```

2024-02-28 09:21 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/helper/helper.go
> +	if caOptions != nil {
```suggestion
	var annotations map[string]string
	if caOptions != nil {
		annotations := map[string]string{}
```

2024-02-28 09:21 UTC, rfranzke commented on pkg/apis/extensions/v1alpha1/helper/helper.go
> +// GetMachineDeploymentClusterAutoscalerAnnotations returns a map of annotations with values intended to be used as cluster autoscaler options for the worker group
```suggestion
// GetMachineDeploymentClusterAutoscalerAnnotations returns a map of annotations with values intended to be used as cluster-autoscaler options for the worker group.
```

2024-02-28 14:24 UTC, rfranzke reviewed
/lgtm
/approve

2024-02-28 18:03 UTC, merged