Reconfigure NodeNotHealth prometheus rule
gardener/gardener pull request #9275
Opened 2024-02-28 07:50 UTC by adenitiu

**How to categorize this PR?**

/area monitoring
/kind bug

**What this PR does / why we need it**:
This PR corrects the seed name mentioned in the alert and removes the wait time of 10m, as we would want to be notified immediately when a node fulfils the expression. 
The expression checks a node is not healthy in a time-window of 30 mins, hence no need to wait for additional 10m. 
 
**Which issue(s) this PR fixes**:
-

**Special notes for your reviewer**:
/invite @rickardsjp @istvanballok 

**Release note**:

```other operator
Reconfigure NodeNotHealth prometheus rule to display correctly the seed name and drop additional waiting time before alerting.
```

2024-02-28 09:01 UTC, rickardsjp commented
/assign

FYI, `/invite` doesn't seem to be doing the job

2024-02-28 09:03 UTC, rfranzke commented
> /assign
> 
> FYI, `/invite` doesn't seem to be doing the job

Prow uses `/cc` 😉

2024-02-28 09:17 UTC, rickardsjp requested changes
I can't edit you PR, but please also adjust the title and the release note with the correct name `NodeNotHealthy prometheus alert`.
What do you think about this release note:

```
Enhance NodeNotHealthy prometheus alert to show the seed name and fire immediately.
```

2024-02-28 09:17 UTC, rickardsjp commented on pkg/component/monitoring/charts/bootstrap/aggregate-prometheus-rules/seed.rules.yaml
> +        Node {{$labels.node}} in seed {{$externalLabels.seed}} in landscape {{$externalLabels.landscape}} has been marked as not healthy for at least 5 times in the past 30 mins.
I think "marked" as not healthy may be a bit misleading, what do you think about the following?

```suggestion
        Node {{$labels.node}} in seed {{$externalLabels.seed}} in landscape {{$externalLabels.landscape}} was not healthy for five scrapes in the past 30 mins.
```

2024-02-28 09:20 UTC, adenitiu commented
Thanks @rickardsjp . Suggestions makes sense. Adapted accordingly.

2024-02-28 09:21 UTC, rickardsjp approved these changes
/lgtm

2024-02-28 09:22 UTC, rfranzke commented
/approve
/cla

2024-02-28 09:49 UTC, adenitiu commented
/retest

2024-03-05 05:52 UTC, rfranzke commented
@adenitiu pls rebase

2024-03-05 06:57 UTC, rfranzke reviewed
/lgtm
/approve

2024-03-05 06:58 UTC, rfranzke commented
@adenitiu pls adapt unit tests...

2024-03-05 07:39 UTC, rfranzke commented
> Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository. Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

@adenitiu pls fix this

2024-03-05 10:03 UTC, closed without merging

2024-03-05 10:11 UTC, adenitiu commented
Closed in favour of https://github.com/gardener/gardener/pull/9311