Added vpa for kube-apiserver with update policy set to off
gardener/gardener pull request #934
Opened 2019-04-16 08:27 UTC by georgekuruvillak

**What this PR does / why we need it**:
This PR adds VPA resource for collecting VPA recommendations for VPA. The `updatePolicy` for VPA is set with `updateMode: "Off"` to prevent HPA and VPA controllers from acting on the same metric. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2019-04-16 08:36 UTC, wyb1 requested changes
You need to add `vpa.enabled` to the `values.yaml` in the kube-apiserver chart. The value also has to be rendered in based on the vpa feature gate in `operation/hybridbotanist/controlplane.go`.

2019-04-16 09:16 UTC, amshuman-kr commented
To be clear, we may not want to switch on update for `kube-apiserver` as fast as for some of the other control-plane components.

2019-04-17 06:46 UTC, wyb1 commented
/lgtm

2019-04-17 06:46 UTC, wyb1 approved these changes

2019-04-17 13:41 UTC, rfranzke approved these changes
/lgtm

2019-04-17 13:41 UTC, merged