Adds common label key to the observability applications
gardener/gardener pull request #9385
Opened 2024-03-14 11:32 UTC by nickytd

/area logging
/area monitoring
/kind enhancement

This PR adds `observability.gardener.cloud/app` label to the observability applications. The purpose of the label is to be used at the objectSelector in the `oidc-apps-controller` webhook definition. In this way we achieve explicit pod targeting by the mutating webhook. 

```other developer
Now the observability applications which are also targets of the authentication & authorization proxies share common label. 
```

2024-03-14 12:36 UTC, nickytd commented
/test pull-gardener-e2e-kind-ha-multi-zone

2024-03-14 13:22 UTC, nickytd commented
/hold

2024-03-14 14:25 UTC, nickytd commented
/retest

2024-03-14 15:15 UTC, nickytd commented
/test pull-gardener-unit

2024-03-14 15:29 UTC, nickytd commented
/test pull-gardener-unit

2024-03-14 15:58 UTC, nickytd commented
/retest

2024-03-14 18:32 UTC, nickytd commented
/test pull-gardener-e2e-kind

2024-03-14 18:34 UTC, nickytd commented
/test pull-gardener-e2e-kind-ha-single-zone-upgrade

2024-03-15 07:53 UTC, rfranzke requested changes
What about Vali?

2024-03-15 07:53 UTC, rfranzke commented on pkg/component/observability/monitoring/alertmanager/alertmanager.go
> +					v1beta1constants.LabelObservabilityApplication:       a.values.Name,
```suggestion
					v1beta1constants.LabelObservabilityApplication:       a.name(),
```

2024-03-15 07:53 UTC, rfranzke commented on pkg/component/observability/monitoring/alertmanager/vpa.go
> +			Labels: utils.MergeStringMaps(a.getLabels(), map[string]string{
same here

2024-03-15 07:53 UTC, rfranzke commented on pkg/component/observability/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus-vpa.yaml
> +    observability.gardener.cloud/app: "prometheus"
```suggestion
    observability.gardener.cloud/app: "prometheus-shoot"
```

2024-03-15 07:53 UTC, rfranzke commented on pkg/component/observability/monitoring/charts/seed-monitoring/charts/core/charts/prometheus/templates/prometheus.yaml
> +        observability.gardener.cloud/app: "prometheus"
```suggestion
        observability.gardener.cloud/app: "prometheus-shoot"
```

2024-03-15 07:53 UTC, rfranzke commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +						v1beta1constants.LabelObservabilityApplication:                                                   p.values.Name,
```suggestion
						v1beta1constants.LabelObservabilityApplication:                                                   p.name(),
```

2024-03-15 07:53 UTC, rfranzke commented on pkg/component/observability/monitoring/prometheus/vpa.go
> +			Labels: utils.MergeStringMaps(p.getLabels(), map[string]string{
same here

2024-03-15 08:35 UTC, nickytd commented on pkg/component/observability/monitoring/alertmanager/vpa.go
> +			Labels: utils.MergeStringMaps(a.getLabels(), map[string]string{
Suggestion applied in cb8cc31c4. Thanks

2024-03-15 08:35 UTC, nickytd commented on pkg/component/observability/monitoring/prometheus/vpa.go
> +			Labels: utils.MergeStringMaps(p.getLabels(), map[string]string{
Suggestion applied in cb8cc31c4. Thanks

2024-03-15 08:37 UTC, nickytd commented
Thanks for the suggestions @rfranzke. 👍 Will put on /hold to add the labels to vali as well.

2024-03-15 10:03 UTC, nickytd commented
/test pull-gardener-e2e-kind-ha-multi-zone

2024-03-15 10:47 UTC, nickytd commented
/test pull-gardener-e2e-kind-ha-multi-zone

2024-03-15 12:45 UTC, rfranzke reviewed
/lgtm
/approve

2024-03-15 16:03 UTC, nickytd commented
/test pull-gardener-e2e-kind

2024-03-15 18:03 UTC, nickytd commented
/test pull-gardener-e2e-kind-ha-single-zone

2024-03-15 20:08 UTC, nickytd commented
/test pull-gardener-e2e-kind-migration-ha-single-zone

2024-03-15 20:45 UTC, merged