[Cleanup] Drop VPN Diffie–Hellman parameters
gardener/gardener pull request #9386
Opened 2024-03-14 11:45 UTC by ary1992

**How to categorize this PR?**

/area quality
/kind cleanup

**What this PR does / why we need it**:
Drop no longer needed VPN Diffie–Hellman parameters. [Vpn](https://github.com/gardener/vpn2) release `v0.23.0` removed the need for supplying the vpn server with `Diffie–Hellman` parameters. Hence the related codes are dropped from our code-base.

`vpn-seed-server-dh`  secret will be cleaned up the GRM garbage-collector controller as this secret has `resources.gardener.cloud/garbage-collectable-reference: "true"` label set.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener/issues/9093

**Special notes for your reviewer**:

**Release note**:

```other operator
secret `vpn-seed-server-dh` will no longer be created as  [Vpn](https://github.com/gardener/vpn2) release `v0.23.0` removed the need for supplying the vpn server with `Diffie–Hellman` parameters.
```

2024-03-14 11:46 UTC, rfranzke commented
/assign

2024-03-14 12:17 UTC, ScheererJ reviewed
Thanks for cleaning up.

/lgtm

2024-03-14 12:18 UTC, ScheererJ commented
Could you please check the tests and run `make generate`?

2024-03-15 07:49 UTC, rfranzke requested changes
Can you delete https://github.com/gardener/gardener/blob/master/example/10-secret-openvpn-diffie-hellman.yaml and adapt https://github.com/gardener/gardener/blob/932601d6cde467b05baede8dc7aff2f46d63dc26/docs/operations/configuration.md?plain=1#L75?

2024-03-15 07:49 UTC, rfranzke commented
Also, please adapt the release note for operators (i.e., they can delete this secret from garden namespace, etc.)

2024-03-26 08:36 UTC, ialidzhikov commented
/assign

2024-03-26 09:25 UTC, ialidzhikov reviewed
Minor cleanup suggestions, otherwise lgtm.

2024-03-26 09:25 UTC, ialidzhikov commented on pkg/component/networking/vpn/seedserver/seedserver.go
> -				Name:      secretNameDH,
Nit: You could also drop the const in https://github.com/gardener/gardener/blob/be23065e1441a703eef7f2ed565c865ab9f43017/pkg/component/networking/vpn/seedserver/seedserver.go#L76.

2024-03-26 09:25 UTC, ialidzhikov commented on pkg/component/networking/vpn/seedserver/seedserver.go
> -							MountPath: volumeMountPathDH,
Nit: You could also drop https://github.com/gardener/gardener/blob/be23065e1441a703eef7f2ed565c865ab9f43017/pkg/component/networking/vpn/seedserver/seedserver.go#L92 and https://github.com/gardener/gardener/blob/be23065e1441a703eef7f2ed565c865ab9f43017/pkg/component/networking/vpn/seedserver/seedserver.go#L85.

2024-03-26 12:19 UTC, ialidzhikov approved these changes
/lgtm

2024-03-26 13:23 UTC, ary1992 commented
/retest

2024-03-26 14:15 UTC, merged