Enhance makefile tools binaries to be system and arch independent
gardener/gardener pull request #9589
Opened 2024-04-15 13:24 UTC by vpnachev

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
Enhance makefile tools binaries to be system and arch independent

Sometimes, I am mounting the source code in a dev container and running various make commands from there, hence the system could differ (`linux` vs `darwin` and `arm64` vs `amd64`). This results in failure because darwin cannot run linux binaries and vise versa, to fix this I have to manually delete binaries one by one or the entire folder which is time consuming. By using dedicated folder for each system and arch, each target will get own set of binaries and the collision will be avoided.
 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2024-04-15 21:37 UTC, vpnachev commented
/retest-required

2024-04-15 21:44 UTC, vpnachev commented
/cc @timebertt

2024-04-15 21:47 UTC, vpnachev commented
/retest-required

2024-04-16 07:47 UTC, oliver-goetz requested changes
This change will break our precompiled tools (ref). When they are imported again ([ref](https://github.com/gardener/gardener/blob/24d0823e8b652536569809f75372d00909b279cc/hack/tools.mk#L139)) the files would be copied to something like `./hack/tools/bin/linux-amd64/linux-amd64` 

I think the tests are failing because `golangci-lint` does not find the library at the place where it is expected ([.golangci-lint.yaml](https://github.com/gardener/gardener/blob/24d0823e8b652536569809f75372d00909b279cc/.golangci.yaml#L260)). I don't know if it is possible to use the sub folder here too.

2024-04-16 13:35 UTC, vpnachev commented
Now, by default the os-arch specific dir will be used, in pre-configured environment the non os-arch specific dir will be used.

2024-04-16 14:10 UTC, vpnachev commented
/retest-required

2024-04-17 14:15 UTC, oliver-goetz approved these changes
/retest

2024-04-17 14:16 UTC, oliver-goetz commented
/remove-lgtm
I wanted to leave `lgtm` for someone else to cross-check 😅

2024-04-17 14:17 UTC, vpnachev commented
I might need to rebase because of the tests failing like https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/9589/pull-gardener-e2e-kind-ha-multi-zone-upgrade/1780228296198328320#1:build-log.txt%3A1694-1697

```
  [FAILED] Expected
      <string>: v1.93.0-dev
  to equal
      <string>: v1.92.1
```

2024-04-17 17:58 UTC, vpnachev commented
/test pull-gardener-e2e-kind

2024-04-17 18:02 UTC, vpnachev commented
/test pull-gardener-e2e-kind-ha-multi-zone

2024-04-17 18:32 UTC, vpnachev commented
/test pull-gardener-e2e-kind-ha-multi-zone

2024-04-17 18:42 UTC, vpnachev commented
/retest

2024-04-18 04:45 UTC, rfranzke reviewed
/lgtm

2024-04-18 06:01 UTC, timebertt approved these changes
Nice improvement!

2024-04-18 07:52 UTC, vpnachev commented
/retest

2024-04-18 08:40 UTC, merged