Drop `Infrastructure Cleanup Wait Period` during shoot deletion
gardener/gardener pull request #9632
Opened 2024-04-19 18:37 UTC by oliver-goetz

**How to categorize this PR?**

/area usability
/kind cleanup

**What this PR does / why we need it**:
There is a `Infrastructure Cleanup Wait Period` of 5 minutes from the times where service finalizers have not been enabled by default yet. This changed a long time ago. Thus, this PR removes the cleanup period.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```noteworthy operator
Five minutes `Infrastructure Cleanup Wait Period` during shoot deletion was removed.
```

2024-04-22 05:26 UTC, shafeeqes reviewed
Thanks!
/lgtm

2024-04-22 06:45 UTC, rfranzke requested changes
Remove `shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds` from the example shoots in the repo

/cc @kon-angelo

2024-04-22 06:45 UTC, rfranzke commented
Also, mention removal of `shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds` in the release notes for others to adapt.

2024-04-22 11:07 UTC, rfranzke commented
/lgtm

2024-04-22 11:59 UTC, kon-angelo approved these changes
/lgtm

2024-04-22 13:47 UTC, merged

2024-04-23 05:49 UTC, timebertt commented
Thanks, love it!