Scrape CCM via HTTP on Alicloud
gardener/gardener pull request #967
Opened 2019-04-30 08:14 UTC by wyb1

**What this PR does / why we need it**:
Prometheus now only scrapes the CCM on alicloud via HTTP. This will prevent prometheus from firing false positive alerts.

/cc @jia-jerry @minchaow 

**Which issue(s) this PR fixes**:
Fixes #963

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

2019-04-30 08:23 UTC, wyb1 commented
I'm not sure why the concourse test failed. It works locally.

2019-04-30 12:42 UTC, rfranzke requested changes
Don't use the CloudProfile name to get the cloud provider info

2019-04-30 12:42 UTC, rfranzke commented on pkg/operation/botanist/controlplane.go
> +				"profile":   b.Shoot.Info.Spec.Cloud.Profile,
```suggestion
				"provider":   b.Shoot.CloudProvider,
```

2019-04-30 12:42 UTC, rfranzke commented on charts/seed-monitoring/charts/prometheus/values.yaml
> +  profile: penguin
```suggestion
  provider: aws
```

2019-04-30 12:42 UTC, rfranzke commented on charts/seed-monitoring/charts/prometheus/templates/config.yaml
> +      {{- if not (eq "alicloud" .Values.shoot.profile) }}
```suggestion
      {{- if not (eq "alicloud" .Values.shoot.provider) }}
```

2019-04-30 15:18 UTC, wyb1 commented
Thanks for the review! I applied the changes. PTAL

2019-05-02 08:55 UTC, rfranzke approved these changes
/lgtm

2019-05-02 08:55 UTC, merged