`Shoot` Deletion with 👀+👀 Principle
gardener/gardener pull request #9680
Opened 2024-04-26 15:33 UTC by rfranzke

**How to categorize this PR?**

/area ops-productivity
/kind enhancement

**What this PR does / why we need it**:
This PR implements the proposal from https://github.com/gardener/gardener/issues/8566#issuecomment-2075042784 with the following deviations:

- the `ProjectSpec` API looks like this to allow for potential further inclusion of resources other than `Shoot`s:
   ```yaml
   spec:
     dualApprovalForDeletion:
     - resource: shoots
       selector:
         matchLabels: {}
       includeServiceAccounts: true
   ```
- In https://github.com/gardener/gardener/issues/8566#issuecomment-2075042784, we discussed that only the project owner can configure `.spec.dualApprovalForDeletion`. This is not implemented since we do not prevent project members from changing the labels of `Shoot`s before deleting them such that the selector no longer matches. See the "important note" [in the docs](https://github.com/rfranzke/gardener/blob/four-eyes-deletion/docs/usage/projects.md#four-eyes-principle-for-resource-deletion).
- The logic is not implemented in a new admission plugin, but in the existing [`DeletionConfirmation`](https://github.com/gardener/gardener/blob/master/docs/concepts/apiserver_admission_plugins.md#deletionconfirmation) plugin (which seems like a perfect fit and avoids the boilerplate overhead).

**Which issue(s) this PR fixes**:
Fixes #8566

**Release note**:

```feature user
It is now possible to configure `Project`s with the "four-👀 approval concept for deletion" concept. For now, this can only be applied to `Shoot`s. If configured, the user confirming a `Shoot` deletion (via the `confirmation.gardener.cloud/deletion` annotation) must not be the same user who is sending the DELETE request. This can help preventing accidental/unintentional `Shoot` deletion. Find all information about the feature in [this document](https://github.com/gardener/gardener/tree/master/docs/usage/projects.md#four-eyes-principle-for-resource-deletion).
```

2024-04-27 18:11 UTC, plkokanov commented
/assign

2024-04-29 12:06 UTC, plkokanov requested changes
Just some minor nits.

2024-04-29 12:06 UTC, plkokanov commented on docs/concepts/apiserver_admission_plugins.md
> +In addition, this admission controller reacts on `CREATE` or `UPDATE` operations for `Shoot`s.
```suggestion
Furthermore, this admission controller reacts on `CREATE` or `UPDATE` operations for `Shoot`s.
```

2024-04-29 12:06 UTC, plkokanov commented on docs/usage/projects.md
> +> This concern is intentionally excluded/ignored for now since the principle is not a "security feature" but shall just help preventing *accidental* deletion.
```suggestion
> This concern is intentionally excluded/ignored for now since the principle is not a "security feature" but shall just help prevent *accidental* deletion.
```

2024-04-29 12:06 UTC, plkokanov commented on plugin/pkg/global/deletionconfirmation/admission.go
> +// Admit validates and if appropriate mutates the given bastion against the shoot that it references.
The comment should be adapted accordingly.

2024-04-30 07:38 UTC, shafeeqes reviewed
Very nice PR, thanks ❤️!
Only one minor nit apart from open comments.

2024-04-30 07:38 UTC, shafeeqes commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	// ConfirmationDeletion is an annotation on a Shoot and Project resources whose value must be set to "true" in order to
```suggestion
	// ConfirmationDeletion is an annotation on a Shoot, Project and ShootState resources whose value must be set to "true" in order to
```

2024-04-30 08:51 UTC, oliver-goetz commented
Nice PR 🚀 
No more findings 😄

2024-04-30 09:18 UTC, rfranzke commented on docs/usage/projects.md
> +> This concern is intentionally excluded/ignored for now since the principle is not a "security feature" but shall just help preventing *accidental* deletion.
I think this is correct

2024-04-30 09:59 UTC, plkokanov commented
/lgtm

2024-04-30 10:37 UTC, shafeeqes commented
/lgtm

2024-04-30 10:39 UTC, rfranzke commented
/approve

2024-04-30 11:30 UTC, merged