Don't do HVPA specific things for etcd when `VPAforETCD` is enabled
gardener/gardener pull request #9703
Opened 2024-05-03 08:17 UTC by voelzmo

**How to categorize this PR?**

/area auto-scaling
/kind bug

**What this PR does / why we need it**:
When the new featuregate `VPAforETCD` is enabled, Shoot deletion fails with 
```
Flow "Shoot cluster deletion" encountered task errors: [
task "Scaling up etcd main and event" failed: retry failed with context deadline exceeded, 
last error: Hvpa.autoscaling.k8s.io "etcd-main" not found] Operation will be retried.
```

because there are still paths in the `etcd` components which try to do HVPA specific things, although `VPAforETCD` disables HVPA usage for the `etcd` component.

This PR ensures we no longer do HVPA specific things for etcd when `VPAforETCD` is enabled, namely
* explicitly adjusting the HVPA resource during `#Scale()`
* explicitly copying over the currently set resources from an existing `etcd` StatefulSet into the newly created one

**Special notes for your reviewer**:

**Release note**:

```bug operator
Fix an issue in the etcd component which caused Shoot deletion to fail when the `VPAforETCD` feature gate was enabled
```

2024-05-03 08:18 UTC, voelzmo commented
/cherry-pick release-v1.94

2024-05-03 08:52 UTC, voelzmo commented
/invite @ashwani2k

2024-05-03 09:40 UTC, dguendisch commented
/lgtm

2024-05-03 10:47 UTC, oliver-goetz requested changes
If it is either HVPA or VPA, I would prefer one single `Autoscaling` option instead of `HVPAEnabled` and `VPAEnabled`. 

It is not transparent when we set these settings individually for [shoot etcds](https://github.com/gardener/gardener/blob/ece32010c9d425157256a99d59ebbf4da4955a08/pkg/gardenlet/operation/botanist/etcd.go#L34-L74) and [virtual-garden etcds](https://github.com/gardener/gardener/blob/57a0fdfa597d90fd17f5aef02d1710dec6f18a05/pkg/operator/controller/garden/garden/components.go#L478-L500), but in the end only one setting wins.

2024-05-03 11:16 UTC, voelzmo commented
> If it is either HVPA or VPA, I would prefer one single `Autoscaling` option instead of `HVPAEnabled` and `VPAEnabled`.
> 
> It is not transparent when we set these settings individually for [shoot etcds](https://github.com/gardener/gardener/blob/ece32010c9d425157256a99d59ebbf4da4955a08/pkg/gardenlet/operation/botanist/etcd.go#L34-L74) and [virtual-garden etcds](https://github.com/gardener/gardener/blob/57a0fdfa597d90fd17f5aef02d1710dec6f18a05/pkg/operator/controller/garden/garden/components.go#L478-L500), but in the end only one setting wins.

Yeah, that would definitely have been an option to consider on the [original PR](https://github.com/gardener/gardener/pull/8984). This PR fixes a bug for that new featuregate, which we probably shouldn't be blocking for a refactoring.

If you insist, I can create an additional PR refactoring the HVPA/VPA booleans for etcd, but I myself wouldn't be doing it. Here is why:
* the two featuregate existing in parallel is a temporary state. In 3 releases, the featuregate will most likely graduate to GA and the whole HVPA options will be removed from etcd
* the two places in the code you linked to aren't situations where someone carefully evaluates if they should put `true` or `false` into the `HVPAenabled` or `VPAenabled` booleans for etcd – we more or less blindly pass in the state of the corresponding featuregates

Does this make sense?

2024-05-03 14:18 UTC, oliver-goetz requested changes
I did not review #8984. It's fine with me for a fix. For that case, l have some smalls remarks.

2024-05-03 14:18 UTC, oliver-goetz commented on pkg/component/etcd/etcd/etcd_test.go
> +			})
`AfterEach` should not be required here.

2024-05-03 14:18 UTC, oliver-goetz commented on pkg/component/etcd/etcd/etcd_test.go
> +			Context("When VPAforETCD is enabled", func() {
This `Context` is  inside `Context("When HVPA is enabled",...`. Please move it one level to the left.

2024-05-03 14:18 UTC, oliver-goetz commented on pkg/component/etcd/etcd/etcd_test.go
> +				It("should update HVPA with the new replica count if it is enabled", func() {
This description does not look right.

2024-05-06 07:37 UTC, voelzmo commented on pkg/component/etcd/etcd/etcd_test.go
> +			Context("When VPAforETCD is enabled", func() {
This is intentional. The error we're fixing raises when both feature gates are turned on.

2024-05-06 07:37 UTC, voelzmo commented on pkg/component/etcd/etcd/etcd_test.go
> +				It("should update HVPA with the new replica count if it is enabled", func() {
Good catch, this was just copy-pasta from the case above

2024-05-06 07:37 UTC, voelzmo commented on pkg/component/etcd/etcd/etcd_test.go
> +			})
Correct, thanks!

2024-05-06 08:28 UTC, voelzmo commented
/retest

2024-05-06 08:39 UTC, oliver-goetz commented on pkg/component/etcd/etcd/etcd_test.go
> +			Context("When VPAforETCD is enabled", func() {
Tbh., that's pretty hard to understand. The most outer `BeforeEach` sets `hvpaEnabled = true`, so from my point of view any test intends to use this setting unless it it specified differently.
Anyway, it's just a fix 😅

2024-05-06 08:39 UTC, oliver-goetz commented
/approve

2024-05-06 08:56 UTC, rfranzke reviewed
/lgtm

2024-05-06 11:42 UTC, merged