Label nodes with expected OperatingSystemConfig name
gardener/gardener pull request #9757
Opened 2024-05-15 08:51 UTC by MichaelEischer

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:

Label all workers with the name of their expected operating system config.

Nodes with an outdated operating system config key are skipped while checking whether a shoot is healthy. Currently, this requires botanist to know how to calculate the OSCkey based on a node object, which leaks implementation details. Instead, each node is now just labeled with the expected config key. This allows for future extensions of the OSCkey calculation without having to introduce additional labels on the node objects.

By including the KeyName in the operatingsystemconfig.Data struct, no other component has to know how the KeyName is calculated. The existing `oscName` field is not really suitable as it also includes a keySuffix which the external components shouldn't know about.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/9699

**Special notes for your reviewer**:
Reworked implementation of https://github.com/gardener/gardener/pull/9465 .

**Release note**:

```other operator
other operator
Nodes are now labeled with "worker.gardener.cloud/operating-system-config", which includes the expected name of the OperatingSystemConfig secret.
```

2024-05-16 07:03 UTC, rfranzke commented
/assign

2024-05-16 07:03 UTC, rfranzke reviewed
/ok-to-test

2024-05-16 08:44 UTC, MichaelEischer commented
/retest

2024-05-21 07:23 UTC, rfranzke commented
/assign

2024-05-21 12:26 UTC, rfranzke requested changes
Nice PR, thanks!

2024-05-21 12:26 UTC, rfranzke commented on pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
> -	SecretName *string
The pointer type was intentional since the OSC of type `reconcile` will no longer generate a `Secret` in the future (currently, this only happens for legacy reasons). Hence, I vote to revert/drop `bf5342c67c98938d32cb130fae4013adfe10a242`.

2024-05-21 12:26 UTC, rfranzke commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	LabelWorkerPoolOperatingSystemConfig = "worker.gardener.cloud/operating-system-config"
```suggestion
	LabelWorkerPoolOperatingSystemConfigSecretName = "worker.gardener.cloud/operating-system-config-secret-name"
```

WDYT? This would make it more explicit. Or, perhaps even better

```suggestion
	LabelWorkerPoolGardenerNodeAgentSecretName = "worker.gardener.cloud/gardener-node-agent-secret-name"
```

The fact, that this secret contains a `OperatingSystemConfig` is a detail that should not be encoded into the label name, don't you think?

2024-05-21 12:26 UTC, rfranzke commented on pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
> +	KeyName string
```suggestion
	GardenerNodeAgentSecretName string
```

2024-05-21 12:26 UTC, rfranzke commented on pkg/utils/gardener/shoot.go
> +func NodeLabelsForWorkerPool(workerPool gardencorev1beta1.Worker, nodeLocalDNSEnabled bool, oscKey string) map[string]string {
`gardenerNodeAgentSecretName string`

2024-05-21 12:26 UTC, rfranzke commented on pkg/gardenlet/operation/botanist/worker.go
> +	// TODO(MichaelEischer): remove after Gardener 1.100
```suggestion
	// TODO(MichaelEischer): Remove this after Gardener v1.101 has been released.
```

2024-05-21 12:26 UTC, rfranzke commented on pkg/gardenlet/operation/botanist/worker.go
> +		return val != secretOSCKey, nil
I guess we should also rename `secretOSCKey` to `gardenerNodeAgentSecretName` here?

2024-05-21 12:26 UTC, rfranzke commented on pkg/component/extensions/worker/worker.go
> +			oscKey            string
gardenerNodeAgentSecretName string

2024-05-21 12:26 UTC, rfranzke commented on pkg/gardenlet/operation/botanist/worker_test.go
> +		Entry("detect outdated nodes without osc label",
without gardener node agent secret name label

2024-05-23 08:46 UTC, MichaelEischer commented on pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
> -	SecretName *string
I've reverted the commit.

> The pointer type was intentional since the OSC of type `reconcile` will no longer generate a `Secret` in the future (currently, this only happens for legacy reasons).

Out of curiosity, where would an OS extension store the result of processing the `reconcile` OSC in the future?

2024-05-23 08:46 UTC, MichaelEischer commented on pkg/apis/core/v1beta1/constants/types_constants.go
> +	LabelWorkerPoolOperatingSystemConfig = "worker.gardener.cloud/operating-system-config"
I've changed the name to `LabelWorkerPoolGardenerNodeAgentSecretName`. Although, my impression is that "operating-system-config" would be generic enough for anyone not familiar with Gardener to interpret it as a general name, not a specify gardener component. But I'm fine with either variant.

2024-05-23 08:47 UTC, MichaelEischer commented on pkg/gardenlet/operation/botanist/worker.go
> +		return val != secretOSCKey, nil
I've renamed all occurrences of OSCKey.

2024-05-23 08:52 UTC, MichaelEischer commented
I've addressed the review comments. PTAL

2024-05-23 10:43 UTC, rfranzke commented on pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
> -	SecretName *string
Nowhere - they do not have to do anything with the resources other than - optionally - putting `.status.extension{Unit,File}s` if there is anything. There is no secret to generate.

2024-05-23 11:04 UTC, MichaelEischer commented on pkg/component/extensions/operatingsystemconfig/operatingsystemconfig.go
> -	SecretName *string
Ah, I wasn't aware of the status.extension... fields, that explains it. Thanks!

2024-05-23 13:15 UTC, rfranzke reviewed
Awesome @MichaelEischer 
Let's go 

/lgtm
/approve

2024-05-23 15:15 UTC, MichaelEischer commented
/retest

2024-05-23 17:01 UTC, merged