Move `machine-controller-manager-provider-local` into `gardener/gardener`
gardener/gardener pull request #9782
Opened 2024-05-16 22:52 UTC by timebertt

**How to categorize this PR?**

/area dev-productivity
/kind enhancement

**What this PR does / why we need it**:
In order to improve development productivity, this PR moves the content of the https://github.com/gardener/machine-controller-manager-provider-local repository into `gardener/gardener`. The images are built dynamically with Skaffold and pushed into the local registry.

On the way, we
- renamed the images in the `skaffold.yaml` file (removing the `europe-docker.pkg.dev/*` prefixes since these images are never actually pushed to this real remote registry
- fixed a bug in the `logcheck` `golangci-lint` plugin to prevent false positive findings in case a package-level functions disguises as `logr` method
- removed the entrypoint of the provider-specific machine-controller sidecars in the helper functions used by extensions to remove assumptions of how the image has been built

**Release note**:

```other operator
NONE
```

2024-05-17 06:46 UTC, rfranzke commented
/retest

2024-05-17 10:43 UTC, plkokanov commented
/assign

2024-05-17 12:16 UTC, plkokanov requested changes

2024-05-17 12:16 UTC, plkokanov commented on docs/extensions/machine-controller-provider-local.md
> +- Machine Controller (MC) behaves as the controller used to interact with the cloud provider AWS and manage the VMs corresponding to the machine objects.
```suggestion
- Machine Controller (MC) behaves as the controller used to interact with the `local` provider and manage the VMs corresponding to the machine objects.
```
Or something along those lines.

2024-05-17 12:16 UTC, plkokanov commented on skaffold.yaml
> +    - image: gardener-resource-manager
I think these changes won't work with the [provider extensions dev setup](https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally_with_extensions.md).
There are kyverno policies which expect the image name to match: https://github.com/gardener/gardener/blob/fa31ef3ee09b5d5fd15666617348c0ac3471f182/example/provider-extensions/kyverno-policies/gardener-image-pull-policy.yaml#L25

If you also update the policy, note that we plan to also use them for the remote extension setup for some extension controllers, e.g:  https://github.com/gardener/gardener-extension-registry-cache/pull/193

2024-05-23 07:01 UTC, timebertt commented on skaffold.yaml
> +    - image: gardener-resource-manager
Good hint, thanks. I dropped the image name simplification from this PR and went back to fully qualified image refs for the new images.

2024-05-23 07:02 UTC, timebertt commented
Thanks for your review @plkokanov. I rebased and addressed your suggestions.
We will take a look at the failing tests later today.

2024-05-23 11:16 UTC, timebertt commented on skaffold.yaml
> +    - image: gardener-resource-manager
@rfranzke went back to the simplified image names but with a well-defined prefix `local-skaffold/`. https://github.com/gardener/gardener-extension-registry-cache/pull/193 should be adapted accordingly.

2024-05-26 18:51 UTC, rfranzke commented
/lgtm
/approve

2024-05-26 18:52 UTC, merged