The shoot control plane Prometheus forwards its alerts to the seed alertmanager
gardener/gardener pull request #9870
Opened 2024-05-29 14:13 UTC by istvanballok

**How to categorize this PR?**

/area monitoring
/kind regression

**What this PR does / why we need it**:

The shoot control plane Prometheus should forward its alerts to the alertmanager in the garden namespace of the seed, to the `alertmanager-seed`.

**Which issue(s) this PR fixes**:

Before #9695 (that was released with [v1.95.0](https://github.com/gardener/gardener/releases/tag/v1.95.0)), the shoot Prometheus always forwarded its alerts to the `alertmanager-seed`. The `alertmanager-seed` can be configured in real landscapes e.g. to send email notifications to Gardener operators. This can be useful if some shoot control plane alerts need to be acted upon e.g. for auditing purposes.

With #9695, the shoot control plane Prometheus only forwards the alerts to the shoot alertmanager. Note that the `alertmanager-shoot` is deployed only if the alerting feature is turned on (see [doc](https://gardener.cloud/docs/gardener/monitoring/alerting/#alerting-for-users)).

**Special notes for your reviewer**:

/cc @vicwicker @rfranzke @ScheererJ 

<details>
<summary>Additional hints when testing in the local setup...</summary>

In the local setup, to deploy the seed alertmanager, we can apply the following secret based on `example/10-secret-alerting.yaml`:

```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: alerting
  namespace: garden
  labels:
    gardener.cloud/role: alerting
type: Opaque
stringData:
  auth_type: smtp
  auth_identity: identity
  auth_password: password
  auth_username: username
  from: from@localhost
  smarthost: localhost:25
  to: to@localhost
EOF
```

and then restart the gardenlet(s) e.g. with `kubectl delete pods -l role=gardenlet`

Furthermore, in the shoot control plane namespace, we can add some alerts that are always firing:

```bash
k apply -f - <<EOF
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: shoot
  name: test
spec:
  groups:
  - name: test
    rules:
    - alert: TestOperator
      expr: vector(1)
      for: 1m
      labels:
        type: seed
        severity: critical
        visibility: operator
      annotations:
        summary: Shoot test summary (operator)
        description: |-
          Shoot test description (operator)
    - alert: TestAll
      expr: vector(1)
      for: 1m
      labels:
        type: seed
        severity: critical
        visibility: all
      annotations:
        summary: Shoot test summary (all)
        description: |-
          Shoot test description (all)
EOF
```

The we can port-forward to the shoot and seed alertmanagers and verify that the alerts were sent there.

</details>

**Release note**:

```other operator
A regression is fixed and now the shoot control plane Prometheus forwards its alerts to the seed alertmanager
```

2024-05-29 14:19 UTC, rfranzke commented
/cherry-pick release-v1.96

2024-05-29 14:19 UTC, rfranzke commented
/cherry-pick release-v1.95

2024-05-29 14:23 UTC, rfranzke requested changes
Nice PR, thanks for finding and fixing this 🙇🏻

2024-05-29 14:23 UTC, rfranzke commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +					Namespace: namespace,
```suggestion
					Namespace: ptr.Deref(alertmanagerItem.Namespace, p.namespace),
```

2024-05-29 14:23 UTC, rfranzke commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +			}
```suggestion
```

2024-05-29 14:23 UTC, rfranzke commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +		for _, alertmanagerItem := range p.values.Alerting.Alertmanagers {
```suggestion

		for _, alertManager := range p.values.Alerting.Alertmanagers {
```

2024-05-29 14:23 UTC, rfranzke commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +				monitoringv1.AlertmanagerEndpoints{
```suggestion
			obj.Spec.Alerting.Alertmanagers = append(obj.Spec.Alerting.Alertmanagers, monitoringv1.AlertmanagerEndpoints{
```

2024-05-29 14:23 UTC, rfranzke commented on pkg/gardenlet/operation/botanist/monitoring.go
> +	values.Alerting = &prometheus.AlertingValues{Alertmanagers: []*prometheus.Alertmanager{{Name: "alertmanager-seed", Namespace: ptr.To(v1beta1constants.GardenNamespace)}}}
You could move this up directly into the `values := prometheus.Values{` definition

2024-05-29 14:41 UTC, istvanballok commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +					Namespace: namespace,
Thank you!

> 4c3ca2b16 Address PR review feedback: use ptr.Deref

2024-05-29 14:41 UTC, istvanballok commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +			}
Thank you!

> 4c3ca2b16 Address PR review feedback: use ptr.Deref

2024-05-29 14:42 UTC, istvanballok commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +		for _, alertmanagerItem := range p.values.Alerting.Alertmanagers {
Thank you!

> ea2137652 Address PR review feedback: rename alertmanagerItem -> alertManager

2024-05-29 14:42 UTC, istvanballok commented on pkg/component/observability/monitoring/prometheus/prometheus.go
> +				monitoringv1.AlertmanagerEndpoints{
Thank you!

> 5059ee123 Address PR review feedback: avoid a line break in the append() function

2024-05-29 14:42 UTC, istvanballok commented on pkg/gardenlet/operation/botanist/monitoring.go
> +	values.Alerting = &prometheus.AlertingValues{Alertmanagers: []*prometheus.Alertmanager{{Name: "alertmanager-seed", Namespace: ptr.To(v1beta1constants.GardenNamespace)}}}
Thank you!

> 209eb0c05 Address PR review feedback: move up the alertmanager-seed config

2024-05-29 14:55 UTC, rfranzke reviewed
/lgtm
/approve

2024-05-29 17:32 UTC, merged

2024-05-31 08:24 UTC, istvanballok commented
> @rfranzke: https://github.com/gardener/gardener/pull/9870 failed to apply on top of branch "release-v1.95":

There were some conflicts while rebasing this PR to the `release-v1.95` branch, hence Prow could not open the PR automatically.

Following the [docs/development/process.md#cherry-picks](https://github.com/gardener/gardener/blob/master/docs/development/process.md#cherry-picks) documentation, I resolved the conflicts and opened #9884 for the `release-v1.95` branch.