Cert manager metric
gardener/gardener pull request #9878
Opened 2024-05-30 17:47 UTC by jguipi

**How to categorize this PR?**
/area monitoring

**What this PR does / why we need it**:
I need this PR to capture the certificate controller manager metrics in each seed and later propagate those logs into the long-term Prometheus. This will allow the Argus team and me to create new monitoring dashboards.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
I might be missing something here, let me know If I need to change more file
**Release note**:

```other operator
1. Add the certificate controller manager to the seed Prometheud scrape configuration
```

2024-05-31 07:36 UTC, rfranzke requested changes
This component is deployed by https://github.com/gardener/gardener-extension-shoot-cert-service, so the `ScrapeConfig` should be created there.

/hold

2024-05-31 18:12 UTC, jguipi commented
> This component is deployed by https://github.com/gardener/gardener-extension-shoot-cert-service, so the `ScrapeConfig` should be created there.
> 
> /hold

I created the new PR : https://github.com/gardener/gardener-extension-shoot-cert-service/pull/265 

I guess I need to adapt this one to make sure it's federated properly ?

2024-06-03 06:19 UTC, rfranzke commented
> I guess I need to adapt this one to make sure it's federated properly ?

What does this mean? 😕 cc @istvanballok

2024-06-03 15:34 UTC, rfranzke commented
As discussed via Slack chat:
/close

2024-06-03 15:34 UTC, closed without merging