Expose and scrape metrics from `machine-controller-manager-provider-xxx`
gardener/gardener pull request #9933
Opened 2024-06-06 07:04 UTC by aaronfern

**How to categorize this PR?**

/area monitoring
/kind enhancement

**What this PR does / why we need it**:
This PR does the following
- Updates the `MCM` deployment and service so that metrics from the `machine-controller-manager-provider-xxx` container are exposed
- Update the `serviceMonitor` so that prometheus can scrape these metrics

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
`machine-controller-manager-provider-xxx` container now exposes metrics that prometheus can scrapes
```

2024-06-06 08:03 UTC, rfranzke reviewed
Technically, the better place to mutate `Service` and `ServiceMonitor` for the MCM deployment would be in the provider extensions themselves, for example https://github.com/gardener/gardener/blob/master/pkg/provider-local/webhook/controlplane/ensurer.go (like [this](https://github.com/gardener/gardener/blob/master/pkg/provider-local/webhook/controlplane/ensurer.go#L41-L72)), since `gardener/gardener` does not know about the provider sidecar containers.

However, given that this seems to always be the same for all providers, we can pragmatically decide to follow this proposed approach, such that we don't have to duplicate/replicate it in all provider repos.

@aaronfern Is this change compatible with older provider sidecars? Before this PR, the metrics were scraped from the main MCM container.

2024-06-06 08:45 UTC, rishabh-11 requested changes
some changes needed

2024-06-06 08:45 UTC, rishabh-11 commented on pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
> +						"mcm_machine_stale_machines_total",
`"mcm_machine_stale_machines_total"` is an MCM metric

2024-06-06 08:45 UTC, rishabh-11 commented on pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
> +						"mcm_machine_controller_frozen",
`"mcm_machine_controller_frozen"` is part of mc metrics

2024-06-06 08:45 UTC, rishabh-11 commented on pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
> +						"mcm_workqueue_retries_total",
These should be common for both containers

2024-06-06 08:49 UTC, aaronfern commented
> @aaronfern Is this change compatible with older provider sidecars? Before this PR, the metrics were scraped from the main MCM container.

Yes, I don't see why not. There's really no change to the provider sidecar logic. Provider metrics were always exposed there, just never being scraped.

2024-06-07 14:37 UTC, aaronfern commented
/test pull-gardener-e2e-kind-ha-single-zone

2024-06-13 09:56 UTC, rishabh-11 reviewed
/lgtm

2024-06-19 13:01 UTC, timuthy commented on pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
> +						"mcm_machine_status_condition",
Why have the machine related metrics moved to this place? I compared both for an AWS cluster and they seem considerably different. Is this intended?

Example for `mcm_machine_status_condition` metric in cluster with 4 machines:

MCM container:
```
# HELP mcm_machine_status_condition Information of the mcm managed Machines' status conditions.
# TYPE mcm_machine_status_condition gauge
mcm_machine_status_condition{condition="ClusterNetworkProblem",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="ClusterNetworkProblem",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="ClusterNetworkProblem",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="ClusterNetworkProblem",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="CorruptDockerOverlay2",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="CorruptDockerOverlay2",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="CorruptDockerOverlay2",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="CorruptDockerOverlay2",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="DiskPressure",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="DiskPressure",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="DiskPressure",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="DiskPressure",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentContainerdRestart",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentContainerdRestart",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentContainerdRestart",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentContainerdRestart",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentDockerRestart",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentDockerRestart",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentDockerRestart",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentDockerRestart",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentKubeletRestart",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentKubeletRestart",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentKubeletRestart",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentKubeletRestart",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentUnregisterNetDevice",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentUnregisterNetDevice",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentUnregisterNetDevice",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentUnregisterNetDevice",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="HostNetworkProblem",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="HostNetworkProblem",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="HostNetworkProblem",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="HostNetworkProblem",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="KernelDeadlock",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="KernelDeadlock",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="KernelDeadlock",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="KernelDeadlock",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="MemoryPressure",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="MemoryPressure",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="MemoryPressure",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="MemoryPressure",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="PIDPressure",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="PIDPressure",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="PIDPressure",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="PIDPressure",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="ReadonlyFilesystem",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="ReadonlyFilesystem",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="ReadonlyFilesystem",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="ReadonlyFilesystem",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="Ready",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 1
mcm_machine_status_condition{condition="Ready",name="shoot--foo--bar-p2-z1-67497-hb2tk",namespace="shoot--foo--bar"} 1
mcm_machine_status_condition{condition="Ready",name="shoot--foo--bar-p2-z2-86867-wzpg6",namespace="shoot--foo--bar"} 1
mcm_machine_status_condition{condition="Ready",name="shoot--foo--bar-p3-z1-6b74f-fs7fd",namespace="shoot--foo--bar"} 1
```

Provider container:
```
# HELP mcm_machine_status_condition Information of the mcm managed Machines' status conditions.
# TYPE mcm_machine_status_condition gauge
mcm_machine_status_condition{condition="ClusterNetworkProblem",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="FrequentContainerdRestart",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--foo--bar"} 0
mcm_machine_status_condition{condition="HostNetworkProblem",name="shoot--foo--bar-p1-z1-5c65d-j25cp",namespace="shoot--scalesim--scenario-c"} 0
```

2024-06-21 07:33 UTC, timuthy commented on pkg/component/nodemanagement/machinecontrollermanager/machine_controller_manager.go
> +						"mcm_machine_status_condition",
As confirmed by @aaronfern, machine related metrics were always exclusively exposed by the provider container. We took more samples to prove that, the one above is faulty and can be ignored.

2024-06-21 07:33 UTC, timuthy reviewed
Thanks @aaronfern 👏 
/lgtm
/approve

2024-06-21 09:40 UTC, aaronfern commented
/retest-required

2024-06-21 10:37 UTC, merged